distribution/distribution

- docs/configuration.md
This page is being pulled into docs.docker.com and sometimes not rendering properly. I think Jekyll doesn't really like mixing markdown and html syntax, so I've changed the code samples to use fences instead of spaces. That seems to make Jekyll happier and infer better markdown and html blocks.
The last table in the document was also not closing and html tag which was causing rendering issues too.
The docs are currently pulling from `releases/2.5`, so if you want I can also submit PRs against `releases/2.5` and `releases/2.6`.
> Format configuration.md with code fences to avoid render issues

- registry/handlers/api_test.go
> registry/handlers: fix incorrect use of Digest.Verifiers

- health/doc.go
make all comment lines less than 79 chars. 
[For more info](https://github.com/docker/distribution/pull/2072/files/658cda621fef91cff547cc06664c49b1a185865b#r92716666)
> refactor doc comment

- manifest/schema2/manifest.go
Used for defining the media type of layer stored in Docker's layer store.
> Add uncompressed layer media type

- docs/configuration.md
Started out to fix a formatting bug seen at https://docs.docker.com/registry/configuration/#/log, but ended up reformatting the whole file and doing some light rewriting. I do not believe I changed any "facts".
@stevvooe please nominate other reviewers.
> Improve formatting of configuration.md

- cmd/registry/main.go
fix panic when using storage redirect middleware in registry version 2.5.1
When we start registry with storage redirect middleware in config file, it will panic. The error message can be show as follows:
```
unable to configure storage middleware (redirect): no storage middleware registered with name: redirect
```
this PR fix this problem by importing storage redirect middleware in main.go
> fix panic when using storage redirect middleware

- registry/handlers/app.go
- registry/storage/driver/base/base.go
`driver.List` on `"/"` is very expensive if registry contains significant amount of images. And the result isn't used anyways.  In most (if not all) storage drivers, `Stat` has a cheaper implementation, so use it instead to achieve the same goal.
Test plan:
`docker build -t registry:latest .` 
Run the registry with `cmd/registry/config-example.yml` and try push a image to the local registry at several different time point: immediately when registry boot up; 10s after registry boot up; 30s after registry boot up. And all pushes finished without problem.
> Use app.driver.Stat for registry health check

- registry/auth/token/token_test.go
- registry/handlers/app.go
- registry/handlers/app_test.go
With token authentication, requiring the "*" action for DELETE requests
makes it impossible to administratively lock a repository against pushes
and pulls but still allow deletion.  This change adds a new "delete"
action for DELETE requests to make that possible.
> Change DELETE action from "*" to "delete"

- reference/helpers.go
- reference/normalize.go
- reference/normalize_test.go
- reference/reference.go
- reference/reference_test.go
- reference/regexp.go
- reference/regexp_test.go
Allows having other parsers which are capable of unambiguously keeping hostname and name separated in a Reference type.
This is intended to address comments made for #1777 and lay the foundation for upstreaming changes from docker/docker. Leaving this as WIP so some of those changes can be included.
> Integrate docker reference changes

- reference/normalize.go
- reference/normalize_test.go
- reference/reference.go
Needed another rebase which was not caught before merge. Now using go-digest package.
Additionally unexported the `NamedRepository` interface. This is not currently needed outside the package and we might want to merge it into `Named`. In the latter case, we don't want to be in a position where we need to keep around unneeded interfaces because they were previously exported.
> Fix reference package

- contrib/docker-integration/docker-compose.yml
- contrib/docker-integration/golem.conf
- contrib/docker-integration/helpers.bash
- contrib/docker-integration/plugins.bats
- contrib/docker-integration/run_multiversion.sh
- contrib/docker-integration/tls.bats
- contrib/docker-integration/token.bats
- contrib/docker-integration/tokenserver-oauth/Dockerfile
- contrib/docker-integration/tokenserver/Dockerfile
- Add plugin push and pull tests. Tests that images pushed as plugins cannot be pulled as images and vice versa.
- Additional base image used for creating plugin rootfs
- Updates login to allow supply the email flag in less than docker 1.11. Needed to support 1.13 which removes the email flag.
> Plugin integration test

- registry/storage/driver/azure/azure.go
- vendor.conf
- vendor/github.com/Azure/azure-sdk-for-go/storage/blob.go
- vendor/github.com/Azure/azure-sdk-for-go/storage/client.go
- vendor/github.com/Azure/azure-sdk-for-go/storage/file.go
- vendor/github.com/Azure/azure-sdk-for-go/storage/queue.go
- vendor/github.com/Azure/azure-sdk-for-go/storage/table_entities.go
- vendor/github.com/Azure/azure-sdk-for-go/storage/util.go
Removing the temporary workaround in is404() method by re-vendoring
the azure-sdk-for-go.
cc: @yuwamsft
> azure: revendor + remove hacky solution in is404

- reference/normalize_test.go
Demonstrate deterministic parsing of names using normalization and the resulting domain and path.
Replaces #1777
> Add tests for splithostname on normalized values

- notifications/http_test.go
If running test behide a proxy, we may get the error code
403 Forbidden which will fail line 135 for the last testcase.
Detail:
```
metrics not as expected: notifications.EndpointMetrics{Pending:0,
Events:0, Successes:4, Failures:0, Errors:0,
Statuses:map[string]int{"307 Temporary Redirect":0, "400 Bad Request":0,
"403 Forbidden":0, "200 OK":4}} !=
notifications.EndpointMetrics{Pending:0, Events:0, Successes:4,
Failures:0, Errors:0, Statuses:map[string]int{"400 Bad Request":0, "200
OK":4, "307 Temporary Redirect":0}}
```
Immediate close will fix that
Signed-off-by: Derek McGowan <derek@mcgstyle.net>
> [Carry #1990]Fix notification unit test

- registry/handlers/app.go
- registry/handlers/manifests.go
Once upon a time, we referred to manifests and images interchangably.
That simple past is no more. As we grow, we update our nomenclature and
so follows our code.
> registy/handlers: move images to manifests

- reference/helpers.go
- reference/normalize.go
- reference/normalize_test.go
The NormalizedNamed interface has shown to not be necessary for integrating the change downstream. The FamiliarName and FamiliarString helpers are the only used interface and allow hiding the normalized completely.
> Remove NormalizedNamed from public interface

- reference/normalize.go
- reference/normalize_test.go
Officials repositories always have 2 part names with the first part being library and second part being the offical repository name. Names with more than 2 parts should not hit the special case for official repositories since they are not valid official repositories. Add tests for this ambiguity and to ensure that 3 part names are supports for the default repository, as used by the docker store.
> Remove ambiguity for unsupported official repository input

- registry/handlers/api_test.go
- registry/handlers/manifests.go
closes issue#2135 image pull returns 404 on manifest request if there is storage error
When get manifest, the handler will try to retrieve it from storage driver. When storage driver is cloud storage, it can fail due to various reasons even if the manifest exists
(like 500, 503, etc. from storage server). Currently manifest handler blindly return 404 which can be confusing to user.
This change will return 404 if the manifest blob doesn't exist, and return 500 UnknownError for all other errors (consistent with the behavior of other handlers).
Signed-off-by: Yu Wang (UC) <yuwa@microsoft.com>
> closes issue#2135 image pull returns 404 on manifest request if there is storage error

- reference/reference.go
The identifier fields were using spaces while the rest of the lines were using tabs!
> Fix inconsistent spacing in reference grammar

- manifests.go
Sorry @Helen-Xie I messed up the other PR when I tried to rebase it and it closed. The rebase was needed to get circleci to pass (apparently it doesn't merge to master before running tests).
Carried from #2153
> [carry #2153] Correct the variable name

- vendor.conf
- vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
- vendor/github.com/aws/aws-sdk-go/aws/version.go
- vendor/github.com/aws/aws-sdk-go/service/s3/api.go
- vendor/github.com/aws/aws-sdk-go/service/sts/api.go
1.6.12 = c6fc52983ea2375810aa38ddb5370e9cdf611716
> Update aws-sdk-go dependency to 1.6.12

- manifest/schema1/config_builder_test.go
- manifest/schema1/reference_builder_test.go
- notifications/bridge_test.go
- notifications/listener_test.go
- reference/normalize_test.go
- reference/reference.go
- reference/reference_test.go
- registry/api/v2/urls_test.go
- registry/client/repository_test.go
- registry/handlers/api_test.go
- registry/handlers/app.go
- registry/handlers/blobupload.go
- registry/proxy/proxyblobstore_test.go
- registry/proxy/proxymanifeststore_test.go
- registry/storage/blob_test.go
- registry/storage/cache/memory/memory.go
- registry/storage/cache/redis/redis.go
- registry/storage/catalog_test.go
- registry/storage/garbagecollect.go
- registry/storage/garbagecollect_test.go
- registry/storage/linkedblobstore_test.go
- registry/storage/manifeststore_test.go
- registry/storage/tagstore_test.go
Updates the `ParseNamed` function to require that the input be in canonical form. Throws an error if the input is not canonical. This protects against using `ParseNamed` to create partial `Named` values. These partial values can still be created explicitly through `WithName` and `Parse`, as used now used by the registry server.
In the future, the registry should start using fully canonical values on the backend and `WithName` should no longer support creating partial values.
> reference: ParseNamed updated to enforce canonical format

- registry.go
Signed-off-by: fate-grand-order <chenjg@harmonycloud.cn>
> fix misspell "lexicographically" in registry.go

- reference/normalize_test.go
- reference/reference.go
Update check for equal references to call the `String` method
Closes #2163
> Fix recursion with digest String

- reference/normalize.go
The common use case for this function is to add a default tag if the
reference only has a name. The current behavior only adds the default
tag if there is no *tag*, which requires most callers to check for a
digest. Change the behavior to only add default tags to name-only
references, and change the name to reflect this. The documentation
already described the new behavior, so it does not need to be changed.
cc @dmcgowan
> reference: Replace EnsureTagged with TagNameOnly

- registry/storage/blob_test.go
- registry/storage/blobwriter.go
A previous inspection of the code surrounding zero-length blobs led to
some interesting question. After inspection, it was found that the hash
was indeed for the empty string (""), and not an empty tar, so the code
was correct. The variable naming and comments have been updated
accordingly.
Closes #2129
cc @aaronlehmann
> registry/storage: clean up zero-length blob comments

- registry/storage/purgeuploads.go
According to the golang's  [CodeReviewComments](https://github.com/golang/go/wiki/CodeReviewComments#initialisms), the acronym should have a consistent case.
This PR replaces uUID with uuid to correct the function name's case.
> Fixing acronym's case

- reference/regexp.go
- reference/regexp_test.go
This fix is based on:
https://github.com/docker/docker/pull/30746#discussion_r99650885
The goal is to reuse the `DomainRegexp` in docker to check for `<host>:<port>` pattern.
/cc @dmcgowan @aaronlehmann not sure this is the best way to handle it so feel free to close the PR or provide any suggestions.
Signed-off-by: Yong Tang <yong.tang.github@outlook.com>
> Expose `DomainRegexp` from reference

- registry/storage/driver/s3-goamz/s3.go
When I test with storage driver s3-goamz, I find it doesn't work in `cn-north-1` region because of not using V4Auth. It reports:
```
The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.
```
I add a helper function `mustV4Auth` to checks whether must use v4 auth in specific region.
> Check whether must use v4 auth in specific aws region ( storage driver s3-goamz ) 

- registry/storage/driver/s3-goamz/s3.go
It took me a long time to understand when I read these lines of code.
Through my refactoring, this part of the code is easier to understand.
Signed-off-by: uhayate <uhayate.gong@daocloud.io>
> refactor the code style in distribution/registry/storage/driver/s3-goamz/s3.go

- notifications/endpoint.go
- notifications/metrics_test.go
Remove EndpointConfig from the registry.notifications.endpoints
expvar.Func's return value.  It results in an empty value for that
expvar variable under Go 1.7 because it contains a non-nil
*http.Transport, which Go 1.7 can no longer encode as JSON.
Removing EndpointConfig has the additional benefit of protecting any secrets in EndpointConfig.Headers.
If keeping EndpointConfig is a goal, an alternative fix is to set epjson.EndpointConfig.Transport to nil.
> notifications: fix expvar for Go 1.7

- blobs.go
- cmd/digest/main.go
- configuration/configuration.go
- errors.go
Use errors.New() directly to output the error message and fix some typos I found.
Signed-off-by: fate-grand-order <chenjg@harmonycloud.cn>
> Use errors.New() to output the error message and fix some typos

- registry/api/v2/urls.go
- registry/api/v2/urls_test.go
Since there's no default case, if there's not a tag or digest you get
back a confusing error from the router about it not matching the
expected pattern.
Also redoing the tests for URLs a bit so that they can handle checking
for failures.
Signed-off-by: Christy Perez <christy@linux.vnet.ibm.com>
> Better error message for BuildManifestURL if not tagged or digested

- circle.yml
The dep-validate target appears to never get invoked. In the CircleCI
build environment, "master" points to the commit under test. The
circle.yml fragment needs to compare again "origin/master" instead.
> Fix vendor validation

- Makefile
Currently, this target makes changes to the vendor directory, which may
overwrite local changes or cause build errors. It's better to restore
the original vendor directory after running the check.
> Makefile: Restore vendor directory after dep-validate

- registry/api/v2/urls.go
- registry/api/v2/urls_test.go
Removes all support for `X-Forwarded-Port` in the URL builder. This header is not informative for determining the host given by the client. Updated the logic to always prefer the [standard](https://tools.ietf.org/html/rfc7239) `Forwarded` header over the non-standard `X-Forwarded-*` headers when provided. Only use the `host` parameter of the `Forwarded` header and never use the `for` parameter, which is incorrect for setting as the server host.
Note the original reason for providing support for `X-Forwarded-Port` was related to a bug in a load balancer (see reference in #2008). Amazon ELB always sets `X-Forwarded-Port` regardless of whether the port is specified in the `Host` header, and leaves the original `Host` header alone. The goal of the URL builder is to recreate the host exactly …
> Fix forwarded logic

- README.md
A stray space in the link for the migrator repository wasn't allowing it
to be rendered properly in markdown viewers. Remove such a space to
avoid this.
> DOC: README: Fix broken link in migrator

- registry/storage/driver/s3-aws/s3.go
As discussed in https://github.com/docker/distribution/issues/2194, when uploading to S3, the Expires tag should not be set as it causes caches to not cache layers after 30 minutes. See documentation https://docs.aws.amazon.com/sdk-for-go/api/service/s3/ and search for Expires.
Signed-off-by: Alvin Feng <alvin4feng@yahoo.com>
> Remove expires tag from s3 upload

- reference/reference.go
This updates the grammar to allow more than one digest algorithm
separator, matching the regular expression and intended grammar.
> reference: allow more than 1 digest algorithm separator

- registry/storage/driver/s3-aws/s3.go
- registry/storage/driver/s3-aws/s3_test.go
- registry/storage/driver/s3-aws/s3_v2_signer.go
Amazon supports [making requests using temporary security credentials](http://docs.aws.amazon.com/AmazonS3/latest/dev/MakingRequests.html#requestsUsingTempCred). This requires a session token besides the access key ID and secret access key.
> Support session token

- registry/handlers/app.go
I was using an old version of [mux](https://github.com/gorilla/mux) which caused this to blow up.
> Return early to prevent nil pointer dereference

- docs/configuration.md
> Fixed #htpasswd link

- circle.yml
It turns out that origin/master may not be up to date in CircleCI
checkouts. Fetch origin so that diffing for the vendor check can be done
correctly.
Note that this doesn't help the case of PRs against branches other than
master, but the worst case is that those will waste a few seconds doing
unnecessary vendor validation. Since those PRs are relatively rare, that
seems fine.
> [CI] Fetch origin before diffing

- docs/configuration.md
Signed-off-by: Masataka Mizukoshi <m.mizukoshi.wakuwaku@gmail.com>
I've modified the ``docs/configuration.md``.   
The notifications ``interval`` and `` timeout`` was deprecated values.  
And Fixed some configuration related with timeout/interval.   
See this issue #2231
> DOC:configuration.md: Change description of interval.

- registry/storage/driver/s3-goamz/s3.go
I think it's a good habitat to keep code clean. So I removed the unused function `hasCode`.
Signed-off-by: william wei <1342247033@qq.com>
> Remove unused function

- Dockerfile
- circle.yml
Build with go 1.8
There is one known regression with 1.8 but we can update to 1.8.1 before the next release.
See https://github.com/golang/go/issues/19182
> go 1.8: update dockerfile and circle

- vendor.conf
- vendor/github.com/stevvooe/resumable/resumable.go
- vendor/github.com/stevvooe/resumable/sha256/resume.go
- vendor/github.com/stevvooe/resumable/sha256/sha256.go
- vendor/github.com/stevvooe/resumable/sha256/sha256block.go
- vendor/github.com/stevvooe/resumable/sha256/sha256block_386.s
- vendor/github.com/stevvooe/resumable/sha256/sha256block_amd64.s
- vendor/github.com/stevvooe/resumable/sha256/sha256block_decl.go
- vendor/github.com/stevvooe/resumable/sha256/sha256block_generic.go
- vendor/github.com/stevvooe/resumable/sha256/sha256block_s390x.go
- vendor/github.com/stevvooe/resumable/sha256/sha256block_s390x.s
- vendor/github.com/stevvooe/resumable/sha512/resume.go
- vendor/github.com/stevvooe/resumable/sha512/sha512.go
- vendor/github.com/stevvooe/resumable/sha512/sha512block.go
- vendor/github.com/stevvooe/resumable/sha512/sha512block_amd64.s
- vendor/github.com/stevvooe/resumable/sha512/sha512block_decl.go
- vendor/github.com/stevvooe/resumable/sha512/sha512block_generic.go
- vendor/github.com/stevvooe/resumable/sha512/sha512block_s390x.go
- vendor/github.com/stevvooe/resumable/sha512/sha512block_s390x.s
Updates resumable hash implementation to Go 1.8 equivalent. This should
be a major speedup, since it includes a number of optimizations from Go
1.7.
cc @dmcgowan @jlhawn @dmp42
> vendor: update resumable dependency

- docs/architecture.md
This is related to https://github.com/docker/docker.github.io/issues/1342
Needs to be cherry-picked back to `release/2.6` branch since that is what the docs are currently using for Distribution.
> Put architecture.md back into distribution repo

- Dockerfile
Add build args. Defaults to Linux/x64 so no change to existing image, but can build for other platforms - e.g.
```
docker build --build-arg GOOS=windows -t distribution-builder:windows .
```
(Replaces #2209).
> Add ARGs for cross-compiling

- registry/handlers/manifests.go
If the client doesn't support manifest lists, the registry will rewrite a manifest list into the old format. The Docker-Content-Digest header should be updated in this case.
> Update Docker-Content-Digest if manifest list is rewritten

- registry/storage/driver/base/regulator.go
- registry/storage/driver/base/regulator_test.go
In some conditions, regulator.exit may not send a signal to blocked
regulator.enter.
Let's assume we are in the critical section of regulator.exit and r.available
is equal to 0. And there are three more gorotines. One goroutine also executes
regulator.exit and waits for the lock. Rest run regulator.enter and wait for
the signal.
We send the signal, and after releasing the lock, there will be lock
contention:
1. Wait from regulator.enter
2. Lock from regulator.exit
If the winner is Lock from regulator.exit, we will not send another signal to
unlock the second Wait.
> Fix signalling Wait in regulator.enter

- docs/spec/manifest-v2-2.md
Docs need to correspond to what is actually in the code.
> Fixing image manifest schema2 medaitype typo in docs.

- registry/storage/cache/redis/redis.go
Signed-off-by: Helen Chen <chenjg@harmonycloud.cn>
> fix misspelling "algorithm" for cache/redis/redis.go

- registry/handlers/blobupload.go
- registry/handlers/helpers.go
- registry/handlers/images.go
- registry/storage/blobstore.go
- registry/storage/io.go
Under certain circumstances, the use of `StorageDriver.GetContent` can
result in unbounded memory allocations. In particualr, this happens when
accessing a layer through the manifests endpoint.
This problem is mitigated by setting a 4MB limit when using to access
content that may have been accepted from a user. In practice, this means
setting the limit with the use of `BlobProvider.Get` by wrapping
`StorageDriver.GetContent` in a helper that uses `StorageDriver.Reader`
with a `limitReader` that returns an error.
When mitigating this security issue, we also noticed that the size of
manifests uploaded to the registry is also unlimited. We apply similar
logic to the request body of payloads that are full buffered.
(cherry picked from …
> [release/2.6] registry/{storage,handlers}: limit content sizes

- registry/handlers/blobupload.go
- registry/handlers/helpers.go
- registry/handlers/images.go
- registry/storage/blobstore.go
- registry/storage/io.go
Under certain circumstances, the use of `StorageDriver.GetContent` can
result in unbounded memory allocations. In particualr, this happens when
accessing a layer through the manifests endpoint.
This problem is mitigated by setting a 4MB limit when using to access
content that may have been accepted from a user. In practice, this means
setting the limit with the use of `BlobProvider.Get` by wrapping
`StorageDriver.GetContent` in a helper that uses `StorageDriver.Reader`
with a `limitReader` that returns an error.
When mitigating this security issue, we also noticed that the size of
manifests uploaded to the registry is also unlimited. We apply similar
logic to the request body of payloads that are full buffered.
(cherry picked from …
> [release/2.5] registry/{storage,handlers}: limit content sizes

- registry/handlers/blobupload.go
- registry/handlers/helpers.go
- registry/handlers/manifests.go
- registry/storage/blobstore.go
- registry/storage/io.go
Under certain circumstances, the use of `StorageDriver.GetContent` can
result in unbounded memory allocations. In particualr, this happens when
accessing a layer through the manifests endpoint.
This problem is mitigated by setting a 4MB limit when using to access
content that may have been accepted from a user. In practice, this means
setting the limit with the use of `BlobProvider.Get` by wrapping
`StorageDriver.GetContent` in a helper that uses `StorageDriver.Reader`
with a `limitReader` that returns an error.
When mitigating this security issue, we also noticed that the size of
manifests uploaded to the registry is also unlimited. We apply similar
logic to the request body of payloads that are full buffered.
cc @riyazdf @dmcgowan
> registry/{storage,handlers}: limit content sizes

- CONTRIBUTING.md
Mimicking [other docker projects](https://github.com/moby/moby/blob/master/CONTRIBUTING.md#reporting-security-issues).
cc @stevvooe @dmcgowan @aaronlehmann 
Signed-off-by: Riyaz Faizullabhoy <riyaz.faizullabhoy@docker.com>
> add CONTRIBUTING info for security issues

- registry/client/auth/session.go
- registry/proxy/proxyregistry.go
- registry/storage/blobcachemetrics.go
- registry/storage/cache/cachedblobdescriptorstore.go
To simplify the vendoring story for the client, we have now removed the
requirement for `logrus` and the forked `context` package (usually
imported as `dcontext`). We inject the logger via the metrics tracker
for the blob cache and via options on the token handler. We preserve
logs on the proxy cache for that case. Clients expecting these log
messages may need to be updated accordingly.
> registry: remove dependency on logrus for client

- registry/client/auth/session.go
AuthorizeRequest() injects the 'pull' scope if `from` is set unconditionally. If the current token already has that scope, it will be inserted into the scope list twice and `addedScopes` will be set to
true, resulting in a new token being fetched that has no net new scopes.
Instead, check whether `additionalScopes` are actually new.
Signed-off-by: Clayton Coleman <ccoleman@redhat.com>
> If the request already has the scope, don't fetchToken again

- registry/client/repository.go
- registry/client/repository_test.go
A statically hosted registry that responds correctly to GET with a manifest will load the right digest (by looking at the manifest body and calculating the digest). If the registry returns a HEAD without
`Docker-Content-Digest`, then the client Tags().Get() call will return an empty digest.
This commit changes the client to fallback to loading the tag via GET if the `Docker-Content-Digest` header is not set.
This allows a static S3 bucket to serve as a registry for the distribution registry client (since S3 cannot set Docker-Content-Digest, but it can serve the manifest correctly). The daemon is able to pull successfully as well.
> Support HEAD requests without Docker-Content-Digest header

- registry/client/repository.go
- registry/client/repository_test.go
- registry/proxy/proxyregistry.go
The context parameter was either not used or misused.
Signed-off-by: Tibor Vass <teabee89@gmail.com>
> Remove context in NewRegistry and NewRepository

- registry/handlers/app.go
I think this is the right fix. It would be great if someone could give this a try. Let me know if you need instructions.
cc @dumyan @liclac @deterralba @beniwtv @pollosp @oms
Closes #2292
> registry/handlers: ignore notfound on storage driver healthcheck

- registry.go
- registry/client/repository.go
- registry/client/repository_test.go
The current registry/client sends the registered manifest types in
random order. Allow clients to request a single specific manifest type
or a preferred order as per the HTTP spec.
Fixes #2385
Signed-off-by: Clayton Coleman <ccoleman@redhat.com>
> Allow clients to request specific manifest media types

- cmd/digest/main.go
the digest cli does not work if we do not import this two packages,
tested in go1.9. basically, we have to make several algorithms to
be available by calling crypto.RegisterHash in init functions.
> cmd/digest: import crypto algorithms

- docs/spec/api.md
- docs/spec/api.md.tmpl
- docs/spec/auth/index.md
- docs/spec/auth/jwt.md
- docs/spec/auth/oauth.md
- docs/spec/auth/scope.md
- docs/spec/auth/token.md
- docs/spec/index.md
- docs/spec/manifest-v2-1.md
- docs/spec/manifest-v2-2.md
- docs/spec/menu.md
> Fix keyword format for downstream docs

- registry/client/repository.go
- registry/client/repository_test.go
The previous code assumed that the link returned when listing tags was
always absolute. However, some registries, such as quay.io, return the
link as a relative link (e.g. the second page for the quay.io/coreos/etcd
image is /v2/coreos/etcd/tags/list?next_page=<truncated>&n=50). Because
the relative link was retrieved directly, the fetch failed (with the
error `unsupported protocol scheme ""`).
Signed-off-by: Kevin Lin <kevin@kelda.io>
> Properly follow relative links when listing tags

- digestset/set_test.go
1. when lookup an entry which is missing, it should say NotFound.
2. when add duplicated entry, the entries size should not be increased.
3. when add entry which has different algorithm, it should be allowed.
Signed-off-by: zhouhaibing089 <zhouhaibing089@gmail.com>
> digestset: refine some words on unit test

- docs/spec/api.md
- docs/spec/api.md.tmpl
I noted this while reading at https://docs.docker.com/registry/spec/api/
> api.md: Fixed incorrect grammar

- registry/root.go
- registry/storage/garbagecollect.go
- registry/storage/garbagecollect_test.go
- registry/storage/vacuum.go
fixes issue https://github.com/docker/distribution/issues/2301
```
% docker tag alpine:3.4 localhost:5000/alpine:latest
% docker push localhost:5000/alpine:latest
The push refers to a repository [localhost:5000/alpine]
8539d1fe4fab: Pushed
latest: digest: sha256:36fbf18a36d0410de46201a76b7cfb1d69d44a8f407d6a0814517247b896f8e9 size: 528
% docker tag alpine:latest localhost:5000/alpine:latest
% docker push localhost:5000/alpine:latest
The push refers to a repository [localhost:5000/alpine]
3fb66f713c9f: Pushed
latest: digest: sha256:0b94d1d1b5eb130dd0253374552445b39470653fb1a1ec2d81490948876e462c size: 528
```
now the situation is that there is two manifests, and only one has active tag.
New flag added 'm'
```
% docker exec f519ebf4cc51 registry garbage-collect
configuration error: …
```
> add possibility to clean untagged manifests

- context/doc.go
- registry/handlers/context.go
> context, registry/handlers: remove net/context references

- registry/storage/driver/swift/swift.go
If tenant or tenantid are passed as env variables, we systematically use Sprint to make sure they are string and not integer as it would make mapstructure fail.
> fixes #2249: sanitize tenant and tenantid

- configuration/configuration.go
- configuration/configuration_test.go
- docs/configuration.md
- registry/registry.go
This adds a new configuration setting `HTTP.TLS.LetsEncrypt.Hosts` which can be set to a list of hosts that the Docker Registry will whitelist for retrieving Let's Encrypt certificates.
It is required to avoid lots of unsuccessful registrations attempts that are triggered by malicious clients connecting with bogus SNI hostnames.
A patch for the vendored [rsc.io/letsencrypt](https://rsc.io/letsencrypt) library is included to fix clearing of the host whitelist if the setting is missing from the configuration.
The patch has been submitted upstream in https://github.com/rsc/letsencrypt/pull/24.
> Let's Encrypt Host Whitelist Support

- BUILDING.md
Signed-off-by: Deshi Xiao <xiaods@gmail.com>
> fix out of date cli arg for registry version

- notifications/endpoint.go
- notifications/metrics_test.go
- registry/storage/tagstore.go
- registry/storage/tagstore_test.go
@stevvooe as you mentioned here [1] (sorry it took so long) Can you consider these commits for a 2.6.3 release?
[1] https://github.com/docker/distribution/issues/2383#issuecomment-346509099
> [release/2.6] Cherry-Pick commits for release 2.6.3

- Dockerfile
- circle.yml
> Update Golang to 1.10

- blobs.go
- manifest/manifestlist/manifestlist.go
- manifest/manifestlist/manifestlist_test.go
- manifest/ocischema/builder.go
- manifest/ocischema/builder_test.go
- manifest/ocischema/manifest.go
- manifest/ocischema/manifest_test.go
- manifest/schema2/manifest.go
- registry/handlers/api_test.go
- registry/handlers/manifests.go
- registry/storage/driver/storagedriver.go
- registry/storage/manifeststore.go
- registry/storage/manifeststore_test.go
- registry/storage/ocimanifesthandler.go
- registry/storage/ocimanifesthandler_test.go
- registry/storage/registry.go
- vendor.conf
- vendor/github.com/opencontainers/image-spec/LICENSE
- vendor/github.com/opencontainers/image-spec/README.md
- vendor/github.com/opencontainers/image-spec/specs-go/v1/annotations.go
- vendor/github.com/opencontainers/image-spec/specs-go/v1/config.go
- vendor/github.com/opencontainers/image-spec/specs-go/v1/descriptor.go
- vendor/github.com/opencontainers/image-spec/specs-go/v1/index.go
- vendor/github.com/opencontainers/image-spec/specs-go/v1/layout.go
- vendor/github.com/opencontainers/image-spec/specs-go/v1/manifest.go
- vendor/github.com/opencontainers/image-spec/specs-go/v1/mediatype.go
- vendor/github.com/opencontainers/image-spec/specs-go/version.go
- vendor/github.com/opencontainers/image-spec/specs-go/versioned.go
Here is a draft of the oci manifest/manifest lists that addresses @stevvooe 's request in pr #2021 for oci manifest to be it's own schema. 
Also fixes some test case failure issues.
Signed-off-by: Mike Brown <brownwm@us.ibm.com>
> Adds support for oci manifests and manifestlists

- notifications/bridge.go
- notifications/bridge_test.go
- notifications/listener.go
- notifications/listener_test.go
- registry.go
- registry/handlers/app.go
- registry/storage/catalog.go
- registry/storage/registry.go
Whenever a repo or tag is deleted an event is sent out via the regular notification channels. When repo is deleted the event will only contain repo name but not tag or digest. When tag is deleted the event it will have repo and tag but not digest. There is new interface `RepositoryRemover` containing method to delete the repo. Its implemented by internal `registry` instance. To capture the event the registry instance is also stored as `RepositoryRemover` in the application context.
> add repo and tag deletion event

- MAINTAINERS
Include rules and roles in file. Remove inactive maintainers who have already acknowledged leaving the maintainer role.
Used containerd maintainers file as the template
> Update project maintainers file

- registry/storage/driver/inmemory/driver.go
According golang [documentation](https://golang.org/pkg/sync/#RWMutex): no goroutine should expect to be able to acquire a read lock until the initial read lock is released.
> Fix deadlock in the inmemory storage driver

- vendor/gopkg.in/yaml.v2/scannerc.go
Indentation is spelled wrong as intendation everywhere the word occurs
Can either be:
> "found a tab character that violates indentation"
or
> "found tab characters that violate indentation"
> Fixed customer facing grammar and spelling

- vendor/gopkg.in/yaml.v2/scannerc.go
This reverts commit a64394ece5f69596602bcdf12ad578caf5ea89b8.
Vendor commits cannot be made without updating the vendor file. Doing this to fix CI, the fix was already made upstream so going to look for an appropriate commit to commit to vendor to or cherry-pick to a fork.
> Revert "Fixed customer facing grammar and spelling"

- registry/storage/driver/s3-aws/s3.go
closes #2619
Signed-off-by: David Wu <david.wu@docker.com>
> use aws sdk to validate regions

- contrib/compose/nginx/docker-registry-v2.conf
Quick follow-up to #9223. This gives better consistency and readability to the
file.
> Replace tab with space in nginx config

- registry/handlers/app.go
- registry/handlers/context.go
`context.App.repoRemover` is single registry instance stored throughout app run. It was wrapped in another remover when processing each request. This remover happened to be remover got from previous request. This way every remover created was stored in infinite linked list causing memory
leak. Fixing it by storing the wrapped remover inside the request context which will get gced when request context is gced. This was introduced in PR #2648.
> fix memory leak introduced in PR #2648

- cmd/registry/config-cache.yml
- cmd/registry/config-dev.yml
- configuration/configuration.go
- docs/configuration.md
- manifest/schema2/manifest.go
- notifications/bridge.go
- notifications/bridge_test.go
- notifications/event.go
- registry/handlers/app.go
Adds a configurable option to include layer info in manifest notification events. When we receive manifest notification events we often want to know which layers were accessed and/or compose the image. Rather than re-querying the registry, it is convenient to have that information in the manifest event itself.
With the change the default behavior of not including layer information in manifest events is not changed. An explicit configuration is needed to include the info.
> Add configurable layers in manifest events

- registry/auth/htpasswd/access.go
Signed-off-by: David Wu <david.wu@docker.com>
Fixes static checks after #2362 was merged. This should make CI green again. Old PRs need to be rebased and go through travis in the future
> fix gometalinter

- registry/storage/driver/walk.go
- registry/storage/driver/walk_test.go
It's possible to run into a race condition in which the enumerator lists
lots of repositories and then starts the long process of enumerating through
them. In that time if someone deletes a repo, the enumerator may error out.
Replaces #2629 
> Ignore missing paths during enumeration

- registry/storage/manifestlisthandler.go
- registry/storage/ocimanifesthandler.go
- registry/storage/schema2manifesthandler.go
Content must be preserved exactly.
Note that `json.Unmarshal` was stripping the trailing newline before passing it to the manifest's `UnmarshalJSON` function, which expected to receive the original content. Considering those functions are designed to parse the original content, there is no reason not to call it directly. This is also further evidence that the manifest packages are the wrong interface and need to be removed.
Fixes #2703
> Fix registry stripping newlines from manifests

- registry/handlers/app.go
- registry/storage/cache/redis/redis_test.go
Signed-off-by: Rui Cao <ruicao@alauda.io>
> Fix some typos

- .mailmap
- releases/v2.7.0-rc.toml
This is following containerd's release format, using the same release tool and toml template. This file will be used for all 2.7.0 RCs.
Generated notes https://gist.github.com/dmcgowan/f081d53a8c674dccd1a742b685195ba0
Updated mailmap, please let me know if you want your name displayed differently
@fate-grand-order @mlmhl @sakeven @uhayate @liyongxin
> Add release notes for 2.7.0 release candidates

- Dockerfile
Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>
> update Dockerfile to multi-stage

- registry/registry.go
- vendor.conf
- vendor/github.com/Shopify/logrus-bugsnag/LICENSE
- vendor/github.com/Shopify/logrus-bugsnag/README.md
- vendor/github.com/Shopify/logrus-bugsnag/bugsnag.go
Along with configuring a bugsnag http Handler, configure a logrus -> bugsnag hook. This will ensure that any `Error` log messages are also sent to bugsnag. 
Signed-off-by: Matt Tescher <matthew.tescher@docker.com>
> add bugsnag logrus hook

- contrib/token-server/main.go
- registry/auth/auth.go
- registry/auth/htpasswd/access.go
- registry/auth/htpasswd/access_test.go
- registry/auth/silly/access.go
- registry/auth/silly/access_test.go
- registry/auth/token/accesscontroller.go
- registry/auth/token/token_test.go
- registry/handlers/app.go
It redirects the user to to the Host header's domain whenever they try to use
token auth.
Signed-off-by: David Wu <david.wu@docker.com>
Originally from #2630
> add autoredirect auth config

- Dockerfile
Allows using dockerfile to cross compile binaries in registry 2.6 branch
> [release/2.6] Add go arguments to dockerfile

- Dockerfile
When building with arm on alpine, GOARM should be set to 6 by default.
Ensures cross compiled binaries on ARM are compiled with GOARM set, GOARM=6 is expected for alpine
> [release/2.6] Add GOARM flag to dockerfile

- Dockerfile
When building with arm on alpine, GOARM should be set to 6 by default. This ensure that
setting the GOARCH build arg also allows setting GOARM.
> Add GOARM flag to dockerfile

- registry/auth/token/accesscontroller.go
2.7 port for #2800
Signed-off-by: David Wu <david.wu@docker.com>
> [2.7] default autoredirect to false

- docs/configuration.md
Config parameter is user facing so should be documented.
> Add docs for autoredirect config parameter

- docs/configuration.md
Config parameter is user facing so should be documented.
> [2.7] Add docs for autoredirect config parameter

- configuration/configuration.go
- configuration/configuration_test.go
- docs/configuration.md
- registry/registry.go
Closes #2807 to allow users to configure the minimum allowable TLS version for Registry.  Usage is via config.yml:
```
http:
tls:
minimumtls: tls1.2
```
An omitted or unrecognized string results in the same TLS1.0 support we have today, and allowed strings are in the updated docs - "tls1.0", "tls1.1", "tls1.2".
> Registry - make minimum TLS version user configurable

- docs/configuration.md
- registry/storage/driver/oss/oss.go
- registry/storage/driver/oss/oss_test.go
- vendor.conf
- vendor/github.com/denverdino/aliyungo/README.md
- vendor/github.com/denverdino/aliyungo/common/client.go
- vendor/github.com/denverdino/aliyungo/common/endpoint.go
- vendor/github.com/denverdino/aliyungo/common/regions.go
- vendor/github.com/denverdino/aliyungo/common/request.go
- vendor/github.com/denverdino/aliyungo/common/types.go
- vendor/github.com/denverdino/aliyungo/oss/authenticate_callback.go
- vendor/github.com/denverdino/aliyungo/oss/client.go
- vendor/github.com/denverdino/aliyungo/oss/regions.go
- vendor/github.com/denverdino/aliyungo/util/encoding.go
- vendor/github.com/denverdino/aliyungo/util/signature.go
- vendor/github.com/denverdino/aliyungo/util/util.go
Merry Xmas!
Some enterprise customers require the BYOK(Bring Your Own Key) support for OSS storage driver. 
The encryptionkeyid is added to the OSS driver configuration for KMS key id used for encryption 
```
oss:
accesskeyid: accesskeyid
accesskeysecret: accesskeysecret
region: OSS region name
endpoint: optional endpoints
internal: optional internal endpoint
bucket: OSS bucket
encrypt: optional enable server-side encryption
encryptionkeyid: optional KMS key id for encryption
secure: optional ssl setting
chunksize: optional size valye
rootdirectory: optional root directory
```
And the Alibaba Cloud SDK is updated for new regions
> Support BYOK for OSS storage driver

- Dockerfile
Ensures that build tags get set in the Dockerfile so that OSS and GCS drivers
are built into the official registry binary.
Closes #2819 
> Use same env var in Dockerfile and Makefile

- contrib/compose/README.md
- docs/spec/api.md
- docs/spec/auth/token.md
- health/health.go
- registry/api/errcode/handler.go
- registry/api/v2/descriptors.go
- registry/client/repository_test.go
- registry/handlers/api_test.go
- registry/handlers/app.go
- registry/handlers/app_test.go
- registry/handlers/catalog.go
- registry/handlers/tags.go
This fixes registry endpoints to return the proper `application/json`
content-type for JSON content, also updating spec examples for that.
As per IETF specification and IANA registry [0], the `application/json`
type is a binary media, so the content-type label does not need any
text-charset selector. Additionally, the media type definition
explicitly states that it has no required nor optional parameters,
which makes the current registry headers non-compliant.
[0]: https://www.iana.org/assignments/media-types/application/json
Signed-off-by: Luca Bruno <lucab@debian.org>
> registry: fix binary JSON content-type

- docs/configuration.md
- registry/storage/driver/middleware/cloudfront/middleware.go
@manishtomar According to [documentation](https://github.com/docker/distribution/blob/master/docs/configuration.md#cloudfront), `ipfilteredby` is not required. And if you don't set `ipfilteredby` for cloudfront middleware, registry crashes and you get the error `panic: interface conversion: interface {} is nil, not string`.
This PR fixes this issue and some minor formatting issues with cloudfront configuration docs.
> Fix cloudfront middleware

- registry/storage/driver/s3-aws/s3.go
Radosgw does not support S3 `GET Bucket` API v2 API but v1.
This API has backward compatibility, so most of this API is working
correctly but we can not get `KeyCount` in v1 API and which is only
for v2 API.
Signed-off-by: Eohyung Lee <liquidnuker@gmail.com>
Fixes: #2553
> Fix s3 driver for supporting ceph radosgw

- registry/handlers/manifests.go
Use mime.ParseMediaType to parse the media types in Accept header in manifest request. Ignore the failed ones.
Signed-off-by: Yu Wang <yuwa@microsoft.com>
> Fixes #2835 Process Accept header MIME types in case-insensitive way

- Dockerfile
The default Dockerfile won't work in docker proxy pull cache mode, error will happen:
```
panic: Get https://xxx/v2/: x509: certificate signed by unknown authority
```
This PR use the config from `distribution-library-image` directly
https://github.com/docker/distribution-library-image/blob/7d18dca46fba84ec5a2a70e0ac81113975c3a159/amd64/Dockerfile#L3-L6
@manishtomar
> change default Dockerfile to install ssl utils

- registry/client/blob_writer.go
- registry/client/blob_writer_test.go
Any byte written should append to the size. Otherwise, the full Size is always zero.
> Append the written bytes to the blob writer's size

- registry/client/auth/session.go
fetchTokenWithBasicAuth checks if a token is in the token response
but fetchTokenWithOAuth does not
these changes implements the same behaviour for the latter
returning a `ErrNoToken` if a token is not found in the resposne
Signed-off-by: Sevki Hasirci <sevki@cloudflare.com>
> fix no error returned in fetchTokenWithOAuth

- Dockerfile
Given the security CVEs related to alpine, sticking with the latest version is best.
> use latest version of alpine when building the Docker container

- registry/handlers/blobupload.go
I've found this logic being in a single method to be quite hard to get.
I believe extracting it makes it easier to read, as we can then more easily see what the main method does and possibly ignore the intricacies of `ResumeBlobUpload`.
> Extract blob upload resume into its own method

- registry/client/repository.go
- registry/client/repository_test.go
Some registries, such as ECR don't provide a `Docker-Upload-UUID` HTTP header when starting a blob upload. So we can't rely on that, which then fails when we try to generate the `Location` header we return (in [blobupload.go](https://github.com/docker/distribution/blob/0d3efadf0154c2b8a4e7b6621fff9809655cc580/registry/handlers/blobupload.go#L310)).
This fallbacks to try reading the UUID from the Location header returned by the underlying service. If we still don't have any UUID, it then returns an error.
I didn't remove @dmcgowan's TODO because we're technically still not checking for invalid UUID, only for empty strings.
> Handle Blob Create when the underlying registry doesn't provide 'Docker-Upload-UUID'

- registry/client/repository.go
- registry/client/repository_test.go
This implements resuming a repository blobs upload.
I'm using `time.Now` as `startedAt`, as the one set when `Create()` was called doesn't seem to be available. I'm happy to follow any guidance on using another value though.
> Implement Repository Blobs upload resuming

- Dockerfile
- Makefile
solve for #2953
Allows `VERSION` and `REVISION` to be set via build args.
E.G `docker build --build-arg VERSION=somerelease --build-arg REVISION=internalRev .`
> allow for VERSION and REVISION to be passed in during docker builds

- registry/storage/driver/swift/swift.go
- registry/storage/driver/swift/swift_test.go
When uploading segments to Swift, the registry generates a random file,
by taking the hash of the container path and 32-bytes of random data.
The registry attempts to shard across multiple directory paths, by
taking the first three hex characters as leader.
The implementation in registry, unfortunately, takes the hash of
nothing, and appends it to the path and random data. This results in all
segments being created in one directory.
Fixes: #2407
Fixes: #2311
Signed-off-by: Terin Stock <terinjokes@gmail.com>
> swift: correct segment path generation

- registry/client/blob_writer_test.go
The `Write` method of `httpBlobUpload` wasn't being tested. I've copied the `ReadFrom` tests using `Write` instead.
It's very similar to `ReadFrom` with the exception that the latter doesn't include any `Content-*` HTTP headers, because it can't know the size of a reader.
We could merge them to avoid repetition. But we'd then have to turn the reader into a bytes slice and back into a reader (for `http.NewRequest`).
> Test httpBlobUpload.Write method

- README.md
CircleCI is no longer used here, so the badge should refer to the CI system that is actually active.
> use travis, not circle, build badge

- registry/storage/tagstore.go
- registry/storage/tagstore_test.go
- tags.go
Add an interface alongside `TagStore` that provides API to retrieve digests of all manifests that a tag historically pointed to. It also includes currently linked tag. This will not currently be used in distribution but is useful to extract data out from the storage.
Signed-off-by: Manish Tomar <manish.tomar@docker.com>
> API to retrive tag's digests

- registry/storage/linkedblobstore_test.go
- registry/storage/paths.go
- registry/storage/paths_test.go
- registry/storage/registry.go
This code is already used by Hub and helps us GC old content.
> Add pathspec for repo _layers directory and allow Repository.BlobStore to enumerate over blobs

- docs/configuration.md
Adding spaces to fix table on https://docs.docker.com/registry/configuration/#cloudfront
Signed-off-by: Adrian Plata <adrian.plata@docker.com>
> Fixing broken table

- registry/client/transport/transport.go
When using the client, I'd like to modify the behavior somewhat (retries, context-aware, etc). This would allow me to interject a transport to handle that; I'm not set on this impl, though, and I'd do it differently if you'd prefer that. Putting this up as a feeler.
> make it possible to wrap the client transport in another one

- registry/handlers/api_test.go
Use a synthetic upstream registry when creating the testing mirror configuration
to avoid the test fail when trying to reach http://example.com
Signed-off-by: Fernando Mayo Fernandez <fernando@undefinedlabs.com>
> Fix TestRegistryAsCacheMutationAPIs

- .gometalinter.json
- vendor/github.com/aws/aws-sdk-go/go.mod
- vendor/gopkg.in/yaml.v2/go.mod
Signed-off-by: Derek McGowan <derek@mcgstyle.net>
> [release/2.7] Fix vndr and check

- docs/configuration.md
Backports of:
- commit e1e72e9563743afc1649b23a2f651a7c3caaf369 (documentation fixes taken from https://github.com/docker/distribution/pull/2837)
- https://github.com/docker/distribution/pull/3053 Fixing broken table
- fixes https://github.com/docker/docker.github.io/issues/9935 Docker Registry: CloudFront requirements table broken
- fixes https://github.com/docker/docker.github.io/issues/9945 "Cloudfront" section is garbled
> [release/2.7 backport] fix markdown issues on configuration page

- reference/normalize.go
- reference/normalize_test.go
backport of https://github.com/docker/distribution/pull/2786 for the release/2.7 branch
to address https://github.com/containerd/containerd/issues/3031 if included in a 2.7.x patch release
ParseDockerRef normalizes the image reference following the docker
convention. This is added mainly for backward compatibility. The reference
returned can only be either tagged or digested. For reference contains both tag
and digest, the function returns digested reference, e.g.
docker.io/library/busybox:latest@sha256:7cc4b5aefd1d0cadf8d97d4350462ba51c694ebca145b08d7d41b41acc8db5aa
will be returned as
docker.io/library/busybox@sha256:7cc4b5aefd1d0cadf8d97d4350462ba51c694ebca145b08d7d41b41acc8db5aa.
> [release/2.7 backport] Add reference.ParseDockerRef utility function

- Dockerfile
forward-port of https://github.com/docker/distribution/pull/2821 to master
https://github.com/docker/distribution/pull/2821  was created directly against the `release/2.7` branch; forward-porting the fix so that there's no regression in upcoming releases.
Ensures that build tags get set in the Dockerfile so that OSS and GCS drivers
are built into the official registry binary.
Closes #2819
> [master] Use same env var in Dockerfile and Makefile

- configuration/parser.go
- configuration/parser_test.go
If the `overwriteStruct()` finds an uninitialized pointer, it tries to initialize it, but does it incorrectly. It tries to assign a pointer to pointer, instead of pointer.
> Fix the pointer initialization

- docs/configuration.md
- registry/storage/driver/middleware/cloudfront/middleware.go
Noticed a typo in the CloudFront storage configuration keys. This is likely to cause errors for people who are typing rather than copy/pasting and don't reproduce the typo in their config. I have fixed the typo here and supported the old key for backwards compatibility.
> Fix typo cloudfront updatefrenquency

- Dockerfile
full diff: https://github.com/golang/go/compare/go1.13.7...go1.13.8
go1.13.8 (released 2020/02/12) includes fixes to the runtime, the crypto/x509,
and net/http packages. See the Go 1.13.8 milestone on the issue tracker for details.
https://github.com/golang/go/issues?q=milestone%3AGo1.13.8+label%3ACherryPickApproved
> Update Golang 1.13.8

- contrib/token-server/token_test.go
- notifications/http_test.go
- registry/storage/driver/middleware/cloudfront/middleware_test.go
- registry/storage/driver/testsuites/testsuites.go
Unit test coverge was increased to cover the usages of crypto. This helps to ensure that everything is working fine with fips mode enabled.
Also updated sha1 to sha256 in registry/storage/driver/testsuites/testsuites.go because sha1 is not supported in fips mode.
Signed-off-by: Naveed Jamil <naveed.jamil@tenpearls.com>
> Increase Unit Test Code Coverage

- registry/storage/driver/middleware/cloudfront/middleware.go
backport of https://github.com/docker/distribution/pull/2837 for the 2.7 release branch
relates to https://github.com/docker/distribution/issues/2838
the documentation changes were cherry-picked as part of https://github.com/docker/distribution/pull/3073
> [release/2.7 backport] Bugfix: Make ipfilteredby not required

- CONTRIBUTING.md
Fix out of date links and add line to route Docker specific requests that.
Note the number of issues opened which actually relate to distributions of Docker increased after the repository rename to moby/moby.
> Update reporting issues guidelines

- registry/storage/driver/s3-aws/s3.go
backport of #2879 for the 2.7 release branch
> [release/2.7] Fix s3 driver for supporting ceph radosgw

- registry/storage/driver/gcs/gcs.go
The error from wc.Write exists only in the loop scope, therefore wc.CloseWithError is never called.
> Fix err shadowing in gcs driver

- .travis.yml
- script/setup/install-dev-tools
- Modify Travis manifest to use Go 1.14.x
- Hardcode version of golangci-lint in setup script
- Hardcode version of go-md2man in setup script
> Fix CI failures, upgrade to Go 1.14+

- docs/spec/api.md
- docs/spec/api.md.tmpl
Looks like there's some projects refering to this old URL:
https://grep.app/search?q=https%3A//docs.docker.com/reference/api/registry_api/
addresses https://github.com/docker/docker.github.io/issues/11105
> docs: add redirect for old URL

- docs/spec/api.md
- docs/spec/api.md.tmpl
backport https://github.com/docker/distribution/pull/3196
Looks like there's some projects refering to this old URL:
https://grep.app/search?q=https%3A//docs.docker.com/reference/api/registry_api/
fixes https://github.com/docker/docker.github.io/issues/11105
> [release/2.7 backport] docs: add redirect for old URL

- registry/storage/catalog.go
A repository need not contain any unique layers, if its images use only layers mounted from other repositories. But, the catalog endpoint was looking for the _layers directory to indicate that a directory was a repository.
Use the _manifests directory as the marker instead, since any repository with revisions will contain a _manifests directory.
Fixes #3172 
Signed-off-by: Adam Wolfe Gordon <awg@digitalocean.com>
> catalog: List repositories with no unique layers

- registry/storage/driver/s3-aws/s3.go
Instead of constructing the list of credential providers manually, if we use the default list we can take advantage of the AWS SDK checking the environment and returning either the EC2RoleProvider or the generic HTTP credentials provider, configured to use the ECS credentials endpoint.
Also, use the `defaults.Config()` function instead of `aws.NewConfig()`, as this results in an initialised HTTP client which prevents a fatal error when retrieving credentials from the ECS credentials endpoint.
Fixes #2960
Signed-off-by: Andrew Bulford <andrew.bulford@redmatter.com>
> Support ECS TaskRole in S3 storage driver

- MAINTAINERS
Maintainers from Docker, GitHub, GitLab, Digital Ocean, Harbor.
Signed-off-by: Justin Cormack <justin.cormack@docker.com>
> Add new maintainers

- registry/storage/driver/s3-aws/s3.go
- registry/storage/driver/s3-aws/s3_test.go
When a given prefix is empty and we attempt to list its content AWS returns that the prefix contains one object with key defined as the prefix with an extra "/" at the end.
e.g.
If we call ListObjects() passing to it an existing but empty prefix, say "my/empty/prefix", AWS will return that "my/empty/prefix/" is an object inside "my/empty/prefix" (ListObjectsOutput.Contents).
This extra "/" causes the upload purging process to panic. On normal circunstances we never find empty prefixes on S3 but users may touch it.
Signed-off-by: Ricardo Maraschini <rmarasch@redhat.com>
> Ignore self reference object on empty prefix

- MAINTAINERS
Per distribution call, adding Steve Lasker as a maintainer to help with OCI and Notary collaboration.
Signed-off-by: Steve Lasker <stevenlasker@hotmail.com>
> Adding Steve Lasker as a maintainer

- registry/client/repository.go
backport of https://github.com/docker/distribution/pull/3289
fixes https://github.com/docker/distribution/issues/3288
addresses https://github.com/moby/moby/issues/41621
> [release/2.7 backport] Remove empty Content-Type header

- MAINTAINERS
Mirantis Secure Registry (once Docker Trusted Registry) also uses
Distribution as its core code. Propose two maintainers from Mirantis
as Distribution maintainers.
cc @corhere @squizzi
Signed-off-by: Justin Cormack <justin@specialbusservice.com>
> Propose two maintainers from Mirantis

- docs/spec/api.md
- docs/spec/api.md.tmpl
In the registry spec, the regular expression provided for the algorithm portion of an image digest appears to be wrong. The expression `/[A-Fa-f0-9_+.-]+/` will not even match `sha256`. I believe the intent here was to match any alphanumeric character instead.
> Fix typo for image digest regular expression in spec

- registry/client/repository.go
- registry/client/transport/http_reader.go
We noticed that some requests passed to the repository client were possibly hanging https://github.com/weaveworks/flux/issues/1940 . 
One of the causes is that the client doesn't honor the contexts passed to it https://github.com/weaveworks/flux/issues/1940#issuecomment-484738754 . This PR fixes that.
> Honor contexts passed to registry client methods

- script/setup/install-dev-tools
Looks like md2man was never used in the build scripts, but got added in commit dc49f84dcc64940628505390a7be3394e4314482 (https://github.com/docker/distribution/pull/2657), possibly due to the script being copy/pasted from another project that does use it.
While we may want to generate man-pages at some point in future, it looks like it's safe to remove for now.
> scripts: remove unused md2man from dev-tools

- registry/storage/driver/filesystem/driver.go
There was a previous PR relaxing the filsystem driver permissions
for files and folders to 0666 and 0777 respectively [1][2], but it was
incomplete. This is required to get the registry to honor the umask
value.
[1] https://github.com/docker/distribution/pull/1304/
[2] https://github.com/docker/distribution/issues/1295
Signed-off-by: Stefan Nica <snica@suse.com>
> Relax filesystem driver folder permissions to 0777 (cont)

- .github/workflows/ci.yml
- Dockerfile
- contrib/compose/README.md
- go.mod
- vendor/modules.txt
This PR pumps Golang version to [1.15](https://golang.org/doc/go1.15), as well as Linux Alpine to [3.12](https://alpinelinux.org/posts/Alpine-3.12.0-released.html) because there is no other version that comes with Golang 1.15. See here for details: https://hub.docker.com/_/golang?tab=tags&page=1&name=1.15-alpine
> Bump Golang to `1.15`.

- Makefile
- configuration/configuration.go
- configuration/configuration_test.go
- docs/configuration.md
- registry/registry.go
- registry/registry_test.go
Configuration of list of cipher suites allows a user to disable use
of weak ciphers or continue to support them for legacy usage if they
so choose.
List of available cipher suites at:
https://golang.org/pkg/crypto/tls/#pkg-constants
Default cipher suites have been updated to:
- TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
- TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
- TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
- TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
- TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
- TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
- TLS_AES_128_GCM_SHA256
- TLS_CHACHA20_POLY1305_SHA256
- TLS_AES_256_GCM_SHA384
MinimumTLS has also been updated to include TLS 1.3 as an option
and now defaults to TLS 1.2 since 1.0 and 1.1 have been deprecated.
Also updated install-dev-tools to use recommended golangci-lint …
> Added flag for user configurable cipher suites

- registry/storage/io.go
Backport PR #3309 to release/2.7
> [cherry pick]close the io.ReadCloser from storage driver

- registry/handlers/manifests.go
The OCI distribution spec allows implementations to support deleting manifests by tag, but also permits returning the `UNSUPPORTED` error code for such requests. docker/distribution has never supported deleting manifests by tag, but previously returned `DIGEST_INVALID`.
The `Tag` and `Digest` fields of the `manifestHandler` are already correctly populated based on which kind of reference was given in the request URL. Return `UNSUPPORTED` if the `Tag` field is populated.
Signed-off-by: Adam Wolfe Gordon <awg@digitalocean.com>
> manifests: Return UNSUPPORTED when deleting manifests by tag

- reference/normalize.go
- reference/normalize_test.go
`regexp.DomainRegexp` matches mixed-case and uppercase strings without `.` as well. For example, in `/v2/SAMPLE/reponame/manifests/latest`, the route handler would match `SAMPLE` as `regexp.DomainRegexp` and `reponame` as `regexp.nameComponentRegexp`. To parse the normalized name, an uppercase or mixed-case string should be considered a valid domain.
Fixes #2858
Redis cache enabled path invokes `ParseNormalizedName` which produces an error because rather than matching `TESTNAME` to the domain like the router does, it matches `TESTNAME/reponame` to the name component.
> Fix bug in parsing domain from repository reference

- manifest/manifestlist/manifestlist.go
- manifest/manifestlist/manifestlist_test.go
Populate the platform information when calling the References() method of manifest list
Signed-off-by: Wenkai Yin <yinw@vmware.com>
> Populate the platform information when calling the References() method of manifest list

- context/logger.go
- registry/registry.go
- registry/registry_test.go
It's possible to configure log fields in the configuration file, and we would like these fields to be included in all logs. Previously these fields were included only in logs produced using the main routine's context, meaning that any logs from a request handler were missing the fields since those use a context based on the HTTP request's context.
Add a configurable default logger to the `context` package, and set it when configuring logging at startup time.
Signed-off-by: Adam Wolfe Gordon <awg@digitalocean.com>
> log: Include configured fields in all logs

- docs/spec/manifest-v2-2.md
The correct `vairant` string for ARM v6 is "v6", not "armv6l".
There is no known implementation that actually uses "armv6l".
See the discussion in https://github.com/opencontainers/image-spec/pull/817#discussion_r568107546
> docs/spec/manifest-v2-2.md: fix ARM variant

- configuration/configuration.go
- configuration/configuration_test.go
- docs/configuration.md
- registry/registry.go
- registry/registry_test.go
Configuration of list of cipher suites allows a user to disable use
of weak ciphers or continue to support them for legacy usage if they
so choose.
List of available cipher suites at:
https://golang.org/pkg/crypto/tls/#pkg-constants
Default cipher suites have been updated to:
- TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
- TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
- TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
- TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
- TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
- TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
- TLS_AES_128_GCM_SHA256
- TLS_CHACHA20_POLY1305_SHA256
- TLS_AES_256_GCM_SHA384
MinimumTLS has also been updated to include TLS 1.3 as an option
and now defaults to TLS 1.2 since 1.0 and 1.1 have been deprecated.
Signed-off-by: David Luu <david@davidluu.info>
> [backport release/2.7]Added flag for user configurable cipher suites

- .github/workflows/ci.yml
Fix the failure reported by git action
Package python-minimal is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
python2-minimal
E: Package 'python-minimal' has no installation candidate
> fix CI dependency error

- registry/registry.go
Fixes #3363
Without this, we emit illegal json logs, the user-agent
ends up as:
```
"http.request.useragent": "docker/19.03.4 go/go1.12.10 git-commit/9013bf583a kernel/5.10.10-051010-generic os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.4 \(linux\))"
```
which is not valid according to [spec](https://www.json.org/json-en.html)
specifically, string: "<any codepoint except " or \ or control>*"
Signed-off-by: Don Bowman <don@agilicus.com>
> fix: disable DisableHTMLEscape on logrus json logging

- .github/workflows/release.yaml
The secrets used in this workflow have been manually added by me to GitHub secrets on this repo. They will be changed once we sort out Docker Hub accounts and tokens, but the current creds work fine for pushing images to Docker Hub.
The idea is when we tag a release the image is automatically built from the tag ref and pushed to Docker Hub.
Signed-off-by: Milos Gajdos <milosgajdos83@gmail.com>
> Add docker image release workflow

- configuration/configuration.go
- docs/configuration.md
- registry/handlers/app.go
> Add configuration option for Redis TLS

- registry/storage/ocimanifesthandler.go
- registry/storage/ocimanifesthandler_test.go
- registry/storage/schema2manifesthandler.go
- registry/storage/schema2manifesthandler_test.go
According to OCI image spec, the descriptor's digest field is required.
For the normal config/layer blobs, the valivation should check the
presence of the blob when put manifest.
REF: https://github.com/opencontainers/image-spec/blob/v1.0.1/descriptor.md
Signed-off-by: Arko Dasgupta <arko.dasgupta@docker.com>
Signed-off-by: Wei Fu <fuweid89@gmail.com>
cc @dmcgowan @thaJeztah
> OCI: verify digest and check blob presence when put manifest

- registry/api/v2/errors.go
- registry/handlers/api_test.go
- registry/handlers/blobupload.go
- registry/handlers/helpers.go
Fixes #3141
1, return 416 for Out-of-order blob upload
2, return 400 for content length and content size mismatch
Signed-off-by: wang yan <wangyan@vmware.com>
> OCI: add content range handling in patch blob

- docs/configuration.md
Adds minimal documentation how to access pull-through cache stats exposed by `expvar` as discussed in https://github.com/distribution/distribution/issues/3407
> add documentation how to access pull-through proxy stats

- .github/workflows/fossa.yml
- README.md
Ref.: https://github.com/cncf/foundation/issues/109
Signed-off-by: Ihor Dvoretskyi <ihor@linux.com>
> FOSSA scan enabled

- docs/spec/api.md
- registry/api/v2/descriptors.go
- registry/api/v2/errors.go
- registry/handlers/tags.go
- registry/storage/tagstore.go
Adding pagination to the registry, which is required to live up to the OCI Distribution Specification.
This will also fix a bug with tags being returned in random orders.
Now supports pagination if the user requests it, otherwise return all tags.
fixes #3232 OCI Conformance: GET number of tags should be limitable by n query parameter
closes #1936
closes #2452.
> OCI: Add pagination on `/v2/<name>/tags/list`

- registry/api/v2/urls.go
- registry/api/v2/urls_test.go
- registry/handlers/api_test.go
Adds test coverage for https://github.com/distribution/distribution/pull/3143.
> Add tests for tags list pagination

- docs/spec/api.md
- notifications/listener_test.go
- registry/api/v2/descriptors.go
- registry/client/repository.go
- registry/client/repository_test.go
- registry/handlers/api_test.go
- registry/handlers/manifests.go
- registry/storage/tagstore.go
- registry/storage/tagstore_test.go
The tag delete API operation has finally made it to the OCI Distribution spec, in v1.0.0 ([source](https://github.com/opencontainers/distribution-spec/blob/v1.0.0/spec.md#deleting-tags)). This PR makes the required changes to incorporate such functionality.
Signed-off-by: João Pereira <484633+joaodrp@users.noreply.github.com>
> Add tag delete API

- docs/spec/api.md
The API spec is currently out of date, due to being manually updated instead of generated with `registry-api-descriptor-template`.
Signed-off-by: João Pereira <484633+joaodrp@users.noreply.github.com>
> Update API spec

- docs/spec/api.md
- registry/api/v2/descriptors.go
If `n` is not present only 100 entries returned
> fix the /v2/_catalog n parameter description

- docs/spec/api.md
- registry/api/v2/descriptors.go
The PUT and PATCH requests should return 201 and 202 respectively. 
Signed-off-by: Brandon Mitchell <git@bmitch.net>
> Fixing http status for PUT/PATCH APIs

- .github/workflows/conformance.yml
- .github/workflows/e2e.yml
- .github/workflows/fossa.yml
Make workflow jobs unique so we can manage which ones are required to pass the build.
Signed-off-by: Milos Gajdos <milosgajdos83@gmail.com>
> Make GH workflows job names unique

- MAINTAINERS
Sargun is a large user of Distribution at Netflix, and is interested
in helping maintain, especially around storage drivers.
Please note as per Governance, this must be approved by 8 of the existing maintainers.
> Propose Sargun as a maintainer

- .github/workflows/ci.yml
- Dockerfile
relates to https://github.com/distribution/distribution/pull/3466, as the updated github.com/golang-jwt/jwt v3.2.2 requires to 1.15 or 1.16
> [release/2.7] update to go1.16

- registry/storage/driver/s3-aws/s3.go
- registry/storage/driver/s3-aws/s3_test.go
fixes https://github.com/distribution/distribution/issues/3142
[(merged) PR digitalocean/docker-distribution #20](https://github.com/digitalocean/docker-distribution/pull/20)
**Overview**
These changes address a low level bug which at a minimum is causing the tag service `Untag` method to sometimes not delete the respective tag files as expected. After a lot of digging, the root cause was tracked down to an edge case that was not properly being handled in the S3 storage driver Delete implementation. 
Currently, the S3 storage driver Delete implementation lists all paths with a given prefix. To expand on this further, listing `{path}` gives expected results like `{path}` and `{path}/{subpath}` but may also give unwanted results of the form `{path}{suffix}` and `{path}{suffix}/{subpath}`. …
> Updated s3 delete to no longer noop under a rare edge case

- .github/workflows/ci.yml
- Dockerfile
- contrib/compose/README.md
corresponding PR for the 2.7 branch is https://github.com/distribution/distribution/pull/3472
fixes https://github.com/distribution/distribution/issues/3484
> Update to go 1.16, and run CI on 1.15.x and 1.16.x

- docs/spec/manifest-v2-2.md
We found some examples of manifests with URLs specififed that did
not provide a digest or size. This breaks the security model by allowing
the content to change, as it no longer provides a Merkle tree. This
was not intended, so explicitly disallow by tightening wording.
Signed-off-by: Justin Cormack <justin.cormack@docker.com>
> Change should to must in v2 spec

- releases/README.md
The existing link to the containerd release tool seems incorrect. Updating to containerd/release-tool, which I'm guessing is the correct location.
> docs: update release-tool link

- docs/spec/manifest-v2-2.md
backport of https://github.com/distribution/distribution/pull/3487
We found some examples of manifests with URLs specififed that did
not provide a digest or size. This breaks the security model by allowing
the content to change, as it no longer provides a Merkle tree. This
was not intended, so explicitly disallow by tightening wording.
Signed-off-by: Justin Cormack <justin.cormack@docker.com>
(cherry picked from commit 1660df4b605cab74deaf851e43de9df104aaa0cd)
Signed-off-by: Sebastiaan van Stijn <github@gone.nl>
> [release/2.7 backport] Change should to must in v2 spec

- registry/storage/driver/middleware/cloudfront/middleware.go
When updatefrequency is set and is a string, its value should be saved into updateFrequency, and it shouldn't override duration.
> updatefrequency should not be saved into duration

- registry/storage/driver/azure/azure.go
- registry/storage/driver/filesystem/driver.go
- registry/storage/driver/inmemory/driver.go
- registry/storage/driver/s3-aws/s3.go
- registry/storage/driver/s3-aws/s3_test.go
- registry/storage/driver/swift/swift.go
- registry/storage/driver/walk.go
- registry/storage/driver/walk_test.go
[(merged) PR digitalocean/docker-distribution](https://github.com/digitalocean/docker-distribution/pull/17)
blobstore enumeration with S3 storage driver (and possibly others with follow up effort) can be optimized by several orders of magnitude in most cases by offloading more work to the S3 API. In some cases this gives identical performance but in extreme cases, eg thousands of blobs in separate folders, this gives a huge performance boost. 
- Use `ListObjectsV2PagesWithContext` **without** `Delimiter`, giving all objects of subpaths in batches up to 1000
- Infer directories (no longer listed without `Delimiter` & recursive implementation) by comparing subsequent object paths of different subdirectories
- Keep track of skipped directory and manually skip over any objects under that …
> Optimize storagedriver/s3 Walk (up to ~500x) + small bugfix

- registry/handlers/manifests.go
The wording of the error message had a typo (missing the word "not") that gave it the opposite meaning from the intended meaning.
Signed-off-by: Chad Faragher <wyckster@hotmail.com>
> Fixed typo in error message

- contrib/token-server/main.go
- registry/handlers/app.go
G404: Replace math rand with crypto rand
> [release/2.7]fix go check issues

- vendor.conf
- vendor/github.com/opencontainers/image-spec/README.md
- vendor/github.com/opencontainers/image-spec/specs-go/v1/index.go
- vendor/github.com/opencontainers/image-spec/specs-go/v1/manifest.go
- vendor/github.com/opencontainers/image-spec/specs-go/version.go
(previous version vendored was v1.0.0)
full diff: https://github.com/opencontainers/image-spec/compare/ab7389ef9f50030c9b245bc16b981c7ddf192882...v1.0.2
> [release/2.7] vendor: github.com/opencontainers/image-spec v1.0.2

- vendor.conf
- vendor/github.com/dgrijalva/jwt-go/LICENSE
- vendor/github.com/dgrijalva/jwt-go/README.md
- vendor/github.com/dgrijalva/jwt-go/claims.go
- vendor/github.com/dgrijalva/jwt-go/ecdsa.go
- vendor/github.com/dgrijalva/jwt-go/ecdsa_utils.go
- vendor/github.com/dgrijalva/jwt-go/ed25519.go
- vendor/github.com/dgrijalva/jwt-go/ed25519_utils.go
- vendor/github.com/dgrijalva/jwt-go/hmac.go
- vendor/github.com/dgrijalva/jwt-go/map_claims.go
- vendor/github.com/dgrijalva/jwt-go/parser.go
- vendor/github.com/dgrijalva/jwt-go/rsa.go
- vendor/github.com/dgrijalva/jwt-go/rsa_pss.go
- vendor/github.com/dgrijalva/jwt-go/rsa_utils.go
- vendor/github.com/dgrijalva/jwt-go/token.go
relates to https://github.com/distribution/distribution/issues/3361
relates to https://github.com/distribution/distribution/pull/3459 (main branch)
alternative to https://github.com/distribution/distribution/pull/3465
closes https://github.com/distribution/distribution/pull/3465
~Using the https://github.com/form3tech-oss/jwt-go.git, which is actively maintained.~
~full diff: https://github.com/form3tech-oss/jwt-go/compare/a601269ab70c205d26370c16f7c81e9017c14e04...v3.2.4~
to address CVE-2020-26160
full diff: https://github.com/golang-jwt/jwt/compare/a601269ab70c205d26370c16f7c81e9017c14e04...v3.2.2
3.2.1 release notes
---------------------------------------
- Import Path Change: See MIGRATION_GUIDE.md for tips on updating your code
Changed the import path from github.com/dgrijalva/jwt-go …
> [release/2.7] github.com/golang-jwt/jwt v3.2.2

- configuration/parser.go
If you set an env var with non-yaml content but accidentally collides with a possible configuration env var,... 
The current error is
```
configuration error: error parsing /etc/docker/registry/config.yml: yaml: unmarshal errors:
line 1: cannot unmarshal !!str `tcp://1...` into configuration.Parameters
```
With this change we can see at least which is the problematic env var.
Some orchestrators such as docker-compose set env vars on top on user env vars, so debugging can be tricky if you are not passing vars, and the error is pointing you to a problably valid config file.
> Improve error message in case invalid env var found

- configuration/fuzz.go
- reference/fuzz.go
- registry/api/v2/fuzz.go
- script/oss_fuzz_build.sh
This PR adds 3 fuzzers for Distribution and a build script to run the fuzzers continuously through OSS-fuzz.
A PR has also been set up on the OSS-fuzz side to integrate Distribution: https://github.com/google/oss-fuzz/pull/6014. Two of the fuzzers that were committed on the OSS-fuzz side are moved upstream in this PR and a third fuzzer is added.
Once this PR gets merged, I will amend the changes on OSS-fuzz to invoke the build script in this PR.
For those unfamiliar with fuzzing and/or OSS-fuzz: Fuzzing (or fuzz testing) is a way of testing software whereby pseudo-random data is passed to a target application with the goal of finding bugs and vulnerabilities. It has been useful in finding bugs, including security-critical bugs, in many open source Go projects to date. Some can be found …
> Fuzzing: Add 3 fuzzers

- .github/workflows/build.yml
- Dockerfile
- docker-bake.hcl
follow-up https://github.com/distribution/distribution/pull/3552
degraded backport of https://github.com/distribution/distribution/pull/3315 to be able to trigger a release on `release/2.8` branch without artifacts releasing.
cc @milosgajdos @thaJeztah 
> [2.8] Release workflow

- registry/storage/driver/s3-aws/s3.go
- registry/storage/driver/s3-aws/s3_test.go
Some Amazon S3 Compatible Storage only supports the same part size（1M-5G） in the multipart upload, expect for the last part. And the last part must not be larger than the same part size.
We add a option `MultipartCombineSmallPart` to enable/disable combining the pending part 
Signed-off-by: Libo Huang <huanglibo2010@gmail.com>
> feat: add option to disable combining the pending part

- reference/regexp.go
This PR reduces the amount of `string -> *regexp.Regexp -> string` in reference Regexps. This conversion (especially the compilation is quite expensive both in memory and CPU usage.
This PR tries to be as minimal as possible by ensuring that the same regexps are exported (even those that are not really exported but just used in the same package) but I would be happy to change it to anything else if bigger changes are desired.
Signed-off-by: Paul Cacheux <paul.cacheux@datadoghq.com>
> Improve how reference regexps are built

- registry/proxy/proxyblobstore.go
ref: https://github.com/distribution/distribution/issues/3438
I found there are some changes after v2.7.1. That is the context will be passed into http request. It may be closed before commit layer into  local cache.
solved before:
solved:
> fix image cache incompletely

- .github/workflows/build.yml
- Dockerfile
- docker-bake.hcl
follow-up #3565
As discussed with @milosgajdos, we might need to also publish artifacts to GitHub Release like it's already done on the main branch. Will look like this:
```shell
docker buildx bake artifact
docker buildx bake artifact-all
```
Waiting for inputs from maintainers so keeping in draft for now.
> [2.8] Release artifacts

- .mailmap
- releases/v2.8.0.toml
- version/version.go
This PR contains release notes and version bump for `2.8.0` release.
This will be the last `v2.x` release -- no future development should be expected on `v2.x` branch; all focus will be on getting a `v3` release out next year.
The reasons why we've decided to go with `v2.8.0` release rather than with a patch release (`v2.7.2`) as originally intended in #3380 is that #3384 technically introduces a new feature that warrants a minor release.
> Prepare for v2.8.0 release

- .github/workflows/build.yml
- Dockerfile
- docker-bake.hcl
follow-up https://github.com/distribution/distribution/pull/3568 to be aligned with https://github.com/distribution/distribution/releases/tag/v2.8.0-beta.1
also update base image to alpine 3.15 like the official image: https://github.com/docker/distribution-library-image/blob/c70c2acb365928f10bfc7706cc0f3f4d16f7427b/Dockerfile#L1
cc @thaJeztah @milosgajdos 
> update build workflow

- registry/proxy/proxyblobstore_test.go
- registry/registry.go
- registry/registry_test.go
- registry/storage/purgeuploads_test.go
github code scan detects the insecure configurations of distribution.
This commit removes the following cipher suites that are known to be insecure:
TLS_RSA_WITH_RC4_128_SHA
TLS_RSA_WITH_AES_128_CBC_SHA256
TLS_ECDHE_ECDSA_WITH_RC4_128_SHA
TLS_ECDHE_RSA_WITH_RC4_128_SHA
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
And this commit deletes the tlsVersions of tls1.0 and tls1.1. The tls1.2 is the minimal supported tls version for creating a safer tls configuration.
Signed-off-by: baojiangnan <baojn1998@163.com>
> optimize: disable insecure cipher suites

- registry/storage/driver/inmemory/mfs.go
This issue was discovered by the following fuzzer:
https://github.com/cncf/cncf-fuzzing/blob/main/projects/distribution/inmemory_fuzzer.go#L24
Reproducing
To reproduce this issue, download the Minimized Testcase from the OSS-fuzz report, and follow the steps here: https://google.github.io/oss-fuzz/advanced-topics/reproducing/
Signed-off-by: Milos Gajdos <milosgajdos83@gmail.com>
> Fix: Avoid a false type assertion in the inmemory driver

- .golangci.yml
- context/http.go
- script/setup/install-dev-tools
This commit updates `golangci-lint` to `v1.44.0`.
It also removes deprecated [golint](https://github.com/golang/lint) in favour of [revive](https://github.com/mgechev/revive) linter.
Finally, it addresses an issue reported by linter: there is no need to check if a prefix contains a string, see `TrimFix` doc:
> // TrimPrefix returns s without the provided leading prefix string.
// If s doesn't start with prefix, s is returned unchanged.
Signed-off-by: Milos Gajdos <milosthegajdos@gmail.com>
> Update golangci-lint version and fix reports

- Dockerfile
- docker-bake.hcl
Discussed with @milosgajdos. Yesterday while releasing `v2.8.0` tag, version was still `v2.8.0-beta.1` because of the current working tree info. This PR solves that behavior in our CI by using the actual ref that triggers the workflow using the [`GITHUB_REF` env var](https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables).
Can be tested with:
```shell
GITHUB_REF=refs/tags/v5.0.0 docker buildx bake
```
cc @thaJeztah 
> ci: use proper git ref for versioning

- Dockerfile
- docker-bake.hcl
backport of #3585
cc @thaJeztah @milosgajdos 
(cherry picked from commit fabf9cd4e94c4d529b1904320b16f431bc599305)
> [2.8 backport] ci: use proper git ref for versioning

- .mailmap
- releases/v2.8.1.toml
- version/version.go
The previous release caused a bit of a [Go modules kerfuffle](https://github.com/distribution/distribution/issues/3590). Let's get this sorted in the patch release.
> Prepare for v2.8.1 release

- registry/storage/manifeststore_test.go
Looks like a copy-paste bug from the same test for the image manifest.
> Incorrect variable in test output

- .github/CODE_OF_CONDUCT.md
- GOVERNANCE.md
Fill in the code of conduct rather than linking to CNCF code of conduct to list available escalation points related to this project.
> Remove duplicate code of conduct

- docs/configuration.md
- registry/storage/driver/s3-aws/s3.go
- registry/storage/driver/s3-aws/s3_test.go
Rebase of https://github.com/docker/distribution/pull/2166 due to inactivity
Original PR comment:
I've added an optional parameter to enable S3 Transfer acceleration for the S3 storage driver. Thank you very much for considering the change.
If s3accelerate is set to true then we turn on S3 Transfer Acceleration via the AWS SDK. It defaults to false since this is an opt-in feature on the S3 bucket.
Signed-off-by: Kirat Singh <kirat.singh@wsq.io>
> Add new parameter accelerate to S3 storage driver.

- docs/configuration.md
- docs/storage-drivers/s3.md
- registry/storage/driver/s3-aws/s3.go
- registry/storage/driver/s3-aws/s3_test.go
At present, most s3 api compatibility modes have supported DNS based bucket routing Moreover, some manufacturers only support DNS based bucket routing. So I extracted this parameter.
Previously, when using `regionendpoint`, it was not rigorous to use force path style in hard coding.
However, in order to ensure backward compatibility, I set the default value of `forcepathstyle` to `true`
> Add forcepathstyle parameter for s3

- docs/spec/auth/oauth.md
Fixes link rendering in HTML portion of the OAuth docs by converting
them to anchor tags.
Signed-off-by: hasheddan <georgedanielmangum@gmail.com>
Follow up to https://github.com/distribution/distribution/pull/3410
> (docs) Fix rendering of markdown links in OAuth docs HTML

- registry/storage/driver/s3-aws/s3.go
- registry/storage/driver/s3-aws/s3_test.go
Closes #3612
Omits 'GLACIER'|'DEEP_ARCHIVE' storage classes, as they are not instant and therefore not suitable for the registry
> Support all S3 instant retrieval storage classes

- go.mod
The replace rule was removed in ec47096efc3b2803b00ff053f9e703e632875b2d (https://github.com/distribution/distribution/pull/3642), so this comment no longer applies.
(my bad; forgot to remove it as part of that PR 😅
> go.mod: remove outdated comment

- Dockerfile
- backport of https://github.com/distribution/distribution/pull/3649
- addresses https://github.com/distribution/distribution/issues/3648
(cherry picked from commit 9f2bc25b7accaa578ea5431b750f8c19a42df1b5)
> [release/2.8 backport] Fix CVE-2022-28391 by bumping alpine from 3.14 to 3.16

- docs/deploying.md
Documentation improvement. It took me almost an hour to track down https://github.com/distribution/distribution/issues/2817#issuecomment-762736783 as the reason my private Docker registry was not working, because of the lack of any error message pointing to the cause.
Relates to https://github.com/distribution/distribution/issues/2817, but does not really solve it. In my opinion, a full solution to that issue would involve Docker Registry outputting a relevant error message when the incorrect credential type is used, rather than silently accepting it and then failing all login attempts.
This is a copy of https://github.com/docker/docker.github.io/pull/14544 since per https://github.com/docker/docker.github.io/pull/14544#issuecomment-1097692369 this repository has the official reference …
> Explain important caveat in htpasswd tutorial

- docs/notifications.md
The example shows a `GET` request to `/callback`, but it looks like it's
intending to show the `POST` request made by the registry to a
notificaitons endpoint. Unless I'm missing something, no `GET` request
should be involved.
> Change GET in example request to POST

- reference/normalize_test.go
- reference/reference.go
- reference/reference_test.go
- reference/regexp.go
- reference/regexp_test.go
registry: support ipv6 addresses
Current registry reference use a subset of dns and IPv4 addresses to
represent a registry domain.
Since registries are mostly compatible with rfc3986, that defines the
URI generic syntax, this adds support for IPv6 enclosed in squared
brackets based on the mentioned rfc, but excluding zone identifiers
as defined by rfc6874 or special addresses such as IPv4-Mapped)
Ref: https://github.com/kubernetes/kubernetes/issues/104491
This builds on top of previous PRs
- Allow IPv6 address literals in DomainRegexp distribution/distribution#2899
- Add IPv6 support for domain parsing distribution/distribution#2575
Kudos to those persons for showing the path
> Ipv6 registries

- registry/api/v2/routes.go
`(*App).context`, called in the HTTP handler on each request, creates a
`URLBuilder`, which involves calling `Router()`. This shows up in profiles a
hot spot because it involves compiling the regexps which define all the
routes. For efficiency, cache the router and return the same object each
time.
It appears to be safe to reuse the router because `GetRoute` is the only
method ever called on the returned router object.
> Do not recreate mux router for each incoming request

- registry/client/auth/session.go
- registry/client/blob_writer.go
- registry/client/blob_writer_test.go
- registry/client/repository.go
This simple change mainly affects the distribution client. By respecting
the context the caller passes in, timeouts and cancellations will work
as expected. Also, transports which rely on the context (such as tracing
transports that retrieve a span from the context) will work properly.
> Use http.NewRequestWithContext for outgoing HTTP requests

- configuration/configuration_test.go
These tests don't validate if options are valid for the storage-driver,
nor do they test if the storage-driver itself is valid. However, the tests
were using actual values (such as s3) and options (such as "region") which
may lead to the conclusion that it's also testing validity of those values.
This patch replaces the test-values with non-existing driver-names and
options to make it more clear these are fake values.
> configuration: use "fake" values for tests

- BUILDING.md
Easier to see what build tags there are and what they are used for.
> Add build tags to BUILDING.md

- CONTRIBUTING.md
As the project has transitioned from Docker to CNCF, clean up the
contributing.md to reflect that:
- CNCF slack
- CNCF maintainers
- Use with other container tools
Fixes #3550
> Review contributing for Docker references

- docs/configuration.md
- go.mod
- go.sum
- notifications/listener_test.go
- registry/client/repository.go
- registry/handlers/app.go
- registry/handlers/app_test.go
- registry/proxy/proxyblobstore_test.go
- registry/proxy/proxymanifeststore_test.go
- registry/storage/blob_test.go
- registry/storage/cache/memory/memory.go
- registry/storage/cache/memory/memory_test.go
- registry/storage/catalog_test.go
- registry/storage/manifeststore_test.go
- vendor/github.com/hashicorp/golang-lru/.gitignore
- vendor/github.com/hashicorp/golang-lru/2q.go
- vendor/github.com/hashicorp/golang-lru/LICENSE
- vendor/github.com/hashicorp/golang-lru/README.md
- vendor/github.com/hashicorp/golang-lru/arc.go
- vendor/github.com/hashicorp/golang-lru/doc.go
- vendor/github.com/hashicorp/golang-lru/lru.go
- vendor/github.com/hashicorp/golang-lru/simplelru/lru.go
- vendor/github.com/hashicorp/golang-lru/simplelru/lru_interface.go
- vendor/modules.txt
Instead of letting the cache grow without bound, use a LRU to impose a
size limit.
The limit is configurable through a new `blobdescriptorsize` config key.
> registry/storage/cache/memory: Use LRU cache to bound cache size

- registry/storage/linkedblobstore.go
- registry/storage/registry.go
- registry/storage/tagstore.go
This reverts commit 06a098c632aee74619a06f88c23a06140f442a6f (pull request: https://github.com/distribution/distribution/pull/864)
This changes the function of linkedBlobStatter.Clear(). It was either removing the first of two possible manifest links or returning nil if none were found. Now it once again it removes only the valid manifest link or returns an error if none are found.
This adresses #3122
Signed-off-by: Bracken Dawson <abdawson@gmail.com>
> Remove workaround from 2.1.1 for faulty 2.1.0 manifest links

- registry/client/transport/http_reader.go
- reverts https://github.com/distribution/distribution/pull/2015
This revisits fix provided regarding https://github.com/moby/moby/pull/25122
According to https://www.rfc-editor.org/rfc/rfc9110.html#name-content-encoding
> If the media type includes an inherent encoding, such as a data format that is always compressed, then that encoding would not be restated in Content-Encoding even if it happens to be the same algorithm as one of the content codings.
So, an image layer, served with media type `application/vnd.oci.image.layer.v1.tar+gzip` should not get any additional `Content-Encoding` header set until http server is misconfigured.
Using a preventive `Accept-Encoding: identity` allows to avoid such a misconfiguration to have consequences on image transfert, but on the other hand …
> Revert "registry/client: set Accept: identity header when getting layers

- registry/storage/driver/s3-aws/s3.go
- registry/storage/driver/s3-aws/s3_test.go
- registry/storage/driver/storagedriver.go
Instead of first collecting all S3 keys first and then batch deleting them, we will do incremental delete _online_ per max allowed batch. Doing this prevents frequent `Go` heap allocations for large S3 keyspaces.
**NOTE:** we also make sure we Skip `S3` tests for `List` unless explicitly triggered.
> Delete S3 keys incrementally in batches

- configuration/parser.go
Without this, the log message for the user indicates a problem with the
yaml file, so identifying the actual error is hard. This change fixes
the output so that the incorrect environment variable is easy to spot.
Fixes #3653
> Raise a specific error for env var parsing issues

- docs/spec/api.md
Last is not an integer, but is the last returned value to start the
pagination from.
Recreate of #3672 and #3673 with a signed DCO.
> Fix API doc parameter placeholder: last

- reference/normalize.go
- reference/normalize_test.go
- reference/regexp.go
- reference/regexp_test.go
The "shortid" syntax was added in https://github.com/moby/moby/commit/d26a3b37a6a8d42b9e7cb7486b928170c43e052e (https://github.com/moby/moby/pull/799), and allowed for matching an image on its ID prefix (this is before images were content-addressable). With the introduction of content-addressable references, this syntax became problematic, and Docker deprecated this syntax in 2016 (Docker v1.13.0) through commit; https://github.com/moby/moby/commit/5fc71599a0b77189f0fedf629ed43c7f7067956c (https://github.com/moby/moby/pull/27207):
> The `repository:shortid` syntax for referencing images is very little used,
> collides with tag references, and can be confused with digest references.
Support for this syntax was removed in 2017 (Docker 17.12) through commit: …
> reference: remove support for deprecated "shortid" refs

- reference/reference.go
Forward-porting the patch from https://github.com/containerd/containerd/commit/694a007543fafe751cbfab07093ba1b3ae58f1b6 (https://github.com/containerd/containerd/pull/5922)
> reference: replace deprecated function SplitHostname

- BUILDING.md
The current doc says to use go get to pull the source code, which no
longer works by default on recent versions of go. Also, the makefile has
changed to not run all the validation automatically, and to use buildx
for some commands.
Fixes #3659
Fixes #3592 
> Update the BUILDING.md to a world with modules

- manifest/schema1/config_builder.go
- registry/storage/linkedblobstore_test.go
- registry/storage/paths.go
- relates to https://github.com/opencontainers/go-digest/pull/83
Both of these were deprecated in https://github.com/opencontainers/go-digest/commit/55f675811a1b915549933c64571fd86b2676ba76 (https://github.com/opencontainers/go-digest/pull/33), but the format of the GoDoc comments didn't follow the correct format, which caused them not being picked up by tools as "deprecated".
This patch updates uses in the codebase to use the alternatives.
> Remove uses of deprecated go-digest.NewDigestFromHex, go-digest.Digest.Hex

- configuration/parser.go
- context/http.go
- reference/normalize.go
- registry/api/v2/urls.go
- registry/auth/token/accesscontroller.go
- registry/auth/token/token.go
- registry/client/repository.go
- registry/handlers/helpers.go
- registry/handlers/hooks.go
- registry/storage/driver/middleware/cloudfront/s3filter.go
- registry/storage/driver/storagedriver.go
- registry/storage/driver/swift/swift.go
Go 1.18 and up now provides a strings.Cut() which is better suited for
splitting key/value pairs (and similar constructs), and performs better:
```go
func BenchmarkSplit(b *testing.B) {
b.ReportAllocs()
data := []string{"12hello=world", "12hello=", "12=hello", "12hello"}
for i := 0; i < b.N; i++ {
for _, s := range data {
_ = strings.SplitN(s, "=", 2)[0]
}
}
}
func BenchmarkCut(b *testing.B) {
b.ReportAllocs()
data := []string{"12hello=world", "12hello=", "12=hello", "12hello"}
for i := 0; i < b.N; i++ {
for _, s := range data {
_, _, _ = strings.Cut(s, "=")
}
}
}
```
BenchmarkSplit
BenchmarkSplit-10            8244206               128.0 ns/op           128 B/op          4 allocs/op
BenchmarkCut
BenchmarkCut-10             54411998                21.80 ns/op            0 B/op          0 …
> replace strings.Split(N) for strings.Cut() or alternatives

- blobs.go
- notifications/listener.go
- registry/client/repository.go
- registry/client/transport/http_reader.go
- registry/proxy/proxyblobstore.go
- registry/proxy/proxyblobstore_test.go
- registry/storage/blobstore.go
- registry/storage/linkedblobstore.go
Go's io package in stdlib now defines this interface, so we can switch to using that instead. Also doing some minor cleanup.
The remaining use of this interface is removed in https://github.com/distribution/distribution/pull/3787
> deprecate ReadSeekCloser in favor of io.ReadSeekCloser

- manifest/ocischema/builder_test.go
- manifest/schema1/config_builder_test.go
- manifest/schema2/builder_test.go
- registry/proxy/proxytagservice_test.go
Embed the interface that we're mocking; calling any of it's methods that are not implemented will panic, so should give the same result as before.
> simplify mocks

- reference/normalize_test.go
- reference/reference_test.go
- reference/regexp_test.go
- reference/sort_test.go
This replaces the "self-made" subtests with native Go subtests, which makes sure that all test-cases are ran (instead of failing early), and helped with debugging (allows for individual tests to be run).
> reference: rewrite various tests to use subtests

- reference/helpers.go
- reference/normalize.go
- reference/reference.go
- reference/regexp.go
- reference/sort.go
⚠️ for reviewers: best to review this commit-by-commit
This PR:
- moves more regular expressions to be a const
- renames / introduces some variables to better match the grammar or to be more descriptive
- updates some documentation comments to describe regular expressions
- removes some abstraction; the package tried to abstract away regular expression patterns with utilities, but in doing so became a bit of a "regular expression generating machine". The verbosity of these utilities sometimes drowned the actual intent. I tried to reduce verbosity, but maintain readability by using descriptive variable and const-names.
- Moves exported regexes separate from the non-exported ones, and moves them to their own "var" declarations, which allows them to be documented separately (including the …
> reference: clean up regular expressions

- manifest/manifestlist/manifestlist_test.go
- manifest/ocischema/manifest.go
- manifest/ocischema/manifest_test.go
- manifest/schema1/manifest.go
- manifest/schema1/manifest_test.go
- manifest/schema2/manifest.go
- manifest/schema2/manifest_test.go
- registry/storage/manifeststore_test.go
- testutil/manifests.go
- testutil/tarfile.go
Extracting this from a branch I'm working on;
- Fix some variables that collided with imports
- Use consts for fixed values 
- Improve test-output for some compares to assist in debugging;
manifest: improve test output and use const
Use consts to make clear these values are fixed, and improve the output
to make it clearer which part is the expected output, and which part
the actual.
Before this:
=== RUN   TestManifest
manifest_test.go:87: manifest bytes not equal: "{\n   \"schemaVersion\": 2,\n   \"mediaType\": \"application/vnd.oci.image.manifest.v1+json\",\n   \"config\": {\n      \"mediaType\": \"application/vnd.oci.image.config.v1+json\",\n      \"size\": 985,\n      \"digest\": \"sha256:1a9ec845ee94c202b2d5da74a24f0ed2058318bfa9879fa541efaecba272e86b\",\n      \"annotations\": {\n …
> minor fixes and enhancements

- blobs.go
- docs/notifications.md
- docs/spec/manifest-v2-2.md
- manifest/manifestlist/manifestlist_test.go
- manifest/ocischema/builder_test.go
- manifest/ocischema/manifest_test.go
- manifest/schema1/config_builder_test.go
- manifest/schema1/manifest.go
- manifest/schema2/builder_test.go
- manifest/schema2/manifest_test.go
- notifications/bridge.go
- notifications/event_test.go
I am looking at aligning the types defined in this repository with the
OCI image specification, and potentially exchanging local types with
those from the specification.
This patch is a stepping-stone towards that effort, but as this changes
the format of the serialized JSON, I wanted to put this up first before
proceeding with the other work in case there are concerns.
> Descriptor: align field order with OCI image specification

- configuration/configuration.go
- docs/spec/manifest-v2-1.md
- manifest/schema1/config_builder.go
- manifest/schema1/manifest.go
- manifest/schema1/reference_builder.go
- manifest/schema1/sign.go
- manifest/schema1/verify.go
- testutil/manifests.go
- relates to https://github.com/distribution/distribution/pull/1068
- relates to https://github.com/moby/moby/pull/42300
- relates to https://github.com/moby/moby/pull/39384
- relates to https://github.com/containerd/containerd/pull/6884
- relates to https://github.com/docker/roadmap/issues/173
- https://github.com/distribution/distribution/pull/3000
Docker Image manifest v2, schema version 1 is deprecated since 2015, when manifest v2, schema version 2 was introduced (2e3f4934a73b27c22ae8966549e11920ffb28b81 (https://github.com/distribution/distribution/pull/1068)).
Users should no longer use this specification other than for backward compatibility.
With this PR, all functions are highlighted as deprecated, and linters will trigger a deprecation warning when importing the package and when …
> manifest/schema1: mark docker manifest v2, schema 1 deprecated

- reference/regexp.go
It looks like the current expression accepts an empty string as a valid separator.
Context: I was attempting to use this regex in a different language and it was hanging on certain inputs. I'm guessing that allowing empty string as a separator here causes pathological behaviors in some regex implementations. Digging around related context, it looks like the intention here was to allow for one or more dashes, and not to accept empty strings.
At the moment, separator is only used here:
```
pathComponent = alphanumeric + anyTimes(separator+alphanumeric)
```
But since alphanumeric is defined as `[a-z0-9]+`, anything that matched with the empty string behavior should still match.
Signed-off-by: Chris K. Wong <chriskw.xyz@gmail.com>
> Fix separator regex to disallow empty strings

- ADOPTERS.md
Using double newlines in markdown makes it easier to read in markdown readers, e.g github
> add double newlines in ADOPTERS.md

- registry/storage/driver/s3-aws/s3.go
If you are running behind a MITM proxy, this allows for the AWS S3 driver to respect the AWS_CA_BUNDLE environment variable.
> Support AWS_CA_BUNDLE when talking to the S3 API

- .github/workflows/fossa.yml
This release contains only a change that updates the runtime that will be deprecated, so it's safe to update.
https://github.com/fossa-contrib/fossa-action/releases/tag/v2.0.0
> Update fossa-contrib/fossa-action action to v2

- registry/storage/driver/s3-aws/s3.go
The loop that iterates over paginated lists of S3 multipart upload parts appears to be using the wrong variable in its loop condition. Nothing inside the loop affects the value of `resp.IsTruncated`, so this loop will either be wrongly skipped or loop forever.
It looks like this is a regression caused by commit 7736319f2ed49768b9d9eb832465a1317dd0b106. The return value of `ListMultipartUploads` used to be assigned to a variable named `resp`, but it was renamed to `partsList` without updating the for loop condition.
I believe this is causing an error we're seeing with large layer uploads at commit time:
upload resumed at wrong offset: 5242880000 != 5815706782
Missing parts of the multipart S3 upload would cause an incorrect size calculation in `newWriter`.
> Fix S3 multipart upload pagination loop condition

- contrib/token-server/token.go
- registry/auth/token/token.go
- registry/auth/token/token_test.go
- registry/auth/token/types.go
- registry/auth/token/types_test.go
- registry/auth/token/util.go
> Accept list of strings in audience claim in token auth

- configuration/configuration_test.go
- configuration/parser_test.go
- registry/storage/driver/azure/azure_test.go
- registry/storage/driver/filesystem/driver_test.go
- registry/storage/driver/middleware/redirect/middleware_test.go
Dot-imports were only used in a couple of places, and replacing them makes it more explicit what's imported.
> remove dot-imports for gopkg.in/check.v1

- registry/client/errors.go
- registry/client/errors_test.go
This fixes error caused by requesting a push token with the "Public repo read-only" permission not being correctly parsed into a typed error.
> registry/errors: Parse http forbidden as denied

- reference/normalize_test.go
- reference/regexp_bench_test.go
- relates to https://github.com/distribution/distribution/pull/3803
BenchmarkParse
BenchmarkParse-10    	   12696	     93805 ns/op	    9311 B/op	     185 allocs/op
PASS
> reference: rewrite test to use sub-tests, add benchmark

- registry/registry.go
Rebase of https://github.com/distribution/distribution/pull/3109
> When configuring bugsnag, bugsnag will fork the process, resulting the port 5001 listened twice. The PR fix this error by moving the initialization of prometheus server after the configuration of bugsnag
>
> Upstreamed from Docker Hub
> Fix the issue that the debug server with port 5001 run twice

- .github/workflows/ci.yml
- registry/storage/driver/s3-aws/s3.go
- backport of https://github.com/distribution/distribution/pull/2815
> [release/2.8] Add code to handle pagination of parts. Fixes max layer size of 10GB bug

- Dockerfile
- backport of https://github.com/distribution/distribution/pull/3910
(cherry picked from commit 435c7b9a7b7ab6c7e44325d6460fb00270ac77cf)
> [release/2.8 backport] Dockerfile: fix filenames of artifacts

- registry/client/transport/http_reader.go
This reverts commit 16f086a0ec1e6158375ab34eb9c716a3f99b26f5.
see https://github.com/distribution/distribution/pull/3754
> [release/2.8 backport] revert "registry/client: set Accept: identity header when getting layers

- registry/client/errors.go
- registry/client/errors_test.go
Backport: https://github.com/distribution/distribution/pull/3881
(cherry picked from commit 5f1df02149bf03f93cd7747ad740a38891fd4b20)
> [release/2.8 backport] registry/errors: Parse http forbidden as denied

- manifest/schema2/builder.go
- manifest/schema2/builder_test.go
- testutil/manifests.go
Rebase from https://github.com/distribution/distribution/pull/2782
> This PR aims to close https://github.com/distribution/distribution/issues/2150 by removing blobstore from schema2 manifest builder.
>
> The builder now take configuration Descriptor as parameter instead of a blobstore and media type.
@milosgajdos friendly ping since you were the one to review the original PR.
> Remove blobstore from manifest builder

- registry/storage/driver/azure/azure.go
- registry/storage/driver/azure/azure_test.go
- registry/storage/driver/testsuites/testsuites.go
The registry [storage driver health check calls `Stat(app, "/")`](https://github.com/distribution/distribution/blob/main/registry/handlers/app.go#L376). For Azure, this call is currently broken.
This PR fixes the call and add test coverage for it.
Also fix a couple of unrelated tests which were broken on main (see commits for details).
Fixes #3931.
> registry/storage/driver: test call to Stat(ctx, "/")

- docs/recipes/mirror.md
Signed-off-by: David Karlsson <david.karlsson@docker.com>
Clarify the restriction that pull-through mirrors must use the root of a domain with no path components.
See: https://github.com/docker/docs/issues/17414
> docs: note restriction on URL format of mirrors

- Dockerfile
See discussion in https://github.com/distribution/distribution/issues/3919.
> It looks like this might have happened by mistake in https://github.com/distribution/distribution/pull/3903. [The Dockerfile used to build the v2.8.1 tag](https://github.com/distribution/distribution/blob/v2.8.1/Dockerfile#L31) clearly passes the BUILDTAGS argument to Go's build command, which no longer is the case for [the Dockerfile used to build the v2.8.2 tag](https://github.com/distribution/distribution/blob/v2.8.2/Dockerfile#LL30C1-L30C1).
Maintainers, please let me know if basing on `release/2.8` is not the right way to do this, and I'll update my PR accordingly.
Fixes #3919
> Pass `BUILDTAGS` argument to `go build`

- docs/spec/api.md
- registry/api/v2/descriptors.go
This simply fixes a typo in `registry/api/v2/descriptors.go` which sets the wrong content type at the body of `RouteNameBlobUpload`.
Also fixes a similar typo in the docs.
> Fix Content type octet stream typos

- configuration/configuration.go
- configuration/configuration_test.go
- registry/registry.go
Add options in config.yaml to enable caller log
After enabling this option in config.yaml, the caller information can be displayed in each log item like that
```
INFO[0000]/home/user/goworkdir/src/github.com/distribution/distribution/registry/handlers/app.go:1085 github.com/distribution/distribution/v3/registry/handlers.startUploadPurger.func1() Starting upload purge in 0s                   go.version=go1.18 instance.id=d2d965f5-2277-4128-80b4-201b7cf5c47f service=registry version=v3.0.0+unknown
``` 
It is helpful to diagnostic.
> Add option to enable caller information in logger

- registry/handlers/app.go
this error doesn't show up anywhere, so when the healthcheck does error the cause is often very mysterious.
> registry/handlers/app: log healthcheck error before return

- BUILDING.md
- Dockerfile
- dockerfiles/lint.Dockerfile
- registry/storage/driver/gcs/gcs.go
- registry/storage/driver/gcs/gcs_test.go
- registry/storage/driver/oss/oss.go
- registry/storage/driver/oss/oss_test.go
It would appear we are missing the Go build tags so the binary packaged in the image built from the source in this repo  would miss support for some storage drivers causing breakages to end users trying to use them.
This PR enables Go build tags so the GCS and OSS driver support is available in the binary distributed via the image build by Dockerfile.
This led to quite a few fixes in the GCS and OSS packages raised as warnings by `golang-ci` linter.
> Enable Go build tags

- configuration/configuration.go
- docs/configuration.md
- docs/recipes/mirror.md
- registry/proxy/proxyblobstore.go
- registry/proxy/proxyblobstore_test.go
- registry/proxy/proxymanifeststore.go
- registry/proxy/proxymanifeststore_test.go
- registry/proxy/proxyregistry.go
Currently when registry is run as proxy it tries to cleanup unused blobs from its cache after 7 days which is hard-coded. This PR makes that value configurable. One can disable caching using this option. 
Continue #3238
Fixes #2736
Fixes #2367
Fixes #3704
Fixes #3879
> Option to configure proxy cache TTL

- registry/storage/driver/middleware/redirect/middleware.go
- registry/storage/driver/middleware/redirect/middleware_test.go
This patch enable us to use path in redirect middleware.
Currently, redirect middleware respects only scheme and host.
But actually our S3-Compatible storage needs this features for redirect to object storage endpoint.
and I believe this should be useful also for other users.
Related: #3022
> Make redirect middleware can use path

- configuration/configuration.go
- configuration/configuration_test.go
- docs/configuration.md
- registry/registry.go
Copy of #3464  with updated tests
> Added support for specifying ACME-server by using REGISTRY_HTTP_TLS_LETSENCRYPT_DIRECTORYURL

- manifest/manifestlist/manifestlist.go
- manifest/ocischema/index.go
- manifest/ocischema/index_test.go
- manifest/ocischema/manifest.go
- manifest/ocischema/manifest_test.go
- registry/storage/manifestlisthandler.go
- registry/storage/manifeststore.go
- registry/storage/manifeststore_test.go
- registry/storage/ociindexhandler.go
- registry/storage/registry.go
Move implementation of the index from the manifestlist package to the ocischema package so that other modules making empty imports support the manifest types their authors would expect. This is a breaking change to distribution as a library but not the registry.
As OCI 1.0 released the manifest and index together, that is a good package from which to initialise both manifests. The docker manifest and manifest list remain in separate packages because one was released later.
The image index and manifest list still share common code in many functions not intended for import by other modules.
This now supports (omits) empty platform objects in OCI Image Indices.
This adds support for annotations on OCI Image Indices.
fixes #3836 
fixes #2652
> Split OCI Image Index from Docker Manifest List

- docs/spec/api.md
Currently the formatting of example JSON is a bit inconsistent. This PR makes sure they are all formatted using a 4 space indent, and resolves some minor syntax errors.
> Fix json formatting in registry api docs

- configuration/configuration.go
- configuration/configuration_test.go
- registry/handlers/app.go
Redis introduced an Access Control List (ACL) mechanism since version 6.0. This commit implements the necessary changes to support configuring the username for Redis. Users can now define a specific username to authenticate with Redis and enhance security through the ACL feature.
> feat: added support for redis username configuration

- registry/handlers/app.go
> Drop docker prefix from storage driver API user agent

- .github/workflows/build.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/conformance.yml
- .github/workflows/e2e.yml
- .github/workflows/fossa.yml
- .github/workflows/validate.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
> GitHub Workflows security hardening

- registry/proxy/proxymanifeststore_test.go
- testutil/push.go
This PR is another step towards the elimination of `schema v1` support in `distribution` (see https://github.com/distribution/distribution/issues/3966).
This PR removes `schema1` package references from the `proxy` package.
**NOTE:** it duplicates `testutil/push.go` file that's also introduced in https://github.com/distribution/distribution/pull/3976. Depending on which PR gets merged first we'll update the other one accordingly.
> Remove references to schema1 pacakge from proxy package

- registry/storage/cache/cachedblobdescriptorstore.go
Split request and hit metrics into separate metrics, rather than using
labels. This avoids duplication of data and makes metric math easier.
* Count cache errors separately to avoid weird math.
* Hit ratio: `registry_storage_cache_hits_total / registry_storage_cache_requests_total`
* Miss ratio: `1 - (registry_storage_cache_hits_total / registry_storage_cache_requests_total`
* Misses: `registry_storage_cache_requests_total -
registry_storage_cache_hits_total`
> Cleanup storage cache metrics

- notifications/bridge_test.go
- notifications/event_test.go
- notifications/http_test.go
- notifications/listener_test.go
- testutil/push.go
This PR is a step towards the elimination of `schema v1` support in `distribution` (see https://github.com/distribution/distribution/issues/3966).
This PR removes `schema1` package references from the `notifications` package.
> Remove references to schema1 pacakge from notifications package

- registry/client/blob_writer.go
Client ReadFrom doesn't set Content-Type header leading to server side implementor to assume it's application/octet-stream. This commit makes this explicit on the client side.
Closes #3965
> Set Content-Type header in registry client ReadFrom

- go.mod
For some reason, we let these get ungrouped and mixed all over the place.
This PR groups direct and indirect Go module dependencies.
> Regroup direct and indirect dependencies

- registry/storage/catalog.go
- registry/storage/catalog_test.go
I believe we should revert #3902.
This change is detrimental to any storage driver that doesn't present as a filesystem. The change moves from using the driver walk function to treating every driver like a filesystem. For example, the walk function is able to return multiple directories with one API Call.
In a quick test on S3, with #3902 merged a request for a list of 1000 repos makes at least 1000 api calls to S3, where before it was around 10.
The right approach to making this more efficient is to pass the walk function a start hint, which I show in #3685. With that mechanism merged we can use the hint in the walk fallback to optimise the search.
This PR was claimed to fix #3233, but #3233 was already closed because the conformance tests were green. It can stay closed unless a further …
> Revert 3902

- registry/storage/driver/s3-aws/s3.go
- relates to https://github.com/distribution/distribution/pull/3927
This was added for the other drivers in 6b388b1ba604bf5b970bbb41878f97cc3fc93376 (https://github.com/distribution/distribution/pull/3950), but it missed the s3 storage driver.
> s3: add interface assertion

- registry/client/repository_test.go
We've replaced all the schema1 references with OCI schema manifest in the next step towards https://github.com/distribution/distribution/issues/3966
Note, there are some TODO items that must be addressed at some point in the future once the schema1 package is removed completely from the codebase.
> Remove schema1 references from registry client

- .github/workflows/scorecards.yml
- README.md
Closes #3738 
Hi, as discussed in the #3738 here are the changes that enable the [Scorecard GitHub Action](https://github.com/ossf/scorecard-action) and the [badge](https://openssf.org/blog/2022/09/08/show-off-your-security-score-announcing-scorecards-badges/).
There is no rush on this and you can take your time to review. 
In case of doubts or concers just reach me out and I'll help the best I can.
> Enable OpenSSF Scorecard Github Action

- .github/workflows/ci.yml
- BUILDING.md
- Dockerfile
- Makefile
- registry/storage/driver/gcs/gcs.go
- registry/storage/driver/gcs/gcs_test.go
- registry/storage/driver/oss/oss.go
- registry/storage/driver/oss/oss_test.go
- registry/storage/driver/s3-aws/s3.go
backports:
- backport https://github.com/distribution/distribution/pull/3950
- backport https://github.com/distribution/distribution/pull/4008
- fixes https://github.com/distribution/distribution/issues/3919
And rebases https://github.com/distribution/distribution/pull/3927 to get the remaining changes
> [release/2.8 backport] Enable Go build tags

- README.md
Hi, just a minor fix to the link attached to the badge: now the OpenSSF Scorecard has a much better viewer to understand the results:
https://securityscorecards.dev/viewer/?uri=github.com/distribution/distribution
Thanks!
> Scorecard Badge Viewer Improvement

- registry/client/blob_writer_test.go
- registry/client/errors.go
- registry/client/errors_test.go
- registry/client/repository_test.go
Client attempts to parse the body of every error it receives as `JSON` regardless of the `Content-Type`.
This PR rectifies that by only parsing the error body as `JSON` if the `Content-Type header` is set to either `application/json` or `application/vnd.api+json`.
Closes https://github.com/distribution/distribution/issues/3962
> Dont parse errors as JSON unless Content-Type is set to JSON

- registry/handlers/app.go
It seems the `username` is lost in https://github.com/distribution/distribution/pull/4019
> Add username to create redis client

- registry/storage/catalog.go
- registry/storage/catalog_test.go
- registry/storage/driver/azure/azure.go
- registry/storage/driver/base/base.go
- registry/storage/driver/filesystem/driver.go
- registry/storage/driver/gcs/gcs.go
- registry/storage/driver/inmemory/driver.go
- registry/storage/driver/s3-aws/s3.go
- registry/storage/driver/s3-aws/s3_test.go
- registry/storage/driver/storagedriver.go
- registry/storage/driver/walk.go
- registry/storage/driver/walk_test.go
- registry/storage/paths.go
Pass the last paging flag to storage drivers
Storage drivers may be able to take advantage of the hint to start
their walk more efficiently.
For S3: The API takes a start-after parameter. Registries with many
repositories can drastically reduce calls to s3 by telling s3 to only
list results lexographically after the last parameter.
For the fallback: We can start deeper in the tree and avoid statting
the files and directories before the hint in a walk. For a filesystem
this improves performance a little, but many of the API based drivers
are currently treated like a filesystem, so this drastically improves
the performance of GCP and Azure blob.
Fixes #3678 
> Work with the storage driver to minimise work when paging

- reference/reference.go
- backport of https://github.com/distribution/distribution/pull/3776
- relates to https://github.com/distribution/distribution/pull/4031
> [release/2.8 backport] reference: replace deprecated function SplitHostname

- registry/storage/driver/s3-aws/s3.go
Only some of the S3 storage driver calls were propagating `context` to the S3 API calls. This PR updates the S3 storage driver so the `context` is propagated to all the S3 API calls by using `WithContext` SDK calls.
> Propagate storage driver context to S3 API calls

- registry/handlers/api_test.go
It was used for signing `schema v1` manifests in tests which have now been removed so there is no point in keeping these there anymore.
`libtrust` imports are now limited to `auth` package only replacement of which will be the subject of this issue https://github.com/distribution/distribution/issues/1820
> Remove libtrust from handler tests

- registry/client/blob_writer_test.go
- registry/client/errors.go
- registry/client/errors_test.go
- registry/client/repository_test.go
- backport of https://github.com/distribution/distribution/pull/4013
- fixes https://github.com/distribution/distribution/issues/3962
- related to https://github.com/moby/moby/issues/46006
Client attempts to parse the body of every error it receives as JSON regardless of the content-type. This commit rectifies by only parsing he error body as JSON if the Content-Type header is set to either "application/json" or "application/vnd.api+json".
(cherry picked from commit 45b7b9cec3a45cbf3343ce773fd5c88bc50f8a7f)
> [release/2.8 backport] Dont parse errors as JSON unless Content-Type is set to JSON

- registry/client/blob_writer.go
- backport of https://github.com/distribution/distribution/pull/3981
- fixes https://github.com/distribution/distribution/issues/3965
- addresses https://github.com/moby/moby/issues/46006#issuecomment-1645389961
Client ReadFrom doesn't set Content-Type header leading to server side implementor to assume it's application/octet-stream. This commit makes this explicit on the client side.
(cherry picked from commit 24de708d229e4b67fb434151895e909f31aa08e6)
> [release/2.8 backport] Set Content-Type header in registry client ReadFrom

- registry/client/auth/session.go
- registry/client/blob_writer.go
- registry/client/errors.go
- registry/client/errors_test.go
- registry/client/repository.go
- relates to / follow-up to https://github.com/distribution/distribution/pull/4013
The SuccessStatus acted on the response's status code, and was used to return early, before checking the same status code with HandleErrorResponse.
This patch combines both functions into a HandleHTTPResponseError, which returns an error for "non-success" status-codes, which simplifies handling of responses, and makes some logic slightly more idiomatic.
> registry/client: combine SuccessStatus and HandleErrorResponse

- registry/proxy/proxyblobstore.go
- registry/proxy/proxyblobstore_test.go
I read through the code of proxyBlobStore. I found that the logic of ServeBlob could be optimized. We don't need to request twice for the same blob when caching it.
> optimize: avoid redundant blob fetching

- docs/configuration.md
- docs/recipes/index.md
- docs/recipes/systemd.md
- go.mod
- go.sum
- registry/listener/listener.go
- vendor/github.com/coreos/go-systemd/v22/LICENSE
- vendor/github.com/coreos/go-systemd/v22/NOTICE
- vendor/github.com/coreos/go-systemd/v22/activation/files_unix.go
- vendor/github.com/coreos/go-systemd/v22/activation/files_windows.go
- vendor/github.com/coreos/go-systemd/v22/activation/listeners.go
- vendor/github.com/coreos/go-systemd/v22/activation/packetconns.go
- vendor/modules.txt
Since version 3.4, podman supports systemd socket-activation.  Socket activation can allow starting containers with `--network=none` for improved security, and speeds up boot time by deferring application startup to be on-demand.
This patch will detect socket-activation and use it automatically if available.
Both unix-domain-sockets and TCP sockets are supported
> Support systemd socket-activation

- .gitignore
- BUILDING.md
- Makefile
- README.md
- cmd/registry/config-dev.yml
- tests/conf-local-cloud.yml
- tests/docker-compose-storage.yml
This PR adds a couple of new `make` targets that let you spin a local cloud storage environment with [min.io](https://min.io/).
This lets you interact with an S3-compatible storage API. See the updated `BUILDING.md` document on how to get started.
Ideally, we integrate this into our CI pipeline soon, but there are still some failing tests in S3 driver that need addressing before we update our GHA workflows. This PR merely adds the environment setup targets.
Requirements:
* A [`docker compose`](https://docs.docker.com/compose/) compatible tool
> Add make targets to allow starting local cloud storage environment.

- registry/storage/driver/testsuites/testsuites.go
Add two new checks to the testsuite that check
the driver can handle zero byte files and appends to zero byte files correctly.
These tests, when applied to the release/2.8 branch will show up flaws in the swift driver, which we use for the Brightbox docker repository.
They may show up flaws in other drivers as well, and hence why we thought it would be valuable to push them upstream.
> driver testsuite: Add zero byte file checks

- registry/storage/blobstore.go
- registry/storage/linkedblobstore.go
`BlobReadService` does not exist, `BlobProvider` is the the suitable interface that it implemented.
> fix comment typos

- registry/storage/tagstore.go
In terms of results, a`manifestTagsPathSpec{ name: "repo" }` equals `manifestTagPathSpec{ name: "repo", tag: "" }`, but from the intention, the `manifestTagsPathSpec` should be used.
> use manifestTagsPathSpec for listing all tags

- registry/storage/driver/s3-aws/s3.go
This PR attempts to optimise the performance of image push in the S3 driver. There are 2 main changes:
* we refactor the S3 driver `writer` where instead of using simple bytes slices for `ready` and `pending` parts which get constantly appended data into them causing unnecessary allocations we use optimised bytes buffers; we make sure these are used efficiently
* we introduce a memory pool that is used for allocating the byte buffers introduced above
These changes should alleviate high memory pressure on the push path to S3 especially when large images (layers) are pushed to the S3 store.
Related PR:
* https://github.com/distribution/distribution/pull/3798
> Optimise push in S3 driver

- docs/configuration.md
Initially I misunderstood that the debug endpoint has to be disabled in production environments. That's why I created https://github.com/distribution/distribution/issues/4084 and https://github.com/distribution/distribution/issues/4085. But it turns out that the docs want to state the the debug endpoint should not be exposed publicly to the internet.
This PR adds few more sentences to clarify further.
> Add few more sentences for the debug endpoint

- docs/configuration.md
Incorrect section indentation of the `prometheus` section in the docs confuses some folks. This commit fixes that by indenting the `prometheus` section under the `debug` configuration section.
This is more visible in the [docs published by Docker inc](https://docs.docker.com/registry/configuration/#prometheus).
Closes https://github.com/distribution/distribution/issues/2935
> Properly indent prometheus docs

- .github/dockerhub-readme.yml
- cmd/registry/config-dev.yml
- docs/dockerhub.md
This PR
* adds a new docs page (`docs/dockerhub.md`) that contains the new contents of the `README` for [`distribution/distribution` Docker Hub repository](https://hub.docker.com/r/distribution/distribution)
* updates the default configuration file that gets baked into the docker image which is published to Docker Hub -- there are a ton of options that produce a lot of logs that confuse the users who are just getting started with the image we distribute via the Docker Hub
* updates the CI with a new workflow job that keeps Docker Hub README in sync with the contents of the `docs/dockerhub.md` file
Closes https://github.com/distribution/distribution/issues/4014
> Update Docker Hub README and keep it in sync with this repository.

- registry/storage/cache/redis/redis.go
This commit removes some `conn` parameters of private functions, which can be obtain from the struct itself. The `conn` is for the old `redisgo` library, which is replaced by `go-redis` in #4019.
> refactor redis cache

- docs/configuration.md
- docs/storage-drivers/s3.md
- registry/storage/driver/s3-aws/s3.go
- registry/storage/driver/s3-aws/s3_test.go
based on the work from https://github.com/distribution/distribution/pull/3057.
---
I have run the s3 tests locally and here's a sample output with `loglevel: logdebug`
```
-----------------------------------------------------
2023/09/27 16:49:15 DEBUG: Request s3/PutObject Details:
---[ REQUEST POST-SIGN ]-----------------------------
PUT /var/folders/p0/c1z2jht90l99pg75kvywwyfw0000gn/T/TestListObjectsV23912336142/001/test-list-objects-v2/3 HTTP/1.1
Host: redacted.s3.eu-north-1.amazonaws.com
User-Agent: aws-sdk-go/1.44.325 (go1.21.0; darwin; amd64) s3aws-test
Content-Length: 23
Authorization: AWS4-HMAC-SHA256 Credential=redacted/20230927/eu-north-1/s3/aws4_request, SignedHeaders=content-length;content-md5;content-type;host;x-amz-acl;x-amz-content-sha256;x-amz-date;x-amz-storage-class, …
```
> registry: add loglevel support for aws s3 storage driver

- docs/spec/auth/jwt.md
This blank line confuses the markdown parser to think
that this is an indented code block.
Before:
After:
Signed-off-by: David Karlsson <35727626+dvdksn@users.noreply.github.com>
> docs: remove blank line

- docs/spec/auth/jwt.md
This blank line confuses the markdown parser to think
that this is an indented code block.
Signed-off-by: David Karlsson <35727626+dvdksn@users.noreply.github.com>
(cherry picked from commit 6183f230920c6bfd907a7fad1270bcb0c1baf317)
> [release/2.8 backport] docs: remove blank line

- .github/workflows/dockerhub-readme.yml
https://github.com/distribution/distribution/pull/4087 added the `dockerhub-readme` workflow into `.github` path from where it can not be triggered:
https://docs.github.com/en/actions/using-workflows/triggering-a-workflow
> GitHub searches the .github/workflows directory in your repository for workflow files that are present in the associated commit SHA or Git ref of the event.
This PR addresses it and updates the workflow paths to the correct values.
> Move dockerhub-readme workflow to the correct path

- manifest/ocischema/index.go
- manifest/ocischema/index_test.go
- manifest/ocischema/manifest.go
- manifest/ocischema/manifest_test.go
`distribution.Descriptor` defined a field `annotation`, but `distribution.UnmarshalManifest` output `descriptor` cannot get the annotation.
We should fill the field correctly.
> Add annotation for descriptor

- .github/workflows/docs.yml
- docker-bake.hcl
- dockerfiles/docs.Dockerfile
We are missing GH pages setup step in the docs GHA
I went down the rabbit hole of GH pages and came across this:
* https://github.com/actions/upload-pages-artifact/issues/6
Which made me think we may be missing this:
* https://github.com/actions/starter-workflows/blob/b1df8a546ed4d0f27d46aaf2f8ac1118bc522638/pages/hugo.yml#L46-L48
We also rename `dockerhub.md` to `distirbution.md`.
> Update docs GHA and renamed a doc file

- .github/workflows/dockerhub-readme.yml
We were missing GitHub checkout step before running the update which is now causing the CI to fail on merge to `main` with the following error:
```
Error: ENOENT: no such file or directory, open './docs/dockerhub.md'
```
> Update dockerhub-readme GH Action

- registry/storage/driver/base/base.go
- registry/storage/driver/errors_test.go
- registry/storage/driver/storagedriver.go
This adds a small bit of refactoring of `storagedriver` errors as a followup to the discussion in https://github.com/distribution/distribution/pull/4099
This PR changes the `Enclosed` field of `storagedriver.Error` to `Detail` and makes sure `storagedriver.Errors` gets properly serialized to JSON. We also add tests.
> refactor: Storage driver errors

- reference/regexp_deprecated.go
- relates to https://github.com/distribution/distribution/pull/4031
An incorrect alias snuck into 152af63ec5c569f074e9cf5d0e409d6928e034d8 (https://github.com/distribution/distribution/pull/4031), and DomainRegexp was aliased to the regex for digests (DigestRegexp).
This didn't affect this repository, as it didn't use the aliases and migrated to the new module, but does affect user of the old module that depend on the aliases.
> reference: fix broken alias for DomainRegexp

- reference/regexp_deprecated.go
- backport of https://github.com/distribution/distribution/pull/4113
- relates to / introduced in https://github.com/distribution/distribution/pull/4031
- relates to https://github.com/distribution/distribution/pull/4063
An incorrect alias snuck into 152af63ec5c569f074e9cf5d0e409d6928e034d8 (https://github.com/distribution/distribution/pull/4031), and DomainRegexp was aliased to the regex for digests (DigestRegexp).
This didn't affect this repository, as it didn't use the aliases and migrated to the new module, but does affect user of the old module that depend on the aliases.
(cherry picked from commit c8c2bc279cee5d3f81e589d59ca02e683e650835)
> [release/2.8 backport] reference: fix broken alias for DomainRegexp

- .github/workflows/ci.yml
- Dockerfile
- partial backport of https://github.com/distribution/distribution/pull/4116
---
go1.20.9 (released 2023-10-05) includes one security fixes to the cmd/go package,
as well as bug fixes to the go command and the linker. See the Go 1.20.9
milestone on our issue tracker for details:
https://github.com/golang/go/issues?q=milestone%3AGo1.20.9+label%3ACherryPickApproved
full diff: https://github.com/golang/go/compare/go1.20.8...go1.20.9
From the security mailing:
[security] Go 1.21.2 and Go 1.20.9 are released
Hello gophers,
We have just released Go versions 1.21.2 and 1.20.9, minor point releases.
These minor releases include 1 security fixes following the security policy:
- cmd/go: line directives allows arbitrary execution during build
"//line" directives can be used to bypass the …
> [release/2.8 backport] update to go1.20.10

- registry/storage/blobwriter.go
- registry/storage/driver/azure/azure.go
- registry/storage/driver/azure/azure_test.go
- registry/storage/driver/filesystem/driver.go
- registry/storage/driver/gcs/gcs.go
- registry/storage/driver/gcs/gcs_test.go
- registry/storage/driver/inmemory/driver.go
- registry/storage/driver/s3-aws/s3.go
- registry/storage/driver/storagedriver.go
- registry/storage/driver/testsuites/testsuites.go
This PR changes `storagedriver.Filewriter` interface by adding `context.Context` as an argument to the `Commit` interface func.
We pass the context appropriately where need be throughout the `distribution` codebase to all the writers and tests.
In the case of the S3 storage driver we pass the `context` down to the driver `writer` and update all the AWS SDK calls in the `writer` with their `WithContext` variant. See this PR for more context (pun intended): https://github.com/distribution/distribution/pull/4066
PTAL @corhere, would love to get your thoughts/ideas on this.
> Add context to storagedriver.(Filewriter).Commit()

- context/context.go
- context/http.go
- context/trace.go
- go.mod
- internal/client/repository_test.go
- notifications/bridge.go
- notifications/bridge_test.go
- registry/registry.go
- registry/storage/linkedblobstore.go
- registry/storage/purgeuploads.go
- registry/storage/purgeuploads_test.go
Our own package wasn't adding anything.
> Switch to github.com/google/uuid

- docs/content/about/configuration.md
- metrics/prometheus.go
- registry/proxy/proxymetrics.go
If registry is configured as pull-through cache the following proxy related prometheus metrics are exposed:
- `registry_proxy_requests_total` - total incoming proxy request received for blob/manifest
- `registry_proxy_hits_total` - total proxy request hits for blob/manifest
- `registry_proxy_misses_total` - total proxy request misses for blob/manifest
- `registry_proxy_pulled_bytes_total` - total bytes pulled from the upstream for blob/manifest
- `registry_proxy_pushed_bytes_total` - total bytes pushed to the client for blob/manifest
> Add prometheus proxy related metrics

- .github/workflows/build.yml
- .github/workflows/e2e.yml
- Makefile
- tests/conf-e2e-cloud-storage.yml
- tests/docker-compose-e2e-cloud-storage.yml
This PR:
* includes storage integration tests in the CI build matrix
* adds a new CI job that runs E2E tests backed by S3 storage driver
> ci: add cloud storage driver integration tests to CI

- registry/handlers/api_test.go
- registry/handlers/app.go
- registry/root.go
- registry/storage/driver/azure/azure.go
- registry/storage/driver/azure/azure_test.go
- registry/storage/driver/factory/factory.go
- registry/storage/driver/filesystem/driver.go
- registry/storage/driver/gcs/gcs.go
- registry/storage/driver/inmemory/driver.go
- registry/storage/driver/middleware/cloudfront/middleware.go
- registry/storage/driver/middleware/cloudfront/middleware_test.go
- registry/storage/driver/middleware/cloudfront/s3filter.go
- registry/storage/driver/middleware/cloudfront/s3filter_test.go
- registry/storage/driver/middleware/redirect/middleware.go
- registry/storage/driver/middleware/redirect/middleware_test.go
- registry/storage/driver/middleware/storagemiddleware.go
- registry/storage/driver/s3-aws/s3.go
- registry/storage/driver/s3-aws/s3_test.go
- Related to #4110 
Make it possible to cancel constructing storage drivers and storage middlewares e.g. if they block making network requests.
> Plumb contexts into storage driver factories and middlewares

- registry/storage/driver/s3-aws/s3.go
This tiny PR makes the S3 driver chunk size constants more straightforward to understand -- instead of remembering the bit shifts we make this more explicit.
We are also updating `appendParam` of the `(writer).Write` to follow the new convention we are trying to establish: `appendMode`.
> cleanup: make chunk sizes easier to understand and change writer append

- .github/workflows/build.yml
This enables pushing distribution images into GHCR.
**NOTE:** This is in addition to the Docker Hub push which remains in place unchanged
Closes https://github.com/distribution/distribution/issues/4125
PTAL @crazy-max 😄
> feat: push distribution images to GHCR

- registry/storage/driver/gcs/gcs_test.go
- registry/storage/driver/middleware/cloudfront/s3filter_test.go
- registry/storage/driver/middleware/redirect/middleware.go
- registry/storage/driver/middleware/redirect/middleware_test.go
- registry/storage/driver/s3-aws/s3_test.go
For some unknown reason, https://github.com/distribution/distribution/pull/4128 passed the CI build even though it was missing various func parameters. This PR fixes those issues.
PTAL @corhere @thaJeztah
> fix: fix broken build

- registry/storage/driver/gcs/gcs.go
This refactors GCS storage driver from the ground up and makes it a bit more consistent with the rest of the storage drivers.
Notably, the `writer` now contains a reference to the `driver` in a similar fashion the S3 writer is implemented.
Some of the "helper" funcs were removed and others were made methods on specific GCS driver objects. This simplifies the code quite a bit and gets it more aligned with other storage driver implementations in this repository. 
**NOTE:** There is more work to be done but I figured this could be a first step hence the PR is marked as a _DRAFT_ at the moment
CC: @flavianmissi @jmontleon @kaovilai since you were the OG authors of the recent GCS driver update. Would you mind having a look and if you have a way to test it somewhere in GCS that'd be grand. I've …
> refactor: gcs storage driver

- registry/proxy/proxyblobstore.go
- registry/proxy/proxyblobstore_test.go
- registry/proxy/proxymanifeststore.go
- registry/proxy/proxymanifeststore_test.go
- registry/proxy/proxymetrics.go
If registry is configured as pull through cache the reported proxy statistics are incorrect.
Fixes #4044.
> Fix proxy statistics

- docs/content/recipes/mirror.md
I noticed a typo when reading the docs
> docs: fix typo in mirror.md

- Dockerfile
This is not necessary to make this mount writable. This will improve cache efficiency as well.
> dockerfile: keep context mount as read only

- registry/api/errcode/errors.go
- registry/storage/cache/memory/memory.go
- registry/storage/cache/redis/redis.go
If the reference in the API request exceeds the threshold allowed by the reference package (**NOTE:** this isn't defined by distribution specification, only the `tag` length has a limit set to 128 see [here](https://github.com/opencontainers/distribution-spec/blob/main/spec.md#pull)) we return 500 back to the client.
This commit makes sure we return `400` and the explanation of the error in the returned JSON payload.
Fixes: https://github.com/distribution/distribution/issues/2670
Example:
```shell
$ curl "http://localhost:5000/v2/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/manifests/aaaaaaaaaaaaaaa …
```
> fix: if reference exceeds max threshold return 400 and detail

- .golangci.yml
- internal/dcontext/trace_test.go
- registry/storage/driver/errors_test.go
This linter both prevents parallel test races as well as suggests parallel tests where appropriate:
See: https://github.com/moricho/tparallel
**NOTE:** the updated tests in this PR are the result of running the new linter
> feat: add tparallel linter to improve handling (parallel) tests

- health/api/api.go
- health/health.go
- internal/client/auth/challenge/authchallenge.go
- notifications/metrics.go
- registry/api/v2/descriptors.go
- registry/auth/auth.go
- registry/auth/htpasswd/access.go
- registry/auth/silly/access.go
- registry/auth/token/accesscontroller.go
- registry/proxy/proxyblobstore_test.go
- registry/proxy/proxymetrics.go
- registry/storage/driver/middleware/cloudfront/middleware.go
- registry/storage/driver/middleware/redirect/middleware.go
- registry/storage/driver/testsuites/testsuites.go
We make sure they're not hiding at the bottom or in the middle which makes debugging an utter nightmare!
> cleanup: move init funcs to the top of the source

- docs/content/recipes/mirror.md
It is wrong to state that:
> Only the central Hub can be mirrored.
The proxy (pull-through cache) supports mirroring any upstream registry (GCR, ECR, Quay, etc.).
The gotcha is rather that you can mirror only one upstream registry.
> Update the gotcha in the proxy guide

- registry/storage/driver/s3-aws/s3.go
- registry/storage/driver/s3-aws/s3_test.go
Unfortunately one of the changes we merged (https://github.com/distribution/distribution/pull/3841) broke the support for [http.ProxyFromEnvironment](https://pkg.go.dev/net/http#ProxyFromEnvironment) that was provided when we used the `distribution` client `transport` package.
This PR attempts to fix that by cloning the `http.DefaultTransport` and updating it accordingly.
Fixes: https://github.com/distribution/distribution/issues/4112
> fix: use http.DefaultTransport in S3 client

- registry/handlers/app.go
We are overriding whatever value is set in the storage driver `useragent` config.
Let's.....NOT do that and only override it if it's not set.
PTAL @Jamstah @thaJeztah
> fix: don't override storage driver useragent if it's set

- docs/content/storage-drivers/s3.md
We were missing documentation for some of the configuration options.
> update: S3 driver docs

- docs/content/storage-drivers/s3.md
- registry/storage/driver/s3-aws/s3.go
- registry/storage/driver/s3-aws/s3_test.go
This reverts https://github.com/distribution/distribution/pull/3556
This feature is currently broken and requires more fundamental changes in the S3 driver. Until then it's better to remove it.
See https://github.com/distribution/distribution/pull/3940 for more detail about why we're doing this.
> fix: remove disabling of multipart combine small parts

- releases/v3.0.0.toml
- version/version.go
The amount of changes since the last release is rather overwhelming.
The full changelog has been compiled using https://github.com/containerd/release-tool
@distribution/distribution-maintainers PTAL
> release: prep for the v3 alpha-1 release

- Makefile
- registry/handlers/app.go
- registry/registry.go
- tracing/tracing.go
- version/get.go
- version/version.go
- version/version.sh
Future-proof the version package's exported interface by only making the data available through getter functions. This affords us the flexibility to e.g. implement them in terms of ["runtime/debug".ReadBuildInfo()](https://pkg.go.dev/runtime/debug#ReadBuildInfo) in the future (if [go issue 50603](https://go.dev/issue/50603) is ever resolved).
> version: export getter functions

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
This adds a GH issue template as discussed in https://github.com/distribution/distribution/pull/4200
To get started it mostly borrows from the `moby/moby`
PTAL @thaJeztah @corhere @Jamstah
> feat: add GH issue template

- README.md
At some point we renamed the build workflow from `CI` to `build` but forgot to update the build status badge link in the readme 😓  
This PR fixes that. Click on the following URL to verify the fix is working: https://github.com/distribution/distribution/workflows/build/badge.svg?branch=main&event=push
> fix: build status badge

- docs/content/recipes/mirror.md
I was reading https://distribution.github.io/distribution/recipes/mirror/#gotcha when I noticed some unexpected annotations after the "fair use policy" link:
```md
...Docker’s fair usage policy{: target=“blank” rel=“noopener” class=“”}.
```
According to [Stack Overflow](https://stackoverflow.com/a/4705645/6571327), these are kramdown options that the current hugo documentation site isn't respecting. I searched the hugo docs and couldn't find an easy way to preserve `rel="noopener" target="_blank"` behavior, so I removed the annotation.
> docs: remove legacy kramdown options from link

- .github/labeler.yml
This PR adds a labeler action that automatically adds labels to PRs based on matched paths (see [here](https://github.com/actions/labeler)).
We can do some quite elaborate things but this is an initial PR to kickstart a conversation about how we want the new PRs to be labelled. TBC.
PTAL @thaJeztah
> feat: add PR labeler

- .mailmap
- AUTHORS
- Makefile
- docker-bake.hcl
- dockerfiles/authors.Dockerfile
Generate authors and update mailmap. As best effort I took linked authors from https://github.com/moby/moby/blob/master/.mailmap and https://github.com/containerd/containerd/blob/main/.mailmap
> chore: generate authors and update mailmap

- docker-bake.hcl
- dockerfiles/vendor.Dockerfile
Since Buildx 0.8.0 we can use the `no-cache-filter` opt.
> chore: use no-cache-filter for outdated stage

- .github/workflows/docs.yml
Fixes artifact fetching failure by ensuring compatibility with actions/artifact@v4
https://github.com/actions/upload-pages-artifact/releases/tag/v3.0.0
Signed-off-by: David Karlsson <35727626+dvdksn@users.noreply.github.com>
> build(deps): bump actions/upload-pages-artifact from 2 to 3

- blobs.go
- manifest/ocischema/builder_test.go
- manifest/schema1/config_builder_test.go
- manifest/schema2/builder_test.go
- notifications/listener.go
- registry/client/repository.go
- registry/client/transport/http_reader.go
- registry/proxy/proxyblobstore.go
- registry/proxy/proxyblobstore_test.go
- registry/proxy/proxytagservice_test.go
- registry/storage/blobstore.go
- registry/storage/linkedblobstore.go
backport of:
- https://github.com/distribution/distribution/pull/3787
- https://github.com/distribution/distribution/pull/3788
relates to:
- https://github.com/distribution/distribution/pull/4245
back porting these so that (if another 2.8.x patch release is done), we can give a warning out to users that this will be removed in v3
> [release/2.8 backport] deprecate ReadSeekCloser in favor of io.ReadSeekCloser

- .github/workflows/build.yml
- .github/workflows/conformance.yml
- .github/workflows/docs.yml
- .github/workflows/e2e.yml
carry and closes #4233 
This handles provenance for built artifacts and disable provenance when generating docs.
See https://github.com/distribution/distribution/actions/runs/7501643046/job/20422754661?pr=4253#step:9:40
> build(deps): bump docker/bake-action from 2 to 4

- blobs.go
- internal/client/transport/http_reader.go
- follow-up to https://github.com/distribution/distribution/pull/3788
- relates to / depends on https://github.com/distribution/distribution/pull/4244
These were deprecated in 019ead86f5603e5b1b3a7afd4bb7cbcdab2613e9 and d71ad5b3a6be14e002d130db9b9703732eee42e8, and are no longer in use in our code.
> remove deprecated ReadSeekCloser interfaces

- Dockerfile
We changed what we print in the version info in https://github.com/distribution/distribution/pull/4204
But we haven't updated the `Dockerfile`. This PR fixes that.
The output now:
```shell
$ make image
docker buildx bake --set "*.tags=distribution/distribution:latest" image-local
[+] Building 77.7s (22/22) FINISHED                                                                                                                                                                                                                                   
...
...
$ docker run -it distribution/distribution --version
registry github.com/distribution/distribution/v3 3.0.0-alpha.1-13-gfb6ccc33.m
```
> fix: update Dockerfile version output

- .github/labeler.yml
- .github/workflows/label.yaml
Whilst in https://github.com/distribution/distribution/pull/4205 we added labels to GHA config, we forgot to add the actual action doing the labelling 🤦‍♂️ 
We are also adding a label for `area/cache`
This PR fixes that. PTAL @thaJeztah
> fix: add labeler action

- .github/labeler.yml
Fixes https://github.com/distribution/distribution/actions/runs/7542009683/job/20529895576?pr=4248
From my PR here https://github.com/distribution/distribution/pull/4248
> chore: Remove duplicate `area/ci` entry in PR labeler

- .github/labeler.yml
Missed this in https://github.com/distribution/distribution/pull/4256
`charts/registry/config/**/*` doesn't exist so I'm assuming this should be only `configuration`. Kept the top entry so everything is nicely sorted
> chore: Remove `area/config` duplicate entry in `labeler.yml`

- .github/labeler.yml
The PR labeler workflow uses v5 of the action but with a v4 configuration so it fails.
This should fix it (I think), see https://github.com/actions/labeler/tree/17086b774338d2689ada0d8fcc8c51b5c9bc782a#breaking-changes-in-v5
> chore: Migrate PR labeler config to v5

- .github/workflows/docs.yml
- docker-bake.hcl
- dockerfiles/docs.Dockerfile
- docs/content/about/configuration.md
- docs/content/about/deploying.md
- docs/content/about/garbage-collection.md
- docs/content/about/insecure.md
- docs/content/about/notifications.md
- docs/content/recipes/apache.md
- docs/content/recipes/mirror.md
- docs/content/recipes/nginx.md
- docs/content/spec/_index.md
- docs/content/spec/api.md
- docs/content/spec/auth/oauth.md
- docs/content/spec/auth/scope.md
- docs/content/spec/auth/token.md
- docs/content/spec/manifest-v2-2.md
- docs/content/storage-drivers/inmemory.md
- docs/hugo.yaml
- docs/layouts/_default/_markup/render-link.html
- Replaces #4243
- closes #4243
- Added a Markdown rendering hook for Hugo to handle relative links like they're handled on GitHub. This means you'll be able to view the source markdown files on GitHub directly and still follow links like they work when viewing the deployed HTML pages.
- Fixed broken internal links that weren't being detected before as a result of using absolute links.
- Simplified the documentation build steps by setting a static base url in the Hugo configuration.
The third change is optional, but makes things a little bit simpler. Simple is good I think. A side-effect of this change is that docs will be served locally on a sub-path (`localhost:1313/distribution`) to mimic the production deployment.
> docs: add rendering hook and fix broken links

- registry/storage/driver/s3-aws/s3.go
A small code refactoring.
`len(dirs) > 0` is redundant because `range` already skips empty slice.
> refactor(storage/s3): remove redundant len check

- registry/handlers/api_test.go
- registry/handlers/manifests.go
The `GetManifest` handler is used for both `HEAD` and `GET` requests. For `HEAD` requests, the handler also calls `w.Write()` on the response writer.
This is not needed as HEAD requests should not include a response body. Most clients will actually just ignore the body, for example `curl` does this and simply skips it.
This PR adds a check to the `GetManifest` handler to return early when the request method is a `HEAD`. This would prevent wasting  resources writing to the response writer.
The `ServeBlob` method of the `blobServer` uses the standard library `http.ServeContent` [which internally has a check ](https://github.com/golang/go/blob/master/src/net/http/fs.go#L382) to only copy the result if the request method is not `HEAD`. So this change will follow the same approach as the blobs …
> Do not write manifests on HEAD requests

- go.mod
- registry/storage/driver/base/base.go
- tracing/exporter.go
- tracing/exporter_test.go
- tracing/tracing.go
This PR introduces `OpenTelemetry` tracing capabilities into the base(storage driver) component.
> [otel-tracing] Added Tracing to Base package (driver)

- tracing/loggerwriter.go
- tracing/tracing.go
Fixes #4275 
**Before**:
**After**:
cc @corhere , @milosgajdos for review
> Standardize OTEL error logging format to match application logs

- docs/content/storage-drivers/gcs.md
- registry/storage/driver/gcs/gcs.go
Hi! GCS storage driver does not support redirect URLs _only_ when configured to use application default credentials. Supporting this case looks useful in general and makes GCS driver behaviour consistent (currently, changing the configuration from using service account key to using default credentials may have an unexpected effect of making registry forward data increasing its' load).
This PR adds support and documentation for using redirects with default credentials. Since it was a very small change I've created the PR directly.
Sadly adding this isn't backward compatible - if someone is running a registry on a vm with default credentials and has left 'redirect' unconfigured then this PR is going to break their setup - after an upgrade they would start receiving errors if required IAM …
> Support redirects in gcs storage with default credentials

- registry/proxy/proxymetrics.go
Proxy prometheus metrics introduced in #4047 uses labeled counters.
With this PR, counters values are initialized to 0 to mitigate the issue of missing metrics after a registry restart, as recommended [here](https://github.com/prometheus/client_python/discussions/952#discussioncomment-6972244).
For more details related to the issue see [Created Timestamps](https://github.com/prometheus/proposals/blob/main/proposals/2023-06-13_created-timestamp.md) proposal.
> Initialize proxy prometheus counters values to 0

- internal/client/errors.go
- internal/client/errors_test.go
HEAD requests for instance return no body while still having all the relevant Content-Type headers set, causing unnecessary parsing errors. This skips further parsing for all requests that don't have any body to begin with.
Augments #4013.
> Don't try to parse error responses with no body

- .github/workflows/scorecards.yml
It seems the new version of Scorecard fixed this error. It seems it was caused by a infrastructure change on Sigstore Cosign used by Scorecard to sign the result artifact before publishing.
Thanks for pinging me!
> @joycebrum this has started failing in this repo and I've no idea why. The verbosity of the log is pretty wild. Mind having a look?
_Originally posted by @milosgajdos in https://github.com/distribution/distribution/issues/3740#issuecomment-2018801221_
> Upgrade Scorecard Action version to fix error 

- registry/storage/garbagecollect.go
- registry/storage/garbagecollect_test.go
- testutil/manifests.go
> Fix garbage-collect --delete-untagged to handle schema 2 manifest list and OCI image index

- docs/content/storage-drivers/s3.md
- registry/storage/driver/s3-aws/s3.go
- registry/storage/driver/s3-aws/s3_test.go
- tests/conf-e2e-cloud-storage.yml
Currently, the `forcepathstyle` parameter for the s3 storage driver is
considered only if the `regionendpoint` parameter is set. Since setting
a region endpoint explicitly is discouraged with AWS s3, it is not clear
how to enforce path style URLs with AWS s3.
This also means, that the default value (true) only applies if a region
endpoint is configured.
This change makes sure we always forward the `forcepathstyle` parameter
to the aws-sdk if present in the config. This is a breaking change where
a `regionendpoint` is configured but no explicit `forcepathstyle` value
is set.
Signed-off-by: Benjamin Schanzel <benjamin.schanzel@bmw.de>
> Allow setting s3 forcepathstyle without regionendpoint

- registry/storage/garbagecollect.go
- registry/storage/garbagecollect_test.go
it is reasonable to ignore the error that the manifest tag path does not exist when querying all tags of the specified repository when executing gc.
Signed-off-by: Liang Zheng <zhengliang0901@gmail.com>
> fix: ignore error of manifest tag path not found in gc

- cmd/registry/config-cache.yml
- cmd/registry/config-dev.yml
- cmd/registry/config-example.yml
- configuration/configuration.go
- configuration/configuration_test.go
- docs/content/about/configuration.md
- go.mod
- registry/handlers/app.go
- registry/handlers/manifests.go
- registry/storage/registry.go
- registry/storage/tagstore.go
- vendor/golang.org/x/sync/errgroup/errgroup.go
- vendor/golang.org/x/sync/errgroup/go120.go
- vendor/golang.org/x/sync/errgroup/pre_go120.go
- vendor/modules.txt
add concurrency limits for tag lookup and untag
Harbor is using the distribution for it's (harbor-registry) registry component.
The harbor GC will call into the registry to delete the manifest, which in turn then does a lookup for all tags that reference the deleted manifest.
To find the tag references, the registry will iterate every tag in the repository and read it's link file to check if it matches the deleted manifest (i.e. to see if uses the same sha256 digest). So, the more tags in repository, the worse the performance will be (as there will be more s3 API calls occurring for the tag directory lookups and tag file reads).
Therefore, we can use concurrent lookup and untag to optimize performance as described in https://github.com/goharbor/harbor/issues/12948.
P.S. This optimization …
> add bounded concurrency for tag lookup and untag

- registry/registry.go
- registry/registry_test.go
Adds a Shutdown method to `registry.Registry`. Enables gracefully shutting down an embedded registry HTTP server.
Closes #4337.
> Add Shutdown method to registry.Registry

- registry/storage/purgeuploads.go
Custom storage drivers could needs information from context (for example the user who requested PurgeUploads)
> Set readStartAtFile context aware for purge uploads

- registry/handlers/app.go
- registry/proxy/proxyregistry.go
- registry/proxy/scheduler/scheduler.go
- registry/proxy/scheduler/scheduler_test.go
- registry/registry.go
For pull through cache registry with configured TTL, a scheduler responsible for blobs garbage collection is started here: [registry/proxy/proxyregistry.go#L109](https://github.com/distribution/distribution/blob/51a72c2aef976bd55de3a7b8b0120f97b4169476/registry/proxy/proxyregistry.go#L109), but its [Stop](https://github.com/distribution/distribution/blob/51a72c2aef976bd55de3a7b8b0120f97b4169476/registry/proxy/scheduler/scheduler.go#L208-L209) method is never invoked.
Scheduler state is written to `scheduler-state.json` if a state change is detected every 5 seconds.
When terminating the registry process, this can result in an inconsistent/corrupted `scheduler-state.json`:
- recent state changes are not saved at all
- `scheduler-state.json` has been truncated, but no new content has been …
> Stop proxy scheduler on system exit

- registry/proxy/proxyauth.go
- registry/proxy/proxyregistry.go
This PR adds support for `Basic Authentication` to registry proxy.
Before it supported Bearer tokens only. However, basic auth was already almost implemented as there was already an appropriate `AuthenticationHandler` used to obtain Bearer tokens.
Fixes #3153
> Add support for `Basic Authentication` to `proxyingRegistry`

- registry/proxy/proxyblobstore.go
- registry/proxy/proxyblobstore_test.go
In commit 17952924f3 we updated ServeBlob() to use an io.MultiWriter to write simultaneously to the local store and the HTTP response.
However, copyContent was using a type assertion to only add headers if the io.Writer was a http.ResponseWriter. Therefore, this change caused us to stop sending the expected headers (i.e. Content-Length, Etag, etc.) on the first request for a blob.
Resolve the issue by explicitly passing in http.Header and setting it unconditionally.
> Include headers when serving blob through proxy

- go.mod
go 1.21 added toolchain support. We should now specify a toolchain version in go.mod.
https://go.dev/doc/toolchain
> Add a go.mod toolchain version

- Dockerfile
- docs/content/about/configuration.md
- docs/content/recipes/mirror.md
- docs/dockerhub.md
- tests/docker-compose-e2e-cloud-storage.yml
The original path was referencing a docker directory which no longer makes much sense.
Closes https://github.com/distribution/distribution/issues/4357
Also see: https://github.com/distribution/distribution-library-image/pull/166
> New path for distribution config

- docs/hugo.yaml
It seems like the `geekdocOverwriteHTMLBase` configuration option caused local links URL fragments to target the root URL of the site, rather than the current page.
Closes #4388
> docs: disable base element override

- cmd/registry/config-cache.yml
- configuration/configuration.go
- configuration/configuration_test.go
- docs/content/about/configuration.md
- registry/handlers/app.go
- registry/storage/cache/redis/redis.go
- tests/conf-e2e-cloud-storage.yml
Less code more features! :-D
This PR replaces the custom `Redis` config struct with `UniversalOptions` from `go-redis`, which implicitly adds support for both redis sentinel and redis clustering.
I have two failing tests that I can't quite figure out how to fix:
```
--- FAIL: TestConfigSuite/TestMarshalRoundtrip (0.00s)
--- FAIL: TestConfigSuite/TestParseInvalidVersion (0.00s)
```
<details><summary>Associated stack trace</summary>
```
suite.go:87: test panicked: cannot marshal type: func(context.Context, string, string) (net.Conn, error)
goroutine 18 [running]:
runtime/debug.Stack()
/usr/lib/go-1.21/src/runtime/debug/stack.go:24 +0x5e
github.com/stretchr/testify/suite.failOnPanic(0xc0002b8820, {0x8ebe40, 0xc0002c5850})
/home/aim/Workspace/forks/distribution/vendor/github.com/stretchr/testi …
```
> Replace custom Redis config struct with go-redis UniversalOptions (adds sentinel & cluster support)

- cmd/registry/main.go
- docs/content/storage-drivers/middleware/_index.md
- docs/content/storage-drivers/middleware/rewrite.md
- registry/storage/driver/middleware/rewrite/middleware.go
- registry/storage/driver/middleware/rewrite/middleware_test.go
This allows to rewrite 'URLFor' of the storage driver to use a specific host/trim the base path.
It is different from the 'redirect' middleware, as it still calls the storage driver URLFor.
For example, with Azure storage provider, this allows to transform the SAS Azure Blob Storage URL into the URL compatible with Azure Front Door.
> feat: implement 'rewrite' storage middleware

- go.mod
- go.sum
- registry/storage/ocimanifesthandler.go
- registry/storage/ocimanifesthandler_test.go
- vendor/github.com/opencontainers/image-spec/specs-go/v1/annotations.go
- vendor/github.com/opencontainers/image-spec/specs-go/v1/config.go
- vendor/github.com/opencontainers/image-spec/specs-go/v1/descriptor.go
- vendor/github.com/opencontainers/image-spec/specs-go/v1/index.go
- vendor/github.com/opencontainers/image-spec/specs-go/v1/layout.go
- vendor/github.com/opencontainers/image-spec/specs-go/v1/manifest.go
- vendor/github.com/opencontainers/image-spec/specs-go/v1/mediatype.go
- vendor/github.com/opencontainers/image-spec/specs-go/version.go
- vendor/modules.txt
full diff: https://github.com/opencontainers/image-spec/compare/v1.0.2...v1.1.0
> vendor: github.com/opencontainers/image-spec v1.1.0

- blobs.go
- manifest/ocischema/builder.go
- manifest/schema2/builder.go
- manifests.go
- registry/storage/manifeststore_test.go
- testutil/manifests.go
Commit cb6f0023500c3d2afb8c9f3ee4a0097526192156 (https://github.com/distribution/distribution/pull/1268) implemented a generic Manifest interface to represent manifests in the registry and remove references to schema specific manifests.
As part of this refactor, the Describable interface was introduced, which allowed for a single ManifestBuilder interface to handle both schema1 and schema2 manifests. Implementations of Describable are generally objects which can be described, not simply descriptors, but for convenience, this interface was also implemented on Descriptor in 2ff77c00bad887928be04367f0dd58f6aed5b756 (https://github.com/distribution/distribution/pull/1281).
This interface served its purpose, but no longer needed for most cases; schema2 (and OCI) descriptors do not need this …
> Descriptor: do not implement Describable interface

- registry/storage/driver/s3-aws/s3.go
`S3.StorageDriver.Stat` always calls `ListObjects` when stat-ing an S3 key to determine if it's a "directory" or not.
Unfortunately, the `ListObjects` is not a free call: both in terms of egress and actual AWS costs (likely because of the egress).
This changes the behaviour of `Stat` such that we always attempt the `HeadObject` call first and only ever fall through to `ListObjects` if the `HeadObject` call returns an AWS API error.
Note, that the official docs mention that the only error returned by HEAD is `NoSuchKey` (https://docs.aws.amazon.com/AmazonS3/latest/API/API_HeadObject.html#API_HeadObject_Errors); experiments show that this is demonstrably wrong and the AWS docs are simply outdated at the time of this commit.
HeadObject actually returns the following errors:
* `NotFound`: if …
> S3 driver: Attempt HeadObject on Stat first, fail over to List

- manifest/manifestlist/manifestlist.go
- manifest/ocischema/index.go
- manifest/ocischema/manifest.go
- manifest/schema2/manifest.go
Change the marshal-funcs to a regular function instead of definining as part of an init and remove some intermediate variables.
> manifest: slight cleanup of init / registration

- internal/client/repository_test.go
- manifest/manifestlist/manifestlist.go
- manifest/ocischema/builder.go
- manifest/ocischema/index.go
- manifest/ocischema/manifest.go
- manifest/ocischema/manifest_test.go
- manifest/schema2/builder.go
- manifest/schema2/manifest.go
- manifest/schema2/manifest_test.go
- manifest/versioned.go
- notifications/bridge_test.go
- notifications/listener_test.go
- registry/handlers/api_test.go
- registry/proxy/proxymanifeststore_test.go
- registry/storage/manifestlisthandler.go
- registry/storage/manifeststore.go
- registry/storage/manifeststore_test.go
- registry/storage/ocimanifesthandler_test.go
- registry/storage/schema2manifesthandler_test.go
- registry/storage/tagstore_test.go
Update the Manifest types to use the oci implementation of the Versioned struct.
> deprecate Versioned in favor of oci.Versioned

- registry/storage/driver/s3-aws/s3.go
The current logic only checks the region and returns if it's empty; however, we are not validating the regionEndpoint parameter. Therefore, if the user provides only the regionEndpoint without any region, this will not be evaluated.
> fix logic for handling regionEndpoint

- registry/storage/driver/s3-aws/s3.go
Fixes #4411
Ref: https://github.com/project-zot/zot/pull/2532
On other situations, a nil check is present. 
https://github.com/distribution/distribution/blob/252619876af36ec194d918b8fd87fba018c4971b/registry/storage/driver/s3-aws/s3.go#L760
---
There are still some missing nil checks, not sure
https://github.com/distribution/distribution/blob/252619876af36ec194d918b8fd87fba018c4971b/registry/storage/driver/s3-aws/s3.go#L740
https://github.com/distribution/distribution/blob/252619876af36ec194d918b8fd87fba018c4971b/registry/storage/driver/s3-aws/s3.go#L727
https://github.com/distribution/distribution/blob/252619876af36ec194d918b8fd87fba018c4971b/registry/storage/driver/s3-aws/s3.go#L794
https://github.com/distribution/distribution/blob/252619876af36ec194d918b8fd87fba018c4971b/registry/storag …
> fix nil pointer in s3 list api

- registry/storage/garbagecollect.go
fix: https://github.com/distribution/distribution/pull/4344#issuecomment-2255978086
Signed-off-by: Liang Zheng <zhengliang0901@gmail.com>
> fix: skip removing layer's link file when '--dry-run' option specified

- go.mod
Updating the `github.com/distribution/distribution/v3` dependency from `v3.0.0-alpha.1` to `v3.0.0-beta.1` the module version of the corresponding project gets updated automatically: see https://github.com/gardener/gardener/pull/10105/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R3-R5
We want to use the `x.y.0` format in the module version, see the motivation in https://github.com/gardener/gardener/pull/9564.
Other projects like [kubernetes](https://github.com/kubernetes/kubernetes/blob/a2106b5f73fe9352f7bc0520788855d57fc301e1/go.mod#L9) and [controller-runtime](https://github.com/kubernetes-sigs/controller-runtime/blob/1ed345090869edc4bd94fe220386cb7fa5df745f/go.mod#L3) are using the same approach (the `x.y.0` format as their module version).
> Use `x.y.0` format for the go module version

- registry/storage/driver/middleware/rewrite/middleware.go
https://github.com/distribution/distribution/pull/4146 introduced a new rewrite storage middleware but somehow missed updating the init logging message. 
This PR fixes that.
> chore: fix typo in rewrite storage middleware init

- docker-bake.hcl
As part of the effort to be able to build `moby/moby` in Docker-in-Docker fashion for `linux/riscv64` natively, it requires this image to be build so as well.
Dependency from https://github.com/moby/moby/blob/master/Dockerfile#L95
I've been able to build and do a basic run of the binary in my riscv64 host:
```
user@bananapif3:~/Projects/distribution$ file bin/registry
bin/registry: ELF 64-bit LSB pie executable, UCB RISC-V, RVC, double-float ABI, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-riscv64-lp64d.so.1, BuildID[sha1]=3997fd5e706d3525b975f50f4badaa70e515c348, for GNU/Linux 4.15.0, stripped
user@bananapif3:~/Projects/distribution$ ./bin/registry --version
./bin/registry github.com/distribution/distribution/v3 v3.0.0-beta.1.m+unknown …
```
> Build artifacts and images for linux/riscv64

- docs/content/about/configuration.md
- docs/content/spec/auth/jwt.md
- docs/content/spec/auth/token.md
- registry/auth/token/accesscontroller.go
- registry/auth/token/accesscontroller_test.go
- registry/auth/token/util.go
- Borrowed two functions from docker/libtrust to generate the key ID from the certificate bundle in the same fashion as v2.8.3.
Addresses: distribution/distribution#4470
> fix: Add the token's rootcert public key to the list of known keys

- registry/proxy/proxymanifeststore_test.go
- relates to https://github.com/distribution/distribution/pull/3888#issuecomment-2359274654
This test was using a hard-coded value for the size of the manifest, which made it difficult to correlate the tested value with what it was testing.
This patch updates populateRepo to return the actual size when serialized, and updates manifestStoreTestEnv to include the size to test for.
> TestProxyManifestsMetrics: use actual size of manifest

- docs/content/about/deploying.md
The documentation stated that ELB couldn't change the healthy response code. However, since both NLB and ALB now support 4xx codes, I've removed this example from the description.
> https://docs.aws.amazon.com/elasticloadbalancing/latest/application/target-group-health-checks.html
> Matcher: If the protocol version is HTTP/1.1 or HTTP/2, the possible values are from 200 to 499.
> https://docs.aws.amazon.com/elasticloadbalancing/latest/network/target-group-health-checks.html
> Matcher: [HTTP/HTTPS health checks] The HTTP codes to use when checking for a successful response from a target. The range is 200 to 599. The default is 200-399.
NLB support for this feature was added in November 2022
> https://aws.amazon.com/about-aws/whats-new/2022/11/elastic-load-balancing-capabilities-application- …
> docs: removed description of ELB as an example of an not sophisticated Load Balancer

- blobs.go
With the removal of the Describable interface from this type, and
deprecation of the Versioned type, the Descriptor is now an exact
equivalent of the oci.Descriptor.
This patch makes Descriptor an alias for oci.Descriptor.
> Make Descriptor an alias for oci.Descriptor

- .github/workflows/validate.yml
- docs/content/spec/api.md
- docs/content/spec/api.md.tmpl
- registry/api/v2/descriptors.go
Solves https://github.com/distribution/distribution/issues/3433
Now validate.yml workflow will also check whether the api docs are up to date with the descriptors in `registry/api/v2/descriptors.go`. If yes, then the job passes with no failure, If no, then the job fails will the appropriate error message.
Note: It looks like the `docs/content/spec/api.md` is being updated manually so there is some difference between the api markdown and the template file. I have updated the template to match the api markdown in most cases but there a few cases where it just cannot be updated:
1. Random newlines in api markdown with no specific pattern
The differences that have been addressed:
1. General spacing differences
4. `"errors:"` -> `"errors":`
5. JSON object pretty formatting
6. Text mismatch …
> ci: Add validation for api docs

- registry/storage/driver/s3-aws/s3.go
- registry/storage/driver/s3-aws/s3_test.go
when a directory is empty, the s3 api lists it with a trailing slash.
this causes the path to be appended twice to the walkInfo slice, causing
purge uploads path transformations to panic when the `_uploads` is
emtpy.
this adds a check for file paths ending on slash, and do not append
those as regular files to the walkInfo slice.
fixes https://github.com/distribution/distribution/issues/4358
> avoid appending directory as file path in s3 driver Walk

- docs/content/storage-drivers/s3.md
- registry/storage/driver/s3-aws/s3.go
- registry/storage/driver/s3-aws/s3_32bit.go
- registry/storage/driver/s3-aws/s3_64bit.go
- registry/storage/driver/s3-aws/s3_test.go
- registry/storage/driver/testsuites/testsuites.go
Some S3 compatible object storage systems like R2 require that all multipart chunks are the same size. This was mostly true before, except the final chunk was larger than the requested chunk size which causes uploads to fail.
In addition, the two byte slices have been replaced with a single *bytes.Buffer and the surrounding code simplified significantly.
Fixes: #3873
> fix(registry/storage/driver/s3-aws): use a consistent multipart chunk size

- configuration/configuration.go
- docs/content/about/configuration.md
- go.mod
- go.sum
- registry/proxy/proxyauth_exec.go
- registry/proxy/proxyauth_exec_test.go
- registry/proxy/proxyregistry.go
- vendor/github.com/docker/docker-credential-helpers/LICENSE
- vendor/github.com/docker/docker-credential-helpers/client/client.go
- vendor/github.com/docker/docker-credential-helpers/client/command.go
- vendor/github.com/docker/docker-credential-helpers/credentials/credentials.go
- vendor/github.com/docker/docker-credential-helpers/credentials/error.go
- vendor/github.com/docker/docker-credential-helpers/credentials/helper.go
- vendor/github.com/docker/docker-credential-helpers/credentials/version.go
- vendor/modules.txt
This change allows users to run the registry as a pull-through cache that can use a credential helper to authenticate against the upstream registry.
Example config:
```
proxy:
remoteurl: https://gcr.io/
exec:
command: docker-credential-gcloud
lifetime: 1h
ttl: 168h
```
Example partial container specs to deploy the registry proxy in GKE with workload identity:
```
initContainers:
- name: prepare-bin
image: distribution/distribution
command: ["cp", "/bin/registry", "/data/bin/"]
volumeMounts:
- name: data
mountPath: /data/bin
subPath: bin
containers:
- name: registry
image: google/cloud-sdk:slim
command: ["registry", "serve", "/etc/distribution/config.yml"]
volumeMounts:
- name: config
mountPath: /etc/distribution/config.yml
subPath: config.yml
- name: data
mountPath: /bin/registry
subPath: …
```
> feat: support custom exec-based credential helper in proxy mode

- MAINTAINERS
I no longer work at Mirantis, updating my maintainer email to my personal.
> Update squizzi maintainer email

- configuration/configuration.go
- configuration/configuration_test.go
- docs/content/about/configuration.md
- registry/registry.go
Hi! This PR allows setting the tls.ClientAuthType parameter in TLS configurations. It’s useful for supporting both clients with and without certificates.
Example:
```
tls:
clientauth: verify-client-cert-if-given
```
This was added to support custom access controllers needing flexible client certificate handling.
> feat(configuration): support mtls auth mod

- .github/workflows/build.yml
- .github/workflows/conformance.yml
- .github/workflows/docs.yml
- .github/workflows/e2e.yml
closes #4552 
Update bake-action to v6 with slight changes to take default to Git context into account. Made also a small change to the docs workflow so it builds on PR to make sure there is no regression.
> ci: update bake-action to v6

- .github/workflows/build.yml
similar to https://github.com/docker/compose/pull/12470
When building using git context, it does not fetch tags and therefore version would be broken in: https://github.com/distribution/distribution/blob/3270367d89f572883be9a3ac2c28dd4222df5bf7/Dockerfile#L18
Let's keep local context as before until we investigate this issue upstream.
> ci: fix bake build

- docs/content/about/garbage-collection.md
- registry/root.go
- registry/storage/garbagecollect.go
Consumers might not want GC output to be displayed (e.g, if you have your own logging system).
> registry/storage: add option to quiet GC output.

- registry/storage/driver/gcs/gcs.go
Apparently, you can upload 0-size content without GCS reporting any errors back to you. Registry operations fail in these situations
This is something a lot of our users experienced and reported. See here for at least one example:
https://github.com/distribution/distribution/issues/3018
This PR sets the MD5 sum on the uploaded content which should rectify things according to the docs:
https://pkg.go.dev/cloud.google.com/go/storage#ObjectAttrs
The alternative would be to set `CRC32C` but that's not been verified unlike the MD5 which is used by GitLab in their registry.
Closes: https://github.com/distribution/distribution/issues/3018
> Enable MD5 check on GCS driver

- docs/content/recipes/osx-setup-guide.md
- docs/content/recipes/osx/com.docker.registry.plist
Incorrect directories fixed. Added explanation for ensuring port 5000 is available or changing it. Fixed com.docker.registry.plist to include the missing "serve" parameter that caused the service to fail at startup.
> Update osx-setup-guide.md and com.docker.registry.plist

- configuration/configuration.go
- configuration/configuration_test.go
- configuration/parser_test.go
Hi! I've started designing Kubernetes Operator for Distribution (see https://registry-operator.dev/latest/), and I noticed that handling the configuration structure from code is extremely cumbersome due to the nested structs. Simplest fix is to define few new structures, and unflatten the configuration.
Progress:
> fix: remove nested structs from configuration

- .golangci.yml
- dockerfiles/lint.Dockerfile
There was a typo and non-existent config option in the linter config.
Because we don't verify the config it's easy to miss it:
```
jsonschema: "issues" does not validate with "/properties/issues/additionalProperties": additional properties 'exlude-dirs' not allowed
jsonschema: "issues" does not validate with "/properties/issues/additionalProperties": additional properties 'deadline' not allowed
Failed executing command with error: the configuration contains invalid elements
```
This PR both fixes the config and adds a command which verifies it before we run the linter.
PTAL @thaJeztah
> Fix golangci-lint config

- releases/v3.0.0.toml
- version/version.go
This is a prep for the first stable v3 release of registry! The time has come to get it out!
Let's get the stable release out in time for [KubeCon Europe](https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/)
The only delta in comparison to the recent rc-4 release is Azure and some other security dependency bumps.
Once this is out and the DOI is built, we must not forget to merge https://github.com/distribution/distribution/pull/4373
Let's go!
> Prep for v3 release

- docs/content/storage-drivers/azure.md
- registry/storage/driver/azure/auth.go
newClient can now return a client using default azure credentials.
updated docs to include information on Azure Workload Identity.
Fixes https://github.com/distribution/distribution/issues/4618
> Fix default_credentials in azure storage provider

- docs/content/about/configuration.md
- registry/auth/token/accesscontroller.go
- registry/auth/token/util.go
In #4471, we implemented JWK fingerprint for RSA and ECDSA public keys, in accordance to [RFC 7638](https://datatracker.ietf.org/doc/html/rfc7638).
This PR implemented JWK fingerprint for Ed25519 public keys, in accordance to [RFC 8037](https://datatracker.ietf.org/doc/html/rfc8037#appendix-A.3).
> fix: implement JWK thumbprint for Ed25519 public keys

- docs/content/about/configuration.md
Adding the `yaml` annotation to the code block from validation.indexes configuration docs, so it will be displayed properly.
> fix: Annotate code block from validation.indexes configuration docs

- registry/storage/driver/filesystem/driver.go
- registry/storage/driver/testsuites/testsuites.go
To address the issue where empty files are created when the write process is interrupted, the solution involves writing to a temporary file first and then atomically renaming it to the target file. This ensures that the target file is only updated if the write completes successfully, preventing empty or partially written files.
**Explanation:**
1. **Temporary File Creation:** The content is first written to a temporary file (appending `.tmp` to the original path). This ensures that the original file remains intact until the write is complete.
2. **Write to Temporary File:** Using the existing `Writer` with truncation (`false`), the content is written to the temporary file. If the write fails, the temporary file is closed and deleted.
3. **Commit and Rename:** After successfully writing to …
> Fix: resolve issue #4478 by using a temporary file for non-append writes

- docs/content/about/configuration.md
This tweak doesn't yet appear in the official documentation, but is in https://github.com/distribution/distribution/issues/4270
> docs: Add note about `OTEL_TRACES_EXPORTER`

- Dockerfile
This updates the default container invocation to avoid spamming the system logs with failure to send trace data.
I think this resolves https://github.com/distribution/distribution/issues/4270 while leaving it easy for folks using this to setup their collectors.
> fix: set OTEL traces to disabled by default

- internal/client/repository_test.go
- internal/dcontext/context.go
- internal/dcontext/http.go
- internal/dcontext/trace.go
- internal/uuid/uuid.go
- notifications/bridge.go
- notifications/bridge_test.go
- registry/storage/driver/filesystem/driver.go
- registry/storage/linkedblobstore.go
- registry/storage/purgeuploads_test.go
This PR switches UUIDs to UUIDv7. UUIDv7s are time ordered which makes them more efficient to store and query.
Here are some UUIDv4 vs UUIDv7 benchmarks with Postgres:
- https://ardentperf.com/2024/02/03/uuid-benchmark-war/
- https://dev.to/umangsinha12/postgresql-uuid-performance-benchmarking-random-v4-and-time-based-v7-uuids-n9b
There's no downside to switching - these are still valid UUIDs so the change is fully backwards compatible. Being able to store things like events with UUIDv7 IDs will be beneficial to everyone.
Also, this makes it easier to change the UUID version in the future.
Closes: https://github.com/distribution/distribution/issues/4665
> Switch UUIDs to UUIDv7

- registry/storage/driver/s3-aws/s3_32bit.go
- registry/storage/driver/s3-aws/s3_64bit.go
When building for 386, we got the following build error:
registry/storage/driver/s3-aws/s3.go:312:99: cannot use
maxChunkSize (untyped int constant 5368709120) as int value
in argument to getParameterAsInteger (overflows)
This is because the s3_64bit.go is used. Adjust the build tag matching in s3_32bit.go and s3_64bit.go to fix this issue.
> s3-aws: fix build for 386

- registry/storage/driver/s3-aws/s3.go
- registry/storage/driver/s3-aws/s3_test.go
Unfortunately YAML struck us hard in this one.
It interprets "off" as a truthy value so setting loglevel to off sets it to false.
This commit makes sure we set the loglevel to off if the param is marshalled into false and if it's not a string.
Fixes https://github.com/distribution/distribution/issues/4616
> Fix S3 driver loglevel param

- docs/content/recipes/mirror.md
The link to https://www.docker.com/pricing/resource-consumption-updates ([archived copy](https://web.archive.org/web/20220901000000*/https://www.docker.com/pricing/resource-consumption-updates)) no longer works, so I changed it to go to https://docs.docker.com/docker-hub/usage/ instead.
> Fix broken link to Docker Hub fair use policy
