distribution/distribution

- README.md
cc @icecrime @jfrazelle @shykes @ncdc @vbatts @dmp42 @dmcgowan @jlhawn
> Outline constraints for interface from distribution to core

- registry/layerupload.go
Because we guarded the error check, nil Upload on the handler was getting
through to unexpected branches. This directly handles the missing upload
ensuring its set as expected.
cc @BrianBland
> Correctly handle missing layer upload

- storagedriver/s3/README.md
Self-explanatory.
@stevvooe @dmp42
> Clarifies s3 driver "secure" flag documentation

- storage/cloudfrontlayerhandler.go
- storage/delegatelayerhandler.go
Expands upon #63 to make HEAD requests function properly with signed URL layer redirects.
> Forwards http method to the layerhandler for layer serving

- Godeps/Godeps.json
- Godeps/_workspace/src/github.com/crowdmob/goamz/aws/aws.go
- Godeps/_workspace/src/github.com/crowdmob/goamz/aws/sign.go
- Godeps/_workspace/src/github.com/crowdmob/goamz/s3/multi.go
- Godeps/_workspace/src/github.com/crowdmob/goamz/s3/s3.go
- Godeps/_workspace/src/github.com/docker/libtrust/jsonsign.go
Includes newer docker/libtrust and crowdmob/goamz
> Updates Godeps to a compiling/stable state

- configuration/configuration_test.go
Signed-off-by: Brian Bland <brian.bland@docker.com>
> Adds test for extraneous configuration environment variables

- circle.yml
Move circle to godep.
cc @stevvooe
> Move to circle.yml to godep

- storagedriver/s3/README.md
- storagedriver/s3/s3.go
- storagedriver/s3/s3_test.go
Also change default chunkSize to 10MB (up from 5).
> Add the chunksize parameter

- storagedriver/testsuites/testsuites.go
I needed to change `TestWriteReadLargeStreams` (uploading 5 GB) to write all the data in one shot rather than 5120 x 1MB chunks. 
* covers the case if the WriteStream is actually able to write that much of data in one shot (theoretically, it should)
* underlying storage driver implementation can optimize the uploads (e.g. parallelize with coroutines etc) rather than serially uploading 1MB chunks
* reduces round-trip calls to underlying storage API (esp. for cloud storage providers)
* takes up less space in memory (no chunk)
Tested this on azure driver and it works. Now, with this change it finishes up this test much faster and more reliably.  I was getting intermittent HTTP failures/timeouts, now I don't.
Somehow memory usage was constantly increasing (a lot) while running the test …
> Modify TestWriteReadLargeStreams to write in one shot

- storagedriver/testsuites/testsuites.go
Also split the test into a small and large version.
> Make TestContinueStreamAppend check if WriteStream can overwrite

- storagedriver/testsuites/testsuites.go
(Follow up to discussion at #71)
This prevents Stat tests on storage drivers to randomly fail due to timestamp differences (+-) between test machine and cloud storage providers. Usually cloud storage providers do not provide any timestamp accuracy guarantees.(in Azure case, where Windows Servers used, ntp guarantee is way more than a few seconds).
This test could also very well fail due to network latency on the test machine or which millisecond of the second the upload is completed.
This change makes the test case failing less due to network or such time syncing issues by adding ɛ=±10s to the time checks. Also removed a commented out code snippet. Anyway, modtime should not be used like an ETag to verify freshness of the file as no cloud storage provider also guarantees that time won't …
> Allow modtime to be a few seconds off on TestStatCall

- client/client.go
- registry/api_test.go
- registry/images.go
> Manifest PUT should return 202 Accepted status

- storagedriver/s3/s3_test.go
> Skip s3 tests if no region is specified

- Makefile
A nice set of common default targets have been added to the Makefile to make
running tests and building binaries more straightforward. Running the Makefile
before committing should make build failures less common.
> Add common targets to Makefile

- Godeps/Godeps.json
- Godeps/_workspace/src/github.com/MSOpenTech/azure-sdk-for-go/clients/storage/blob.go
- Godeps/_workspace/src/github.com/MSOpenTech/azure-sdk-for-go/clients/storage/blob_test.go
- Godeps/_workspace/src/github.com/MSOpenTech/azure-sdk-for-go/clients/storage/client.go
- Godeps/_workspace/src/github.com/MSOpenTech/azure-sdk-for-go/clients/storage/client_test.go
- Godeps/_workspace/src/github.com/MSOpenTech/azure-sdk-for-go/clients/storage/util.go
- Godeps/_workspace/src/github.com/MSOpenTech/azure-sdk-for-go/clients/storage/util_test.go
- cmd/registry-storagedriver-azure/main.go
- storagedriver/azure/azure.go
- storagedriver/azure/azure_test.go
- storagedriver/azure/blockblob.go
- storagedriver/azure/blockblob_test.go
- storagedriver/azure/blockid.go
- storagedriver/azure/blockid_test.go
- storagedriver/azure/randomwriter.go
- storagedriver/azure/randomwriter_test.go
- storagedriver/azure/zerofillwriter.go
- storagedriver/azure/zerofillwriter_test.go
Catching up with some recent changes in the storage driver API.
Added Stat method, removed CurrentSize and fixed some issues revealed in recent tests.
Uncommented relevant parts for the test to be included in the suite when it is set up.
cc: @stevvooe @BrianBland 
> storagedriver/azure: fix azure storage driver methods, implement Stat

- registry/app.go
The branch that executes after a failed request authorization due to a missing
repo name now correctly returns an error. This is somewhat superficial since
the response would have already been executed. Although, unintended repository
operations may have occurred.
Documentations and comments have also been updated to be in line with
surrounding changes.
> Correctly return when repo name is not available

- CONTRIBUTING.md
Check out the rich diff: https://github.com/docker/distribution/pull/165/files?short_path=6a33714#diff-6a3371457528722a734f3c51d9238c13
cc @amylindburg @docker/distribution-maintainers
> define meaning of project management labels for issues and PRs

- registry/storage/driver/azure/README.md
cc: @stevvooe @AndreyKostov @BrianBland @johngossman
> registry/storage/driver/azure: add README

- .gitignore
> Add pem and out files to gitignore

- registry/handlers/layerupload.go
> A digest missing parameter should result in a bad request

- manifest/manifest.go
> Specify manifest schema version 1 media type

- doc/spec/api.md
add url link, as to jump to relevant issue page
> jump to relevant issue page

- registry/api/v2/routes_test.go
https://github.com/docker/distribution/issues/199
This minimal Gist can be used to demonstrate it is Go's core net/http library that is doing the protection against path traversal, not mux https://gist.github.com/endophage/0aad76b0f32486818962
The test for bad characters includes short and long versions. The short version just adds a single Chinese character into the URL and looks for a 404. The long version generates 1000 urls containing random multibyte characters in key path segments, and ensures we receive a 404 on all responses.
> registry/api/v2: test cases for path traversal and bad characters

- AUTHORS
- version/version.go
> Update AUTHORS and default version package

- registry/api/v2/names.go
> documentation for name validation grammar

- registry/client/client.go
> Remove unnecessary close in client

- doc/spec/api.md.tmpl
> doc/spec: patch #222 to api.md.tmpl

- notifications/bridge.go
- notifications/event.go
- notifications/event_test.go
- notifications/http_test.go
- registry.go
- registry/storage/layerreader.go
Update event target to contain a blob descriptor.
> notifications: update notification event Target fields

- registry/api/v2/names.go
- registry/api/v2/names_test.go
Fixes #241
Signed-off-by: Andy Goldstein <agoldste@redhat.com>
> Remove max repository component length restriction

- registry/handlers/app.go
- registry/handlers/app_test.go
Title says it all. The code pulled out of authorized and into its own function is now fully covered by tests.
Signed-off-by: David Lawrence <david.lawrence@docker.com> (github: endophage)
Closes #201.
> minor refactor + tests for app.go just to improve test coverage.

- registry/auth/silly/access.go
- registry/handlers/app_test.go
Signed-off-by: Andy Goldstein <agoldste@redhat.com>
> Send WWW-Authenticate header for silly auth

- context/http.go
> context: validate prefix lookups for WithRequest/WithResponse contexts

- registry.go
- registry/handlers/layer.go
- registry/storage/driver/storagedriver.go
- registry/storage/layerreader.go
... Rather than ServeHTTP directly.
> Refactor Layer interface to return a Handler

- doc/spec/json.md
> doc/spec: canonicalized JSON format for distribution APIs

- doc/configuration.md
Signed-off-by: David Lawrence <david.lawrence@docker.com> (github: endophage)
> Adding docs for full suite of configuration options

- CONTRIBUTING.md
> Update Sprint label link from Ready

- doc/configuration.md
> removing references to chunksize which is optional

- doc/spec/api.md
- doc/spec/api.md.tmpl
> Fix GitHub issue link, simple typo

- doc/architecture.md
There is probably a better place for this documentation but we'd like to move
this elsewhere than a github issue. We can move this to a more appropriate
location with the documentation effort.
Closes #146
cc @moxiegirl
> doc: document approach to eventual consistency

- doc/notifications.md
An overview the notification system is provided, covering topics on
architecture, configuration, implementation and formats. This may need to
filled out with further details covering format specifications.
cc @moxiegirl
> doc: document event notification system

- version/version.go
> version: update rough version to be closer to reality

- registry/storage/signaturestore.go
To avoid compounded round trips leading to slow retrieval of manifests with a
large number of signatures, the fetch of signatures has been parallelized. This
simply spawns a goroutine for each path, coordinated with a sync.WaitGroup.
> registry/storage: parallelize signature fetch in signature store

- configuration/README.md
- configuration/configuration_test.go
Update S3 configuration documentation to accurately reflect rootdirectory field name
> Update S3 configuration documentation

- AUTHORS
- docs/spec/manifest-v2-1.md
> doc/spec: documentation for the Image Manifest V2 format

- docs/deploying.md
Example configuration for setting up a v1 and v2 registry behind nginx
> docs: add nginx configuration for v1 and v2 registry

- docs/deploying.md
> server --> serve

- Makefile
- docs/spec/api.md
- registry/api/v2/descriptors.go
Updates description about content length and location
> Update final upload chunk api doc

- digest/digester.go
- digest/digester_resumable.go
- registry/storage/layerstore.go
- registry/storage/layerwriter.go
- registry/storage/layerwriter_nonresumable.go
- registry/storage/layerwriter_resumable.go
Signed-off-by: Andy Goldstein <agoldste@redhat.com>
Closes #341.
> Use a build flag to disable resumable digests

- README.md
- contrib/compose/README.md
- docs/configuration.md
- docs/deploying.md
- docs/notifications.md
- docs/overview.md
Adjusting deploying after new RC pushed
Fixing typos and adding tables
Updating with testing material
Tweak after read through
Fixes issue #363 too!
> docs: updating with new RC work

- docs/deploying.md
Signed-off-by: Ben Firshman <ben@firshman.co.uk>
> Use registry:2.0 tag in docker run

- .mailmap
- AUTHORS
- version/version.go
Updates AUTHORS and rough version for release.
> Release preparation

- digest/tarsum.go
- doc.go
- notifications/sinks.go
- registry/auth/auth.go
- registry/auth/token/util.go
- registry/storage/driver/ipc/server.go
- registry/storage/driver/testsuites/testsuites.go
- registry/storage/layer_test.go
- registry/storage/layerwriter.go
- registry/storage/paths.go
Signed-off-by: bin liu <liubin0329@gmail.com>
> fix some typos in source comments

- registry/storage/driver/base/base.go
> registry/storage/driver: add path and other info to filesytem trace methods.

- docs/deploying.md
Signed-off-by: Shawn Falkner-Horine <dreadpirateshawn@gmail.com>
> Fix deployment guide typos re: image name consistency.

- registry/storage/layerwriter.go
Rather than accept the resulting of a layer validation, we retry up to three
times, backing off 100ms after each try. The thought is that we allow s3 files
to make their way into the correct location increasing the liklihood the
verification can proceed, if possible.
> Attempt to deal with eventual consistency by retrying

- registry/storage/layerwriter.go
> log canonical digest on verification error

- registry/storage/layerwriter.go
> Backoff retry on verification to give s3 time to propagate

- registry/handlers/layerupload.go
> Check error returned from io.Copy

- registry/storage/driver/s3/s3.go
The code using values from the yaml package wasn't careful enought with the
possible incoming types. Turns out, it is just an int but we've made this
section somewhat bulletproof in case that package changes the behavior.
This code likely never worked. The configuration system should be decoupled
from the object instantiation.
> Allow configuration of chunksize parameter

- registry/storage/driver/s3/s3.go
> Correctly check s3 chunksize parameter

- registry/storage/driver/s3/s3.go
Addresses #413. Only close #413 after we have confirmed 400/500 errors have subsided on hub.
> Attempt to address intermittent s3 RequestTimeout error

- docs/mkdocs.yml
#396 Introduced a problem in the mkdocs.yml (stripped out ###) for Hidden.
This puts them back in.
> Pushing fix for mkdocs.yml introduced

- docs/configuration.md
> Add registry configuration environment variable documentation

- cmd/registry/config.yml
- configuration/configuration.go
- docs/configuration.md
- docs/deploying.md
- registry/handlers/app.go
> Add configuration for upload purging

- contrib/compose/nginx/registry.conf
Drops in the header into the registry.conf for nginx.
Refers to #397 
> Updating configuration with required header

- contrib/compose/nginx/registry.conf
- docs/configuration.md
- docs/mkdocs.yml
- docs/storagedrivers.md
Fixing the broken release branch.
This is a cherry pick series to fix broken release.  
/cc ping @stevvooe
> Fix release branch

- docs/storagedrivers.md
I'm very sorry @stevvooe I missed this change yesterday.  I'll need to pull this into Master and Cherry pick into the release.  
> Fixing headings

- registry/storage/driver/s3/s3.go
This deals with a memory leak, caused by goroutines, experienced when using the
s3 driver. Unfortunately, this section of the code leaks goroutines like a
sieve. There is probably some refactoring that could be done to avoid this but
instead, we have a done channel that will cause waiting goroutines to exit.
Closes #436.
> registry/storage/driver/s3: use done channel to avoid goroutine leak

- notifications/http.go
> Address possible goroutine leak in notification library

- context/http.go
- context/http_test.go
- registry/handlers/api_test.go
> Ensure the instrumentedResponseWriter correctly sets the http status in the context.

- registry/handlers/api_test.go
- registry/storage/layerreader.go
closes: #509 
- Set an Etag header
- Check If-None-Match and respond appropriately
- Set a Cache-Control header with a default of 1 week
> Set cache headers for layers.

- docs/configuration.md
> docs: add warning about using window's volumes with registry

- docs/deploying.md
- docs/index.md
> docs: clarify minimum docker version for use with v2 API

- docs/configuration.md
> Revise description of debug endpoint

- registry/client/repository.go
Signed-off-by: Tibor Vass <teabee89@gmail.com>
> client: fix a typo preventing compilation

- registry/storage/driver/s3/s3.go
> Better error message when failing to get AWS auth

- CONTRIBUTING.md
Fixes #377
Also:
* re-express the bug reporting workflow with clear steps and checklists we can link to
* simplified a couple of things
* removed references to waffle
* remove section about PR title
> Enhance CONTRIBUTING

- Dockerfile
As mentioned [here](https://github.com/docker/distribution/pull/443#issuecomment-106969267). Please merge this PR only after #578.
> Dockerfile: build with the RADOS driver

- Dockerfile
- cmd/registry/main.go
- docs/building.md
- docs/storage-drivers/azure.md
> Disable building of azure storage driver by default

- health/checks/checks_test.go
> Test: add test for health/check

- registry/api/v2/names_test.go
These cover some cases referred to in docker/docker#13070.
> Add more repository name validation test cases

- docs/configuration.md
Fixing docs went out of sync with `azure.md`.
Signed-off-by: Ahmet Alp Balkan
> docs: Update azure docs in configuration.md

- docs/spec/manifest-v2-1.md
ping @stevvooe @dmcgowan 
Signed-off-by: Vincent Batts <vbatts@redhat.com>
> spec/manifest: clarify the v2-s1 is provisional

- health/checks/checks_test.go
> Test: add test for HTTPChecker

- cmd/registry/main.go
@stevvooe 
Enabling log hook to capture the registry panic, when it happens.
Refer to #394.
> Panic: Add Handler

- docs/authentication.md
Pretty sure that service and docker were the wrong way around
Signed-off-by: Adrian Mouat <adrian.mouat@gmail.com>
> Fix service command

- Makefile
Enable the registry to be built with debug symbols with an environment variable 'REGISTRY_DEBUG'.
$ REGISTRY_DEBUG=true make binaries
> Enable the registry to be built with debug symbols

- uuid/uuid.go
> Correctly detect EPERM on crypto/rand.Random.Read failure

- docs/Dockerfile
- docs/configuration.md
- docs/deploying.md
- docs/help.md
- docs/index.md
- docs/introduction.md
- docs/notifications.md
- docs/spec/api.md
- docs/spec/api.md.tmpl
- docs/spec/json.md
- docs/storage-drivers/azure.md
- docs/storage-drivers/filesystem.md
- docs/storage-drivers/inmemory.md
- docs/storage-drivers/rados.md
- docs/storage-drivers/s3.md
Hugo final 1.7 Documentation PR -- please read carefully
This PR fixes problems found in review yesterday.  Review so you understand, then, do the following:
1. Merge into `master` branch.
2. Cherry-pick merge commit into the branch where you want me to release docs from.
3.  Send me an email with titled *Release Registry Docs from BRANCHNAME*
Unfortunately, while I fixed the majority of problems with your content there
are a few remaining ones that  we **must address after the release** these are:
- links to .md files in a GitHub repository are not working (.md -- unsupported)
- couple # links are not working; confirmed; suspected markdown/build interaction
We worked around this code problem with Olivier. But we will want that functionality in the future.
To see for yourself, `make docs` …
> Hugo final 1.7 Documentation PR -- please read carefully

- docs/Dockerfile
- docs/configuration.md
- docs/deploying.md
- docs/notifications.md
+ rollback the (now) unnecessary changes
> Fixed doc generation

- registry/client/blob_writer_test.go
> Add 'message' back to BlobTest sample json

- registry/handlers/api_test.go
- registry/handlers/images.go
Add Etag header for manifests.  Return 304 (Not Modified) if retrieved with If-None-Match header
> Cache headers for manifests.

- docs/authentication.md
Authentication was missed from the upgrade to Hugo
> Adding metadata files

- docs/authentication.md
Fixing heading not rendering
Fixing bad links:
deployed.md > deploying.md
spec/auth/token.md > /spec/auth/token.md
> Updates to authentication

- ROADMAP.md
Signed-off-by: Amy Lindburg <amy.lindburg@docker.com>
> Add relevant goal to Roadmap

- docs/index.md
> Fixing old ref to DHE to DTR fixes #681

- registry/storage/blobwriter.go
- registry/storage/blobwriter_resumable.go
> Fix build when using build tag 'noresumabledigest'

- registry/api/errcode/errors.go
- registry/api/errcode/errors_test.go
- registry/client/blob_writer_test.go
- registry/client/errors.go
- registry/client/repository_test.go
> Add ability to pass in substitution args into an Error

- ROADMAP.md
> Add goals and feature discussion to ROADMAP

- CONTRIBUTING.md
Closes #688
cc @icecrime @dmp42 
> Add Go coding style guidelines

- docs/Dockerfile
Use the base image from master.
> Updating to use base image from master

- README.md
> Add registry oyster to README

- CONTRIBUTING.md
> Clarify style rule about testing frameworks

- contrib/ceph/ci-setup.sh
Please see https://github.com/docker/distribution/issues/663#issuecomment-123481386 for details on this possible fix.
Closes #663.
> Attempt to fix Ceph after command syntax changed

- CONTRIBUTING.md
Some updates from review in docker/docker#14821.
> Revise coding style guidelines from Docker project commentary

- registry/api/v2/names_test.go
- registry/api/v2/routes_test.go
This was inspired by problems found with new regexps proposed in PR #690
> Add additional test coverage for the regexp contained in RepositoryNameRegexp

- registry/client/errors.go
thanks to @tiborvass for noticing
> Remove dead code

- docs/spec/api.md
- registry/api/v2/descriptors.go
- registry/handlers/api_test.go
- registry/handlers/images.go
Update descriptors table and regenerate API spec.
Fixes #142
> Manifest PUT should return 201 Created

- registry/handlers/app.go
When a request completes ensure only one log line is printed which
includes the http response code.
When debugging non-successful registry requests this will place
the error details and http status fields in the same log line
giving easier visibility to what error occured in the request.
> Log a single line when a response completes.

- docs/configuration.md
Fixes #672
Signed-off-by: Dave Tucker <dt@docker.com>
> Fix dead links in configuration.md

- registry/api/v2/names_test.go
> Add image name tests around hostnames

- cmd/registry/config-example.yml
Change suggested in https://github.com/docker/distribution-library-image/pull/1/files#r35935117
> Enable upload purging in example configuration file

- docs/authentication.md
- docs/building.md
- docs/configuration.md
- docs/introduction.md
- docs/notifications.md
- docs/spec/api.md
- docs/spec/auth/token.md
- docs/storage-drivers/s3.md
Signed-off-by: Alex Chan <alex.chan@metaswitch.com>
> Fix a few typos in the docs

- Godeps/Godeps.json
- Godeps/_workspace/src/github.com/AdRoll/goamz/aws/sign.go
- Godeps/_workspace/src/github.com/AdRoll/goamz/s3/multi.go
- Godeps/_workspace/src/github.com/AdRoll/goamz/s3/multi_test.go
- Godeps/_workspace/src/github.com/AdRoll/goamz/s3/responses_test.go
- Godeps/_workspace/src/github.com/AdRoll/goamz/s3/s3.go
- Godeps/_workspace/src/github.com/AdRoll/goamz/s3/s3i_test.go
- Godeps/_workspace/src/github.com/AdRoll/goamz/s3/s3t_test.go
- Godeps/_workspace/src/github.com/AdRoll/goamz/s3/s3test/server.go
The S3 library has made a few fixes to the retry logic. Updating the bindings
accordingly.
> Update s3 bindings

- docs/spec/api.md
- docs/spec/api.md.tmpl
- registry/api/v2/descriptors.go
> Spelling corrections

- README.md
Signed-off-by: Matt Bentley <matt@docker.com>
> Added information about docker/migrator

- AUTHORS
> Update authors file for 2.1 release

- .mailmap
- AUTHORS
> Fix double entry in AUTHORS file

- docs/configuration.md
> docs: Small typo fix in config.md

- docs/configuration.md
- docs/deploying.md
- docs/insecure.md
- docs/nginx.md
Couples of minor nits that where not addressed.
> Additional fixes

- docs/insecure.md
- docs/nginx.md
@aaronlehmann @RichardScothern
> Fix docs.docker.com

- docs/configuration.md
Signed-off-by: Miquel Sabaté <msabate@suse.com>
> docs: added the "delete" subsection in the configuration.md file

- Dockerfile
make `docker run registry:2+` support aliyun oss
> enable aliyun oss support by default in docker image

- cmd/registry/main.go
- docs/deploying.md
Certain load balancers, such as Amazon's Elastic Load Balancer, have a very
limited notion of health. While a properly configured and operational registry
should always return a 401 when hitting "/v2/", such load balancers cannot be
configured to treat this response code as healthy. This changeset makes "/"
always return a 200 response, unless the health checks have failed.
Closes #840 
> Provide yes man endpoint for inflexible load balancers

- docs/apache.md
- docs/deploying.md
- docs/nginx.md
- docs/recipes.md
- apache recipe, including group level fine-grain authorization (enforce -B for @stevvooe)
- streamlined nginx recipe a bit to match better with Apache
- recipes file
Validated and fully tested accompanying shell scripts.
Fixes #855 and starts the recipe effort.
cc @docker/distribution-maintainers
> Starting with recipes

- docs/configuration.md
- docs/mirror.md
> Add some clarifying documentation for pull through cache configuration

- registry/client/repository.go
- registry/client/repository_test.go
May need a few more test cases.
Closes #928, need to bring downstream for https://github.com/docker/docker/issues/15875.
cc @dmcgowan
> Correctly sanitize location url preserving parameters

- docs/configuration.md
Signed-off-by: bin liu <liubin0329@gmail.com>
> add indentations

- Godeps/Godeps.json
- Godeps/_workspace/src/github.com/ncw/swift/.travis.yml
- Godeps/_workspace/src/github.com/ncw/swift/README.md
- Godeps/_workspace/src/github.com/ncw/swift/auth_v3.go
- Godeps/_workspace/src/github.com/ncw/swift/swift.go
- Godeps/_workspace/src/github.com/ncw/swift/swift_test.go
- Godeps/_workspace/src/github.com/ncw/swift/swifttest/server.go
- docs/configuration.md
- registry/storage/driver/swift/swift.go
- registry/storage/driver/swift/swift_test.go
github/ncw/swift has added support for trust [1], so let's add it.
[1]https://github.com/ncw/swift/commit/8f232e4782787aee6ab31050e4aa75eb970b277c
> Add TrustId parameter to swift driver

- contrib/docker-integration/Dockerfile
> Download dind from v1.8.1 tag of docker/docker repo

- registry/registry.go
This solves a issue from #909 where instance.id was not printed in logs,
because this file was using the background context from
golang.org/x/net/context instead of
github.com/docker/distribution/context.
It's cleaner to standardize on one package, so this commit removes the
import of golang.org/x/net/context entirely. The Context interfaces
defined in both packages are the same, so other code using
golang.org/x/net/context can still pass its context to NewRegistry.
> Only use the distribution/context package in registry.go

- docs/spec/auth/token.md
Clarify that the token server **should not** return authorization errors.
Clarify that the registry **should** return a 403 response status if the token is invalid.
(The registry does not currently meet this requirement - see https://github.com/docker/distribution/issues/967).
> [docs/spec/auth] Clarify the Token auth workflow

- docs/nginx.md
closes #970
Signed-off-by: Louis Kottmann <louis.kottmann@gmail.com>
> Add exemple proxy mistake whith nginx sitting behind an ELB

- docs/spec/manifest-v2-1.md
Signed-off-by: Sungho Moon <sungho.moon@navercorp.com>
> Minor grammar fix : duplicated coordinators.

- Godeps/Godeps.json
- Godeps/_workspace/src/github.com/AdRoll/goamz/aws/aws.go
- Godeps/_workspace/src/github.com/AdRoll/goamz/aws/regions.go
- Godeps/_workspace/src/github.com/AdRoll/goamz/aws/sign.go
- Godeps/_workspace/src/github.com/AdRoll/goamz/s3/multi.go
- Godeps/_workspace/src/github.com/AdRoll/goamz/s3/multi_test.go
- Godeps/_workspace/src/github.com/AdRoll/goamz/s3/s3.go
- Godeps/_workspace/src/github.com/AdRoll/goamz/s3/s3_test.go
- Godeps/_workspace/src/github.com/AdRoll/goamz/s3/s3test/server.go
This upgrades to AdRoll/goamz@aa6e716d710a0c7941cb2075cfbb9661f16d21f1 which resolves AdRoll/goamz#358 (fixing support for subdomain endpoints).
> Upgrade Amazon library

- docs/configuration.md
> Clearer documentation around environment variable overrides

- registry/auth/auth.go
This interface was changed in a0fdfb9d4dd6e84703d155d9c1f3c72d52324814 (#736), but the comment wasn't ever updated to match.
Happy to rebase, amend, adjust, etc as desired. :+1:
> Update "type auth.Challenge" comment example code

- docs/notifications.md
> Prevent md->html link generation

- docs/nginx.md
This adds a variable to help nginx add the
Docker-Distribution-Api-Version when using basic auth, and not add the
header when it sees it from the upstream.
Also fix some minor spelling/grammar issues.
This should help with issues like #1028.
However, a better solution is probably for `docker pull` to not fall back to the v1 API when presented with a 401.
> Add annotated example for adding header; +spelling

- context/logger.go
> Add go version to logger output

- ROADMAP.md
Update pull through cache status.
Add section for metadata storage.
> Update distribution roadmap.

- registry/proxy/scheduler/scheduler.go
Buffer writing the scheduler entry state to disk by waiting for a threshold (10)
of changes to to the entry index.
> Buffer writes to scheduler state file.

- AUTHORS
- MAINTAINERS
> Update AUTHORS and MAINTAINERS

- Godeps/Godeps.json
- Godeps/_workspace/src/github.com/ncw/swift/README.md
- Godeps/_workspace/src/github.com/ncw/swift/auth.go
- Godeps/_workspace/src/github.com/ncw/swift/auth_v3.go
- Godeps/_workspace/src/github.com/ncw/swift/swift.go
- Godeps/_workspace/src/github.com/ncw/swift/swift_test.go
- Godeps/_workspace/src/github.com/ncw/swift/swifttest/server.go
- docs/storage-drivers/swift.md
- registry/storage/driver/swift/swift.go
- registry/storage/driver/swift/swift_test.go
> Redirect support in Swift driver

- README.md
> Add nice status badges to README

- Makefile
- circle.yml
> Use go 1.5 on the build machine

- docs/architecture.md
- docs/glossary.md
- docs/migration.md
- docs/spec/implementations.md
- docs/spec/manifest-v2-1.md
> Doc fixes found by validation job

- docs/configuration.md
errant H1 - yup, we'll be finding these in future validation checkers :)
> TOC for configuration page incorrect

- errors.go
- registry/handlers/images.go
- registry/storage/manifeststore.go
> Remove name verification

- registry/storage/driver/swift/swift.go
- registry/storage/driver/swift/swift_test.go
Signed-off-by: Sylvain Baubeau <sbaubeau@redhat.com>
> Use bulk delete to remove segments in Swift driver

- registry/storage/catalog.go
This change removes the sort() from the Repositories() function since
we're now guaranteed to have a lexigraphically sorted walk.  Also added
is the new ErrFinishedWalk which signals the walk function to stop feeding
files and directories since no more can be processed.
Signed-off-by: Patrick Devine <patrick.devine@docker.com>
> Make the catalog more efficient

- registry/storage/driver/storagedriver.go
I forgot how to make useful PRs, so I decide to do this one =)
> Fix comment for PathRegexp

- registry/storage/driver/testsuites/testsuites.go
> storage/driver: decrease memory allocation done during testsuite

- .mailmap
- AUTHORS
> Update AUTHORS for release

- Dockerfile
> Update go version to 1.5.2

- docs/configuration.md
> Fix typo in docs/configuration.md

- README.md
- contrib/docker-integration/README.md
> Update links to documentation

- circle.yml
- coverpkg.sh
Signed-off-by: Brian Bland <brian.bland@docker.com>
> Enables cross-package code coverage reporting

- docs/configuration.md
- docs/storage-drivers/swift.md
doesn't solve, but is related to #1254 
I can't say that I've tested any of these myself, but `prefix` is definitely correct (not `rootdirectory`).
@lebauce since it looks like you were the main contributor for the swift driver, do you think you could take a look?
> Help converge disagreeing swift docs

- digest/digest.go
- digest/digester.go
> digest: make FromBytes available on digest.Algorithm

- digest/digest.go
> digest: add NewDigestFromBytes for completeness

- registry/handlers/api_test.go
> Fix manifest API unit tests

- registry/storage/driver/gcs/gcs_test.go
This PR is a follow-up on #1332. PR #1332 made it a bit tricky to run the test suite on my development machine as it assumes that GOOGLE_APPLICATION_CREDENTIALS contains a private key in JSON format. However, on my development machine I use a simple oauth token. 
This PR first tries to initialise a DefaultTokenSource and if that fails attempts to interpret the GOOGLE_APPLICATION_CREDENTIALS as JSON text containing a private key. So this should work nicely for both CircleCI  and local development.
@RichardScothern
> StorageDriver GCS test suite: try google.DefaultTokenSource first

- docs/nginx.md
Carry #1329 : Fixes so that nginx will start
> Carry #1329 : Fixes so that nginx will start

- docs/spec/api.md
- docs/spec/api.md.tmpl
> spec/api: add missing entries to changelog

- docs/configuration.md
- docs/storage-drivers/azure.md
- docs/storage-drivers/filesystem.md
- docs/storage-drivers/gcs.md
- docs/storage-drivers/index.md
- docs/storage-drivers/inmemory.md
- docs/storage-drivers/oss.md
- docs/storage-drivers/rados.md
- docs/storage-drivers/s3.md
- docs/storage-drivers/swift.md
> Pulling driver specs out of configuruation.md

- registry/client/repository.go
- registry/client/transport/http_reader.go
Add a correctly-formatted Range header when the reader has been seeked to a different position.
Remove buffering on the reader, because it's not useful. Also remove artificial io.EOF return.
Add a CheckRedirect function to the HTTP client. Use it to preserve Accept and Range headers that were added to the original request.
> Support range requests in the client's httpReadSeeker

- manifests.go
- registry/client/repository.go
- registry/client/repository_test.go
> Add manifest put by digest to the registry client

- registry/auth/htpasswd/access.go
This was "authentication failured". Change it to "authentication
failure".
> Correct ErrAuthenticationFailure message

- docs/compatibility.md
> Add compatibility notes about pull by digest across Docker and Registry versions.

- docs/recipes.md
> Move 'Recipes' into the Registry menu

- version/version.go
> Update version file

- .mailmap
- AUTHORS
- MAINTAINERS
> Update maintainers and authors

- docs/storage-drivers/s3.md
- registry/storage/driver/s3/s3.go
- registry/storage/driver/s3/s3_test.go
Defaults to STANDARD, also supports REDUCED_REDUNDANCY.
Addresses #753
> Adds "storageclass" configuration parameter for S3 driver.

- registry/client/auth/session.go
> Print the correct token expiration time

- registry/storage/blob_test.go
> Correct type for repo reference

- Godeps/Godeps.json
- Godeps/_workspace/src/github.com/docker/goamz/aws/aws.go
- Godeps/_workspace/src/github.com/docker/goamz/aws/regions.go
Updates docker/goamz dependency
Fixes #1427
Note: region already supported in s3-aws driver in #1385
> [driver/s3] Adds support for ap-northeast-2 region

- context/doc.go
- context/trace.go
- digest/set.go
- notifications/metrics.go
- reference/regexp.go
- registry/api/v2/descriptors.go
- registry/api/v2/errors.go
- registry/handlers/api_test.go
- registry/handlers/app.go
- registry/handlers/helpers.go
- registry/storage/driver/gcs/gcs.go
- registry/storage/driver/storagedriver.go
- registry/storage/driver/testsuites/testsuites.go
- registry/storage/paths.go
Correct spelling of words in source code comments.
> Typo fixes in comments

- reference/reference.go
> Reference name rather than repository in reference grammar

- registry/storage/driver/oss/oss.go
Closes #1461 
Signed-off-by: liuchang0812 <liuchang0812@gmail.com>
> enhance log message of oss driver

- registry/client/auth/session.go
> Cleanup: remove unused log

- README.md
Signed-off-by: Asuka Suzuki <hello@tanksuzuki.com>
> Fix deadlink to license file

- registry/storage/tagstore_test.go
> compare error output in tagstore unit test

- registry/storage/driver/gcs/gcs.go
- registry/storage/driver/gcs/gcs_test.go
The Move operation is only used to move uploaded blobs to their final destination. There is no point in implementing Move on "folders". Apart from simplifying the code, this also saves an HTTP request in the GCS driver.
> StorageDriver: GCS: remove support for directory Moves

- registry/client/auth/session.go
Login needs to add an offline token flag to ensure a refresh token is returned by the token endpoint.
> Add offline token option

- registry/client/auth/session.go
Cross repository push tokens were not being cached and could not be used,
now any returned token will be used and the caching is hidden in the getToken function.
> Fix oauth cross repository push

- registry/storage/driver/s3-aws/s3.go
Mirrors changes from #1414 into the newer driver
> [driver/s3aws] Update s3aws driver parameter parsing to match s3goamz

- registry/client/repository.go
just spotted this one for now, we'll keep looking though
> registry: client: repository: close response body

- registry/storage/linkedblobstore.go
Signed-off-by: 姜继忠 <jizhong.jiangjz@alibaba-inc.com>
> fix manifest revision search, closes #1535

- README.md
I believe it's a typo somehow? :)
> Replace a strange comma with a space.

- configuration/configuration.go
- configuration/configuration_test.go
- docs/configuration.md
- notifications/bridge_test.go
- registry/api/v2/urls.go
- registry/api/v2/urls_test.go
- registry/client/repository.go
- registry/handlers/api_test.go
- registry/handlers/app.go
- registry/handlers/app_test.go
Return relative URLs
Closes #1346 
> Return relative URLs 

- docs/configuration.md
Update duration.
Fix and Close #925 
> Update the Duration value for Cloudfront

- context/util.go
simplify the type judgment in context.
> type judgment in context

- docs/spec/api.md
- docs/spec/api.md.tmpl
Add a note to the delete manifest section to aid getting the correct 
digest to delete manifests.
closes #1565 #1579
> Manifest delete documentation enhancement

- docs/storage-drivers/s3.md
Document required IAM permissions for S3 storage driver.
Closes #1391 
> Document required IAM permissions for S3 storage driver.

- registry/storage/driver/swift/swift.go
After #1578, this is the second product of my investigations on errors with my team's internal Registry. Similar errors are tracked here as #1013 and #1539 aka docker/docker#21290.
During load tests, I especially saw the same error ("digest invalid: provided digest did not match uploaded content") as @tdooner in #1013:
```
time="2016-03-29T13:06:13.84409888Z" level=error msg="response completed with error" err.code="digest invalid" err.detail="invalid digest for referenced layer: sha256:61cdfc955489883180ac1bf6f96a8f8d4bfbacafdde22da069c40084cabe7d95, content does not match digest" err.message="provided digest did not match uploaded content" go.version=go1.5.3 http.request.host="registry.local:31201" http.request.id=9bb40523-dbee-4cb2-90a4-ec58ec3fdecc http.request.method=PUT …
```
> registry/storage/swift: detect and fix outdated container listings

- docs/insecure.md
- docs/spec/manifest-v2-1.md
- docs/spec/manifest-v2-2.md
Fixes #1598
@RichardScothern  for review.  The error was coming from the .tmpl file.  Links to the `manifest*` files didn't resolve because they are listed as draft.  Fixed this too.
> Updated per conversation with Richard

- docs/storage-drivers/s3.md
> Correction for JSON example.

- notifications/listener.go
Signed-off-by: yuzou <zouyu7@huawei.com>
> use context.GetLogger to replace logrus in listener

- registry/storage/driver/s3-aws/s3.go
According to the S3 specification (http://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadComplete.html), the server returns InvalidPartOrder error when we send a Complete Multipart Upload xml request with parts not sorted by part number. While Amazon S3 seems to not hard require this, some alternative s3 compliant tools (like https://github.com/minio/minio/) need this to work smoothly with Distribution.
> s3 driver: Sorting completed parts by part number for a better accordance with S3 spec

- contrib/docker-integration/README.md
Updates the readme to mention running the tests using golem.
Also provides instructions for making test development easier.
> Integration test readme update

- registry/garbagecollect.go
- registry/root.go
- registry/storage/garbagecollect.go
- registry/storage/garbagecollect_test.go
> Move GC into storage package and add tests

- AUTHORS
- version/version.go
> Update AUTHORS and version file

- registry/storage/driver/s3-aws/s3.go
> Add 'us-gov-west-1' to the valid region list.

- docs/spec/api.md
- docs/spec/api.md.tmpl
> Remove the unimplemented monolithic upload section from the API

- blobs.go
- registry/handlers/app.go
- registry/middleware/registry/middleware.go
- registry/storage/registry.go
Add ability to replace blobAccessController to solve #1707 .
@stevvooe @RichardScothern WDYT?
> Add support for  blobAccessController middleware

- docs/spec/auth/oauth.md
Signed-off-by: Ke Xu <leonhartx.k@gmail.com>
> fix broken markdown

- cmd/registry/config-dev.yml
> Revert inadvertant filepath change

- docs/storage-drivers/swift.md
- registry/storage/driver/swift/swift.go
- registry/storage/driver/swift/swift_test.go
> Swift auth version param

- docs/compatibility.md
- docs/deploying.md
- docs/index.md
- docs/insecure.md
- docs/spec/manifest-v2-2.md
Some more checker complaints squashed. Now the registry docs will work in the archive too.
> Next load of docs validation fixes

- registry/api/errcode/register.go
- registry/client/errors.go
Now Docker is built with go1.6 /cc @aaronlehmann 
> registry: use const for status code 429

- docs/spec/api.md
- registry/api/v2/descriptors.go
> Clarify API documentation around catalog fetch behavior

- registry/client/repository.go
- registry/client/repository_test.go
The client may need the content digest to delete a manifest using the digest used by the registry.
Allows implemented suggestion deletion flow from here https://github.com/docker/distribution/issues/1566#issuecomment-205484205 with the registry client.
> Add option to get content digest from manifest get

- contrib/token-server/errors.go
- contrib/token-server/main.go
- contrib/token-server/token.go
- registry/auth/auth.go
- registry/auth/htpasswd/access.go
- registry/auth/htpasswd/htpasswd.go
Updates the test token server to support oauth2.
Tracking specification changes in #1418
> Integration token server supporting oauth

- CHANGELOG.md
> Changelog for 2.5

- .mailmap
- AUTHORS
- MAINTAINERS
Update .mailmap, AUTHORS and MAINTAINERS files.
> Prepare for the release.

- docs/deploying.md
Signed-off-by: Victoria Bialas <victoria.bialas@docker.com>
> fixed broken link due to topic re-org in PR#23492

- BUILDING.md
- docs/recipes/index.md
- docs/recipes/menu.md
Closes #1776
@RichardScothern @stevvooe This is all that needed doing :)
> Move the building.md doc to the top of the git repo

- docs/recipes/mirror.md
> Stop hugo from making the example URL into a link

- registry/storage/driver/s3-aws/s3.go
- registry/storage/driver/s3-aws/s3_test.go
Submitting to upstream for full storage driver test suite.
Signed-off-by: Josh Chorlton <josh.chorlton@docker.com>
> fixed s3 Delete bug due to read-after-delete inconsistency

- registry/storage/driver/s3-aws/s3.go
> Allow EC2 IAM roles to be used when authorizing region endpoints

- docs/spec/api.md
- docs/spec/api.md.tmpl
- registry/api/v2/descriptors.go
Add entries with this error code in registry/api/v2/descriptors.go.
> Document TOOMANYREQUESTS error code

- registry/storage/catalog_test.go
> Use registry APIs to generate catalog test environment

- contrib/docker-integration/docker-compose.yml
- contrib/docker-integration/install_certs.sh
- contrib/docker-integration/nginx/Dockerfile
- contrib/docker-integration/nginx/registry.conf
- contrib/docker-integration/nginx/v1/search.json
- contrib/docker-integration/token.bats
- contrib/docker-integration/tokenserver-oauth/registry-config-notls.yml
- contrib/token-server/main.go
Test for v1 search endpoint using v2 oauth with refresh token.
This is testing https://github.com/docker/docker/pull/24568.
> Search v2 auth test

- manifest/versioned.go
> manifest: versioned: fix typo

- cmd/registry/main.go
> Load the middleware/redirect driver

- registry/storage/manifestlisthandler.go
- registry/storage/registry.go
- registry/storage/schema2manifesthandler.go
- registry/storage/signedmanifesthandler.go
> Decouple storage components by redefining dependencies as interfaces 

- circle.yml
> Remove godep check from build and increase test timout

- registry/handlers/catalog.go
- registry/storage/catalog.go
Signed-off-by: Edgar Lee <edgar.lee@docker.com>
> Stop ErrFinishedWalk from escaping from Repositories walk

- registry/storage/catalog.go
- registry/storage/catalog_test.go
Signed-off-by: Edgar Lee <edgar.lee@docker.com>
> Improve catalog enumerate runtime by an order of magnitude

- manifest/schema2/manifest.go
This is required for github.com/docker/docker/pull/25582
Signed-off-by: Anusha Ragunathan <anusha@docker.com>
> Add plugin mediatype to distribution manifest.

- docs/storage-drivers/s3.md
- registry/storage/driver/s3-aws/s3.go
- registry/storage/driver/s3-aws/s3_test.go
- registry/storage/driver/s3-aws/s3_v2_signer.go
Closes #1796
Closes #1606
Signed-off-by: Fabio Berchtold <fabio.berchtold@swisscom.com>
> Add v2 signature signing to S3 storage driver

- README.md
Points to the current location of BUILDING.md
Signed-off-by: Mike Brown <brownwm@us.ibm.com>
> fixes link to building.md

- registry/auth/token/accesscontroller.go
- registry/auth/token/token_test.go
closes #1909
Signed-off-by: Jason Heiss <jheiss@twosigma.com>
> Check PEM block type when reading token cert file

- registry/storage/garbagecollect_test.go
> Fix unit test

- registry/proxy/proxymanifeststore_test.go
- registry/storage/cache/cachecheck/suite.go
- registry/storage/catalog_test.go
> Satisfy the latest go lint rules

- registry/storage/driver/oss/oss.go
- registry/storage/driver/s3-goamz/s3.go
Fix Delete method's notion of subpaths for s3-goamz and aliyun OSS.
Signed-off-by: RIchard Scothern <richard.scothern@docker.com>
> Nwt fix s3 goamz & Aliyun OSS delete

- registry/storage/driver/s3-aws/s3.go
> Allow using ec2 roles when specifying region endpoint

- registry/storage/garbagecollect.go
> storage/garbagecollect: add emit comments for when dryRun is false

- registry/storage/driver/s3-aws/s3.go
Signed-off-by: Matt Bentley <mbentley@mbentley.net>
> Added new us-east-2 region for S3

- registry/client/transport/http_reader.go
Close https://github.com/docker/docker/issues/27642
@stevvooe @aaronlehmann PTAL
> registry/client: set Accept: identity header when getting layers

- Dockerfile
- circle.yml
Ref: #2028
@dmcgowan let's see how this goes.
> Bump to go1.7

- Makefile
Signed-off-by: yuexiao-wang <wang.yuexiao@zte.com.cn>
> Add targets for Makefile

- registry/client/errors.go
For more consistency in handling client errors, this just converts to an API error instead of having the caller handle yet another type of error.
> Update oauth errors to use api errors

- RELEASE-CHECKLIST.md
> Document registry release process

- docs/configuration.md
> Fix storage driver links

- AUTHORS
- version/version.go
> Release preperation: update AUTHORS and version file

- CHANGELOG.md
> Release notes for v2.6.0-rc1

- Godeps/Godeps.json
- vendor/github.com/ncw/swift/README.md
- vendor/github.com/ncw/swift/swift.go
Gets rid of deviation between hash and upstream.
> Update swift vendor for upstreamed change

- docs/spec/api.md
- docs/spec/api.md.tmpl
Signed-off-by: Ling FaKe lingfake@huawei.com
> api.md:fix disordered placement of section "Deleting a Layer"

- docs/spec/manifest-v2-1.md
- docs/spec/manifest-v2-2.md
> Fix doubled words

- registry/storage/driver/oss/oss.go
fix #2057 
Signed-off-by: Kira me@imkira.com
> filter listResponse.Contents in OSS driver.List() 

- registry/storage/driver/azure/azure.go
See #2077 for the background.
The PR #1438 which was not reviewed by azure folks basically introduced
a race condition around uploads to the same blob by multiple clients
concurrently as it used the "writer" class introduced in #1438 which does
chunked upload of blobs using "AppendBlob" type, which was not atomic.
This patch fixes PutContent() to use the atomic upload operation that works
for uploads smaller than 64 MB and works on "BlockBlob" types only. To be
backwards compatible, we query the type of the blob first and if it is not
a "BlockBlob" we delete the blob first before doing an atomic PUT. This
creates a small inconsistency/race window "only once". Once the blob is made
"BlockBlob", it is overwritten with a single PUT atomically next time.
Tested with existing code side by …
> azure: fix race condition in PutContent()

- digest/digest.go
- digest/digester.go
> digest: add FromString helper to Digest

- digest/algorithm.go
- digest/algorithm_test.go
- digest/digest.go
- digest/digest_test.go
> digest: better test coverage

- digest/algorithm.go
- digest/digest.go
- reference/reference_test.go
Pull request ci was not running and caused these minor issues to not be caught.
> Fix small lint and unit test issues

- CHANGELOG.md
- configuration/configuration.go
- contrib/token-server/main.go
- contrib/token-server/token.go
- docs/spec/auth/scope.md
- registry/auth/auth.go
- registry/auth/token/accesscontroller.go
- registry/auth/token/token.go
- registry/client/auth/session.go
- registry/handlers/images.go
- registry/storage/garbagecollect.go
Updates change log
Cherry-picks related changes
> Release 2.6.0 rc2 changes

- docs/configuration.md
Improve formatting of configuration.md
Backported from master to release/2.5
> Backport #2116 to releases/2.5

- docs/configuration.md
Same as #2122 but against `releases/2.6`.
> Backport #2116 to releases/2.6

- CHANGELOG.md
> Release notes for 2.6

- registry/handlers/api_test.go
Update handler test to use WithName
> Update handler test to use WithName

- context/doc.go
- health/health_test.go
- manifest/manifestlist/manifestlist.go
Signed-off-by: fate-grand-order <chenjg@harmonycloud.cn>
> fix typos in comment

- RELEASE-CHECKLIST.md
Add details for release checklist for where to put the update the changelist and which branch to cherry-pick from. Also add more details around creating the tag and verifying the tag is correct.
> Update release checklist with further details

- notifications/event.go
- notifications/sinks.go
Signed-off-by: fate-grand-order <chenjg@harmonycloud.cn>
> fix some typos in notifications/event.go and sinks.go

- CHANGELOG.md
- registry/api/v2/urls.go
- registry/api/v2/urls_test.go
Changes from #2219 into release 2.6. Merge into master first.
> [2.6] Fix forwarded logic

- CHANGELOG.md
- registry/handlers/app.go
- registry/storage/driver/base/base.go
Include fix for expensive health checks
Updated changelog for rc2
> [2.6] Updates for 2.6.1-rc2

- registry/handlers/app.go
- registry/handlers/context.go
- vendor.conf
- vendor/github.com/gorilla/mux/README.md
- vendor/github.com/gorilla/mux/context_gorilla.go
- vendor/github.com/gorilla/mux/context_native.go
- vendor/github.com/gorilla/mux/doc.go
- vendor/github.com/gorilla/mux/mux.go
- vendor/github.com/gorilla/mux/regexp.go
- vendor/github.com/gorilla/mux/route.go
> register/handlers: remove context manager

- docs/architecture.md
> Put architecture.md back into distribution repo

- configuration/configuration.go
- context/doc.go
Signed-off-by: kaiwentan <kaiwentan@harmonycloud.cn>
> fix some misspells

- docs/spec/api.md
- docs/spec/api.md.tmpl
- registry/api/v2/routes_test.go
> api: url typo in specification

- .mailmap
- AUTHORS
- version/version.go
> [release/2.6] release: prepare for 2.6.2 release

- .mailmap
- AUTHORS
- version/version.go
> [release/2.5] release: prepare for 2.5.2 release

- docs/spec/api.md
- docs/spec/api.md.tmpl
Signed-off-by: Jon Johnson <jonjohnson@google.com>
> Fix typo in api spec

- CONTRIBUTING.md
> Fix registry version argument

- registry/api/errcode/handler.go
- registry/proxy/proxyauth.go
- registry/storage/blobwriter.go
> registry: feed the linter by removing redundant err check

- registry/api/errcode/handler.go
- registry/proxy/proxyauth.go
- registry/storage/blobwriter.go
(cherry picked from commit 4abf680c76151da0f4a9086d44abad655cb1f01e)
> [2.6] registry: feed the linter by removing redundant err check

- docs/spec/index.md
> Fixed broken storage driver link

- .gometalinter.json
- notifications/endpoint.go
- registry/storage/driver/base/base.go
- registry/storage/driver/middleware/cloudfront/s3filter_test.go
`goimports` needed to be run on 3 files, did that and enabled check for ci
> Enable goimports check

- configuration/configuration.go
- configuration/configuration_test.go
- registry/registry.go
- vendor.conf
- vendor/gopkg.in/yaml.v2/LICENSE
- vendor/gopkg.in/yaml.v2/NOTICE
- vendor/gopkg.in/yaml.v2/README.md
- vendor/gopkg.in/yaml.v2/apic.go
- vendor/gopkg.in/yaml.v2/decode.go
- vendor/gopkg.in/yaml.v2/emitterc.go
- vendor/gopkg.in/yaml.v2/encode.go
- vendor/gopkg.in/yaml.v2/parserc.go
- vendor/gopkg.in/yaml.v2/readerc.go
- vendor/gopkg.in/yaml.v2/resolve.go
- vendor/gopkg.in/yaml.v2/scannerc.go
- vendor/gopkg.in/yaml.v2/sorter.go
- vendor/gopkg.in/yaml.v2/writerc.go
- vendor/gopkg.in/yaml.v2/yaml.go
- vendor/gopkg.in/yaml.v2/yamlh.go
Mark the top level Loglevel field as deprecated
> Update yaml parser

- registry/storage/manifestlisthandler.go
- registry/storage/manifeststore_test.go
- registry/storage/ocimanifesthandler.go
- registry/storage/schema2manifesthandler.go
Addresses issue #2650
Signed-off-by: Mike Brown <brownwm@us.ibm.com>
> adds validation testing for schema version values

- MAINTAINERS
People in this list: please double check your information is correct.
@manishtomar 
@caervs 
@davidswu 
@RobbKistler
Ping @dmcgowan @thaJeztah
> Add new reviewers

- contrib/compose/nginx/docker-registry-v2.conf
Added nginx configuration for uploading large sized blobs (layer size) to registry when using nginx as reverse proxy
> Added nginx config for uploading large sized blobs

- blobs.go
Signed-off-by: Jie Yu <390282283@qq.com>
> Fix the sentence

- configuration/configuration.go
- contrib/docker-integration/tokenserver-oauth/registry-config-notls.yml
- contrib/docker-integration/tokenserver-oauth/registry-config.yml
- contrib/docker-integration/tokenserver/registry-config.yml
- docs/configuration.md
- errors.go
- notifications/listener_test.go
- registry/handlers/api_test.go
- registry/handlers/app.go
- registry/proxy/proxymanifeststore_test.go
- registry/storage/catalog_test.go
- registry/storage/garbagecollect_test.go
- registry/storage/manifeststore_test.go
- registry/storage/registry.go
- registry/storage/v1unsupportedhandler.go
port of #2473
Signed-off-by: Viktor Stanchev <me@viktorstanchev.com>
> disable schema1 by default, add a config flag to enable it

- configuration/configuration.go
- contrib/docker-integration/tokenserver-oauth/registry-config-notls.yml
- contrib/docker-integration/tokenserver-oauth/registry-config.yml
- contrib/docker-integration/tokenserver/registry-config.yml
- docs/configuration.md
- errors.go
- notifications/listener_test.go
- registry/handlers/api_test.go
- registry/handlers/app.go
- registry/proxy/proxymanifeststore_test.go
- registry/storage/catalog_test.go
- registry/storage/garbagecollect_test.go
- registry/storage/manifeststore_test.go
- registry/storage/registry.go
- registry/storage/v1unsupportedhandler.go
port of #2473
Signed-off-by: Viktor Stanchev <me@viktorstanchev.com>
Carrying to trigger updated CI
closes #2472
closes #2474
> [carry #2474] disable schema1 by default, add a config flag to enable it

- docs/spec/auth/oauth.md
- manifest/ocischema/manifest.go
- manifest/schema1/manifest.go
Signed-off-by: ruicao <ruicao@alauda.io>
> Fix some typos

- version/version.go
> Update version to 2.7.0-rc.0

- contrib/compose/README.md
Signed-off-by: Rui Cao <ruicao@alauda.io>
> Fix typo: commmand -> command

- registry/client/repository_test.go
Signed-off-by: Yongxin Li <yxli@alauda.io>
> typo fix about overridden

- releases/v2.7.0.toml
- version/version.go
> Release notes for 2.7

- releases/v2.7.1.toml
Release notes for single fix release
> Release notes for 2.7.1

- version/version.go
Needs to be included for 2.7.1 release
> Update version file for 2.7.1

- reference/normalize.go
- reference/normalize_test.go
This copies the `NormalizeImageRef` utility function that was added in containerd/cri https://github.com/containerd/cri/blob/0e42438e7a157f6aec41cd808a85bc883d646ff3/pkg/util/image.go#L23-L50
Reason for this PR is that starting with https://github.com/containerd/containerd/commit/bce20b75da6264f5f26e26130e9a0d52c006ecfd (https://github.com/containerd/containerd/pull/2633), containerd now adds containerd/cri as a new dependency when vendoring in docker/cli (because of this utility which is mainly a small wrapper for other functions in docker/distribution);
```
Building statically linked build/docker-linux-amd64
vendor/github.com/containerd/containerd/images/archive/reference.go:22:2: cannot find package "github.com/containerd/cri/pkg/util" in any of: …
```
> Add reference. ParseDockerRef utility function

- registry/handlers/app.go
This is useful to know which user pulled/pushed which repo.
> Log authorized username

- registry/handlers/blobupload.go
- registry/storage/driver/testsuites/testsuites.go
Signed-off-by: Jesse Brown <jabrown85@gmail.com>
> Fix typo: offest -> offset

- docs/spec/deprecated-schema-v1.md
Signed-off-by: Adrian Plata <adrian.plata@docker.com>
> Adding deprecated schema instructions

- CONTRIBUTING.md
- README.md
- code-of-conduct.md
Update project details to align more closely with community updates in OCI and containerd.
> Update readme and contributing docs

- go.mod
- go.sum
- notifications/bridge.go
- notifications/bridge_test.go
- notifications/endpoint.go
- notifications/event.go
- notifications/http.go
- notifications/http_test.go
- notifications/metrics.go
- notifications/sinks.go
- notifications/sinks_test.go
- registry/handlers/app.go
- vendor/github.com/docker/go-events/.gitignore
- vendor/github.com/docker/go-events/CONTRIBUTING.md
- vendor/github.com/docker/go-events/LICENSE
- vendor/github.com/docker/go-events/MAINTAINERS
- vendor/github.com/docker/go-events/README.md
- vendor/github.com/docker/go-events/broadcast.go
- vendor/github.com/docker/go-events/channel.go
- vendor/github.com/docker/go-events/errors.go
- vendor/github.com/docker/go-events/event.go
- vendor/github.com/docker/go-events/filter.go
- vendor/github.com/docker/go-events/queue.go
- vendor/github.com/docker/go-events/retry.go
- vendor/modules.txt
This addresses #1553.
TBD: Queue not converted yet
Signed-off-by: Elliot Pahl <elliot.pahl@gmail.com>
> Use go-events package

- go.mod
- go.sum
- vendor/github.com/opencontainers/go-digest/.mailmap
- vendor/github.com/opencontainers/go-digest/MAINTAINERS
- vendor/github.com/opencontainers/go-digest/README.md
- vendor/github.com/opencontainers/go-digest/algorithm.go
- vendor/github.com/opencontainers/go-digest/digest.go
- vendor/github.com/opencontainers/go-digest/digester.go
- vendor/github.com/opencontainers/go-digest/doc.go
- vendor/github.com/opencontainers/go-digest/verifiers.go
- vendor/github.com/opencontainers/image-spec/specs-go/version.go
- vendor/modules.txt
1, update go-digest to v1.0.0-rc1
2, update image-spec to v1.0.1
Signed-off-by: wang yan <wangyan@vmware.com>
> Update oci library

- registry/proxy/proxyblobstore.go
Signed-off-by: zhipengzuo <zuozhipeng@baidu.com>
> clean up code because err is always nil

- registry/storage/driver/s3-aws/s3.go
This PR reopens #2973 and fixes still hardcoded list of credential providers:
- `StaticProvider`
- `EnvVarProvider`
- `SharedCredentialProvider`
-  `EC2RoleProvider`
Instead it relies on SDK defaults when creating a new AWS Config and AWS Session. And only overrides them with `StaticProvider` if `accesskey` and `secretkey` are provided via `config.yml`:
```yaml
storage:
s3:
accesskey: ABCDEFG123HY4LWA5TOG
secretkey: AB1C+D2EF/Ge3cA/vQbUfMVpuDImUZsxkpCQDUy0
region: us-east-1
...
``` 
As the result, it uses AssumeRoleWithWebIdentity credential provider (in [`session.resolveCredentials`](https://github.com/aws/aws-sdk-go/blob/95871fc3b42a8910f81ec01c74975293dafced97/aws/session/session.go#L630)) that resolves assigned IAM role to K8s Service Accounts via OIDC token. Please see …
> Reopen PR #2973 (Support ECS TaskRole in S3 storage driver).

- registry/client/repository.go
fixes https://github.com/docker/distribution/issues/3288
addresses https://github.com/moby/moby/issues/41621
> #3288 Remove empty Content-Type header

- ADOPTERS.md
Signed-off-by: Justin Cormack <justin@specialbusservice.com>
> Add Adopters

- .github/workflows/dummy.yml
@arkodg Merge this PR to be able to enable GitHub Actions on this repo and then workflow of #3312 will be turned on
> Dummy workflow to enable GitHub Actions

- MAINTAINERS
Thanks for all the work Arko, and welcome Milos!
Signed-off-by: Justin Cormack <justin@specialbusservice.com>
> Replace Arko with Milos as a maintainer

- .github/workflows/ci.yml
Signed-off-by: Chris Patterson <chrispat@github.com>
> Fixing push workflow

- CONTRIBUTING.md
- README.md
fixes https://github.com/distribution/distribution/issues/3342
> Update slack channel to CNCF slack

- reference/regexp.go
Add context to comment to explain the repo name regex in addition to describing it.
Signed-off-by: David Warshaw <david.warshaw@gmail.com>
> Clarify repo name regex intention

- Dockerfile
based on this comment https://github.com/docker/distribution-library-image/pull/92#discussion_r409143114
> get rid of apache2-utils

- README.md
Make more neutral, link to new CNCF Slack channel.
Signed-off-by: Justin Cormack <justin@specialbusservice.com>
> Update README a bit

- .github/workflows/ci.yml
- script/validate/dco
Signed-off-by: Chris Patterson <chrispat@github.com>
> [backport release/2.7] First draft of actions based ci

- .github/workflows/e2e.yml
- Dockerfile
- tests/push.sh
> Add a basic e2e test for CI

- health/health.go
This PR releases the unreleased time.Ticker resources.
> Release ticker resources

- docs/spec/auth/token.md
> Fix html not rendering markdown link properly

- .github/workflows/conformance.yml
- README.md
> OCI: add conformance test github action

- .github/workflows/conformance.yml
- README.md
Signed-off-by: Milos Gajdos <milosgajdos83@gmail.com>
> Fix OCI conformance workflow report and README badge

- cmd/registry/config-dev.yml
> use memory as the cache in test

- contrib/token-server/main.go
- registry/handlers/app.go
- registry/registry.go
1, Fix GoSec G404: Use of weak random number generator (math/rand instead of crypto/rand)
2, Fix Static check: ST1019: package "github.com/sirupsen/logrus" is being imported more than once
> fix go check issues

- CONTRIBUTING.md
Signed-off-by: Steve Lasker <stevenlasker@hotmail.com>
> Add CNCF Security email account

- MAINTAINERS
Signed-off-by: Steve Lasker <stevenlasker@hotmail.com>
> Add cncf-distribution-maintainers@cncf.io to maintainers file

- Dockerfile
> go 1.16.15

- releases/v2.8.1.toml
OPening now that https://github.com/distribution/distribution/pull/3604 has been merged in
> Update 2.8.1. release notes

- registry/storage/driver/s3-aws/s3.go
add multipart uploads pagination on s3 driver (add support of 1000+ rows).
Fixes #3420
> fix: paginate through s3 multipart uploads

- registry/storage/driver/inmemory/mfs.go
> Fix panic in inmemory driver

- registry/storage/driver/s3-aws/s3.go
- registry/storage/driver/s3-aws/s3_test.go
Since #3218 looks stalled, I've taken the liberty to try getting this over the finish line
Signed-off-by: Milos Gajdos <milosthegajdos@gmail.com>
> Update s3 ListObjects to V2 API

- MAINTAINERS
> Update maintainers mailing list

- manifest/manifestlist/manifestlist.go
Just a minor comment fix. The previous comment appears to have been a copy/paste error.
Signed-off-by: Brandon Mitchell <git@bmitch.net>
> Fix comment for manifest list

- Dockerfile
https://github.com/tonistiigi/xx/releases/tag/v1.1.1
> Update to xx 1.1.1

- .github/workflows/build.yml
Signed-off-by: Gábor Lipták gliptak@gmail.com
> Add Go 1.19 to GHA

- registry/handlers/api_test.go
- registry/handlers/blobupload.go
1, return the right upload offset for client when asks.
2, do not call ResumeBlobUpload on getting status.
3, return 416 rather than 404 on failed to patch chunk blob.
4, add the missing upload close
> fit get status issue

- docs/configuration.md
> Update doc to reflect that logs go to stderr

- reference/sort.go
- reference/sort_test.go
This forward-ports the following patches;
- https://github.com/containerd/containerd/pull/5250
- https://github.com/containerd/containerd/pull/6993
- https://github.com/containerd/containerd/pull/7007
Patches were slightly modified to account for different import paths.
> reference: implement Sort()

- .github/workflows/build.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/conformance.yml
- .github/workflows/e2e.yml
- .github/workflows/fossa.yml
- .github/workflows/validate.yml
Bump actions to fix warnings in the workflows: https://github.com/distribution/distribution/actions/runs/3495490054
Also adds concurrency check: https://docs.github.com/en/actions/using-jobs/using-concurrency
> ci: update github actions

- registry/handlers/app.go
Currently, "response completed with error" log lines include an `auth.user.name` key, but successful "response completed" lines do not include this, because they are logged a few stack frames up where `auth.user.name` is not present on the `Context`. Move the successful request logging inside the `dispatcher` closure, where the logger on the context automatically includes this key.
> Log username on successful requests

- registry/storage/driver/s3-aws/s3.go
This is an edge case when we are trying to upload an empty chunk of data using a `MultiPart` upload.
As a result, we are trying to complete the `MultipartUpload` with an empty slice of `completedUploadedParts` which will always lead to 400 being returned from S3 See: https://docs.aws.amazon.com/sdk-for-go/api/service/s3/#CompletedMultipartUpload
Solution: we upload an empty i.e. 0 byte part as a single part and then append it to the `completedUploadedParts` slice used to complete the `MultiPart` upload.
> Enable pushing empty blobs

- registry/storage/driver/inmemory/mfs.go
Signed-off-by: Shengjing Zhu <zhsj@debian.org>
> [release/2.8] Fix panic in inmemory driver

- context/http_test.go
- context/trace_test.go
- notifications/sinks_test.go
- reference/normalize_test.go
- reference/reference_test.go
- reference/regexp_test.go
- registry/api/errcode/errors_test.go
- registry/api/v2/routes_test.go
- registry/api/v2/urls_test.go
- registry/auth/token/types_test.go
- registry/handlers/hmac_test.go
- registry/storage/driver/middleware/cloudfront/s3filter_test.go
> assorted test updates

- .mailmap
- releases/v2.8.2-beta.toml
- version/version.go
> Add 2.8.2-beta.1 release notes

- releases/v2.8.2-beta.toml
- version/version.go
Updates Release notes for `beta-2` release.
PTAL @thaJeztah @squizzi @corhere
> Add 2.8.2 beta.2 release notes

- registry/storage/driver/s3-aws/s3.go
Context in https://github.com/distribution/distribution/issues/3533#issuecomment-1563549913
fixes https://github.com/distribution/distribution/issues/3533
> Fix panic in the s3 backend walk logic

- docs/recipes/nginx.md
Followup for https://github.com/docker/docs/pull/9270#pullrequestreview-287741236
Import of https://github.com/docker/docs/pull/9441
It was mentioned that the docs moved here, so, Hi! :slightly_smiling_face: https://github.com/docker/docs/pull/9441#discussion_r1133128534
> Use docker-compose spec v3 in nginx receipt

- README.md
New PR with GPG signed commit, signer info in message.
> Centered logo in README.md

- CODE-OF-CONDUCT.md
Closes https://github.com/distribution/distribution/issues/3970
> Update Code of Conduct

- configuration/parser.go
- configuration/parser_test.go
resolves https://github.com/distribution/distribution/issues/625
copied from https://github.com/distribution/distribution/issues/625#issuecomment-916392527
> Added support for configuring array values with environment variables

- registry/storage/driver/azure/azure_test.go
The Azure tests fail if there is no Azure configuration available, instead they should be skipped.
Also, one of the Azure tests is wrong and doesn't match the code.
> Fix Azure tests

- MAINTAINERS
James has been an active member of the community for a while now, being very involved with many issues on this repo and in the Slack channel and has a number of contributions here.
Although I myself am new, I'm happy to propose him as a new reviewer on this project so that we can ramp up the activity.
As per Governance process, this must be approved by 4 of the existing maintainers.
CC: @Jamstah
> Propose James Hewitt as a new reviewer

- registry/handlers/api_test.go
- registry/handlers/app.go
- registry/handlers/manifests.go
This is a rebase of https://github.com/distribution/distribution/pull/3984 taken over from @DavidSpek with his permission due to GH permissions sadness (https://github.com/distribution/distribution/pull/3984#issuecomment-1681327720).
> Remove references to schema1 pacakge from handlers

- MAINTAINERS
Unfortunately, I don't think I am a good candidate for maintainers on this repo. I originally joined because I was tech lead on a cloud product built around distribution and wanted to help get some of our fork's changes upstream. I have since been laid off and don't intend to work on container registries in the future.
Thanks for having me and good luck with everything!
> Remove waynr from MAINTAINERS

- Makefile
As the title says.
Closes: https://github.com/distribution/distribution/issues/3617
> Add some secure compilation options, especially PIE and RELRO.

- docs/spec/api.md
This PR addresses issues raised in the following PRs that have been impossible to get hold of their original authors:
* https://github.com/distribution/distribution/pull/3540
* https://github.com/distribution/distribution/pull/3964
> Small update of API docs

- .golangci.yml
- context/http_test.go
- health/checks/checks.go
- registry/client/auth/session_test.go
- registry/client/blob_writer.go
- registry/client/repository.go
- registry/handlers/api_test.go
- registry/handlers/app_test.go
- registry/registry_test.go
- registry/storage/driver/middleware/cloudfront/s3filter.go
- registry/storage/driver/testsuites/testsuites.go
> Enable bodyclose linter

- registry/storage/linkedblobstore.go
> fix typo in comment and log

- registry/storage/catalog.go
We are given a slice to fill, write catalog entries directly to the slice until it is full.
This picks up the last optimisations from #3902 which got reverted in #4004.
> Don't make a new buffer for catalog listing

- registry/storage/cache/redis/redis.go
Lines 138-140 are the same as 134-136
> remove duplicated code

- registry/storage/paths.go
fix typos in registry/storage/paths.go
> fix typos in registry/storage/paths.go

- docs/storage-drivers/index.md
Do we want something like this?
> Add note on custom storage drivers

- docs/spec/auth/scope.md
This is a bare minimum PR for documenting resource class deprecation. Feedback welcome!
> document resource class deprecation

- registry/handlers/app.go
- registry/handlers/tags.go
Closes https://github.com/distribution/distribution/issues/4065
> Do not close HTTP request body in HTTP handler

- registry/handlers/app.go
- registry/handlers/tags.go
Same as https://github.com/distribution/distribution/pull/4067 but for `2.8`.
I've opened this as a draft per @thaJeztah request
See https://github.com/distribution/distribution/issues/4065 for more context
PTAL @corhere @dmcgowan
> [release/2.8] Do not close HTTP request body in HTTP handler

- registry/storage/paths.go
add top level repositories path comment.
> add repositoriesRootPathSpec in pathFor documentation

- .mailmap
- releases/v2.8.3.toml
- version/version.go
> Add v2.8.3 release notes

- docs/go.mod
- docs/go.sum
- follow-up to https://github.com/distribution/distribution/pull/4101
> docs: remove unused go.mod

- internal/client/transport/http_reader.go
Fixes: https://github.com/distribution/distribution/security/code-scanning/34
> fix: invalid conversion when using Content-Range in client

- go.mod
- go.sum
- vendor/github.com/sirupsen/logrus/README.md
- vendor/github.com/sirupsen/logrus/buffer_pool.go
- vendor/github.com/sirupsen/logrus/entry.go
- vendor/github.com/sirupsen/logrus/logger.go
- vendor/github.com/sirupsen/logrus/writer.go
- vendor/modules.txt
full diff: https://github.com/sirupsen/logrus/compare/v1.8.1...v1.9.3
> vendor: github.com/sirupsen/logrus v1.9.3

- registry/storage/driver/gcs/gcs.go
We also clean up some redundant code.
> update: set User-Agent header in GCS storage driver

- README.md
- docs/dockerhub.md
> update: readme cleanup and fxes

- go.mod
- go.sum
- vendor/github.com/mitchellh/mapstructure/.travis.yml
- vendor/github.com/mitchellh/mapstructure/CHANGELOG.md
- vendor/github.com/mitchellh/mapstructure/decode_hooks.go
- vendor/github.com/mitchellh/mapstructure/mapstructure.go
- vendor/modules.txt
note that this repository will be sunset, and the "endorsed" fork will be maintened by "go-viper". Updating the dependency to the latest version in preparation.
full diff: https://github.com/mitchellh/mapstructure/compare/v1.1.2...v1.5.0
> vendor: github.com/mitchellh/mapstructure v1.5.0

- docs/hugo.yaml
- docs/i18n/en.yaml
> Add a trademarks and docs license link

- go.mod
- go.sum
- vendor/github.com/distribution/reference/README.md
- vendor/github.com/distribution/reference/normalize.go
- vendor/github.com/distribution/reference/reference.go
- vendor/modules.txt
We've made a new release https://github.com/distribution/reference/releases/tag/v0.6.0
PTAL @thaJeztah
> chore: bump distriution/reference dependency

- registry/handlers/app.go
Fixes https://github.com/distribution/distribution/issues/4304
> proxy: Do not configure HTTP secret for proxy registry

- docs/dockerhub.md
**PR Summary**:
PR #4101 moved the location of `filesystem.md`. This PR adjusts sources to changes.
> docs: update location of `filesystem.md`

- docs/content/about/configuration.md
- docs/content/storage-drivers/azure.md
Closes #4345 and addresses https://github.com/distribution/distribution/pull/3839#issuecomment-2211275574
CC: @kirat-singh @veikkoeeva
PTAL @thaJeztah @squizzi @Jamstah
> Update docs: JWKS credentials and AZ identity

- registry/auth/token/accesscontroller.go
- registry/storage/driver/middleware/redirect/middleware.go
- registry/storage/driver/middleware/rewrite/middleware.go
> chore: fix typos returned in some errors

- docs/content/about/deploying.md
- docs/content/recipes/apache.md
- docs/content/recipes/nginx.md
https://www.docker.com/blog/new-docker-compose-v2-and-v1-deprecation/
> Remove deprecated version field

- docs/content/storage-drivers/s3.md
Figuring out what `S3` storage does under the hood was tricky. I hope this small note will help other people set up the infrastructure.
> Add a note regarding redirects to pre-signed URLs

- .mailmap
- releases/v3.0.0-rc.1.toml
- version/version.go
* Created a changelog file
* Updated mailmap
* Updated version
PTAL: @thaJeztah @squizzi @corhere @joaodrp @wy65701436 @Jamstah @davidspek
> Prep for v3-rc.1 release

- .mailmap
- AUTHORS
- releases/v3.0.0-rc.2.toml
- version/version.go
Seems like we havent done AUTHORS update in a while: this commit rectififes that.
> Prepare for rc2 release

- registry/storage/manifeststore_test.go
- registry/storage/registry.go
Fixes https://github.com/distribution/distribution/issues/4569, https://github.com/distribution/distribution/issues/3322
> use cached blob statter in ManifestService if available

- .github/workflows/build.yml
- Makefile
- docs/content/about/configuration.md
- docs/content/storage-drivers/azure.md
- registry/storage/driver/azure/auth.go
- registry/storage/driver/azure/azure.go
- registry/storage/driver/azure/azure_test.go
- registry/storage/driver/azure/parser.go
- registry/storage/driver/azure/retry_notification_policy.go
- registry/storage/driver/filesystem/driver_test.go
- registry/storage/driver/gcs/gcs_test.go
- registry/storage/driver/inmemory/driver_test.go
- registry/storage/driver/s3-aws/s3_test.go
- registry/storage/driver/testsuites/testsuites.go
- tests/docker-compose-azure-blob-store.yaml
Most of this is a copy-pasta from [the fix in GitLab container registry](https://gitlab.com/gitlab-org/container-registry/-/commit/959132477ef719249270b87ce2a7a05abcd6e1ed?merge_request_iid=2059) introduced by @vespian
<details>
<summary>Click me!</summary>
```shell
=== RUN   TestAzureDriverSuite
=== RUN   TestAzureDriverSuite/TestConcurrentFileStreams
=== RUN   TestAzureDriverSuite/TestConcurrentStreamReads
=== RUN   TestAzureDriverSuite/TestContinueStreamAppendLarge
=== RUN   TestAzureDriverSuite/TestContinueStreamAppendSmall
=== RUN   TestAzureDriverSuite/TestDelete
=== RUN   TestAzureDriverSuite/TestDeleteFolder
=== RUN   TestAzureDriverSuite/TestDeleteNonexistent
=== RUN   TestAzureDriverSuite/TestDeleteOnlyDeletesSubpaths
=== RUN   TestAzureDriverSuite/TestInvalidPaths
=== RUN …
```
> Azure driver retry fix

- internal/client/transport/http_reader.go
Resolves #4494 replaces, closes #4567, including recommendations from @thaJeztah
> Fix potential resource leak by ensuring the response body is closed in HTTPReadSeeker

- .mailmap
- AUTHORS
- releases/v3.0.0-rc.4.toml
- version/version.go
* Created a changelog file
* Updated version
* Updated AUTHORS
* Updated .mailmap
> Prep for v3-rc.4 release

- registry/storage/blobwriter_nonresumable.go
- registry/storage/driver/azure/retry_notification_policy.go
- registry/storage/driver/middleware/cloudfront/middleware.go
make function comment match function name
> chore: make function comment match function name
