doc/SPEC.md
doc/SPEC.md.tmpl

Rewrite Introduction section of specification

---

api_test.go
client/client.go
client/client_test.go
client/objectstore.go
client/pull.go
client/push.go
images.go
manifest/manifest.go
manifest/manifest_test.go
manifest/sign.go
manifest/verify.go
storage/layer.go
storage/layerstore.go
storage/layerupload.go
storage/manifeststore.go
storage/manifeststore_test.go
storage/services.go

This moves the manifest oriented type definitions out of the storage package. This is the first attempt at resolving #6. Specifically, this covers item 4.
cc @jlhawn @dmcgowan @dmp42 @jfrazelle @icecrime

Move manifest to discrete package 

---

api_test.go
app.go
configuration/configuration.go
layerupload.go
storage/layer_test.go
storage/layerstore.go
storage/layerupload.go
storage/manifeststore_test.go
storage/services.go
tokens.go
tokens_test.go

To support clustered registry, upload UUIDs must be recognizable by
registries that did not issue the UUID. By creating an HMAC verifiable
upload state token, registries can validate upload requests that other
instances authorized. The tokenProvider interface could also use a redis
store or other system for token handling in the future.

Serializes upload state to an HMAC token for subsequent requests

---

api/v2/descriptors.go
api/v2/errors.go
api_test.go
app.go
app_test.go
doc/SPEC.md
doc/SPEC.md.tmpl
helpers.go
images.go
tags.go

These changes fill in a lot of missing detail in the API endpoint definitions. Please the generated `SPEC.md` file for the results. This file will be submitted to docker core for review, as a companion to docker/docker#9784.
Note that this PR contains part of the content from #7, which should be merged before this.
cc @icecrime @jfrazelle @dmp42 @dmcgowan @jlhawn 
Replaces #15, because old repository lost its fork status.

Fill in detail for V2 registry api specification

---

storagedriver/s3/README.md
storagedriver/s3/s3.go

....
Note that the README currently contains details about the secure parameter which is part of a
separate pull request. I feel confident adding it here since I am certain we will eventually add
the secure parameter. Also note that encrypt now defaults to true and rootdirectory defaults to
the empty string.

Add a README file and make encrypt and rootdirectory optional parameters

---

storagedriver/storagedriver.go
storagedriver/testsuites/testsuites.go

No longer requires that file paths match the repository naming scheme,
but instead allows path components as short as a single character, as to
accommodate for single-character tag names.
Fixes #47

Relaxes storagedriver path constraints

---

client/client.go

When adding parameters to a location header, the client must not destroy
parameters already present. This change ensures that parameters are added,
rather than replaced when assembling the url.

Correctly assemble URL during blob upload

---

storagedriver/filesystem/driver.go
storagedriver/inmemory/driver.go
storagedriver/s3/s3.go
storagedriver/storagedriver.go
storagedriver/testsuites/testsuites.go

This implements part of proposal #49

Add the URLFor optional method to the storagedriver api

---

configuration/configuration.go
registry/app.go
registry/layer.go
storage/cloudfrontlayerhandler.go
storage/delegatelayerhandler.go
storage/layerhandler.go
storage/layerstore.go
storage/paths.go
storage/services.go
storagedriver/filesystem/driver.go
storagedriver/inmemory/driver.go
storagedriver/s3/s3.go
storagedriver/storagedriver.go
storagedriver/testsuites/testsuites.go

Includes a delegate implementation which redirects to the URL generated by the storagedriver, and a cloudfront implementation.
Satisfies proposal #49

Adds support for content redirects for layer downloads

---

storagedriver/s3/README.md
storagedriver/s3/s3.go
storagedriver/s3/s3_test.go

Do not merge yet, as this is blocked on the v4 auth option.

Add features to the s3 driver

---

cmd/registry/main.go
storagedriver/s3/s3.go

Also limits startup permission check to scope of rootdirectory parameter

Enables s3 driver

---

storagedriver/s3/s3.go
storagedriver/testsuites/testsuites.go

Wait until https://github.com/crowdmob/goamz/pull/319 is merged before merging this.
Update: It was merged.

Add functionality to make a url signed for a HEAD request to S4 driver

---

digest/digest.go
digest/verifiers_test.go
storage/blobstore.go
storage/delegatelayerhandler.go
storage/layer_test.go
storage/layerstore.go
storage/layerupload.go
storage/manifeststore.go
storage/manifeststore_test.go
storage/paths.go
storage/paths_test.go
storage/revisionstore.go
storage/services.go
storage/tagstore.go

Several requirements for storing registry data have been compiled and the backend layout has been refactored to comply. Specifically, we now store most data as blobs that are linked from repositories. All data access is traversed through repositories. Manifest updates are no longer destructive and support references by digest or tag. Signatures for manifests are now stored externally to the manifest payload to allow merging of signatures posted at different time.
The design is detailed in the documentation for pathMapper.
This change refactors the storage backend to use the new path layout. To facilitate this, manifest storage has been separated into a revision store and tag store, supported by a more general blob store. The blob store is a hybrid object, effectively providing both small …

Refactor backend storage layout to meet new requirements (addresses #25, #46)

---

registry/app.go
registry/app_test.go
registry/context.go
registry/images.go
registry/layer.go
registry/layerupload.go
registry/tags.go
storage/blobstore.go
storage/layer_test.go
storage/layerstore.go
storage/layerupload.go
storage/manifeststore.go
storage/manifeststore_test.go
storage/registry.go
storage/revisionstore.go
storage/services.go
storage/tagstore.go

In support of making the storage API ready for supporting notifications and mirroring, we've begun the process of paring down the storage model. The process started by creating a central Registry interface. From there, the common name argument on the LayerService and ManifestService was factored into a Repository interface. The rest of the changes directly follow from this.
An interface wishlist was added, suggesting a direction to take the registry package that should support the distribution project's future goals. As these objects move out of the storage package and we implement a Registry backed by the http client, these design choices will start getting validation.
Connects to #42.
Signed-off-by: Stephen J Day <stephen.day@docker.com

Refactor storage API to be registry oriented

---

registry/app.go

Setting a header for all responses can help clients better determine
if the server speaks the legacy v1 API or the v2 API. It is important
that the header be set *BEFORE* routing the request.
Docker-DCO-1.1-Signed-off-by: Josh Hawn <josh.hawn@docker.com> (github: jlhawn)

Add Docker Distribution API Version header

---

storage/decorator/decorator.go
storage/decorator/decorator_test.go

This change provides a toolkit for intercepting registry calls, such as
`ManifestService.Get` and `LayerUpload.Finish`, with the goal of easily
supporting interesting callbacks and listeners. The package proxies
returned objects through the decorate function before creation, allowing one to
carefully choose injection points.
Use cases range from notification systems all the way to cache integration.
While such a tool isn't strictly necessary, it reduces the amount of code
required to accomplish such tasks, deferring the tricky aspects to the
decorator package.
Connects to #42.

Implement registry decorator toolkit

---

Dockerfile

This speeds up the build (and makes it more consistent) since it doesn't have to clone a bunch of repos. :+1:
With this change, my final image is ~493.8 MB (versus ~567.7 MB when I build from master).
Also:
```console
$ time docker build --no-cache .
...
real	0m38.081s
user	0m0.027s
sys	0m0.029s
```
Versus:
```console
$ time docker build --no-cache https://github.com/docker/distribution.git
...
real	1m31.629s
user	0m0.145s
sys	0m0.082s
```
(most of which is spent in `Step 2 : RUN go get github.com/docker/distribution/...`)

Update the Dockerfile to use the Godeps versions of libraries and to explicitly use golang:1.4

---

storagedriver/s3/s3.go

More specifically, the driver panics if initialized with
FromParameters with no accesskey or secretkey.

Fixes an IAM role authentication bug

---

storagedriver/inmemory/mfs.go

discovered in the new `TestStatCall` (#77). currently breaks CI for #77.
cc: @stevvooe @BrianBland @AndreyKostov

update modtime on WriteAt for inmemory driver

---

api/v2/names.go
api/v2/names_test.go
api/v2/routes_test.go

Will allow images with a single name component, on the client side they may appear as <private repo>/myapp

Allow single name component repository names

---

storagedriver/inmemory/driver.go

Method  ```d.root.find(normalized)``` reads an internal map of dir struct, so we have to protect it.

[InMemory] Add missing mutex.RLock/RUnlock in List

---

api/v2/urls.go
api/v2/urls_test.go

Handles an issue where mux.Route does not set the desired scheme
when building a url and always uses `http`.
Now uses X-Forwarded-Proto when creating a URLBuilder from a request.
fixes #123

Improve URL Builders

---

client/client.go
client/client_test.go

* Result of ```regexp.FindStringSubmatch``` must be checked to be not nil.
Otherwise it leads to `index out of range`.
* Range header regexp is compiled only once to speedup (5x) the parsing.
* Replace `strconv.ParseInt(s, 10, 0)` with a shorthand `strconv.Atoi`
* Add test for the parsing
```
BenchmarkCompiledEachTime	  200000	     12966 ns/op
BenchmarkOnceCompiled	 1000000	      2543 ns/op
```

[Client] Fix error in parsing of 'Range' header.

---

cmd/registry/main.go
configuration/configuration.go

This changeset provides simple tls support for a registry instance. Simply
providing a cert and key file are enough to get a tls registry running. If the
certs are trusted by the client, tls can be used throughout the push and pull
process.
If more complex TLS options are required, it is recommend that a proxy be used.
Contributions will be accepted to add more features, if necessary.
Closes #95.

Add native TLS support to registry

---

storage/paths.go
storage/paths_test.go
storagedriver/storagedriver.go
storagedriver/testsuites/testsuites.go

To address the possibility of confusing registry name components with
repository paths, path components that abut user provided repository names are
escaped with a prefixed underscore. This works because repository name
components are no allowed to start with underscores.
Closes #124, alternative to #128.

Prefix non-name path components

---

api/v2/descriptors.go
digest/digest.go
digest/digest_test.go
doc/SPEC.md
registry/api_test.go
registry/layerupload.go
storage/filereader.go
storage/filereader_test.go
storage/filewriter.go
storage/layer.go
storage/layer_test.go
storage/layerupload.go
storage/revisionstore.go

This changeset addresses intermittent internal server errors encountered during pushes.  The root cause has been isolated to layers that result in identical, empty filesystems but may have some path declarations (imaginge "./"), resulting in different tarsums. The main error message reported during these upload problems was a 500 error, which was not correct.  Further investigation showed the errors to be rooted in digest verification when finishing uploads.
Inspection of the surrounding code also identified a few issues. PutLayerChunk was slightly refactered into PutLayerUploadComplete. Helper methods were avoided to make handler less confusing. This simplification leveraged an earlier change in the spec that moved non-complete chunk uploads to the PATCH method. Simple logging was also …

Address server errors received during layer upload

---

storagedriver/testsuites/testsuites.go

I thought having this might be a good check of the requirements expected from **PutContent**.
i.e. some implementation like
PutContent(path, data) error {
return d.WriteStream(path, 0, data)
}
would be an erroneous implementation as PutContent should delete old contents and should support multiple writes (at offset=0 of the file –whereas WriteStream does not require it).
Adding this small test helped me avoid a potential pitfall in writing the Azure storage driver. cc: @stevvooe @BrianBland 

Add TestPutContentMultipleTimes to storage driver suite

---

storagedriver/base/base.go
storagedriver/filesystem/driver.go
storagedriver/inmemory/driver.go
storagedriver/s3/s3.go

This changeset moves common checks from driver implementations into base
package. The Base type can be embedded in a driver implementation, ensuring
that incoming arguments are checked for validity.
This supersedes #79.

Move shared checks to base storage driver

---

Godeps/Godeps.json
Godeps/_workspace/src/golang.org/x/net/context/context.go
Godeps/_workspace/src/golang.org/x/net/context/context_test.go
Godeps/_workspace/src/golang.org/x/net/context/withtimeout_test.go
auth/auth.go
auth/silly/access.go
auth/silly/access_test.go
auth/token/accesscontroller.go
auth/token/token.go
auth/token/token_test.go
registry/app.go
registry/context.go

The auth package has been updated to use "golang.org/x/net/context" for
passing information between the application and the auth backend.
AccessControllers should now set a "auth.user" context value to a AuthUser
struct containing a single "Name" field for now with possible, optional, values
in the future.
The "silly" auth backend always sets the name to "silly", while the "token" auth
backend will set the name to match the "subject" claim of the JWT.
closes #137

Use context for auth access controllers

---

storage/layer.go

This allows wrappers of LayerUpload to implement io.ReadFrom, which
prevents io.Copy on LayerUpload implementations from using repeated 32kB
Writes.
This has a huge performance implication, especially for s3/azure storage
drivers.
@stevvooe

Makes LayerUpload an io.ReaderFrom

---

storagedriver/s3/s3.go

The reason we prefer v2 is that it performs better since it does not
hash the payloads.

storagedriver/s3: Change the default signature to v2 auth

---

storagedriver/ipc/client.go

There's no need to send `struct{}{}` to notify a waiting goroutine with an infinite loop about the stop.
It's enough to close stopChan. Moreover it could lead to a deadlock if `driver.Stop` is called before `driver.handleSubprocessExit`.

[IPC/Client] Get rid of an unnecessary stopChan sending

---

configuration/configuration.go

Avoid tons of empty string fields when marshaling the configuration back into yaml.

configuration: Adds yaml omitempty tags to config fields

---

cmd/dist/list.go
cmd/dist/main.go
cmd/dist/pull.go
cmd/dist/push.go

This implements the basic structure of the `dist` binary following the UX proposal in #43 so it **will** be subject to change, but provides a working base nevertheless.
```
$ ./dist --help
NAME:
dist - Package and ship Docker content
USAGE:
dist [global options] command [command options] [arguments...]
VERSION:
0.0.0
AUTHOR:
Author - <unknown@email>
COMMANDS:
list		List available images
pull		Pull and verify an image from a registry
push		Push an image to a registry
help, h	Shows a list of commands or help for one command
GLOBAL OPTIONS:
--help, -h		show help
--version, -v	print the version
```
```
$ ./dist list --help
NAME:
list - List available images
USAGE:
command list [arguments...]
```
```
$ ./dist pull --help
NAME:
pull - Pull and verify an image from a registry
USAGE:
command pull …
```

Basic skeleton for `dist` binary

---

digest/digest.go
digest/digest_test.go
digest/verifiers.go

Remote md5 and sha1 hashes which are not supported by distribution.
Add more secure hashes sha384 and sha512.

Replace unsupported hashes with supported

---

registry/auth/token/accesscontroller.go
registry/auth/token/token_test.go

This is necessary so that rootcertbundle setting can be overridden by an
environment variable (e.g. REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE)

Rename auth.token.{rootCertBundle -> rootcertbundle}

---

configuration/configuration.go
registry/api/v2/descriptors.go
registry/api/v2/routes.go
registry/api/v2/routes_test.go
registry/api/v2/urls.go
registry/api/v2/urls_test.go
registry/handlers/api_test.go
registry/handlers/app.go

This allows the docker registry to run somewhere other than the root of the server
Connects to #29.

registry/handlers: support prefixed registry app

---

doc/spec/api.md
doc/spec/api.md.tmpl
registry/api/v2/descriptors.go
registry/handlers/api_test.go
registry/handlers/layerupload.go

This changeset adds support for a header to identify docker upload uuids. This
id can be used as a key to manage local state for resumable uploads. The goal
is remove the necessity for a client to parse the url to get an upload uuid.
The restrictions for clients to use the location header are still strongly in
place.
Closes #180.

doc/spec, registry/handlers: specify and implement Docker-Upload-UUID

---

registry/storage/filewriter.go
registry/storage/filewriter_test.go
registry/storage/layerstore.go
registry/storage/layerupload.go

Resolves https://github.com/docker/distribution/issues/148
Tests included to confirm buffer is working. Cover all new code except the inside of some err conditionals.
I believe the only place bfw.Close needed to be added was in LayerUpload.Finish

registry/storage: buffered wrapper for fileWriter

---

registry.go
registry/storage/registry.go
registry/storage/revisionstore.go
registry/storage/signaturestore.go

Add a SignatureService and expose it via Signatures() on Repository so
external integrations wrapping the registry can access signatures.
Signed-off-by: Andy Goldstein <agoldste@redhat.com>

Expose Signatures() on Repository

---

digest/digest.go

old func Validate in digest seems not to validate when digest data isn't HEX format.
As it accepts the data string which is out of range of a-f0-9.
@stevvooe @dmp42 ,
Please help take a view. Thanks a lot!

digest: func Validate in digest doesn't filter no-hex data

---

doc/spec/api.md
doc/spec/api.md.tmpl
notifications/listener.go
notifications/listener_test.go
registry.go
registry/api/v2/descriptors.go
registry/api/v2/errors.go
registry/api/v2/routes_test.go
registry/api/v2/urls.go
registry/handlers/api_test.go
registry/handlers/app.go
registry/handlers/app_test.go
registry/handlers/context.go
registry/handlers/images.go
registry/handlers/layer.go
registry/handlers/layerupload.go
registry/storage/manifeststore.go
registry/storage/manifeststore_test.go
registry/storage/paths.go
registry/storage/paths_test.go
registry/storage/tagstore.go

Manifests are now fetched by a field called "reference", which may be a tag or a digest. When using digests to reference a manifest, the data is immutable. The routes and specification have been updated to allow this. There are a few caveats to this approach:
1. It may be problematic to rely on data format to differentiate between a tag and a digest. Currently, they are disjoint but there may modifications on either side that break this guarantee.
2. The caching characteristics of returned content are very different for digest versus tag-based references. Digest urls can be cached forever while tag urls cannot.
Both of these are minimal caveats that we can live with in the future.
Most of the changes follow from modifications to ManifestService. Once updates were made across the repo to …

doc/spec, registry: immutable manifest reference support

---

digest/digest.go
digest/digester.go
registry/handlers/api_test.go
registry/storage/layer_test.go
registry/storage/layerupload.go
registry/storage/paths.go

Supersedes https://github.com/docker/distribution/pull/237
@jlhawn @stevvooe

digest, registry/storage, registry/handlers: switch to SHA256 as canonical digest

---

digest/digest.go
digest/digest_test.go

@stevvooe 
The invalid character in the middle of HEX digest should be well-marked.
Hence, add 'full string verification' rule in DigestRegexp.
By the way, the relevant point in docker/docker should be modified to accordant, right?

supplement of digest refactoring

---

registry/storage/layerreader.go

Otherwise `HEAD` requests using s3 result in a redirect to a 403.

Insert request method option storage driver URLFor

---

digest/digest.go
digest/verifiers.go
digest/verifiers_test.go

This addresses a subtle deadlock where an error during a copy prevented pipe
closure to propagate correctly. By closing down the read end of the pipe rather
than the write end, the waiting writer is properly signaled. A nice side-effect
of this change is that errors encountered by io.Copy are no propagated to the
verifier's Write method.
A test to ensure validation errors for unsupported digest types has been added,
as well.
Closes #269.

digest: correctly close pipe after error in tarsum verification

---

digest/verifiers_test.go

The linter was complaining about these and they are quite unnecessary.

digest: remove unnecessary error pointer formats in test

---

cmd/registry/main.go
health/api/api.go
health/api/api_test.go
health/checks/checks.go
health/doc.go
health/health.go
health/health_test.go

Package health provides a generic health checking framework. The health package works expvar style. By importing the package the debug server is getting a `/debug/health` endpoint that returns the current status of the application. If there are no errors, `/debug/health` will return a HTTP 200 status, together with an empty JSON reply `{}`. If there are any checks with errors, the JSON reply will include all the failed checks, and the response will be have a HTTP 500 status.
A Check can either be run synchronously, or asynchronously. We recommend that most checks are registered as an asynchronous check, so a call to the `/debug/health` endpoint always returns
immediately. This pattern is particularly useful for checks that verify upstream connectivity or database status, since they might …

registry/health: adding healthcheck package

---

cmd/registry/main.go

Importing Azure storage driver to make it register itself as
a storage driver.
:exclamation: cc: @dmp42 @stevvooe can you guys add it to the 2.0 milestone or merge as soon as possible?

cmd/registry: Import Azure driver for factory registration

---

doc/storagedriver/azure.md
registry/storage/driver/azure/azure.go
registry/storage/driver/azure/azure_test.go

This enables Azure storage driver to be used with non-default
cloud storage endpoints like Azure China or Azure Government which
do not use the `.blob.core.windows.net` FQDN suffix.
Change introduces an optional `domain:` key in the `config.yml`.

azure: Allow non-default Azure realms

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/Sirupsen/logrus/README.md
Godeps/_workspace/src/github.com/Sirupsen/logrus/examples/basic/basic.go
Godeps/_workspace/src/github.com/Sirupsen/logrus/examples/hook/hook.go
Godeps/_workspace/src/github.com/Sirupsen/logrus/exported.go
Godeps/_workspace/src/github.com/Sirupsen/logrus/formatters/logstash/logstash.go
Godeps/_workspace/src/github.com/Sirupsen/logrus/formatters/logstash/logstash_test.go
Godeps/_workspace/src/github.com/Sirupsen/logrus/hooks/airbrake/airbrake.go
Godeps/_workspace/src/github.com/Sirupsen/logrus/hooks/airbrake/airbrake_test.go
Godeps/_workspace/src/github.com/Sirupsen/logrus/hooks/bugsnag/bugsnag.go
Godeps/_workspace/src/github.com/Sirupsen/logrus/hooks/bugsnag/bugsnag_test.go
Godeps/_workspace/src/github.com/Sirupsen/logrus/hooks/sentry/README.md
Godeps/_workspace/src/github.com/Sirupsen/logrus/json_formatter.go
Godeps/_workspace/src/github.com/Sirupsen/logrus/json_formatter_test.go
Godeps/_workspace/src/github.com/Sirupsen/logrus/logger.go
Godeps/_workspace/src/github.com/Sirupsen/logrus/logrus_test.go
Godeps/_workspace/src/github.com/Sirupsen/logrus/terminal_notwindows.go
Godeps/_workspace/src/github.com/Sirupsen/logrus/terminal_openbsd.go
Godeps/_workspace/src/github.com/Sirupsen/logrus/text_formatter.go
Godeps/_workspace/src/github.com/Sirupsen/logrus/text_formatter_test.go
Godeps/_workspace/src/github.com/Sirupsen/logrus/writer.go
cmd/registry/config.yml
cmd/registry/main.go
configuration/configuration.go
configuration/configuration_test.go
doc/configuration.md

This changeset simply adds hooks into the configuration system to support multiple different kinds of output formats. These formatters are provided by logrus and include options such as "text" and "json". The configuraiton documentation has been updated accordingly.
The logrus dependency has been updated as an order of maintenance.
The logging system now has a separate configuration section. The default configuration would be as follows:
```yaml
log:
level: info
formatter: text
```
This configuration would yield the standard text output, as shown below when output to a TTY:
```
$ ./bin/registry cmd/registry/config.yml
INFO[0000] endpoint local-8082 disabled, skipping        app.id=c2156935-05a3-4c11-86f1-b33e5a51ce17 version=v2.0.0-alpha.3-43-g3b9cbb7
INFO[0000] endpoint local-8083 …
```

main, configuration, doc: allow logging formatter to be configured

---

AUTHORS
context/http.go
context/http_test.go
notifications/bridge.go

Add a function to examine X-Forward-For and X-Real-Ip headers for
originating IP addresses.  Use RemoteAddr for notification request
record and HTTP request context.
Closes #298.

Attempt to identify remote IP addresses for requests which come through proxies.

---

cmd/registry/main.go
configuration/configuration.go
configuration/configuration_test.go
doc/configuration.md

Some organisations require authentication via certificates for security purposes. This PR allows for that, by specifying the CA cert in the TLS configuration block, one is able to require certificates to be presented during a request.
Refs: #278 
I guess this work could be continued for #280, #279

registry, configuration, doc: client certificates for authentication purposes.

---

.gitignore
cmd/registry/main.go
configuration/configuration.go
configuration/configuration_test.go
context/context.go
context/http.go
context/http_test.go
context/logger.go
context/util.go

You shouldn't have to import both:
github.com/docker/distribution/context
golang.org/x/net/context
just to use the distribution tools and implement the distribution interfaces.
By pulling the Context interface from golang.org/x/net/context into the
context package within the distribution project, you no longer have to import
both packages.
Note: You do not have to change anything anywhere else yet! All current uses
of both packages together will still work correctly because the Context
interface from either package is identical.
I've also made some other minor changes:
- Added a RemoteIP function. It's like RemoteAddr but discards the port suffix
- Added `.String()` to the response duration context value so that JSON log
formatting shows human-parseable duration and not just number of …

context: improve context package

---

registry/storage/driver/inmemory/mfs.go
registry/storage/driver/testsuites/testsuites.go

This chnage prevents a crash when moving from a non-existent directory that has
a file as a parent. To prevent this, we simply check that the node is a
directory and throws an error if it is not.

registry/storage/driver/inmemory: avoid crash on invalid Move arguments

---

doc/spec/api.md
registry/api/v2/descriptors.go
registry/api/v2/routes_test.go

This change adds strong validation for the uuid variable for v2 routes. This is
a minor specification change but is okay since the uuid field is controlled by
the server. The character set is restricted to avoid path traversal, allowing
for alphanumeric values and urlsafe base64 encoding.
This change has no effect on client implementations.

registry/api/v2: stronger validation for uuid field in urls

---

context/logger.go

This fixes the build after a bad merge.

context: correctly reference context object

---

Dockerfile

Fixes #319.
Environment variables don't work in the command when an entrypoint is used because it isn't executed by a shell so I've removed `CONFIG_PATH`. Any suggestions on how to bring it back are welcome...

Use entrypoint in Dockerfile

---

registry/storage/driver/middleware/cloudfront/middleware.go
registry/storage/driver/s3/s3.go

This may not be the *best* solution, but it is the cleanest that we could come up with short of fixes to goamz or manually altering the URL returned by the underlying storage driver.

Handle cloudFront bucket prefix issue

---

registry/storage/driver/storagedriver.go
registry/storage/driver/testsuites/testsuites.go

Rather than enforce lowercase paths for all drivers, support for
case-sensitivity has been deferred to the driver. There are a few caveats to
this approach:
1. There are possible security implications for tags that only differ in their
case. For instance, a tag "A" may be equivalent to tag "a" on certain file
system backends.
2. All system paths should not use case-sensitive identifiers where possible.
This might be problematic in a blob store that uses case-sensitive ids. For
now, since digest hex ids are all case-insensitive, this will not be an issue.
The recommend workaround is to not run the registry on a case-insensitive
filesystem driver in security sensitive applications.

registry/storage/driver: defer case-sensitive support to storage backend

---

configuration/configuration.go
configuration/configuration_test.go

Includes deprecated Loglevel, Log.Formatter, and Log.Fields

Adds omitempty to several configuration fields

---

contrib/compose/README.md
contrib/compose/docker-compose.yml
contrib/compose/nginx/Dockerfile
contrib/compose/nginx/docker-registry-v2.conf
contrib/compose/nginx/docker-registry.conf
contrib/compose/nginx/nginx.conf
contrib/compose/nginx/registry.conf

Add nginx configuration to proxy to both a v1 and v2 registry. Nginx is configured to force 1.5 clients to use the v1 registry.
Currently does not use official v2 image

Add docker compose configuration for v1 and v2

---

registry/storage/signaturestore.go

The original implementation wrote to different locations in a shared slice.
While this is theoretically okay, we end up thrashing the cpu cache since
multiple slice members may be on the same cache line. So, even though each
thread has its own memory location, there may be contention over the cache
line. This changes the code to aggregate to a slice in a single goroutine.
In reality, this change likely won't have any performance impact. The theory
proposed above hasn't really even been tested. Either way, we can consider it
and possibly go forward.

registry/storage: prevent false sharing in signature fetch

---

docs/configuration.md
docs/glossary.md
registry.go
registry/handlers/app.go
registry/middleware/registry/middleware.go
registry/storage/manifeststore_test.go
registry/storage/registry.go

Registry is intended to be used as a service and API specification rather than an abstract collection of repositories. Namespace better describes a collection of repositories retrievable by name. Unlike Registry, a Namespace has a scope which can be used to determine whether a name (such as a repository name) belongs in that namespace.

Rename top level registry interface to namespace

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/Sirupsen/logrus/CHANGELOG.md
Godeps/_workspace/src/github.com/Sirupsen/logrus/README.md
Godeps/_workspace/src/github.com/Sirupsen/logrus/formatter.go
Godeps/_workspace/src/github.com/Sirupsen/logrus/formatters/logstash/logstash.go
Godeps/_workspace/src/github.com/Sirupsen/logrus/json_formatter.go
Godeps/_workspace/src/github.com/Sirupsen/logrus/text_formatter.go
Godeps/_workspace/src/github.com/Sirupsen/logrus/text_formatter_test.go
cmd/registry/main.go

This updates logrus and changes the default `TimestampLayout` to `time.RFC3339`.
Closes #323

main: nanosecond logging timestamps

---

AUTHORS
registry/storage/layerwriter.go

Close() writes hash state to the filesystem.  If Finish has already been called, return the underlying error to prevent this.

Prevent Close() from being called after Finish()

---

cmd/registry/main.go
context/context.go
context/trace.go
context/trace_test.go
registry/handlers/app.go
registry/storage/driver/base/base.go

This adds `WithTrace` function to the context package that allows users to trace a time span between a trace allocation and returned function call. The resulting context includes ids that will allow for future dapper-like analysis. Please see the godoc addition for details.
This supports tracing calls to backend storage drivers.
This also moves the instance id out of the app so that it is associated with an instantiation of the runtime. The instance id is stored on the background context. This allows allow contexts using the main background context to include an instance id for log messages. It also simplifies the application slightly

context, storagedriver: trace function calls to Base storage driver

---

contrib/compose/nginx/docker-registry-v2.conf
contrib/compose/nginx/docker-registry.conf

Set forward headers so the IP and scheme get sent to the registry. This allows the registry to set a proper redirect with the correct scheme when HTTPS is being used.

Update nginx proxy setting to set forward headers

---

cmd/registry/main.go

This was a regression from some changes made to the logging setup.
Example output:
```
INFO[0000] endpoint local-8082 disabled, skipping        environment=development instance.id=8cd53d89-d823-4ed4-8afa-1e034ecb1900 service=registry version=v2.0.0-rc.3-3-g600de20.m
INFO[0000] endpoint local-8083 disabled, skipping        environment=development instance.id=8cd53d89-d823-4ed4-8afa-1e034ecb1900 service=registry version=v2.0.0-rc.3-3-g600de20.m
INFO[0000] using inmemory layerinfo cache                environment=development instance.id=8cd53d89-d823-4ed4-8afa-1e034ecb1900 service=registry version=v2.0.0-rc.3-3-g600de20.m
INFO[0000] listening on :5000                            environment=development instance.id=8cd53d89-d823-4ed4-8afa-1e034ecb1900 service=registry …
```

cmd/registry: correctly log application version

---

context/http.go
registry/handlers/app.go
registry/handlers/context.go

Ensure that the status is logged in the context by instantiating before the request is routed to handlers. While this requires some level of hacking to achieve, the result is that the context value of "http.request.status" is as accurate as possible for each request.
Closes #356

context, registry/handlers: instantiate http context before dispatch

---

docs/overview.md

- Explain why you would want to use a registry
- Explain difference between Docker Hub and Registry
- List some features of Registry
- Add table of contents for documentation - particularly "deploying a registry" call to action
- Use standard "Getting help" section from orchestration projects
Still needs some better sentence structure and so on, but would appreciate some feedback on high-level structure and message.

docs: add landing page for Registry to docs

---

AUTHORS
registry/handlers/app.go
registry/storage/paths.go
registry/storage/purgeuploads.go
registry/storage/purgeuploads_test.go
registry/storage/walk.go
registry/storage/walk_test.go

Automatically purge old upload files
When the registry starts a background timer will periodically
scan the upload directories on the file system and delete
any files older than 1 week.
Jitter is randomly selected to be 0 - 60 minutes.

registry/storage: automatically purge old upload files

---

docs/configuration.md

The docs as available at
https://github.com/docker/distribution/blob/master/docs/configuration.md
result in 404 errors:
https://github.com/docker/distribution/blob/master/cmd/registry/%0Aconfig.yml
http://docs.aws.amazon.com/AWSSecurityCredentials/1.0/%0AAboutAWSCredentials.html#KeyPairs
instead of pointing to the correct ones, being:
https://github.com/docker/distribution/blob/master/cmd/registry/config.yml
http://docs.aws.amazon.com/AWSSecurityCredentials/1.0/AboutAWSCredentials.html#KeyPairs
So avoid the newlines in the corresponding source files.
Signed-off-by: Michael Prokop <mika@grml.org>

docs: drop newlines in URLs to avoid 404

---

context/http.go
context/http_test.go

This is ensures that users of the ResponseWriter from the context correctly
track usage. Otherwise, context reporting is incorrect.

context: return instrumented response writer from context

---

registry/handlers/app.go

Log status code and error contents in the dispatcher before error JSON is served.
Closes #403

Add logging for generic handler errors.

---

circle.yml

This should massively speed up the unit tests. We don't really use go1.3 anymore.

Disable go1.3 tests for circle and upgrade to go1.4.2

---

registry/storage/driver/s3/s3.go

Pooling these buffers should help to reduce garbage collection pressure experience when using the s3 driver. The theory is that these are causing timeouts while sending requests to s3's backend.

Pool buffers used in S3.WriteStream

---

registry/handlers/layerupload.go

This adds a missing return statement. It is not strictly needed since if the
io.Copy fails, the Finish operation will fail. Currently, the client reports
both errors where this new code will correctly only report the io.Copy error.

Return after error in handler

---

registry/storage/driver/azure/azure.go
registry/storage/driver/base/base.go
registry/storage/driver/filesystem/driver.go
registry/storage/driver/inmemory/driver.go
registry/storage/driver/s3/s3.go
registry/storage/driver/storagedriver.go

This simply adds a `Name` method to the storage driver interface. This can be used so drivers can report their name in errors and logs.

Expose storage driver names for tracing

---

docs/mkdocs.yml
docs/storagedrivers.md

Side note: after reading docs it seems like v2 is still far in the future and incomplete. It make sense to proof-read docs by someone who wasn't working on the spec directly to fix that.

Fixed links for storage drivers

---

registry/api/v2/urls.go
registry/api/v2/urls_test.go

According to the Apache mod_proxy docs, X-Forwarded-Host can be a
comma-separated list of hosts, to which each proxy appends the requested
host. We want to grab only the first from this comma-separated list
to get the original requested Host when building URLs.
http://httpd.apache.org/docs/2.2/mod/mod_proxy.html
fixes #431

Updated urlbuilder X-Forwarded-Host logic

---

registry/storage/layerstore.go
registry/storage/layerwriter.go

@stevvooe 
struct `registry` is the only embedded field of `repository`.
However, these 2 files use repository.registry expression, which seems superfluous.
So, I simplify them, to use `repository.{registry_field}` directly.
* `registry` fields as pm, blobStore, etc, match repository property. So that modification make code context meaning clearer.
* Better Uniform expression in  *layerstore.go*, *manifeststore.go*, and etc on purpose of my patch.
* The project will re-factor Distribution interface as your proposal #354. Simplifying can make re-factoring cooperation easily;
Do you agree? if yes, please help review it. Thanks a lot!

simplify the embedded method expression of repository

---

docs/configuration.md

The position was a bit too early. Fleshed out the example.
Also, using the _ underscore for emphasis was confusing because it is also used to indicate
a level change.
/cc ping @RichardScothern

Updating env var documentation

---

digest/set.go
digest/set_test.go

Create table for generating and looking up short digests.  Any operation involving short codes may be considered secure if the list of digests added to the table is secure.
closes #194

Add short digest implementation

---

docs/Dockerfile
docs/configuration.md
docs/deploying.md
docs/index.md
docs/notifications.md
docs/spec/api.md
docs/spec/api.md.tmpl
docs/spec/auth/token.md
docs/spec/json.md
docs/storage-drivers/azure.md
docs/storage-drivers/filesystem.md
docs/storage-drivers/inmemory.md
docs/storage-drivers/s3.md
docs/storagedrivers.md

Fix issue #471 
- Add sed to Dockerfile; this sed exists on publish script; breaks headings/nav in files without metadata
- Ensure sed runs over storage-driver/ subdir
- Add metadata to all the files (including specs) that don't have it; this ensures they display correctly on publish

Fixes Issue #471 with Publish

---

docs/Dockerfile
docs/configuration.md
docs/deploying.md
docs/index.md
docs/mkdocs.yml
docs/notifications.md
docs/spec/api.md
docs/spec/api.md.tmpl
docs/spec/auth/token.md
docs/spec/json.md
docs/storage-drivers/azure.md
docs/storage-drivers/filesystem.md
docs/storage-drivers/inmemory.md
docs/storage-drivers/s3.md
docs/storagedrivers.md

Signed-off-by: Ian Babrou <ibobrik@gmail.com>
(cherry picked from commit 824e7e8ae25299b5953e38088c085198774f945f)
Conflicts:
docs/mkdocs.yml
Add environment variable override instructions
(cherry picked from commit 937c3565856344e85ee93ba282916f76bccbb21b)
Fixing headings
(cherry picked from commit 7c93c8c265fe7cf1c59f857d7049c39902e854a0)
Fixes Issue #471 with Publish
- Add sed to Dockerfile; this sed exists on publish script; breaks headings/nav in files without metadata
- Ensure sed runs over storage-driver/ subdir
- Add metadata to all the files (including specs) that don't have it; this ensures they display correctly on publish
- Implement the fix for the showing up in Github
- …

Multiple fixes for issues in links, content, and display of GitHub

---

circle.yml

Disable code coverage in the build system because of coveralls errors.

---

contrib/apache/apache.conf

I'm submitting an update to https://github.com/docker/distribution/pull/423 authored by @hgomez for compatibility with httpd 2.2.
See [my comment](https://github.com/docker/distribution/issues/397#issuecomment-98828277) in the original issue.
Also I don't think that the Host header directive is necessary, especially in conjunction with `ProxyPreserveHost`.

Updating the Request Header directive for compatibility with httpd 2.2

---

docs/spec/api.md
docs/spec/api.md.tmpl
docs/spec/implementations.md
registry/api/v2/descriptors.go
registry/handlers/api_test.go
registry/handlers/layerupload.go

- Ensures new uploads and resumed upload statuses always return an offset of 0. This allows future clients which support resumable upload to not attempt resumable upload on this version which does not support it.
- Add PATCH support for streaming data on upload.
- Add messaging to specification that PATCH with content range is currently not supported.
- Update PUT blob to only support full data or no data, no more last chunk messaging as it was not supported.
closes #470

Modify blob upload API

---

CONTRIBUTING.md
ROADMAP.md
cmd/registry-api-descriptor-template/main.go

this fixes a broken link on the ROADMAP doc page, and confusing references elsewhere.

docs/spec: correct doc/spec to docs/spec everywhere

---

cmd/registry/main.go
configuration/configuration.go
configuration/configuration_test.go
docs/configuration.md
registry/listener/listener.go

Related to #477. It's just a prototype.
I'd like to discuss next questions:
+ is it good to determine if an unix socket should be used by a prefix (similar to nginx configuration of an upstream)?
+ is  ```registry/listener``` good place for a helper package?
+ should I try to remove the unix socket if it already exists (like it's done in Tornado)? For example, if we kill the registry the socket will stay.

cmd/registry, registry/listener: listen and serve on a unix socket

---

contrib/compose/nginx/registry.conf

This configuration setting should not be set in the compose configuration. This configuration (or the `add_header` configuration) will only be needed when using basic auth in nginx. This is needed because the registry will not get a chance to set the distribution header and it will be the responsibility of nginx to set the header on 403. The v2 registry will correctly set this header variable in this configuration and it is not necessary for nginx to interfere. The cases where this is needed should be referenced in the documentation, not here.

Remove set header in compose script

---

docs/index.md

Thanks to Mary and Stephen hard work, we have a solid basis for the documentation on top of which we can now iterate.
This first attempt at enhancing things is rather modest, and focused on a couple of key items:
* shortening things: making the message easier to digest by removing redundant information, avoidable expansions, etc
* clearer message: with more focus on what matters from a product POV
Let me know if you feel this is going in the right direction and if we want to go further.

Revamp index

---

notifications/listener_test.go
registry/client/repository.go
registry/handlers/app.go
registry/handlers/app_test.go
registry/storage/blob_test.go
registry/storage/cache/cache.go
registry/storage/cache/memory/memory.go
registry/storage/cache/memory/memory_test.go
registry/storage/cache/memory_test.go
registry/storage/cache/redis/redis.go
registry/storage/cache/redis/redis_test.go
registry/storage/cache/suite.go
registry/storage/manifeststore_test.go

Ensure that clients can use the blob descriptor cache provider without needing the redis package.
cc @dmcgowan

Decouple redis dependency from blob descriptor cache

---

uuid/uuid_test.go

Remove trailing spaces from range check on UUID parser

---

notifications/bridge.go
notifications/bridge_test.go
notifications/listener.go
notifications/listener_test.go

Previously, the most accurate reference for a manifest was the tag url. After
adding pull by digest, all event notifications should refer directly to the
digest url. This ensures that event uniquely identifies the target of the
notification. Testing has been added for manifest pull events to check that
this doesn't change.
In addition, the listener interface has been refactored to only use the
repository name, rather than the full repository object.

notifications: digest url should be sent in event target

---

docs/deploying.md

Small detail, but when generating certificates using sha256 is recommended. See for example http://googleonlinesecurity.blogspot.se/2014/09/gradually-sunsetting-sha-1.html.

sha256 when generating certificates

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/noahdesu/go-ceph/rados/conn.go
Godeps/_workspace/src/github.com/noahdesu/go-ceph/rados/doc.go
Godeps/_workspace/src/github.com/noahdesu/go-ceph/rados/ioctx.go
Godeps/_workspace/src/github.com/noahdesu/go-ceph/rados/rados.go
Godeps/_workspace/src/github.com/noahdesu/go-ceph/rados/rados_test.go
Makefile
circle.yml
cmd/registry/rados.go
contrib/ceph/ci-setup.sh
docs/building.md
docs/configuration.md
docs/mkdocs.yml
docs/storage-drivers/rados.md
docs/storagedrivers.md
registry/storage/driver/rados/rados.go
registry/storage/driver/rados/rados_test.go

This driver implements the storagedriver.StorageDriver interface and
uses Ceph Object Storage as storage backend.
Since RADOS is an object storage and no hierarchy notion, the
following convention is used to keep the filesystem notions stored in
this backend:
* All the objects data are stored with opaque UUID names prefixed
(e.g. "blob:d3d232ff-ab3a-4046-9ab7-930228d4c164).
* All the hierarchy information are stored in rados omaps, where the
omap object identifier is the virtual directory name, the keys in
a specific are the relative filenames and the values the blob
object identifier (or empty value for a sub directory).
e.g. For the following hierarchy:
/directory1
/directory1/object1
/directory1/object2
/directory1/directory2/object3
The omap "/directory1" will contains the following …

Storage Driver: Ceph Object Storage (RADOS)

---

docs/storagedrivers.md

Catch up after 88795e0a (Lots of various golint fixes, 2014-11-17, #1)
and 65b0d73c (Move storagedriver package to registry/storage/driver,
2015-02-10, #167).

docs/storagedrivers.md: Update filesystem.go -> driver.go reference

---

registry/storage/driver/rados/rados.go

Build with rados is broken since #556 (rados driver used code.google.com/p/go-uuid/uuid too).
@stevvooe @dmp42 Could you please check if there is any chance that the CI keeps the removed uuid dependency? Most recent CI builds should have failed. Thanks.

Fix rados build, remove uuid dependency

---

cmd/registry/config.yml
configuration/configuration.go
configuration/configuration_test.go
docs/configuration.md
registry/handlers/app.go
registry/handlers/hooks.go
registry/handlers/mail.go

@stevvooe 
This PR is for issue email after registry webapp panic #41, improving my previous design (closed).
It use self setting up hooks, to catch panic in web application.
And, send email in hooks handle directly, to no use new http server and handler.
Please help to take a view.
Thanks a lot!

Feature: Add Hook for Web Application Panic

---

circle.yml

See #578 for context.
Goveralls does fetch google uuid with it.
Builds that should fail for failure to find uuid are actually passing.
Though goveralls is installed only on "stable", the build should still fail for go1.3 - but apparently we disabled it :-)
This build here should FAIL and this is expected (save circleci caching)

Disable goverall for now

---

docs/spec/api.md
registry/api/v2/descriptors.go

In the request parameters lists `tag` was used instead of
`reference` present in the HTTP requests paths.

doc/spec: coherence between requests and parameters + typo

---

docs/building.md

This clarifies the importance of properly setting a Go build environment when
building targets. Typically, users seem to editorialize the checkout location,
either ignoring the first section or have limited experience with the Go
development environment. We clarify the checkout requirements and point to the
documentation on how to setup Go.

Build environment requires proper checkout of project

---

CONTRIBUTING.md

This is a follow-up of https://github.com/docker/distribution/pull/545 and makes some stylistic changes in the CONTRIBUTING document;
- Replaces checkboxes with regular bullets. Because the checkboxes are
read-only for non-contributors, they are presented as 'greyed out',
which makes them harder to see (depending on the browser used)
- Replaces bullets for numbered lists in the "creating an issue" and
"contributing a patch" sections. The numbers make it easier for
readers to track where they left off.
- Cleans up some minor Markdown changes for consistency

Minor contributing fixups

---

docs/spec/api.md
docs/spec/api.md.tmpl
registry/api/v2/descriptors.go

Some clarification around manifest deletes have been added, as well.
Closes #505, #549

Clarify digest in API specification

---

contrib/compose/nginx/docker-registry.conf

When using the private registry with a user defined index endpoint I was getting the following error .....
FATA[0017] HTTP code 401 while uploading metadata: {"error": "Requires authorization"}
The cause of this was the Authorization header being unset by Nginx. I followed the issue reported as a comment on the .conf but it seems like that issue was closed and listed as resolved but it seems like this is a breaking change for people running their own index.

Removing Nginx Authorization header unset because it breaks with a user defined index endpoint

---

Dockerfile

I added a sensible default volume to support the default registry data location. In doing so, we can save users the effort of digging up the location and manually creating the volume. If the default configuration is overridden, the volume will remain unused and empty.
Signed-off-by: Jeff Nickoloff <jeff@allingeek.com>

Adding a volume for the default 'registry-dev' location.

---

cmd/registry/main.go

Signed-off-by: yuzou <zouyu7@huawei.com>
after registry configuration is parsed, close its related file handle.

add configuration file close after it is parsed.

---

Dockerfile

Following native basic auth and while reviewing the doc, I would suggest to ship htpasswd.
Benefits are:
* controlled version: does support bcrypt
* self-contained: no separate installation required to operate
* straight-forward doc (to come): `docker run --entrypoint htpasswd registry -Bbn batman robin > batcave`

Ship htpasswd

---

circle.yml
registry/storage/driver/rados/doc.go
registry/storage/driver/rados/rados.go
registry/storage/driver/rados/rados_test.go

This ensures that rados is not required when building the registry. This was
slightly tricky in that when the flags were applied, the rados package was
completely missing. This led to a problem where rados was basically unlistable
and untestable as a package. This was fixed by simply adding a doc.go file that
is included whether rados is built or not.
This carries #611.

Ensure that rados is disabled without build tag

---

registry/api/v2/errors.go
registry/auth/auth.go
registry/auth/htpasswd/access.go
registry/auth/htpasswd/access_test.go
registry/auth/silly/access.go
registry/auth/silly/access_test.go
registry/auth/token/accesscontroller.go
registry/handlers/app.go

See: https://github.com/docker/distribution/blob/3ea67df37383dd6941908a9949ab55c7073ece5b/registry/handlers/app.go#L498
Per the comment on line 498, this moves the logic of setting the http
status code into the serveJSON func, leaving the auth.Challenge.ServeHTTP()
func to just set the auth challenge header.

Move challenge http status code logic

---

registry/api/errcode/errors.go
registry/api/errcode/errors_test.go
registry/client/blob_writer_test.go

See: https://github.com/docker/distribution/pull/548/files#r32794064

Add back in the "errors" wrapper in the Errors serialization

---

docs/authentication.md

Fixing heading not rendering
Fixing bad links:
deployed.md > deploying.md
spec/auth/token.md > /spec/auth/token.md
(cherry picked from commit 9510ef363705851811581fa5ddaa03b70836e909)

Updates to authentication

---

docs/spec/api.md
docs/spec/api.md.tmpl

There is some problems with table on the api page : https://docs.docker.com/registry/spec/api/#errors-2.
This PR fixes that on the ``api.md`` file only. I can take a *tour* of the other pages if needed.
Signed-off-by: Vincent Demeester <vincent@sbr.pm>

Fix table render in specs/api.md

---

docs/authentication.md

Reverts docker/distribution#661, which broke the links in github.

Revert "Updates to authentication"

---

registry/storage/blobserver.go

Prevent the ErrUnsupportedMethod error from being returned up the stack,
it is not an error here. It eventually causes the go http library to do a double 
WriteHeader() which is an error.

Prevent the ErrUnsupportedMethod error from being returned up the stack.

---

docs/authentication.md

This should make the link work in both github and the docs site.
We may need to fix the sed calls in the docs build process and see if we can address this in hugo.

Fix broken specification link in docs

---

registry/storage/driver/base/base.go

Pass correct context into tracer

Pass correct context into tracer

---

registry/client/repository.go

The one minute timeout was too short and caused errors due to reading on a closed connection when downloading blobs.

Increase timeout of http.Client for Docker Registry V2 client

---

registry/client/auth/api_version.go
registry/client/auth/authchallenge.go
registry/client/auth/authchallenge_test.go
registry/client/auth/session.go
registry/client/auth/session_test.go

Move client auth into a separate package.
Separate ping from the authorizer and export Challenges type.
This will allow for separating the ping logic from the transport. The ping can cleanly be done before creating the transport. This may lead to a condition where if multiple endpoints need to be called, the ping is not done. This case can be avoided by pinging each endpoint which may require an authentication challenge.

Refactor client auth

---

docs/spec/api.md
docs/spec/api.md.tmpl
registry/api/v2/names.go
registry/api/v2/names_test.go
registry/api/v2/routes_test.go

The main goal of this changeset is to allow repository name components to
consist of a single character. The number of components allowed and the slash
separation requirements have also been clarified.
To go along with this simplification, errant constants and unneeded error types
have been removed.
Closes #687
cc @jfrazelle @tiborvass @dmcgowan 

Allow single character repository names

---

docs/deploying.md

Intermediate certificates are issued by TLS providers who themselves are
an intermediate of a certificate in the trust store. Therefore, to prove
the chain of trust is valid, you need to include their certificate as
well as yours when you send your certificate to the client.
Contrary to what I said in issue #683, distribution can handle these
certificate bundles like nginx. As discussed in #docker-distribution,
I have updated the deployment documentation (which recommends the use of
a TLS certificate from a provider) to include instructions on how to
handle the intermediate certificate when a user is configuring
distribution.
Closes #683.

Include configuration explanation for intermediate TLS certificates

---

docs/configuration.md
docs/notifications.md

Yaml sections in the documentation does not display well on [docs.docker.com](https://docs.docker.com/registry/configuration/). Example:
This is due to the syntax highlighting which uses highlight.js and does not support yaml currently.
The fix is to remove triple back ticks, the yaml keyword, and indent instead.
We loose yaml syntax highlighting on github, but it displays an acceptable version on both github and docs.docker.com (`<pre>` like version):
Note that with this change, we loose yaml syntax highlighting on github:
Discussed with @moxiegirl [here](https://github.com/docker/distribution/pull/493#issuecomment-120493650)

docs: fix yaml sections formatting at docs.docker.com

---

notifications/listener.go
registry.go
registry/client/repository.go
registry/client/repository_test.go
registry/storage/manifeststore.go
testutil/handler.go

Add a functional argument to pass a digest to (ManifestService).GetByTag().
If the digest matches an empty manifest and nil error are returned.
See 1bc740b0d59a31cef7779dab7ddc522a4020de7c for server implementation.
Closes #692 

Allow conditional fetching of manifests with the registry client.

---

notifications/listener.go
notifications/listener_test.go
registry.go
registry/client/repository.go
registry/client/repository_test.go
registry/handlers/images.go
registry/handlers/tags.go
registry/storage/manifeststore.go
registry/storage/manifeststore_test.go
registry/storage/registry.go

Enable manifest verification to be specified external to the Manifest 
interface and be passed in to the Put function.
I would have preferred VerifyManifest to live in the manifest package
but it would result in an import cycle

External manifest verification

---

docs/configuration.md

Link was broken in [commit `cf9b4ab5e`](https://github.com/docker/distribution/commit/cf9b4ab5e9458eb4e542b8db487344a59657f4fe#diff-76e731333fb756df3bff5ddb3b731c46L245)

Fix link to token specification

---

registry/handlers/app.go

An error level log is already produced within app.authorized() if an
actual unexpected error occurs during authorization, so this warning
level log remains for auditability purposes, but should not be
considered an error condition.
Addresses #704

Reduces log level of auth error lines from error->warn

---

registry/api/errcode/errors.go
registry/api/errcode/handler.go
registry/handlers/app.go
registry/handlers/helpers.go

This changeset provides a common http handler for serving errcodes. This should
unify http responses across webservices in the face of errors.
Several type assertions have been added, as well, to ensure the error interface
is implemented.
This supports some work in notary.
CC @duglin @endophage @NathanMcCauley @diogomonica 

Export ServeJSON for serving error codes

---

blobs.go
docs/notifications.md
notifications/bridge.go
notifications/event.go
notifications/event_test.go
registry/client/repository.go
registry/client/repository_test.go
registry/storage/blob_test.go
registry/storage/blobserver.go
registry/storage/blobstore.go
registry/storage/blobwriter.go
registry/storage/cache/cache.go
registry/storage/cache/redis/redis.go
registry/storage/cache/suite.go

After consideration, we've changed the main descriptor field name to for number
of bytes to "size" to match convention. While this may be a subjective
argument, commonly we refer to files by their "size" rather than their
"length". This will match other conventions, like `(FileInfo).Size()` and
methods on `io.SizeReaderAt`. Under more broad analysis, this argument doesn't
necessarily hold up. If anything, "size" is shorter than "length".
Closes #680 

Use "Size" field to describe blobs over "Length"

---

docs/authentication.md

The link was pointing to deployement.md, while the file is deploying.md
Note: 
Currently the problem is not visible on https://docs.docker.com/registry/authentication/
The issue is visible on https://github.com/docker/distribution/blob/master/docs/authentication.md

Fix broken link to deploying.md

---

cmd/registry/config.yml
docs/building.md
docs/notifications.md

Since the actual port is 5003, it would make sense to name it local-5003 instead of local-8082

Change confusing enpoint name

---

registry/storage/driver/testsuites/testsuites.go

Signed-off-by: yuzou <zouyu7@huawei.com>
After TestWriteReadLargeStreams is finished, close the reader created by ReadStream to free the underlying resources used by drivers.

Close reader after the test is finished.

---

registry/api/errcode/errors.go
registry/api/errcode/errors_test.go

Missed this during the removal of the args property
ping @stevvooe 

Make Error.Error() return the post-arg-substitution Message

---

docs/spec/api.md
docs/spec/api.md.tmpl

To avoid confusion with the registry version number or other project versions,
the specification updates are now lettered.

Identify V2 API changes by letter

---

docs/spec/api.md
registry/api/v2/descriptors.go

Some missing descriptions and error code for tags pagination was cleaned up to
ensure clarity. Specifically, we ensure the request variations are named and
the proper error codes are included.
cc @pdevine @aaronlehmann @dmcgowan @RichardScothern 

Clean up pagination specification

---

registry/handlers/app.go

Because the logger was incorrectly replaced while adding hooks, log output did
not include the version and instance ids. The main issue was the the
logrus.Entry was replaced with the logger, which included no context. Replacing
the logger on the context is not necessary when configuring hooks since we are
configuring the contexts logger directly.
The main problem was demonstrated by log output like this:
```
INFO[0000] listening on [::]:5000
```
When it should include the context information:
```
INFO[0000] listening on [::]:5000                        environment=development instance.id=a519e71f-4874-4738-b302-f4d0d1956733 service=registry version=v2.0.0-434-g984037f.m
```

Do not replace logger when adding hooks

---

blobs.go
cmd/registry/config.yml
configuration/configuration.go
docs/spec/api.md
docs/spec/api.md.tmpl
notifications/listener_test.go
registry/client/repository.go
registry/client/repository_test.go
registry/handlers/api_test.go
registry/handlers/app.go
registry/handlers/app_test.go
registry/handlers/blob.go
registry/handlers/images.go
registry/storage/blob_test.go
registry/storage/blobstore.go
registry/storage/blobwriter.go
registry/storage/cache/cachedblobdescriptorstore.go
registry/storage/cache/memory/memory.go
registry/storage/cache/redis/redis.go
registry/storage/cache/suite.go
registry/storage/catalog_test.go
registry/storage/linkedblobstore.go
registry/storage/manifeststore.go
registry/storage/manifeststore_test.go
registry/storage/registry.go
registry/storage/revisionstore.go
registry/storage/signaturestore.go

Implement the delete API by implementing soft delete for layers
and blobs by removing link files and updating the blob descriptor
cache.  Deletion is configurable - if it is disabled API calls
will return an unsupported error.
We invalidate the blob descriptor cache by changing the linkedBlobStore's
blobStatter to a blobDescriptorService and naming it a blobAccessController.
Delete() is added throughout the storage API to support this functionality.
Closes #461

Manifest and layer soft deletion

---

docs/spec/api.md

Reverts docker/distribution#737
This incorrectly fixed the type.

Revert "Fix typo"

---

Godeps/Godeps.json

Deleted brace was causing an error on master.  Fixed tabs/spaces at the same time.
Test:
```
jq . Godeps/Godeps.json
parse error: ':' not as part of an object at line 85, column 16
```

fix json parse error on Godeps

---

registry/client/repository.go
registry/client/repository_test.go
registry/handlers/api_test.go
registry/handlers/images.go
registry/storage/blobserver.go

According to the http specification, [ETags must be quoted](http://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.11). This ensures all API responses are quoted correctly. Where we can, we still accept the unquoted version.
We'll need to get this fix into docker/docker for 1.8 as a bugfix if we using the client libraries.

Etags must be quoted according to http spec

---

registry/auth/auth.go
registry/auth/htpasswd/access.go
registry/auth/htpasswd/access_test.go
registry/auth/silly/access.go
registry/auth/silly/access_test.go
registry/auth/token/accesscontroller.go
registry/handlers/app.go

This removes the erroneous `http.Handler` interface in favor a simple SetHeaders
method that only operates on the response. Several unnecessary uses of pointer
types were also fixed up.
`auth.AccessController` interface now uses `distribution/context`.
Closes #614

Authorization interface cleanup

---

docs/spec/api.md
docs/spec/api.md.tmpl

This is the correct fix for #737.
cc @tsing

Correctly generate URL examples specifications

---

registry/client/auth/session.go
registry/client/blob_writer.go
registry/client/errors.go
registry/client/repository.go
registry/client/transport/http_reader.go

Generally, all 2xx and 3xx codes should be treated as success.

Make the registry client more tolerant about HTTP status codes

---

contrib/docker-integration/tls.bats

Make `has_digest` function more robust for testing 1.8 and newer

[contrib/docker-integration] Update has digest test in scripts

---

uuid/uuid.go

The whole CI infrastructure on docker/docker is suffering from entropy exhaustion. As pointed out by @ewindisch, the UUID generation code here is wasting some entropy bytes. That may not be a sufficient fix, but still seems like an improvement.
The UUID generation retries multiple times to read a full UUID, but preserves any bytes of entropy he successfully managed to read between retries.
Ping @jfrazelle @crosbymichael @calavera.

Reduce consumption of entropy source

---

registry/handlers/api_test.go

This passed in the #744 before merge, but apparently the test changed
since the PR was created in ways that led to a new failures.
@dmcgowan

Fix for api_test.go

---

cmd/registry/config.yml
docs/configuration.md
registry/handlers/app.go

Log a warning if the registry generates its own secret.
Update configuration doc, and remove the default secret from the
development config file.
@stevvooe PTAL

Automatically generate a HTTP secret if none is provided

---

configuration/configuration.go
docs/configuration.md
notifications/listener_test.go
registry/handlers/app.go
registry/handlers/app_test.go
registry/storage/blob_test.go
registry/storage/blobserver.go
registry/storage/catalog_test.go
registry/storage/manifeststore_test.go
registry/storage/registry.go

Storage drivers can implement a method called URLFor which can return a direct url for a given path. The functionality allows the registry to direct clients to download content directly from the backend storage. This is commonly used with s3 and cloudfront. Under certain conditions, such as when the registry is not local to the backend, these redirects can hurt performance and waste incoming bandwidth on pulls. This feature addition allows one to disable this feature, if required.
Closes #432. #739 must be merged before this PR.

Allow disabling of storage driver redirects

---

Dockerfile

This preserves the previously documented mountpoint for the
configuration file.

Copy dev-config.yml to config.yml at image build time

---

cmd/registry/config-example.yml

Rather than setting this to "true", the whole section should be removed.
@stevvooe

Fix earlier commit to enable upload purging in example config file

---

cmd/registry/main.go
context/context.go
context/logger.go
uuid/uuid.go

To avoid errant log messages, we've disabled logging by default when uuid is having trouble accessing `/dev/urandom`. This also takes the work from #786 and incorporates the feedback.
This carries #784 and #786.
cc @jfrazelle @tiborvass @ibuildthecloud

UUID package improvements

---

cmd/registry/main.go

Change the minimum TLS version to TLS 1.0, and add a custom list of
ciphersuites which are thought to be the most secure options.

Change server TLS config to tighten security

---

Makefile
circle.yml

It's necessary to compile the code first; otherwise go vet silently
fails to load imports.
Fixes #807.

Fix go vet in CI

---

registry/storage/blob_test.go

registry/storage/blob_test.go:149: arg d for printf verb %s of wrong type: github.com/docker/distribution.Descriptor

Fix vet issue

---

contrib/docker-integration/run_multiversion.sh
contrib/docker-integration/tls.bats

Add a run_multiversion.sh script that downloads a variety of Docker
engines and runs the integration tests against each of them.
Skip some of the tests when running with Docker 1.6.0. It has a bug that
prevents these tests from completing successfully.
Fixes #751

Run integration tests with multiple Docker engine versions

---

context/http_test.go

This channel never gets written to, but this only means that the mock
ResponseWriter will never signal a premature disconnect.
Based on feedback from #763.

Make testResponseWriter's CloseNotify return an actual channel instead of nil

---

contrib/docker-integration/Dockerfile
contrib/docker-integration/run_multiversion.sh

- Add a command line argument to run_multiversion.sh which has it start
a docker daemon. This allows it to run directly inside an outermost
docker-integration container instead of running outside all containers.
- Install Docker 1.7.1 intead of 1.7.0-rc1 in the docker-integration
container. 1.7.0 has a bug that prevents "docker cp" from working
properly.

Two fixes for Docker integration tests

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/denverdino/aliyungo/oss/client.go
Godeps/_workspace/src/github.com/denverdino/aliyungo/oss/client_test.go
Godeps/_workspace/src/github.com/denverdino/aliyungo/oss/config_test.go
Godeps/_workspace/src/github.com/denverdino/aliyungo/oss/export.go
Godeps/_workspace/src/github.com/denverdino/aliyungo/oss/multi.go
Godeps/_workspace/src/github.com/denverdino/aliyungo/oss/multi_test.go
Godeps/_workspace/src/github.com/denverdino/aliyungo/oss/regions.go
Godeps/_workspace/src/github.com/denverdino/aliyungo/oss/signature.go
Godeps/_workspace/src/github.com/denverdino/aliyungo/util/attempt.go
Godeps/_workspace/src/github.com/denverdino/aliyungo/util/attempt_test.go
Godeps/_workspace/src/github.com/denverdino/aliyungo/util/encoding.go
Godeps/_workspace/src/github.com/denverdino/aliyungo/util/encoding_test.go
Godeps/_workspace/src/github.com/denverdino/aliyungo/util/iso6801.go
Godeps/_workspace/src/github.com/denverdino/aliyungo/util/iso6801_test.go
Godeps/_workspace/src/github.com/denverdino/aliyungo/util/signature.go
Godeps/_workspace/src/github.com/denverdino/aliyungo/util/signature_test.go
Godeps/_workspace/src/github.com/denverdino/aliyungo/util/util.go
Godeps/_workspace/src/github.com/denverdino/aliyungo/util/util_test.go
circle.yml
cmd/registry/main.go
docs/storage-drivers/oss.md
docs/storagedrivers.md
registry/storage/driver/oss/doc.go
registry/storage/driver/oss/oss.go
registry/storage/driver/oss/oss_test.go

This driver implements the storagedriver.StorageDriver interface and uses Aliyun OSS Open Storage Service as storage backend.
The documentation for this driver is in [https://github.com/denverdino/distribution/blob/master/docs/storage-drivers/oss.md](https://github.com/denverdino/distribution/blob/master/docs/storage-drivers/oss.md)
To run the unit test case for this driver, you need set the following environment variables before
```
export ALIYUN_ACCESS_KEY_ID=<YOUR_ACCESS_KEY_ID>
export ALIYUN_ACCESS_KEY_SECRET=<YOUR_ACCESS_SECRET>
export OSS_REGION=<OSS_REGION_ID>   E.g. oss-us-west-1
export OSS_BUCKET=<OSS_BUCKET_NAME>
export OSS_ENCRYPT=false
```
NOTE: This driver reuses the code logic from the S3 driver. 
Signed-off-by: Li Yi (denverdino@gmail.com) Boshi Lian(farmer1992@gmail.com)

Storage Driver for Aliyun OSS

---

contrib/docker-integration/Dockerfile
contrib/docker-integration/run.sh

- Upgrade docker-compose to 1.3.3 to work around
https://github.com/docker/compose/issues/1314
- Change run.sh to run the Docker container in the foreground so that
the exit code is propagated.

Two more Docker integration test fixes

---

docs/storage-drivers/oss.md

This page was missing styling once exported to HTML. Adding a
<!--[metadata]> block similar to the ones the other *.md files have
appears to solve the problem.

Fix lack of styling on Aliyun OSS documentation page

---

context/http.go
context/http_test.go
registry/handlers/helpers.go

Instead, provide a variant of instrumentedResponseWriter that does not
implement CloseNotifier, and use that when necessary. In
copyFullPayload, log instead of panicing when we encounter something
that doesn't implement CloseNotifier.
This is more complicated than I'd like, but it's necessary because
instrumentedResponseWriter must not embed CloseNotifier unless there's
really a CloseNotifier to embed.
Closes #828

Don't panic when a http.ResponseWriter does not implement CloseNotifier

---

version/version.go

Now that we've tagged a release candidate, we can now say all builds are
"2.1.0+unknown" if the makefile is not used.
cc @RichardScothern 

Rev base version to 2.1.0

---

registry/storage/driver/rados/rados.go
registry/storage/driver/testsuites/testsuites.go

When using the RADOS driver, the hierarchy of the files is stored
in OMAPs, but the root OMAP was not created and a call to List("/")
was returning an error instead of returned the first level files
stored. This patches creates an OMAP for "/" and excludes the listed
directory from the list of files returned.
Fixes: #832
Related: #831

driver/rados: Create OMAP for root directory

---

contrib/docker-integration/helpers.bash
contrib/docker-integration/install_certs.sh
contrib/docker-integration/run.sh
contrib/docker-integration/run_engine.sh
contrib/docker-integration/run_multiversion.sh
contrib/docker-integration/test_runner.sh

Previously, the strategy for avoiding lots of rebuilding and repulling
for each Docker version being tested was to use a mountpoint to persist
/var/lib/docker. This was pretty broken, and may not be a reliable
strategy. This commit changes the scripts to instead build/pull images
outside the innermost container, and copy them to the final test
environment with docker save/docker load.
This requires a fair amount of changes, since run.sh must now
communicate with the Docker engine that was formerly started by
test_runner.sh. The code that starts this engine has been broken out to
run_engine.sh so that starting the engine and running the tests under it
can be done separately (with the images loaded in between these steps).

Redesign integration testing to copy images to nested containers

---

cmd/registry-api-descriptor-template/main.go
cmd/registry/main.go
docs/spec/api.md
health/health.go
health/health_test.go
registry/api/errcode/register.go
registry/api/v2/descriptors.go
registry/api/v2/errors.go
registry/client/errors.go
registry/client/repository_test.go
registry/handlers/app.go
registry/handlers/app_test.go
registry/handlers/blob.go
registry/handlers/images.go
registry/proxy/proxymanifeststore.go

To ensure the ensure the web application is properly operating, we've added a
periodic health check for the storage driver. If the health check fails three
times in a row, the registry will serve 503 response status for any request
until the condition is resolved. The condition is reported in the response body
and via the /debug/health endpoint.
To ensure that all drivers will properly operate with this health check, a
function has been added to the driver test suite.
Close #272.

Provide simple storage driver health check

---

blobs.go
docs/spec/api.md
errors.go
registry/api/errcode/register.go
registry/api/v2/descriptors.go
registry/handlers/api_test.go
registry/handlers/blob.go
registry/handlers/blobupload.go
registry/handlers/images.go
registry/proxy/proxymanifeststore.go

Change some incorrect error types in proxy stores from API errors to distribution errors.
Also promote ErrUnsupported to a typed error to fit more in with other error types and check for it approriately.
Give v2.ErrorCodeUnsupported an HTTP status code.
Fill in missing checks for mutations on a registry configured as a pull-through cache.  Add unit tests and update documentation.

Error handling fixes

---

Dockerfile

This makes it consistent with the new official image.
Paths in the docs were updated in
34067d7d43f282a67528764ba36527b800da25fa.
Fixes #843.

In the build container, change the config file location to /etc/docker/registry/config.yml

---

CONTRIBUTING.md

Commenting on closed issues is rude and confusing. Most of the time, the issues
aren't actually the same. It is much better to file a duplicate and merge them
later when root cause has been identified than to have conflicting information
throughout a ticket.

Forbid commenting on closed issues

---

registry/storage/linkedblobstore.go
registry/storage/manifeststore_test.go
registry/storage/registry.go
registry/storage/signaturestore.go
registry/storage/tagstore.go

- Use correct path for manifest revision path
Unfortunately, the refactor used the incorrect path for manifest links within a
repository. While this didn't stop the registry from working, it did break
compatibility with 2.0 deployments for manifest fetches.
- Maintain manifest link compatibility
Unfortunately, the 2.1 releease has written manfiest links into the wrong
directory. This doesn't affect new 2.1 deployments but fixing this to be 2.0
backwards compatible has broken 2.1.0 compatibility. To ensure we have
compatibility between 2.0, 2.1.0 and future releases, we now check one of
several locations to identify a manifest link.
Tests were added to ensure these are locked down to the appropriate paths.

registry/storage: use correct manifest link

---

cmd/registry/config-example.yml
docs/osx/config.yml

The storage cache option layerinfo is deprecated,
so use blobdescriptor instead in example config files.

Update example config to avoid deprecated option

---

registry/storage/blobstore.go
registry/storage/blobwriter.go
registry/storage/blobwriter_resumable.go
registry/storage/catalog.go
registry/storage/catalog_test.go
registry/storage/linkedblobstore.go
registry/storage/manifeststore_test.go
registry/storage/paths.go
registry/storage/paths_test.go
registry/storage/purgeuploads.go
registry/storage/purgeuploads_test.go
registry/storage/registry.go
registry/storage/signaturestore.go
registry/storage/tagstore.go
registry/storage/vacuum.go

The use of the pathMapper is no longer needed the way we have organized the
code base. The extra level of indirection has proved unnecessary and confusing
so we've opted to clean it up. In the future, we may require more flexibility,
but now it is simply not required.

Remove pathMapper object

---

cmd/registry/config-cache.yml
cmd/registry/config-dev.yml
cmd/registry/config-example.yml
configuration/configuration.go
configuration/configuration_test.go
docs/configuration.md
registry/handlers/api_test.go
registry/handlers/app.go

The example configuration files add X-Content-Type-Options: nosniff.
Add coverage in existing registry/handlers unit tests.
Fixes #265.

Add a section to the config file for HTTP headers to add to responses

---

registry/handlers/api_test.go

Change checkResponse to only expect the configured
X-Content-Type-Options header if it doesn't receive a 405 error, which
means the handler isn't registered for that method.

Fix tests after #846

---

context/http.go
registry/handlers/api_test.go
registry/handlers/helpers.go

A change in #763 to address review comments caused problems. Originally,
instrumentedResponseWriter implemented the CloseNotifier interface, and
would panic if it was wrapping something that did not implement that
interface. This was split into a separate instrumentedResponseWriterCN
type that implements CloseNotifier, so there's a fallback if
instrumentedResponseWriter ever needs to wrap something that does not
implement this interface.
instrumentedResponseWriter's Value method would end up upcasting either
type back to instrumentedResponseWriter, which does not implement the
interface. In effect, instrumentedResponseWriterCN was never visible to
the handler.
This fixes the problem by implementing a wrapper Value method for
instrumentedResponseWriterCN.
cc …

Fix CloseNotifier handling and avoid "the ResponseWriter does not implement CloseNotifier" warnings in logs

---

notifications/listener_test.go
registry/handlers/app.go
registry/handlers/app_test.go
registry/proxy/proxyblobstore_test.go
registry/proxy/proxymanifeststore_test.go
registry/storage/blob_test.go
registry/storage/catalog_test.go
registry/storage/manifeststore_test.go
registry/storage/registry.go

Clean up calling convention for NewRegistryWithDriver to use functional
arguments.
This is a first step towards the refactor described in #215. I plan to
add additional options in the process of moving configurable items from
the App structure to the registry structure.

Functional options for NewRegistryWithDriver

---

cmd/registry/config-cache.yml
cmd/registry/config-dev.yml
cmd/registry/config-example.yml
configuration/configuration.go
docs/configuration.md
health/checks/checks.go
health/checks/checks_test.go
health/doc.go
health/health.go
health/health_test.go
registry/auth/silly/access_test.go
registry/auth/token/token_test.go
registry/handlers/api_test.go
registry/handlers/app.go
registry/handlers/app_test.go
registry/handlers/health_test.go

Add a section to the config file called "health". Within this section,
"filecheckers" and "httpcheckers" list checks to run. Each check
specifies a file or URI, a time interval for the check, and a threshold
specifying how many times the check must fail to reach an unhealthy
state.
Document the new options in docs/configuration.md.
Add unit testing for both types of checkers. Add an UnregisterAll
function in the health package to support the unit tests, and an
Unregister function for consistency with Register.
Fix a string conversion problem in the health package's HTTP checker.
Fixes #271.

Add configurable file-existence and HTTP health checks

---

contrib/docker-integration/install_certs.sh
contrib/docker-integration/run.sh
contrib/docker-integration/run_engine.sh

When running a different version of docker outside of the default in the integration image, then commands will fail with mismatched version unless the docker binary is specified to the correct version.
Add various cleanups to run script.
Run all commands interacting with docker inside the container in an exec.
Remove port binding to outside of container since all commands run inside.
Trap docker rm to exit in case of failure which prevents final command from running.
Do no copy images when $DOCKER_VOLUME is specified, this allows for faster runs when mounting a volume with a warm image cache.
Move exec and graph driver defaulting into run engine script.
Remove duplicated update of /etc/hosts.
@aaronlehmann sorry was not able to review last change to integration tests. I addressed some of …

Fix mismatched version error on integration tests

---

Makefile
cmd/digest/main.go
digest/digest.go
digest/digester.go

Previously a useful gist, this changeset polishes the original tarsum tool into
a utility that can be used to calculate content digests. Any algorithm from the
digest package is supported with additional support from tarsum.
This tool is very useful for quickly checking backend digests and verifying
correctness.

Add generic content digest tool

---

manifest/doc.go
manifest/schema1/manifest.go
manifest/schema1/manifest_test.go
manifest/schema1/sign.go
manifest/schema1/verify.go
manifest/versioned.go
notifications/bridge.go
notifications/bridge_test.go
notifications/event_test.go
notifications/http_test.go
notifications/listener.go
notifications/listener_test.go
registry.go
registry/client/repository.go
registry/client/repository_test.go
registry/handlers/api_test.go
registry/handlers/images.go
registry/proxy/proxymanifeststore.go
registry/proxy/proxymanifeststore_test.go
registry/storage/manifeststore.go
registry/storage/manifeststore_test.go
registry/storage/revisionstore.go

As we begin our march towards multi-arch, we must prepare for the reality of
multiple manifest schemas. This is the beginning of a set of changes to
facilitate this. We are both moving this package into its target position where
it may live peacefully next to other manfiest versions.

Move manifest package to schema1

---

docs/spec/json.md

...and add blurb about not relying on canonicalization to ensure
identical output.

Update JSON spec to point out escaping of <, >, &

---

ROADMAP.md

Alter Project Planning area to point to Wiki so ROADMAP.md does not get stale.
Signed-off-by: Amy Lindburg <amy.lindburg@docker.com>

Delete stale info from Project Planning in ROADMAP.md

---

configuration/configuration.go
configuration/configuration_test.go
configuration/parser.go
docs/configuration.md

Overriding configuration parameters with environment variables used to
work by walking the configuration structure and checking for a
corresponding environment variable for each item. This was very limiting
because only variables corresponding to items that already existed in
the configuration structure would be checked. For example, an
environment variable corresponding to nested maps would only be noticed
if the outer map's key already existed.
This commit changes environment variable overriding to iterate over the
environment instead. For environment variables beginning with the
REGISTRY_ prefix, it splits the rest of their names on "_", and
interprets that as a path to the variable to unmarshal into. Map keys
are created as necessary. If we encounter an empty interface partway
through …

More flexible environment variable overrides

---

context/doc.go
context/logger.go
context/util.go
context/version.go
context/version_test.go
registry/handlers/app.go
registry/registry.go
registry/storage/blobwriter.go

By adding WithVersion to the context package, we can simplify context setup in the application. This avoids some odd bugs where instantiation order can lead to missing instance.id or version from log messages.
We also allow interface{} keys when using logger to support integer keys.

context: WithVersion and context package cleanup

---

registry/storage/driver/s3/s3.go

In the S3 storage driver there is currently an initial access permission check by listing the bucket. If this check fails, registry will panic and exit.
However, this check is broken in two ways. First of all it strips the final slash from the root directory path, meaning that any access permissions which limit access to a single directory will fail, because S3 treats the path as strict prefix match. Secondly it fails to strip any leading slash that might be present, unlike the other access places, which means that the path used is different as a leading slash is allowed and significant in a filename in S3.
Since there is also a periodic health check which correctly checks access permissions and shows the error more cleanly, the best solution seems to be to just remove this initial access …

Remove initial access check from S3 driver

---

errors.go
registry/client/repository.go
registry/client/repository_test.go
registry/proxy/proxymanifeststore.go

Avoid returning nil, nil when fetching a manifest by tag by introducing a new error ErrManifestNotModified which can be checked by clients.
Don't return a nil array and a nil error if the Tags endpoint cannot be found.
closes #983

Don't return nil, nil from functions

---

registry/storage/cache/cachecheck/suite.go
registry/storage/cache/memory/memory_test.go
registry/storage/cache/redis/redis_test.go

The "testing" package adds some flags in its init function, so utilities
that import distribution code can print a page of extra testing flags in
their help output.
This commit solves the issue by moving an import of "testing" in the
registry/storage/cache package to a new registry/storage/cache/testsuite
package, which is only imported by tests.

Avoid importing "testing" in externally-facing code

---

digest/set.go
digest/set_test.go

Also adds mutex protection around set access. This makes `digest.Set` more generally useful.

Add remove and list functions to digest set

---

Godeps/Godeps.json

The "github.com/ncw/swift" package was declared twice in the Godeps.json and has been since 540e3f1433d89cabc7612bb224c828d34b4f00ef.

Remove duplicate dependency definition

---

docs/storage-drivers/s3.md

According to [the S3 storage driver documentation](https://github.com/docker/distribution/blob/51bd34eaeda4702dfa1fbae96e0fcff47452798c/docs/storage-drivers/s3.md), the default should be true:
> `v4auth`: (optional) Whether you would like to use aws signature version 4 with your requests. **This defaults to true** if not specified (note that the eu-central-1 region does not work with version 2 signatures, so the driver will error out if initialized with this region and v4auth set to false)

Fix incorrect default

---

docs/spec/manifest-v2-1.md

This PR add some description to manifest spec.
I think the relationship between `fsLayers` and `history` fields should be clarified.

add description to manifest spec

---

registry/storage/driver/swift/swift.go

With some container ACLs, container creation will error with access denied if the container already exists.

Skip creating swift container if already exists

---

docs/configuration.md

This defaults to true in the code, but the doc claimed it defaults to
false.

Correct the default setting of s3's "secure" parameter in configuration.md

---

registry/api/v2/names.go
registry/api/v2/names_test.go

Fixes https://github.com/docker/distribution/issues/1062
This relaxes the naming restrictions places on Docker images to permit
valid hostnames according to [RFC-2396](https://www.ietf.org/rfc/rfc2396.txt).
It deviates from the RFC in the following ways:
1) Allow underscores where we allow hyphens (hostnames don't allow
underscores, which we must for backwards compatibility).
2) Leave "top-level" name segments unrestricted (domains require an
alpha character to begin a top-level domain, e.g. "com").
3) DO NOT allow a trailing dot, as permitted by FQDNs.
Signed-off-by: Matt Moore <mattmoor@google.com>

Allow hostname components in component names.

---

reference/reference.go
reference/reference_test.go
reference/regexp.go

These functions allow a Named type to be combined with a tag or a
digest. WithTag will replace the ImageReference function in
github.com/docker/docker/utils as the Docker Engine transitions to the
reference package.

Add WithTag and WithDigest combinator functions

---

docs/storage-drivers/swift.md

No longer claims that an additional segments container is used

Fixes documentation for swift driver "container" parameter

---

cmd/registry-api-descriptor-template/main.go
docs/spec/api.md
registry/api/errcode/register.go
registry/api/v2/descriptors.go

Associate HTTP 401s with Authentication errors rather than Authorization
errors. Changes the meaning of the UNAUTHORIZED error to be authentication
specific.
Defines DENIED error code to be associated with authorization
errors which result in HTTP 403 responses.
Add 'No Such Repository' errors to more endpoints.

[api spec] Update authN and authZ errors

---

configuration/configuration.go
configuration/configuration_test.go
docs/configuration.md
registry/api/v2/urls_test.go
registry/handlers/app.go

This allows the administrator to specify an externally-reachable URL for
the registry. It takes precedence over the X-Forwarded-Proto and
X-Forwarded-Host headers, and the hostname in the request.
NOTE: This is an alternative approach to #1000. I'm opening this as a separate PR so the patches can be compared and the best one can be chosen. Only one of the two should be merged.

Add http.host parameter

---

reference/reference.go
reference/reference_test.go

Various improvements motivated by early real-world use in engine code
under development:
- Make `WithDigest` return `Canonical`, since the return value always
has a name and a digest.
- Introduce a `NamedTagged` type, which can be used for strongly typing
cases where something must have a name and a tag. It provides a
more useful return type for `WithTag`, since its return value always has
both a name and a tag.
- Rename `ParseNamed` to `WithName`, and create a
`ParseNamed` that accepts tags and digests (returning a `Named` type).
The new `ParseNamed` makes code using the reference package much less
verbose, since typical use cases require a name, and this is an
additional type assertion and error case after every `Parse` call.

Usability improvements for reference package

---

manifest/schema1/manifest.go
registry/client/repository_test.go
registry/handlers/api_test.go
registry/handlers/images.go

To ensure that we only unmarshal the verified payload into the contained
manifest, we first copy the entire incoming buffer into Raw and then unmarshal
only the Payload portion of the incoming bytes. If the contents is later
verified, the caller can then be sure that the contents of the Manifest fields
can be trusted.

Correct unmarshal order for SignedManifest

---

registry/proxy/proxyblobstore.go
registry/proxy/proxyblobstore_test.go
registry/proxy/proxyregistry.go

Fix a race condition in pull through cache population by removing the functionality of readers joining current downloads.  Concurrent requests for the same blob will not block, but only the first instance will be comitted locally.
Add more unit tests.
This is a temporary fix. Closes #944 #913 

Fix a race condition in pull through cache population

---

registry/storage/registry.go

The resumableDigestEnabled of blobWriter is always set to false. That causes the following lines in "github.com/docker/distribution/registry/storage/blobwriter_resumable.go" always return errResumableDigestNotAvailable
```go
func (bw *blobWriter) resumeDigestAt(ctx context.Context, offset int64) error {
if !bw.resumableDigestEnabled {
return errResumableDigestNotAvailable
}
...
}
```
And then in 
```go
func (bw *blobWriter) validateBlob(ctx context.Context, desc distribution.Descriptor) (distribution.Descriptor, error) 
```
it will always set fullHash=true which it will download the uploaded file to get the digest again. The performance of pushing will be impacted a lot especially with the large file on the distributed object store.
I set the resumableDigestEnabled from the registry …

Redundant digest verification in validateBlob when pushing a new layer

---

docs/deploying.md
docs/insecure.md

The docs don't render emoji, so replaced the `:warning:` with a `**Warning**:` to keep the formatting consistent with `**Note**:` used in other parts of the docs.
Fixes https://github.com/docker/docker/issues/17281

Docs: replace emoji with regular warning

---

docs/spec/auth/token.md
registry/client/auth/session.go
registry/client/auth/session_test.go

This proposes an extension to the specification for the Bearer token
exchange to include information pertaining to when an issued Bearer
token will expire.
Signed-off-by: Matt Moore <mattmoor@google.com>

Add `expires_in` and `issued_at` to the auth spec.

---

registry/proxy/scheduler/scheduler.go
registry/proxy/scheduler/scheduler_test.go

The proxy scheduler implemented its own timer state machine. It's
simpler and more efficient to leverage the Go runtime's timer heap by
using time.AfterFunc.
This commit adds a time.Timer to each scheduler entry, and starts and
stops those timers as necessary. Then the mainloop goroutine and its
associated logic are not needed.

Simplify proxy scheduler

---

reference/reference.go
reference/reference_test.go

This was using a different regexp from the intended one. This meant that
tags with uppercase characters were not accepted.

Use correct regexp in reference.WithTag

---

reference/reference.go
reference/reference_test.go

There is a constraint on the length of the name in a reference, so
WithName should be checking this instead of potentially creating a
reference that doesn't comply with the rules.

Check length of input in WithName

---

registry/storage/blobwriter.go
registry/storage/blobwriter_resumable.go

registry/storage: close filereader after allocation

---

MAINTAINERS

Add github IDs to maintainers

---

registry/storage/blobserver.go
registry/storage/driver/base/base.go
registry/storage/driver/filesystem/driver.go
registry/storage/driver/gcs/gcs.go
registry/storage/driver/inmemory/driver.go
registry/storage/driver/oss/oss.go
registry/storage/driver/rados/rados.go
registry/storage/driver/s3/s3.go
registry/storage/driver/storagedriver.go
registry/storage/driver/swift/swift.go
registry/storage/driver/testsuites/testsuites.go

Carry #1070.  This PR implements review feedback.
Errors thrown by storage drivers don't have the name of the driver, causing user confusion about whether the error is coming from Docker or from a storage driver. This change adds the storage driver name to each error message.
This required changing ErrUnsupportedDriver to a type, leading to code changes whenever ErrUnsupportedDriver is used.  The tests check whether the driver name appears in the error message.
Closes: #664

Add Storage Driver Context.

---

manifest/schema1/manifest_test.go
notifications/listener_test.go
registry/handlers/api_test.go
registry/storage/manifeststore.go
registry/storage/manifeststore_test.go

Before materializing a schema1 manifest from JSON, ensure that contains equal
length History and FSLayer arrays.
This is required to prevent malformed manifests being put to the registry and
failing external verification checks.
Closes #1153 

Manifest Verification

---

registry/storage/driver/swift/swift.go

The Delete method lists objects under the given path and tries to delete
all of them with a bulk delete request. If the path has no objects
underneath it, the body of this request will be empty, which causes
HTTP-level issues. Specifically, Go's HTTP client senses the empty
request buffer and doesn't include a Content-Length, which causes the
Swift server to fail the request.
This commit fixes the problem by avoiding sending empty bulk delete
requests. This is the correct thing to do anyway, since there's no
reason to request deletion of zero objects.

Fix empty delete requests with Swift fs driver

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/ncw/swift/README.md
Godeps/_workspace/src/github.com/ncw/swift/auth.go
Godeps/_workspace/src/github.com/ncw/swift/auth_v3.go
Godeps/_workspace/src/github.com/ncw/swift/swift.go
Godeps/_workspace/src/github.com/ncw/swift/swift_test.go
Godeps/_workspace/src/github.com/ncw/swift/swifttest/server.go
registry/storage/driver/swift/swift.go

When a manifest has been uploaded, some segments of this manifest may not appear in the object listing yet. The manifest would then report a wrong size. To avoid this, we check that a segment appears after it has been created.
Signed-off-by: Sylvain Baubeau <sbaubeau@redhat.com>

Ensure read after write for segments

---

registry/api/v2/urls_test.go

When building a URL don't include path components in the host parameter.
Closes #1124
Signed-off-by: Rusty Conover <rusty@luckydinosaur.com>

Fix failing test case for URL escaping problem.

---

registry/auth/htpasswd/access.go

Previously, this error message would stringify as a pointer address,
which isn't particularly helpful.
This change breaks out the elements of the challenge object such that
the error is appropriately represented.
Signed-off-by: Ted Reed <ted.reed@gmail.com>

De-obfuscate error message

---

README.md

Superfluous space in the name was bothering me.
Signed-off-by: Jonathan Boulle <jonathanboulle@gmail.com>

README: fix formatting of docker-registry link

---

docs/insecure.md

On OL6, the Shared System Certificates are not enabled by default and need to be activated using `update-ca-trust enable`.
Signed-off-by: Avi Miller <avi.miller@oracle.com>

Adding additional command to enable the shared system certificates

---

docs/spec/api.md
docs/spec/api.md.tmpl

Formatting content digest calculation to avoid copyright symbols

---

registry/client/repository.go
registry/client/transport/http_reader.go

Without this commit, three round-trips are required to fetch a blob with
a progress bar. The first is a call to Stat (HEAD request), to determine
the size. Then Open is called, which also calls Stat, and finally
performs a GET request.
Only the GET request is actually needed. The size of the blob can be
sniffed from Content-Length in the GET response.
This commit changes HTTPReadSeeker to automatically detect the size from
Content-Length instead of requiring it to be passed in. The Stat call is
removed from Open because it is no longer necessary.
HTTPReadSeeker now takes an additional errorHandler callback argument which
translates an unsuccessful HTTP response into an appropriate API-level
error. Using a callback for this makes it possible to avoid leaking the
repsonse body to Read's …

Avoid stat round-trips when fetching a blob

---

registry/storage/walk.go
registry/storage/walk_test.go

This ensures sorted order of elements encountered during walk. This open up a number of optimizations for the catalog API, in addition to other enumeration methods.
The error propagation for Walk has also been fixed.
Attempts to address issues in #1190.

storage: enforce sorted traversal during Walk

---

docs/spec/api.md
docs/spec/api.md.tmpl

This change clarifies the way the catalog endpoint returns results
when pagination was not explicitly requested.  This addresses part of issue #1190.
Signed-off-by: Patrick Devine <patrick.devine@docker.com>

Clarify pagination for catalog API endpoint

---

docs/nginx.md

If this example was copied and pasted, the shell would try to interpolate `$upstream_http_docker_distribution_api_version` and `$docker_distribution_api_version`.

Escape dollar signs

---

docs/Dockerfile
docs/help.md
docs/spec/api.md
docs/spec/auth/index.md
docs/storagedrivers.md

The documentation needs an `index.md` or alias for each output dir - idk enough about the content here, so I've given examples of each.
@moxiegirl

Small doc fixes found by the linkchecker

---

reference/reference.go
reference/regexp.go
reference/regexp_test.go

To resolve some inconsistencies between the grammar and the regular
expressions, the grammar has been slightly refactored to match the intent. The
regular expressions have been redefined with the same structure to make it
easier to verify the grammar is correct.

reference: refactor grammar and regular expressions

---

registry/client/repository.go
registry/client/repository_test.go

Add clearer messaging around missing content-length headers.
Closes #1235 

Add clearer messaging around missing content-length headers.

---

registry/storage/driver/filesystem/driver.go
registry/storage/driver/oss/oss.go
registry/storage/driver/rados/rados.go
registry/storage/driver/s3/s3.go
registry/storage/driver/storagedriver.go
registry/storage/driver/swift/swift.go
registry/storage/driver/testsuites/testsuites.go

Issue #1186 describes a condition where a null tags response is returned when
using the s3 driver. The issue seems to be related to a missing
PathNotFoundError in s3. This change adds a test for that to get an idea of the
lack of compliance across storage drivers. If the failures are manageable,
we'll add this test condition and fix the s3 driver.
Don't merge this.

[WIP] registry/storage/driver: checking that non-existent path returns PathNotFoundError

---

docs/nginx.md

Fixes a huge problem where a nginx variable was not escaped and nginx was adding the literal string "always" to all requests.
The most obvious result was that basic auth was entirely broken.
Signed-off-by: Carson Anderson <ca@carson-anderson.com>

Fix incorrectly interpolated config setting

---

docs/apache.md
docs/building.md
docs/nginx.md
docs/osx-setup-guide.md
docs/recipes.md

These headers were rendered as body text because there was no space, but a "tab" after the `#`.
Took me a few minutes to find out why they didn't render as header, haha

Fix headers in documentation

---

digest/digest.go
digest/verifiers_test.go
notifications/bridge.go
notifications/bridge_test.go
notifications/listener_test.go
registry/client/repository_test.go
registry/handlers/api_test.go
registry/handlers/images.go
registry/proxy/proxyblobstore_test.go
registry/proxy/proxymanifeststore.go
registry/proxy/proxymanifeststore_test.go
registry/storage/blob_test.go
registry/storage/blobstore.go
registry/storage/linkedblobstore.go
registry/storage/manifeststore_test.go

The current implementation of digest.FromBytes returns an error. This
error can never be non-nil, but its presence in the function signature
means each call site needs error handling code for an error that is
always nil.
I verified that none of the hash.Hash implementations in the standard
library can return an error on Write. Nor can any of the hash.Hash
implementations vendored in distribution.
This commit changes digest.FromBytes not to return an error. If Write
returns an error, it will panic, but as discussed above, this should
never happen.
This commit also avoids using a bytes.Reader to feed data into the hash
function in FromBytes. This makes the hypothetical case that would panic
a bit more explicit, and should also be more performant.

Simplify digest.FromBytes calling convention

---

registry/client/repository.go

This calls Stat before Open, which should be unnecessary because Open
can handle the case of a nonexistent blob. Removing the Stat saves a
round trip.
This is similar to the removal of stat in Open in #1226.

Remove unnecessary stat from blob Get method

---

docs/spec/manifest-v2-2.md

This is a follow-on to PR #62, and it borrows much of the format
from #993, but uses specific formats for the image manifest and manifest
list (fat manifest) instead of a combined generic format.
The intent of this proposed manifest format is to allow multi-arch, and
allow for full content-addressability of images in the Docker engine.

docs/spec: Proposal for new manifest format

---

registry/storage/blobserver.go

Fixes issue where an error was returned instead of serving the blob
#1300, docker/docker#15264

Serve blobs when a storage driver supports redirects but are disabled

---

digest/digester.go

After running into a few nil pointer errors during development, it is clear
that having this function return nil when a hash is not available is the wrong
approach. Nearly every time, this lack of availability was due to a missing
import statement for the hash. This is always a programming error.
To avoid future confusion, we now appropriately panic when the hash function is
not imported by the application. More dynamic uses of the package should call
Algorithm.Available() before calling Algorithm.Hash() to avoid this panic.

digest: panic on unavailable hash algorithm

---

registry/storage/driver/filesystem/driver.go

Leaves any further permissions restrictions to the process umask
Signed-off-by: Brian Bland <brian.bland@docker.com>
Addresses #1295

Relaxes filesystem driver permissions to 0777 (dirs) and 0666 (files)

---

docs/spec/manifest-v2-2.md

Markdown linter produced an error on this page;
running markdownlint
ERROR (registry/spec/manifest-v2-2.md) frontmatter: Unexpected non-whitespace char: # Image Manifest Version 2, Schema 2

docs: mark manifest as "draft"

---

contrib/docker-integration/run.sh
contrib/docker-integration/run_engine.sh
contrib/docker-integration/run_multiversion.sh

Since the daemon flag was deprecated and replaced by the daemon subcommand, the run engine should use the subcommand and only the flag for older version.
Updated docker versions which are tested to include the last 2 releases.
Also the jenkins has been updated to no longer attempt to run the distribution tests on a centos machine (which would fail because it was trying to use aufs).

Fix broken daemon startup with master

---

registry/client/auth/session.go
registry/client/blob_writer.go
registry/client/errors.go
registry/client/repository.go

In the case of a failed HTTP auth token request, in addition to the current message that is returned, also return the error message in the response. This is to provide the user with a more descriptive message about what went wrong.
Signed-off-by: Kenny Leung <kleung@google.com>

Print error for failed HTTP auth request.

---

registry/storage/driver/gcs/gcs.go

This PR fixes a test failure due to an added test case. 
@stevvooe @RichardScothern

GCS Storagedriver: fix test failure caused by #1187

---

registry/storage/driver/gcs/gcs.go
registry/storage/driver/gcs/gcs_test.go

This PR fixes two bugs in the retry-function:
* the function panics if a request returns an error that is not of type googleapi.Error
* the function redeclares the "err" variable causing it to return nil if the request still fails after the maximum number of retries.
@RichardScothern

GCS storage driver: fix retry function

---

registry/api/errcode/errors.go
registry/api/errcode/errors_test.go

To bring ErrorCode into liine with Go conventions, ErrorCode.Error() now
returns the "nice" value of the error code. This ensures error message assembly
works similar to commonly used Go conventions when directly using ErrorCode as
an error.

More consistent return from ErrorCode.Error()

---

blobs.go
docs/spec/manifest-v2-2.md
manifest/manifestlist/manifestlist.go
manifest/manifestlist/manifestlist_test.go
manifest/schema1/config_builder.go
manifest/schema1/config_builder_test.go
manifest/schema1/reference_builder.go
manifest/schema1/reference_builder_test.go
manifest/schema2/builder.go
manifest/schema2/builder_test.go
manifest/schema2/manifest.go
manifest/schema2/manifest_test.go
manifest/versioned.go
manifests.go
registry/handlers/api_test.go
registry/handlers/app.go
registry/handlers/images.go
registry/storage/manifestlisthandler.go
registry/storage/manifeststore.go
registry/storage/registry.go
registry/storage/schema2manifesthandler.go
registry/storage/signedmanifesthandler.go

This PR introduces support for the schema2 manifest defined in #1068. This covers both an "image manifest", which supersedes the schema1 manifest format, and a "manifest list" that points to the appropriate manifests for specific platforms, to facilitate multi-architecture images.
The `Accept` header is used to gauge which schema versions are accepted by a client. If the client does not indicate that it accepts the schema2 format, and requests a manifest that is stored in this format, the registry will automatically convert it to schema1 format for backward compatibility.
schema1's `ManifestBuilder` has been renamed to `ReferenceBuilder`. This PR introduces a second schema1 `ManifestBuilder` called `ConfigBuilder`, which can generate a schema1 manifest from a Docker 1.10+ image …

Implement schema2 manifest formats

---

blobs.go
docs/spec/api.md
docs/spec/api.md.tmpl
manifest/schema1/config_builder_test.go
manifest/schema2/builder_test.go
notifications/bridge.go
notifications/event.go
notifications/listener.go
notifications/listener_test.go
registry/api/v2/descriptors.go
registry/client/auth/session.go
registry/client/repository.go
registry/client/repository_test.go
registry/handlers/app.go
registry/handlers/blobupload.go
registry/proxy/proxyblobstore.go
registry/proxy/proxyblobstore_test.go
registry/storage/blob_test.go
registry/storage/linkedblobstore.go
registry/storage/registry.go

Extends blob upload POST endpoint to support mount and from query
parameters as described in #634

Adds cross-repository blob mounting behavior

---

registry/handlers/api_test.go
registry/handlers/images.go
registry/storage/tagstore.go
registry/storage/tagstore_test.go

When a manifest is deleted by digest, look up the referenced tags in the tag
store and remove all associations.
closes #1293 
closes #938
supercedes #1297 

Remove tags referencing deleted manifests.

---

docs/spec/api.md.tmpl

Uses UPPER_UNDERSCORE_CASE instead of the nice error message format
added in #911

Fixes error codes in the API spec template

---

blobs.go
docs/spec/api.md
docs/spec/api.md.tmpl
manifest/schema1/config_builder_test.go
manifest/schema2/builder_test.go
notifications/listener.go
registry/client/repository.go
registry/client/repository_test.go
registry/handlers/blobupload.go
registry/proxy/proxyblobstore.go
registry/proxy/proxyblobstore_test.go
registry/storage/blob_test.go
registry/storage/linkedblobstore.go

Removes the Mount operation and instead implements this behavior as part
of Create a From option is provided, which in turn returns a rich
ErrBlobMounted indicating that a blob upload session was not initiated,
but instead the blob was mounted from another repository

Adds functional options arguments to the Blobs Create method, remove Mount operation

---

registry/handlers/blobupload.go

Accidentally checked for err != nil instead of err == nil :/
Also now ensures that only a non-nil option is appended to the create
options slice

Fixes cross-repo blob mounting in the BlobUploadHandler

---

circle.yml

Go 1.5.0 has some stack pointer bugs. This may have been causing some CI
failures. Upgrade to a newer version.

Upgrade CI to go 1.5.3

---

registry/client/repository.go
registry/client/repository_test.go
registry/storage/linkedblobstore.go

Redefines privately in both storage and client packages
Signed-off-by: Brian Bland <brian.bland@docker.com>

Splits up blob create options definitions to be package-specific

---

Dockerfile

Updates Dockerfile to Go 1.5.3 base image.

Use Go 1.5.3

---

registry/storage/driver/gcs/gcs.go
registry/storage/driver/gcs/gcs_test.go

Remove the requirement of file system access to run GCS unit tests.  Deconstruct
the input parameters to take the private key and email which can be specified on
the build system via environment variables.

Change the parameters to the GCS drivers to allow CircleCI testing.

---

manifest/schema1/manifest.go
manifests.go
registry/handlers/api_test.go

For compatibility with other registries that don't use this exact
variant of the Content-Type header, we need to be more flexible about
what we accept. Any form of "application/json" should be allowed. The
charset should not be included in the comparison.
See docker/docker#19400.

Do not require "charset=utf-8" for a schema1 with content type application/json

---

manifest/schema1/manifest.go
notifications/event_test.go
notifications/http_test.go
registry/client/repository_test.go
registry/handlers/api_test.go

The Payload function for schema1 currently returns a signed manifest,
but indicates the content type is that of a manifest that isn't signed.
Note that this breaks compatibility with Registry 2.3 alpha 1 and
Docker 1.10-rc1, because they use the incorrect content type.

Fix content type for schema1 signed manifests

---

registry/storage/driver/gcs/gcs.go
registry/storage/driver/gcs/gcs_test.go
registry/storage/driver/testsuites/testsuites.go

This PR is a followup on #1366. While #1366 solves issues where the results of the List call after a Delete operation is inconsistently reporting that some files still exist, it does not handle the case where the Delete operation itself does not delete files that were just created (due to "eventual consistency").
In addition this PR changes the test suite to report errors occurring during cleanup instead of silently continuing and panicking with a generic message later. This makes it much easier to figure out why a file was not deleted.  
In fact sometimes files were not deleted due the the Google API returning 5XX status codes. In such cases the operation can simply be retried and usually succeeds the next time.  To solve this, this PR automatically retries all storage API requests. …

StorageDriver GCS: improve test suite clean-up and add retrying to all GCS api calls

---

registry/api/errcode/errors.go
registry/client/errors.go

https://github.com/docker/distribution/pull/1249 changed token fetching
to parse HTTP error response bodies as serialized errcodes. However,
Docker Hub's authentication endpoint does not return error bodies in
this format. To work around this, convert its format into
ErrCodeUnauthorized or ErrCodeUnknown.
Fixes #1373
See also docker/docker#19476

Handle nonstandard token endpoint errors

---

manifests.go

One of the keys in the manifest media type map is an empty string. This
should not be sent as an Accept header.

Avoid empty Accept headers in client requests

---

notifications/bridge.go
notifications/bridge_test.go

Ensure the canonical manifest digest and length are sent to notification endpoints.
Closes #1374 

Ensure the canonical manifest digest and length are sent to notification endpoints.

---

manifests.go

This replaces custom parsing with the standard library's mime package.
This is simpler and more correct.

Use mime package to parse media type

---

manifests.go
registry/client/repository_test.go

This is needed for compatibility with some third-party registries that
send an inappropriate Content-Type header such as text/html.

If the media type for a manifest is unrecognized, default to schema1

---

registry/proxy/proxyblobstore.go
registry/proxy/proxyblobstore_test.go
registry/proxy/proxymanifeststore.go
registry/proxy/proxymanifeststore_test.go
registry/proxy/proxyregistry.go
registry/proxy/scheduler/scheduler.go
registry/proxy/scheduler/scheduler_test.go
registry/storage/cache/cachecheck/suite.go

Invalidate the blob store descriptor cache when content is removed from from
the proxy.  Also, change the scheduler to use the reference package.
Closes #1356

Invalidate the blob store descriptor cache

---

contrib/token-server/main.go
contrib/token-server/token.go
registry/auth/token/token.go
registry/auth/token/token_test.go

Minimal token server implementation for integration testing to be used alongside the registry. This is currently functional with existing docker 1.9.x release and latest distribution release. It may also be used as a reference implementation for properly creating JWTs expected by the registry when using token authentication.

Simple integration test token server

---

registry/auth/auth.go
registry/auth/htpasswd/access_test.go
registry/auth/silly/access_test.go
registry/auth/token/token_test.go
registry/handlers/app.go
registry/handlers/context.go

Prevent using strings throughout the code to reference a string key defined in the auth package.
For reference 
```
$ grep -rn "auth\.user" .
./registry/auth/silly/access_test.go:34:	t.Fatal("silly accessController did not set auth.user context")
./registry/auth/token/token_test.go:380:	t.Fatal("token accessController did not set auth.user context")
./registry/auth/htpasswd/access_test.go:61:	t.Fatal("basic accessController did not set auth.user context")
./registry/auth/auth.go:43:					UserKey     = "auth.user"
./registry/auth/auth.go:44:					UserNameKey = "auth.user.name"
./registry/auth/auth.go:91:					// object should have a "auth.user" value set to a UserInfo struct.
```

Update auth context keys to use constant

---

docs/index.md

This adds Docker to the Registry menu.
cc/ @RichardScothern @endophage @dmp42

Update title of Registry to Docker Registry

---

registry/storage/driver/testsuites/testsuites.go

Dear maintainer,
This PR is to grantee that we will read the correct number of bytes from randReader in testsuites of storage driver.
Currently, we will usually read more number of bytes than the initial size from randReader.

read the actual number of bytes according to the initial size.

---

notifications/listener.go
notifications/listener_test.go
registry.go
registry/client/repository.go
registry/handlers/app_test.go
registry/handlers/blobupload.go
registry/handlers/images.go
registry/handlers/tags.go
registry/proxy/proxyregistry.go
registry/storage/blob_test.go
registry/storage/blobwriter.go
registry/storage/blobwriter_resumable.go
registry/storage/linkedblobstore.go
registry/storage/manifeststore.go
registry/storage/registry.go
registry/storage/signaturestore.go
registry/storage/tagstore.go

This makes code that gets the name as a string read like
`repo.NameRef().Name()` instead of `repo.Name().Name()`.
Requested in
https://github.com/docker/docker/pull/19887#discussion_r51479753

Rename Name method of Repository to Named

---

registry/storage/blob_test.go
registry/storage/blobwriter.go
registry/storage/filewriter.go
registry/storage/filewriter_test.go
registry/storage/linkedblobstore.go

A bufferedFileWriter has an underlying fileWriter and a buffered writer that it initialised with a pointer to its fileWriter. When a bufferedFileWriter is copied its underlying fileWriter struct is copied as well. However, the buffered writer will still refer to fileWriter struct of the original bufferedFileWriter.
A bufferedFileWriter is dereferenced here: https://github.com/aibaars/distribution/blob/9f83bfc071094019b942c4332d17327b4dc5cdfc/registry/storage/linkedblobstore.go#L200
@stevvooe @RichardScothern

Storage: remove bufferedFileWriter (dead code)

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/docker/goamz/aws/aws.go

Includes change from AdRoll/goamz#424 to support AWS_DEFAULT_PROFILE environment variable, falling back to AWS_PROFILE, falling back to "default".
Fixes #1041

Updates docker/goamz dependency to support AWS profile env

---

registry/client/repository.go

A changeset under consideration for Go 1.7 would automatically copy
headers on redirect. This change future-proofs our code so we won't make
duplicate copies of the headers if net/http does it automatically in the
future.

On redirect, only copy headers when they don't already exist in the redirected request

---

contrib/ceph/ci-setup.sh

It looks like the `apt-get` process of ceph installation can time out after 300s without killing the process which holds a lock.

Attempt to unblock the ceph build process

---

reference/reference.go
reference/regexp.go
reference/regexp_test.go

This allows hostnames to contain uppercase characters, matching behavior
in Docker versions before 1.10. It does not attempt to canonicalize
hostnames into a lowercase format before parsing, since this could lead
to corner cases (for example, making `Hostname.Domain.Com/ref` ambiguous
on a daemon which contains references for both `hostname.domain.com/ref`
and `Hostname.Domain.Com/ref`).
Fixes: #1433

Allow uppercase characters in hostnames

---

docs/notifications.md
notifications/bridge.go
notifications/bridge_test.go
notifications/listener.go
notifications/listener_test.go

Send manifest and blob delete events to the notifications subsystem.
Closes #1396 

Send manifest and blob delete events to the notifications subsystem.

---

registry/storage/driver/s3/s3.go

Treats nil parameters the same as unprovided parameters (fixes issues
where certain parameters are printed to "<nil>").
Accepts "true" and "false" string values for boolean parameters.
Fixes parsing issue found in #1199

Improves flexibility of configuration handling for S3 driver

---

docs/insecure.md

Certificate was create with different path on the examples.

Change certificate hypothetic path

---

configuration/configuration.go
docs/configuration.md
manifest/schema1/manifest.go
registry/handlers/app.go
registry/storage/manifeststore_test.go
registry/storage/registry.go
registry/storage/signedmanifesthandler.go

Add option for specifying trust key for signing schema1 manifests.
Since schema1 signature key identifiers are not verified anywhere and deprecated, storing signatures is no longer a requirement.
Furthermore in schema2 there is no signature, requiring the registry to already add signatures to generated schema1 manifests.
Remaining items if design approved:

Add option to disable signatures

---

registry/handlers/api_test.go
registry/handlers/images.go

When schema2 manifests are rewritten as schema1 currently the etag and docker content digest header keep the value for the schema2 manifest.
Fixes #1444

Fix schema1 manifest etag and docker content digest header

---

registry/client/auth/session.go

Making this an exported error value will allow users of the
registry/client/auth module to have consistent behavior between
authentication failures and cases where no credentials are provided.

Export "no basic auth credentials" as an error value

---

registry/storage/driver/s3-aws/s3_test.go

Fixes bug in TestStorageClass for s3aws driver where the "standard" file
was checked for reduced-redundnancy storage.

[driver/s3aws] Fix TestStorageClass

---

registry/storage/driver/storagedriver.go

May be my English is bad and I did not understand ( actually I read twice :smile:  ), but a test case
https://github.com/docker/distribution/blob/master/registry/storage/driver/testsuites/testsuites.go#L439
does not meet the requirement that offset must be less than size.

Fix description of StorageDriver.WriteStream

---

registry/proxy/proxyauth.go
registry/proxy/proxyblobstore.go
registry/proxy/proxyblobstore_test.go
registry/proxy/proxymanifeststore.go
registry/proxy/proxymanifeststore_test.go
registry/proxy/proxyregistry.go
registry/proxy/proxytagservice.go
registry/proxy/proxytagservice_test.go

To avoid any network use unless necessary, delay establishing authorization 
challenges with the upstream until any proxied data is found not to be local.
Implement auth challenges behind an interface and add to unit tests.  Also,
remove a non-sensical unit test.
Closes #1435

Lazily evaluate auth challenges

---

registry/client/repository.go
registry/proxy/proxyblobstore.go
registry/proxy/proxyblobstore_test.go

Ensure Accept headers are sent with TagService.Get (which hits manifest
endpoints).  Add support for remote Get and Put for the proxied blobstore.
Implement todo after #1466 

Enable proxying registries to downgrade fetched manifests to Schema 1.

---

CONTRIBUTING.md
docs/apache.md
docs/spec/api.md
docs/spec/api.md.tmpl
registry/auth/token/token_test.go
registry/client/transport/http_reader.go
registry/proxy/proxymanifeststore_test.go
registry/proxy/scheduler/scheduler_test.go
registry/storage/driver/testsuites/testsuites.go
registry/storage/walk_test.go

All of them were found and fixed by codespell.
Signed-off-by: Stefan Weil <sw@weilnetz.de>

Fix some typos in comments and strings

---

Makefile

While it is generally good practice to look before jumping, many
developers enjoy running `make` without reading the Makefile and
indiscriminately use `git add -A`. This behavior, coupled with
generating AUTHORS in the default target result in garbage in various
PRs and extra round trips to remove said garbage.

Makefile: remove AUTHORS from default target

---

errors.go
registry/handlers/blobupload.go
registry/handlers/images.go

Middleware code may return error targeted for client application with
specified HTTP code (e.g. 403 Forbidden). Error handler should respect
it.

Respect errors returned from middleware code

---

registry/handlers/blobupload.go

Let the blobWriter know the size of uploaded blob when comitting to a blob
store. Size may be used by middleware wrappers to check quota limits and refuse
oversized blobs.

Commit uploaded blob with size

---

docs/spec/api.md
docs/spec/api.md.tmpl
registry/api/v2/descriptors.go

Bring the spec up to date for schema2 changes.

Add information about manifest content types to API spec

---

registry/client/auth/session.go
registry/client/auth/session_test.go
registry/proxy/proxyauth.go

Extends credentialstore interface to support oauth token servers.
Implements the behavior defined in #1418

Add oauth support to registry client auth

---

docs/building.md

the original ```$GOPATH/bin/registry $GOPATH/src/github.com/docker/distribution/cmd/registry/config-example.yml``` leads to the error like 
```
Error: unknown command "/Users/EricYang/go/src/github.com/docker/distribution/cmd/registry/config-example.yml" for "registry"
Run 'registry --help' for usage.
```
I think the correct command should be ```registry serve```

command correction in documentation

---

registry/client/auth/session.go

Ensures that any generate offline token can be linked back to a client ID.
ping @tonyhb

Add client ID to token fetch to GET endpoint

---

docs/configuration.md
docs/storage-drivers/s3.md
registry/storage/driver/s3-aws/s3.go
registry/storage/driver/s3-aws/s3_test.go

Main purpose of this PR is to enhance the support to provide custom endpoint url which can be used to connect to other S3 compatibly storage services like [Minio](https://github.com/minio/minio).
I also want to know if there is any reason preventing from adding the extra condition to create a bucket if it doesn't exist similar to https://github.com/docker/distribution/blob/master/registry/storage/driver/azure/azure.go#L87

Added support to specifiy custom endpoint

---

registry/client/auth/authchallenge.go
registry/client/auth/authchallenge_test.go
registry/client/auth/session.go
registry/handlers/blobupload.go
registry/proxy/proxyregistry.go

It is possible for a middlebox to lowercase the URL at somepoint causing a
lookup in the auth challenges table to fail.  Lowercase hostname before
using as keys to challenge map.
@dmcgowan 
closes #1492

URL parse auth endpoints to normalize hostname to lowercase.

---

registry/storage/driver/azure/azure.go

Change c03b5fc5ee9e4364cc216c712ab8a53daf3b1273 vendored a newer version of the Azure storage API which uses different error structures.  Missing blob errors were not being caught correctly.
Ran unit tests in short mode with a 'free' Azure account.

 Update missing blob error checking with latest Azure API

---

registry/client/errors.go
registry/client/errors_test.go

If this slice ends up empty after parsing the HTTP response body, it
means the body is not well-formed. We've probably encountered an error
message produced by something that uses a different JSON schema, or
an error that just happens to validate as JSON.
An empty errcode.Errors slice is not a very useful thing to return,
since its Error() output is just `<nil>`. Detect this case, and instend
return an UnexpectedHTTPResponseError.
Also, fix `UnexpectedHTTPStatusError` and
`UnexpectedHTTPResponseError` to use lowercase characters at the
beginning of their `Error` output.

Don't return empty errcode.Errors slices

---

registry/client/auth/session.go

/cc @aaronlehmann - this is one of the many errors, in my opinion, for which we do not have to retry in docker
This is related to https://github.com/docker/docker/pull/21283#issuecomment-198120408 and followup comments.
Basically, in Docker we keep retrying in those cases where it would be more appropriate to give up because the token service is clearly misconfigured if it returns StautsOK w/o meaningful information. This PR will provide strong error types to Docker to compare with.

registry: client: auth: type errors

---

docs/spec/manifest-v2-2.md
manifest/manifestlist/manifestlist.go

These are needed to differentiate incompatible Windows versions. In the short run, Windows will need os, osvariant, and osversion matching. Eventually we should be able to avoid matching on osvariant.
cc/@aaronlehmann

Add osversion and osvariant to platform specification

---

docs/notifications.md
notifications/bridge.go
notifications/bridge_test.go
notifications/event.go
notifications/listener.go
notifications/listener_test.go
registry.go
registry/client/repository.go
registry/client/repository_test.go
registry/handlers/images.go

Add events for tag, untag and remove tag. 
Update examples in notifications.md.
Closes #1280    

Send tag events to notification listeners

---

docs/spec/api.md
docs/spec/api.md.tmpl

Fix grammatical and formatting issues.
Add links to sections or other documents where appropriate.
Signed-off-by: Jon Johnson <jonjohnson@google.com>

Fix typos in docs/spec/api.md

---

docs/configuration.md

HTML links are not converted by HUGO, so will work on GitHub, but not in the online documentation.
Converted the HTML table (and links) to Markdown to fix broken links.
Also added a header for the table, because none was present.

Fix broken links in configuration

---

registry/garbagecollect.go
registry/garbagecollect_test.go

This ensures that the GC command uses the same logging format as specified in the registry's YAML config.

Utulize config log format within gc

---

docs/deploying.md

I was setting up a v2 registry and it took me much time to get the information that the 'Docker-Distribution-Api-Version' header must be set. I added a heading to the readme to drive more attention to this segment.

added heading to get more focus into the headers that need to be set

---

version/version.go

Now that we've tagged a release candidate, we can now say all builds are
"2.4.0+unknown" if the makefile is not used.

Rev base version to 2.4.0

---

registry/storage/driver/factory/factory.go
registry/storage/driver/storagedriver.go

This commit adds context-specific documentation on StorageDriver,
StorageDriverFactory, and the factory’s Register func, explaining how
the internal registration mechanism should be used.
This documentation follows from the thread starting at
https://github.com/deis/builder/pull/262/files#r56720200.
cc/ @stevvooe

Add documentation for how to register new StorageDrivers

---

registry/garbagecollect.go

- Clean up error messages
- Add a missing error check on the result of blobService.Enumerate.

garbagecollect: Clean up errors

---

docs/gc.md
registry/garbagecollect.go
registry/garbagecollect_test.go
registry/storage/manifeststore.go

Fix signature handling with GC.
If a schema 1 manifest is uploaded with the `disablesignaturestore` option set
to true, then no signatures will exist.  Handle this case.
If a schema 1 manifest is pushed, deleted, garbage collected and pushed again, the
repository will contain signature links from the first version, but the blobs will
not exist.  Disable the signature store in the garbage-collect command so
signatures are not fetched.
Also, add a dry-run mode.

Fix signature handling with GC.

---

registry/storage/driver/swift/swift.go

In 326c3a9c49486f4c5dbb16508f08b6b766bd4852, which was only intended to be a refactoring commit, the behavior of this block subtly changed so that unknown types of errors would be swallowed instead of propagated.
I noticed this while investigating an error similar to #1539 aka docker/docker#21290. It appears that during GetContent() for a hashstate, the Swift proxy produces an unexpected error. Since this error was silently swallowed, an empty []byte is used to restart the hash, then producing the digest of the empty string instead of the layer's digest.
This PR will not fix the issue, but it should make the actual error more visible by propagating it into `blobWriter#resumeDigest' and 'blobWriter#validateBlob', respectively.
/cc @lebauce

don't swallow errors in Swift driver's GetContent()

---

docs/spec/auth/index.md
docs/spec/auth/oauth.md
docs/spec/auth/scope.md
docs/spec/auth/token.md

Currently the token server uses a single short lived token which can only be fetched using basic auth credentials. This not only forces clients to save credentials but also makes properly scoping authorization requests difficult (basic auth credentials could be used for any account resource associated with the credentials, even those not in the domain of the authorization server). OAuth is standard practice for providing the necessary security scopes as well as limited credential leaking to clients. This initial version will still require sending credentials to the client but leaves the specification open for completely bypassing having to directly send credentials from the client using the OAuth authorization code grants.
This only PR only expands the specification and is intended to …

Add specification for using OAuth with the token server

---

docs/building.md

Now that we are using "native" Go vendoring, there is no need to
manipulate GOPATH.
Fixes #1586

docs: No need to change GOPATH to use vendored code

---

Makefile

Using $GOPATH/bin/godep or $GOPATH/bin/golint is problematic because
$GOPATH can contain multiple colon-separated paths.
We should just run these like normal binaries. The user should make sure
their $PATH contains $GOPATH/bin, if necessary. This is part of normal
Go setup.

Makefile: don't look for golint and godep in specific places

---

docs/spec/manifest-v2-2.md

Add link to the official list of $GOOS and $GOARCH values and correct
values that were incorrectly listed in the spec examples.
Docker-DCO-1.1-Signed-off-by: Phil Estes <estesp@linux.vnet.ibm.com>

Correct examples and architecture references in v2.2 spec

---

registry/handlers/helpers.go

If there are errors copying the request body into the temporary upload file within `copyFullPayload` we currently assume that the client disconnected and there were no distribution errors.
This change logs any io errors, bytes copied and content length for easier debugging with backends like our favourite NFS.

Ensure we log io.Copy errors and bytes copied/total in uploads

---

registry/storage/driver/s3-aws/s3.go

The current S3 implementation was expanded in #1512 to allow specifying a custom endpoint. Currently, this only allows talking to a custom S3 implementation with one of a few hardcoded regions.
This PR skips the check to validate the region if a custom S3 endpoint is provided, so that custom regions can be used as well.

Only check validity of S3 region if not using custom endpoint

---

manifest/schema2/builder.go
manifest/schema2/builder_test.go

The schema2 manifest builder fills in this part of the manifest based on
the descriptor it gets back from `BlobIngester`'s `Put` method. It passes
the correct media type to `Put`, but `Put` ends up replacing this value with
`application/octet-stream` in its return value.
This commit works around the issue in the manifest builder. Arguably `Put`
should not be changing the media type in its return value, but this
commit is a targeted fix to keep it very low-risk for possible inclusion
in Docker 1.11.
Fixes #1621 (but maybe we should open a separate issue for the media
type behavior in the distribution client, and the unnecessary stat).

Use correct media type for config blob in schema2 manifest

---

registry/storage/blobwriter.go

`blobWriter` has to close blob after commit.

Add blobWrtiter.Close() call into blobWriter.Commit()

---

registry/storage/driver/s3-aws/s3.go

Signed-off-by: jhaohai <jhaohai@foxmail.com>
Add cn-north-1 to the valid check because the aws driver supports this region in fact.
closes #1649

Add cn-north-1 to valid check

---

registry/garbagecollect.go

I believe it should be "except" instead of "expect".
Signed-off-by: Serge Dubrouski <sergeyfd@gmail.com>

Fix wording for dry-run flag in usage message for garbage collector.

---

docs/configuration.md
registry/storage/driver/middleware/redirect/middleware.go
registry/storage/driver/middleware/redirect/middleware_test.go

Adding a new middleware storage driver to customize the redirect url for retrieving layers as suggested in #1628. This middleware driver can be used in conjunction with the S3 storage driver. This redirect driver will allow you to set the redirect hostname for retrieving layers which can be useful for directing requests to your own cache proxy to front S3 storage.
The config file will then accept an entry for specifying the proxy hostname to override with:
```
middleware:
storage:
- name: redirect
disabled: false
options:
baseurl: http://example.com:8080
```
Signed-off-by: Andrew Hsu <andrewhsu@acm.org> (github: andrewhsu)
Signed-off-by: Alvin Feng <alvin4feng@yahoo.co> (github: alvinfeng)

add middleware storage driver for redirect

---

contrib/docker-integration/run_multiversion.sh

It would be great to define which docker versions to test against somewhere else, but currently this list will need to be manually updated. Test against 1.11.1 to find issues with the official docker release.

Use official docker 1.11.1 image to test docker 1.11

---

registry/storage/blob_test.go
registry/storage/blobwriter.go

When a blob upload is committed prevent writing out hashstate in the 
subsequent close.
When a blob upload is cancelled close the blobwriter before removing
upload state to ensure old hashstates don't persist.

Clean uploads

---

registry/storage/driver/swift/swift.go

Not just when `Commit()`ing the result. This fixes some errors I observed when the layer (i.e. the DLO) is `Stat()`ted immediately after closing, and reports the wrong file size because the container listing is not yet up-to-date (usually recognized by the error message "digest invalid: provided digest did not match uploaded content").
Related to #1013 and maybe to #1539 aka docker/docker#21290.

[Swift] wait for DLO segments to show up when Close()ing the writer

---

registry/api/errcode/register.go
registry/client/errors.go

ping @aaronlehmann 
This patch adds an error type to be later checked also in docker/docker if the registry
is replying with 429.

registry: type too many requests error

---

registry/api/errcode/register.go
registry/client/errors.go

go1.5 doesn't export http.StatusTooManyRequests while
go1.6 does. Fix this by hardcoding the status code for now.
ping @aaronlehmann @cpuguy83 @icecrime - we probably could update go to 1.6 but....

registry: do not use http.StatusTooManyRequests

---

docs/configuration.md
docs/storage-drivers/filesystem.md
registry/proxy/proxyblobstore_test.go
registry/storage/driver/base/regulator.go
registry/storage/driver/filesystem/driver.go
registry/storage/driver/filesystem/driver_test.go

This is a rebased and squashed version of #1674.
The previous PR was as follows:
----
This PR adds a regulator wrapper around the Filesystem driver.
The regulator ensures that there is an upper bound on the number
of concurrent blocking filesystem operations which spawn new
threads.
By default maxthreads is set to 100. This means the FS driver is
limited to 100 concurrent blocking file operations. Any subsequent
operations will block in Go until previous filesystem operations
complete.
This ensures that the registry can never open thousands of simultaneous
threads from os filesystem operations.
Note that maxthreads can never be less than 25.
PS: Thanks @jlhawn for the regulator implementation.

Add regulator to filesystem

---

Dockerfile

Use Alpine Linux as the parent image for the registry.

---

docs/nginx.md

Customer reported the following issue:
```
I wasn't sure which email to direct this to so if this is the incorrect place to report this please let me know. I notice a slight typo in one of the guides on https://docs.docker.com/registry/nginx/ .
In the final step the guide lists the command
docker login -p=testuser -u=testpassword -e=root@example.ch myregistrydomain.com:5043
The -p and -u flags are backwards, it should be
docker login -u=testuser -p=testpassword -e=root@example.ch myregistrydomain.com:5043
```

Fixing nginx flag issue identified by customer

---

registry/storage/driver/gcs/gcs.go

@RichardScothern This is a quick patch for #1698. Note that this PR targets the release/2.4 branch instead of master. I am not sure this is the right way of submitting a "hot fix" to a release.
@aaronlehmann The cause of the problem is that the registry calls the FileWriter.Size function of the GCS driver before closing the FileWriter. The Size function of the GCS driver used to report the number of bytes that were correctly saved to cloud storage. This excludes any bytes that are buffered in memory. The registry seems to expect that the Size function returns the size including the buffered bytes, regardless of whether these bytes will ever make it to the backing storage (the future Close call may occasionally fail).
In my opinion Size should report only the bytes that are guaranteed to …

GCS: FileWriter.Size: include number of buffered bytes if the FileWriter is not closed

---

registry/storage/driver/gcs/gcs.go

@RichardScothern @manuelmazzuola

GCS: FileWriter.Size: return offset + buffer size for Writers that are not closed

---

docs/spec/auth/scope.md

This removes the restriction that the resource name cannot support hostnames.

Hostnames can be optionally supported by the auth spec scope grammar

---

blobs.go
docs/spec/manifest-v2-2.md
manifest/schema2/manifest.go
registry/proxy/proxytagservice_test.go
registry/storage/blob_test.go
registry/storage/cache/cachecheck/suite.go
registry/storage/schema2manifesthandler.go
registry/storage/schema2manifesthandler_test.go

This will be used to support downloading Windows base layers from Microsoft URLs.
You can see this change in full context at jstarks/docker@27b81d4484c5f7e5a80f79fbcda5068587817c38.
cc @aaronlehmann

Add support for layers from foreign sources

---

configuration/configuration.go

Correct yaml key names in configuration

---

registry/handlers/app.go

This lets us access registry config within middleware for additional
configuration of whatever it is that you're overriding.
Currently needed for overriding the metadata service within repository middleware: the metadata service needs to see whether deletes are enabled, whether it's a cache, the signing key for v1 compat etc.

Pass in `app` as context to apply{N}Middleware

---

vendor/github.com/ncw/swift/swift.go

Handle rare case when ceph doesn't return Last-Modified for HEAD requests in case DLO manifest doesn't have any segments
Signed-off-by: Gleb Schukin <gs1983@gmail.com>

Handle responce from ceph correctly if no Last-Modifed header specified 

---

registry/handlers/app.go
registry/handlers/blobupload.go
registry/handlers/images.go
registry/handlers/tags.go

This addresses the "That's an easy fix, though" part of #1682.
With this change, a repository middleware can return a [`errcode.Error`](https://godoc.org/github.com/docker/distribution/registry/api/errcode#Error) which will be shown to the user when interacting with `docker`.

Pass through known errors

---

docs/compatibility.md
docs/deprecated.md
docs/garbage-collection.md
docs/index.md
docs/insecure.md

I've added the pages to the top level registry menu, but it feels to me like the gc and test-insecure pages should go into the reference and recipes menus (respectively)
@RichardScothern ?

Add topics to the menu

---

configuration/configuration.go

When I am trying to write a customized access controller, I found this comment does not make any sense, I guess it was copied from the storage part most probably.

Fix incorrect comment about auth type

---

registry/handlers/api_test.go
registry/handlers/images.go

In Go's header parsing, the same header multiple times results in multiple entries in the `r.Header[...]` slice, but Go does no further parsing beyond that (and in https://golang.org/cl/4528086 it was determined that until/unless the stdlib itself needs it, Go will not do so).
The consequence here for parsing of `Accept:` headers is that we support the way Go outputs headers, but not all language HTTP libraries have a facility to output multiple headers instead of a single list header.
This change ensures that the following (valid) header blocks all parse to the same result for the purposes of what is being tested here:
```
Accept: a/b
Accept: b/c
Accept: d/e
```
```
Accept: a/b; q=0.5, b/c
Accept: d/e
```
```
Accept: a/b; q=0.1, b/c; q=0.2, d/e; q=0.8
```
This was discussed briefly in …

Update "Accept" header parsing for list values

---

registry/handlers/api_test.go
registry/handlers/app_test.go
registry/handlers/blobupload.go
registry/storage/blob_test.go
registry/storage/blobwriter.go
registry/storage/driver/gcs/gcs.go
registry/storage/driver/testdriver/testdriver.go

@RichardScothern @aaronlehmann This is a patch for #1698 as alternative to #1703 . In contrast to #1703 this PR attempts to fix the root cause (ie a call of Size on an upload that is not (fully) flushed to the backing storage.
The first commit changes the tests so they fail when Size is called on a "dirty" writer. The second commit ensures that Size is not called before Close when committing an upload. The third commit addresses the case where Cancel is called after closing an upload. The Cancel operation used to fail in that case.

Blobwriter: call BlobWriter.Size after BlobWriter.Close

---

registry/handlers/blobupload.go
registry/storage/blobwriter.go
registry/storage/blobwriter_nonresumable.go

If resumable digest support is disabled, detect this when closing the blobwriter and allow the close to continue.  Also update the name of the function.
closes #1717 

Re-add support for non-resumable digests

---

Godeps/Godeps.json
docs/storage-drivers/swift.md
registry/storage/driver/swift/swift.go
registry/storage/driver/swift/swift_test.go
vendor/github.com/ncw/swift/.travis.yml
vendor/github.com/ncw/swift/README.md
vendor/github.com/ncw/swift/auth.go
vendor/github.com/ncw/swift/auth_v3.go
vendor/github.com/ncw/swift/swift.go

This PR allows setting a non-standard endpoint type to be used when connecting to swift (`Internal` or `Admin` instead of the default `Public`). To enable this change the version of the vendored ncw/swift library also had to be updated.
I have added docs for the new configuration entry and also fixed some weirdness in swift docs where the table containing configuration parameters was duplicated.

[Swift] Expose EndpointType parameter in driver

---

registry/client/repository.go
registry/client/repository_test.go

This returns all tags even when the registry forces pagination.

Changes the client Tags All() method to follow links

---

manifest/schema2/builder.go

Closes #1771
When a manifest configuration blob already exists, the media type will be set to `application/octet-stream` by the registry, causing the manifest to be re-pushed under a different digest.

Override media type returned from Stat for existing manifests.

---

registry/handlers/blobupload.go
registry/storage/blobstore.go

Today I came across the following log message in our distribution servers:
`time="2016-07-01T13:18:37Z" level=error msg="unknown error completing upload: driver.Error{DriverName:\"swift\", Enclosed:(*errors.errorString)(0xc82029a2d0)}" go.version=...`
As you can see the `Enclosed` part is not really useful in an error message as we cannot see the original error string. This happens due to the original error being formatted with `%#v`. This pull request changes two occurrences I found of errors being formatted with `%#v` to `%v`. The latter will correctly output the string returned by `Error()`.

Avoid formatting errors with %#v

---

registry/storage/schema2manifesthandler.go
registry/storage/schema2manifesthandler_test.go

The existing code effectively ignored errors from all but the last of a
foreign layer's URLs.
Signed-off-by: Noah Treuhaft <noah.treuhaft@docker.com>

Properly validate multi-URL foreign layers

---

notifications/endpoint.go
notifications/http.go
notifications/http_test.go

The EndpointConfig struct in the notifications package has some config
fields for a notification endpoint. This commit adds the ability to pass
in an *http.Transport to use when notifying that endpoint of an event.
This is especially useful for endpoints that use self-signed CAs.

Add transport field to notifications endpoint config

---

registry/client/auth/session.go
registry/client/auth/session_test.go

Allows using v2 for v1 endpoints.
The primary use case being for search which does not have a v2 specification.
Added a user scope for allowing v2 search

Add support for using v2 ping challenges for v1

---

registry/handlers/catalog.go
registry/storage/catalog.go
registry/storage/catalog_test.go

This fixes errors other than io.EOF from being dropped when a storage driver
lists repositories. For example, filesystem driver may point to a missing
directory and errors, which then gets subsequently dropped.
Signed-off-by: Edgar Lee <edgar.lee@docker.com>

Fix storage drivers dropping non EOF errors when listing repositories

---

context/http.go

closes #1843 
tested with go 1.7-rc2

Fix vet errors with go 1.7

---

registry/storage/driver/swift/swift.go

This is similar to waitForSegmentsToShowUp (cf. #1650) which is called during Close/Commit. Intuitively, you wouldn't expect missing segments to be a problem during read operations, since the previous Close/Commit confirmed that all segments are there.
But due to the distributed nature of Swift, the read request could be hitting a different storage node of the Swift cluster, where the segments are still missing.
Load tests on my team's staging Swift cluster have shown this to occur about once every 100-200 layer uploads when the Swift proxies are under high load. The retry logic, borrowed from waitForSegmentsToShowUp, allows the Registry to skip past this temporary inconsistency.
Tip: View the diff with [`?w=1`](https://github.com/docker/distribution/pull/1710/files?w=1).

[Swift] add simple heuristic to detect incomplete DLOs during read ops

---

registry/auth/token/token.go
registry/auth/token/token_test.go

Adds a constant leeway (60 seconds) to the nbf claim check to account
for clock skew between the registry servers and the authentication
server that generated the JWT.
The leeway of 60 seconds is a bit arbitrary but it was based on
hub.docker.com logs/metrics where we don't see drifts of more than a
second on our servers running ntpd (happy to lower or increase if necessary).
I didn't attempt to make the leeway configurable as it would add extra
complexity to the PR and I am not sure how Distribution prefer to
handle runtime flags like that.
Also, I am simplifying the exp and nbf check for readability as the
previous `NOT (A AND B)` with cmp operators was not very friendly.
Ref:
https://tools.ietf.org/html/rfc7519#section-4.1.5
cc @jlhawn as he reported the same error.
Signed-off-by: …

Add leeway to JWT nbf checking

---

blobs.go
registry/client/repository.go
registry/storage/linkedblobstore.go
registry/storage/linkedblobstore_test.go

In OpenShift, there's a `pullthroughBlobStore` middleware wrapper that acts like a proxy. It allows to pull blobs from remote registries based on per-repository configuration stored in etcd.
We definitely want to utilize the cross-repository mount functionality where the blob existing in other repository (in this case a remote registry) is mounted/linked into the target one if the client knows about it.
With this mount functionality working for the remote blobs, the registry won't store them on local storage. Which is what we aim for.
This PR allows to pass repository middleware wrapper to the `Create()` method of `linkedBlobsStore()` as an option. The method then calls it in order to `Stat()` the blob in the source repository.
Maybe there's a less intrusive way to achieve the same, …

Allow to use repo middleware wrapper during cross-repo mounts

---

configuration/configuration.go
docs/configuration.md
registry/handlers/app.go
registry/storage/garbagecollect_test.go
registry/storage/registry.go
registry/storage/schema2manifesthandler.go
registry/storage/schema2manifesthandler_test.go

Until we have some experience hosting foreign layer manifests, the Hub
operators wish to limit foreign layers on Hub to those hosted by
Microsoft. To that end, this change adds a registry configuration option
to whitelist hosts that may appear in foreign layer URLs of pushed
manifests, and it modifies manifest validation to reject pushes
containing foreign layer URLs whose host is not whitelisted.
Signed-off-by: Noah Treuhaft <noah.treuhaft@docker.com>

Add a foreign layer URL host whitelist

---

registry/storage/registry.go
registry/storage/schema2manifesthandler.go

Pass the manifestURL directly into the schema2 manifest handler instead of
accessing through the repository as the reference has since become an
interface.
cc @nwt 

Fix the build.

---

Dockerfile

Running `apk add` before copying source into the image takes better
adavantage of layer caching when developing and regularly building the
image. This avoids source code changes invalidating the `apk add` layer
and causing that step to run on every image build.
Signed-off-by: Adam Duke <adam.v.duke@gmail.com>

reorder Dockerfile steps for better layer caching

---

docs/storage-drivers/s3.md
registry/storage/driver/s3-aws/s3.go
registry/storage/driver/s3-aws/s3_test.go

Adds `objectAcl` as a new option for the S3 storage backend to allow registry operators to specify a canned object ACL for each object stored in S3. 
This solves the issue where a registry in AWS Account A is set to use an S3 bucket owned by AWS Account B. By default, all objects are set to `private`, which means that Account B cannot view or modify the uploaded files in their own bucket. If the object ACL option is set to `bucket-owner-full-control` on the registry, then there would be no problem.
closes #1865 
closes #1730

Add 'objectAcl' Option to the S3 Storage Backend

---

blobs.go
registry/storage/linkedblobstore.go
registry/storage/linkedblobstore_test.go

In OpenShift, there's a pullthroughBlobStore middleware wrapper that acts like a proxy. It allows to pull blobs from remote registries based on per-repository configuration stored in etcd.
During a cross-repo mount, the [linkedBlobStore](https://github.com/docker/distribution/blob/master/registry/storage/linkedblobstore.go#L288) stats requested blob in the source repository. The repository object used for it doesn't have middleware wrappers, therefore it's impossible to override this behaviour.
With the [CreateOptions](https://github.com/docker/distribution/blob/master/blobs.go#L197) exposed we are able to intercept the request and handle it in custom way. However, we still need to create the layer link for a successful mount. Sadly, this operation is private.
It's true we could handle …

Provide stat descriptor for Create method during cross-repo mount

---

registry/proxy/proxyblobstore.go

if registry was deployed as a pull through cache ,function copeContent() may cause a socket leak when docker user canceled its pull operation.
use `netstat -tnp` command ,you will see output like this below, registry`s socket recv_q blocked with data
```
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0 1754584 127.0.0.1:3128          127.0.0.1:34097         ESTABLISHED 10/ssh
tcp        0 1757960 127.0.0.1:3128          127.0.0.1:34124         ESTABLISHED 10/ssh
tcp   971464      0 127.0.0.1:34097         127.0.0.1:3128          ESTABLISHED 11/registry
tcp        0      0 192.168.0.2:45885       166.111.206.63:80       TIME_WAIT   -
tcp   990992      0 127.0.0.1:34156         127.0.0.1:3128          ESTABLISHED 11/registry
tcp …
```

function copyContent() cause socket leak.

---

registry/storage/catalog.go
registry/storage/catalog_test.go

Previous component-wise path comparison is recursive and generates a
large amount of garbage. This more efficient version simply replaces the
path comparison with the zero-value to sort before everything. The
comparison is then down with this new value, using the regular string
comparison.
Direction of the comparison is also reversed to match Go style.

registry/storage: more efficient path compare in catalog

---

registry/storage/driver/testsuites/testsuites.go
registry/storage/filereader_test.go
testutil/tarfile.go

Use the much faster math/rand.Read function where cryptographic
guarantees are not required. The unit test suite should speed up a
little bit but we've already optimized around this, so it may not
matter.

testutil, storage: use math/rand.Read where possible

---

docs/storage-drivers/swift.md
registry/storage/driver/swift/swift.go
registry/storage/driver/swift/swift_test.go

This is already supported by [ncw/swift](https://github.com/ncw/swift), so we just need to pass the parameters from the storage driver to the backend.

[swift] support different user-domain and tenant-domain

---

configuration/configuration.go
configuration/configuration_test.go
docs/configuration.md
registry/registry.go
registry/registry_test.go

Signed-off-by: Adam Duke <adam.v.duke@gmail.com>
I couldn't really find much related to http2 in open/closed issues/PRs or on the mailing list. As far as I know, http2 is natively supported as of go 1.6. It's not clear if the protocol is restricted to http/1.1 for a reason.

Allow registry clients to connect via http2

---

docs/configuration.md
docs/storage-drivers/s3.md
registry/storage/driver/s3-aws/s3.go
registry/storage/driver/s3-aws/s3_test.go

This change to the S3 Move method uses S3's multipart upload API to copy
objects whose size exceeds a threshold.  Parts are copied concurrently.
The level of concurrency, part size, and threshold are all configurable
with reasonable defaults.
Using the multipart upload API has two benefits.
* The S3 Move method can now handle objects over 5 GB
closes #886.
* Moving most objects, and espectially large ones, is faster.  For
example, moving a 1 GB object averaged 30 seconds but now averages 10.
Signed-off-by: Noah Treuhaft <noah.treuhaft@docker.com>

Use multipart upload API in S3 Move method

---

registry/storage/driver/swift/swift.go
registry/storage/driver/swift/swift_test.go

The current implementation attempts to delete all objects provided at once. Swift servers are configured with a max_deletes_per_request, and if the number of objects exceeds that then it returns a 413 and errors.
Use the limit provided by Swift and delete in chunks of that size.
Resolves docker/distribution#1914

Swift driver now bulk deletes in chunks specified by the server

---

registry/client/repository.go
registry/client/repository_test.go

re-issuing requests as GET for proper error details.
Fixes #1911.

tag service: properly handle error responses on HEAD requests by

---

registry/client/auth/authchallenge.go
registry/client/auth/authchallenge_test.go

Signed-off-by: spacexnice <yaoyao.xyy@alibaba-inc.com>
go1.6`s  map does not support cocurrent read and write , which will cause fatal error: concurrent map read and map write and panic , then the whole registry was shutdown.
this can be reproduce by the unitest case which i commited.
```
fatal error: concurrent map read and map write
goroutine 8 [running]:
runtime.throw(0x4e6e80, 0x21)
/usr/local/go/src/runtime/panic.go:547 +0x90 fp=0xc820026580 sp=0xc820026568
runtime.mapaccess1_faststr(0x353fc0, 0xc8201951d0, 0xc820221300, 0x1a, 0xc820294088)
/usr/local/go/src/runtime/hashmap_fast.go:202 +0x5b fp=0xc8200265e0 sp=0xc820026580
github.com/spacexnice/distribution/registry/client/auth.(*simpleChallengeManager).GetChallenges(0xc820028378, 0xc820220760, 0x4, 0x0, 0x0, 0x0, 0xc82026c440, 0xf, …
```

fix simpleAuthChallge concurrent problem

---

docs/spec/manifest-v2-2.md

Previously, the specificiation incorrectly bound the fates of `urls` and
foreign layers. These are complementary but unrelated features, in that
the `urls` field may be populated for layers that aren't foreign. The
type of the layer only dictates the push behavior of the layer, rather
than involving where it came from.
For example, one may pull a foreign layer from a registry, but they may
not push it back to another registry. Conversely, a layer that has no
restrictions on push/pull behavior may be fetched via `urls` entries.
Closes #1931

spec/manifest: clarify relationship between urls and foreign layers

---

registry/auth/htpasswd/access.go

To parse the latest account list dynamically instead of restarting the distribution service frequently.
Signed-off-by: CUI Wei <ghostplant@qq.com>

Dynamically Parsing the Latest HTPassword File

---

circle.yml
registry/handlers/api_test.go
registry/handlers/app_test.go
registry/handlers/health_test.go
registry/proxy/proxyblobstore_test.go
registry/proxy/scheduler/scheduler.go
registry/proxy/scheduler/scheduler_test.go
registry/storage/cache/memory/memory.go

With go 1.6, concurrent read/write map access can cause a panic, we need the race detector to help prevent against this condition arising.

Re-enable race detector in circleci

---

docs/configuration.md

Let's Encrypt uses tls-sni to validate the certificate on the standard https port 443. If the registry is outwardly listening on a different port Let's Encrypt will not issue a certificate.

Add note about required let's encrypt port

---

manifest/schema2/manifest.go

`application/vnd.docker.plugins.v1.2+json` is already used in the engine. the only difference with this one was `s`. It's confusing.
Let's add `.distribution` to make it clear it's used in distribution.

update plugin MediaType

---

registry/auth/token/token.go

The token auth package logs JWT validation and verification failures at
the `error` level.  But from the server's perspective, these aren't
errors.  They're the expected response to bad input.  Logging them at
the `info` level better reflects that distinction.
The motivation here is increasing SNR at the `error` level for registry operators.

Downgrade token auth JWT logging from error to info

---

registry/handlers/hmac.go

handlers: provide better log message on mismatched secret

---

reference/reference.go
reference/reference_test.go

Use the same error message as is used in [docker/reference/reference.go](https://github.com/docker/docker/blob/9ba5e0fa725e3ffa592473283d9a52213dc09638/reference/reference.go#L195) to provide slightly more information about the error.
Relates to https://github.com/docker/docker/issues/25599
ping @dmcgowan ptal

Improve "invalid reference" error message

---

notifications/listener.go

options parameter gets lost in the manifestServiceListener.Get. That causes issues for proxyManifestStore,Get which needs options to pass down to client.
Signed-off-by: Serge Dubrouski <sergeyfd@gmail.com>

manifestServiceListener.Get to pass down options parameter

---

registry/proxy/proxyregistry.go

In file proxyregistry.go ```remoteURL``` parameter error cause ```challenge map cache ``` not working,critical area consume to much time, which eventually lead to client manifest request timeout(90s) in massive(which i test 80 concurrent) concurrent manifest request situation. this directly lead to docker pull error.
GetChallenges(key),this key should be remoteURL not r.remoteURL ,because AddResponse(key) key=remoteURL. 
this little error cause Challenge cache Map not working ,which the r.Lock() `s critical area consume to much time ,and in massive concurrent situation which will lead to client request timeout.  we observe this timeout in our product environment.
1. first bound ``` ekv59auv.mirror.aliyuncs.com``` to you registry mirror ip in your /etc/hosts
2. use the following python …

remoteURL parameter error cause  challenge cache not working which eventually lead to client manifest request timeout

---

configuration/configuration.go
configuration/configuration_test.go
docs/configuration.md
registry/registry.go

Access logging is great.  Access logging you can turn off is even
better.  This change adds a configuration option for that.

Add configuration option to disable access logging

---

configuration/configuration.go
configuration/configuration_test.go
docs/configuration.md
notifications/endpoint.go
notifications/sinks.go
notifications/sinks_test.go
registry/handlers/app.go

The Hub registry generates a large volume of notifications, many of
which are uninteresting based on target media type.  Discarding them
within the notification endpoint consumes considerable resources that
could be saved by discarding them within the registry.  To that end,
this change adds registry configuration options to restrict the
notifications sent to an endpoint based on target media type.

Add notification filtering by target media type

---

registry/client/auth/addr.go
registry/client/auth/authchallenge.go
registry/client/auth/authchallenge_test.go

If a user specifies `mydomain.com:443` in the `Host` configuration, the PATCH request for the layer upload will fail because the credentials will be omitted because the challenge does not appear to be in the map. To fix this, we normalize the map keys always to use the Host:Port combination.
Closes https://github.com/docker/docker/issues/18469

Fix missing auth headers with PATCH HTTP request when pushing to default port

---

registry/storage/cache/redis/redis_test.go

The Redis tests were failing with a "connection pool exhausted" error
from Redigo. Closing the connection used for FLUSHDB fixes the problem.

Fix connection pool exhaustion in Redis tests

---

docs/spec/auth/oauth.md

Reading the oauth2 token documentation is misleading as it makes no mention of it being a newer feature which may not be supported by the token server. Add a note mentioning if it is not supported to refer to the token documentation for getting a token.

Add note about implementation of oauth2

---

contrib/token-server/main.go
registry/auth/silly/access_test.go
registry/auth/token/token_test.go
registry/handlers/app.go
registry/storage/driver/s3-aws/s3.go
registry/storage/driver/s3-aws/s3_test.go

Context should use type values instead of strings.
Updated direct calls to WithValue, but still other uses of string keys.
Update Acl to ACL in s3 driver.

Update to fix lint errors

---

registry/proxy/proxyauth.go
registry/proxy/proxyregistry.go

This patch allows configuring custom URL for token authentication service in the proxyingRegistry. This allows creating mirrors for private registries that use token based authentication. 
Signed-off-by: Serge Dubrouski <sergeyfd@gmail.com>

Support for custom authentication URL in proxying registry

---

registry/storage/driver/s3-aws/s3.go
registry/storage/driver/testsuites/testsuites.go

Deleting "/a" was deleting "/a/b" but also "/ab".

Fix S3 Delete method's notion of subpaths

---

reference/reference.go

This nil check is not necessary.

reference: Simplify SplitHostname

---

docs/configuration.md
docs/spec/api.md
docs/spec/api.md.tmpl
docs/spec/auth/index.md
docs/spec/auth/jwt.md
docs/spec/auth/oauth.md
docs/spec/auth/scope.md
docs/spec/auth/token.md
docs/spec/implementations.md
docs/spec/index.md
docs/spec/json.md
docs/spec/manifest-v2-1.md
docs/spec/manifest-v2-2.md
docs/spec/menu.md

Some frontmatter such as the weights, menu stuff, etc is no longer used
'draft=true' becomes 'published: false'

Convert Markdown frontmatter to YAML

---

BUILDING.md
README.md

Signed-off-by: Jihoon Chung <jihoon@gmail.com>
This fixes broken doc links. (Replaces with [general doc repo's](https://github.com/docker/docker.github.io) links)

Fix broken doc links

---

manifest/schema1/config_builder.go
manifest/schema2/builder_test.go
manifest/schema2/manifest.go
manifest/schema2/manifest_test.go
manifests.go
registry/handlers/images.go
registry/storage/garbagecollect.go
registry/storage/schema2manifesthandler.go
registry/storage/schema2manifesthandler_test.go

To allow generic manifest walking, we define an interface method of
`References` that returns the referenced items in the manifest. The
current implementation does not return the config target from schema2,
making this useless for most applications.
The garbage collector has been modified to show the utility of this
correctly formed `References` method. We may be able to make more
generic traversal methods with this, as well.

manifest: references should cover all children

---

Godeps/Godeps.json
vendor/github.com/denverdino/aliyungo/common/regions.go
vendor/github.com/denverdino/aliyungo/common/types.go
vendor/github.com/denverdino/aliyungo/oss/client.go
vendor/github.com/denverdino/aliyungo/oss/multi.go
vendor/github.com/denverdino/aliyungo/oss/regions.go
vendor/github.com/denverdino/aliyungo/oss/signature.go
vendor/github.com/denverdino/aliyungo/util/encoding.go

when push a large layer to the repo, previous oss driver copy the uploaded blob to store sequentially, we optimize the current oss driver to CopyLargeFileInParallel. which can reduce the copy time to 3/4.
CopyLargeFileInParallel
Change-Id: I8744deb826dd9f5481d2c67c257face87771909f
Signed-off-by: yaoyao.xyy <yaoyao.xyy@alibaba-inc.com>

optimize oss copy action when push upload finished.

---

Jenkinsfile

The documentation has been migrated to docker/docker.github.io, so I'm removing this Jenkins file that was running docs-related CI and can start breaking the builds.
Signed-off-by: Joao Fernandes <joao.fernandes@docker.com>

Remove Jenkinsfile used for docs CI

---

registry/storage/driver/azure/azure.go

In GetContent() we read the bytes from a blob but do not close
the underlying response body.
Apparently this is not a big deal (it's been there since 4054cd3e, which is Nov 2014).
I found other memory leaks caused by not reusing http client and not specifying http.Client.Timeout. I'll address that in another PR by re-vendoring the Azure storage SDK.

storagedriver/azure: close leaking response body

---

registry/storage/driver/swift/swift.go

Driver was passing connections by copying indirectly. Storing `swift.Connection` as pointer to fix the warnings.
Ref: #2030.
@RichardScothern PTAL

driver/swift: Fix go vet warning

---

registry/api/v2/headerparser.go
registry/api/v2/headerparser_test.go
registry/api/v2/urls.go
registry/api/v2/urls_test.go

If the explicit port is specified using this header, use it as a base for redirect urls.
As documented in article "HTTP Headers and Elastic Load Balancing" of AWS ELB docs:
> The X-Forwarded-Port request header helps you identify the port that an HTTP or HTTPS load balancer uses to connect to the client.
This makes registry behave correctly when proxy strips port from the requests e.g.:
```
GET /openshift/token?account=unused&scope=repository%3Apjoe%2Fhello-world%3Apush%2Cpull HTTP/1.1
Host: registry.f24-ose.vm
User-Agent: docker/1.12.1 go/go1.7 git-commit/23cf638 kernel/4.7.6-1-ARCH os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.1 \(linux\))
Authorization: Basic dW51c2VkOlV1WGoyTGdTWkk4TGc0azY1bXFwc3ZlT1VKdXg1NnFDMTJXMThRdUdYOG8=
Accept-Encoding: gzip
Connection: close …
```

Honor X-Forwarded-Port header

---

Godeps/Godeps.json
registry/storage/driver/azure/azure.go
vendor/github.com/Azure/azure-sdk-for-go/LICENSE
vendor/github.com/Azure/azure-sdk-for-go/storage/README.md
vendor/github.com/Azure/azure-sdk-for-go/storage/blob.go
vendor/github.com/Azure/azure-sdk-for-go/storage/client.go
vendor/github.com/Azure/azure-sdk-for-go/storage/file.go
vendor/github.com/Azure/azure-sdk-for-go/storage/table.go
vendor/github.com/Azure/azure-sdk-for-go/storage/table_entities.go
vendor/github.com/Azure/azure-sdk-for-go/storage/util.go

Updating to a recent version of Azure Storage SDK to be
able to **patch some memory leaks** through configurable HTTP client
change added to the registry recently.

Update vendored azure-sdk-for-go

---

reference/reference.go
reference/reference_test.go

When `WithDigest` is called on a reference that has a tag, it should
preserve the tag.
When `WithTag` is called on a reference that has digest, it should
preserve the digest.
cc @stevvooe @dmcgowan @nishanttotla

digest: Preserve tag and digest in With* functions

---

registry/client/auth/challenge/addr.go
registry/client/auth/challenge/authchallenge.go
registry/client/auth/challenge/authchallenge_test.go
registry/client/auth/session.go
registry/client/auth/session_test.go
registry/client/errors.go
registry/proxy/proxyauth.go
registry/proxy/proxymanifeststore_test.go
registry/proxy/proxyregistry.go

Allow clients to handle errors being set in the WWW-Authenticate rather than in the body. The `WWW-Authenticate` errors give a more precise error describing what is needed to authorize with the server. This allows clients to distinguish between 401s which require user login and 401s which are caused by insufficient scope.

Add OAuth error for client

---

reference/reference.go
reference/reference_test.go

The Match method allows to see if a reference matches a specified patterns.
This is linked to https://github.com/docker/docker/pull/27872#discussion_r86425039 👼
/cc @stevvooe @aaronlehmann 
🐸
Signed-off-by: Vincent Demeester <vincent@sbr.pm>

Add a new Match method to the reference package

---

docs/spec/manifest-v2-2.md
manifest/schema2/manifest.go

plugins are going out of experimental so let's bump to v1, also @stevvooe suggested we remove `.image`

switch to v1 and remove .image

---

Godeps/Godeps.json
registry/storage/driver/oss/oss.go
vendor/github.com/denverdino/aliyungo/oss/client.go

oss native large file copy consume too much time which will eventually lead to oss 90s timeout because of no data transmit throughout native copy. change maxCopySize to 128MB, ensure only small medium size file use oss native copy to avoid connection reset by peer.
set maxCopySize to 128MB to avoid oss native copy consume too much time.

fix: oss driver would get connection reset by peer when upload large image layer.

---

reference/reference.go

Add a simple helper to create name only references without having to first get the name as a string and reparse. This method does not fail so ignoring or checking error to simply trim reference is not required.
Ping @tonistiigi @aaronlehmann

Add trim name method helper to create name only references

---

registry/storage/driver/s3-aws/s3_v2_signer.go

The current code determines the header order for the
"string-to-sign" payload by sorting on the concatenation
of headers and values, whereas it should only happen on the
key.
During multipart uploads, since `x-amz-copy-source-range` and
`x-amz-copy-source` headers are present, V2 signatures fail to
validate since header order is swapped.
This patch reverts to the expected behavior.
Signed-off-by: Pierre-Yves Ritschard <pyr@spootnik.org>

v2 signer: correctly sort headers

---

reference/helpers.go
reference/normalize.go

`IsNameOnly` and `WithDefaultTag` aren't present in `docker/docker/reference`, but useful trivial utility functions. This also reduces the gap between the the Docker reference package and the one in this repo.
Signed-off-by: Nishant Totla <nishanttotla@gmail.com>

Adding utility functions - IsNameOnly and EnsureTagged

---

registry/storage/garbagecollect.go

Golint now checks for new lines at the end of go error strings, remove these unneeded new lines.

Remove newlines from end of error strings

---

configuration/configuration.go
contrib/token-server/main.go
contrib/token-server/token.go
docs/spec/auth/scope.md
registry/auth/auth.go
registry/auth/token/accesscontroller.go
registry/auth/token/token.go
registry/client/auth/session.go
registry/handlers/images.go

Adds ability to enforce a policy in which a repository may only contain manifests of a single class. A class can currently be "image" (application/vnd.docker.container.image.v1+json) or "plugin" (application/vnd.docker.plugin.v1+json).
This change updates the authorization scope to allow subtyping the resource type and defines a class subtype for "repository". The repository class can be checked on push to ensure no data gets put into the registry which does not match the authorized class. The class is not used to deny the request in middleware but saved in the request context to be accessible within the manifest store when the policy is enabled.

Add support for repository class 

---

contrib/docker-integration/helpers.bash
contrib/docker-integration/malevolent.bats
contrib/docker-integration/run_multiversion.sh
contrib/docker-integration/tls.bats

Remove use of `tag -f` since it is no longer allowed in 1.12 and not needed for any of the currently tested versions of Docker. Additionally don't add the email flag on login starting in docker 1.11.
Do not merge until Docker 1.12 has been released. Periodic failure caused by startup time for 1.12 taking longer than previous versions. A wait may need to be added to the tests.

Integration tests support for docker 1.12

---

manifest/schema1/config_builder.go

If the digest is malformed, it will cause a panic when building the
manifest.
cc @dmcgowan

schema1: Validate descriptors in AppendReference

---

configuration/configuration.go
docs/configuration.md
registry/handlers/app.go

Even when validation is off, we don't want to allow manifests with foreign layers urls.

registry/handles/app: always append default urls regexps

---

registry/client/auth/session.go

Enforces backwards compatibility with older authorization servers without requiring the client to know about the compatibility requirements.
ping @stevvooe

Enforce image is treated as empty class

---

health/checks/checks.go
health/doc.go

This PR is a migration of #2049 
FileChecker can not work properly when the specified file can not be Stat because the app has no proper permission (read and execute permission for directory along with the specified file path). This should be make clear to end users and under such circumstance, FileChecker should return error instead nil to make the precondition ready. Otherwise, we can not actually disable the app by touch the disable file.
We should also add more document about the usage of FileChecker.
FileChecker only accepts absolute or relative file path. It does not work properly with tilde(~). You should make sure that the application has proper permission(read and execute permission for directory along with the specified file path). Otherwise, the FileChecker will report error …

fix filechecker in health with precondition check

---

manifest/schema2/builder.go
manifest/schema2/builder_test.go
manifest/schema2/manifest.go
manifest/schema2/manifest_test.go
registry/handlers/api_test.go
registry/handlers/images.go
registry/storage/schema2manifesthandler_test.go
testutil/manifests.go

Modify manifest builder so it can be used to build manifests with different configuration media types.

[carry #1972] Update schema2 builder to take media type

---

digest/digest.go
digest/digest_test.go
digest/set.go
reference/reference.go
registry/client/repository.go
registry/handlers/blobupload.go
registry/handlers/context.go
registry/handlers/images.go
registry/storage/blobstore.go
registry/storage/vacuum.go

digest: remove stuttering ParseDigest function
